### ISSUE TITLE
func_get_args returns arguments by references instead values

### ISSUE THREAD

**Issue by javer** [facebook/hhvm#1027]
Test case:

``` php
<?php
function test($param)
{
  $param = 'local_value';
  var_dump(func_get_args());
}

test('param_value');
```

PHP output:

```
array(1) {
  [0]=>
  string(11) "param_value"
}
```

HipHop output:

```
array(1) {
  [0]=>
  string(11) "local_value"
}
```

**Comment by metaclass-nl** [comment]
This fix also solves the problem of crashes probably caused by endless recursion when earlier versions Doctrine\DBAL\Query\QueryBuilder::andWhere (and probably orWhere) is used on PHP 7. See [this issue](https://github.com/metaclass-nl/tresholds-governor/issues/6) for details.

Currently two supported editions of Symfony Standard Edition still require "doctrine/orm": "^2.4.8" which requires "doctrine/dbal": "~2.4".
