### ISSUE TITLE
igbinary support for memcached

### ISSUE THREAD

**Issue by demon** [facebook/hhvm#1248]
What it says on the tin.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by demon** [comment]
Yeah this was based off of a really old usecase we had at Wikimedia that is no longer relevant. If someone else wants to champion this more power to them :)

**Comment by TysonAndre** [comment]
A related issue in the igbinary project is https://github.com/igbinary/igbinary/issues/42

I'm a maintainer of igbinary, and started working on https://github.com/TysonAndre/igbinary-hhvm a year ago, but got distracted with other projects. I wasn't able to build HHVM from source at the time (For integration with Memcached) due to dependency issues.

My main use case for igbinary would be in combination with Memcached (A site may have pre-existing data serialized with igbinary, and the lack of igbinary support would interfere with testing out HHVM alongside php 5/7).

- But it's not really realistic for me to migrate the site in question, due to other factors.

Observations/Questions I had at the time:

1. (not a question) In order to get it to work with the Memcached HHVM extension, it seems as if igbinary would have to be built into HHVM (When I looked at memcached's code a year ago), and couldn't be a separate extension
   (Memcached uses the "flags" from the memcache protocol to indicate which serializer is used, igbinary is hardcoded by hhvm as unsupported)
2. Are there any documented guidelines for designing a custom serializer?
    E.g. if an unserializer is attempting to unserialize a PHP reference to a string (e.g. from Zend php) (Within an object/array), should it throw immediately, or silently convert it to a value (Which of those alternatives)?
3. What are the criteria for HHVM accepting a custom serializer?
   Would writing equivalent tests to the php serializer be enough?

**Comment by TysonAndre** [comment]
https://github.com/TysonAndre/igbinary-hhvm is close to feature complete; there are [52 passing tests, 7 failing tests](https://travis-ci.org/TysonAndre/igbinary-hhvm)

Still wondering about the previous questions before creating a PR:

> 2\. Are there any documented guidelines for designing a custom serializer?
E.g. if an unserializer is attempting to unserialize a PHP reference to a string (e.g. from Zend php) (Within an object/array), should it throw immediately, or silently convert it to a value (Which of those alternatives)?
3\. What are the criteria for HHVM accepting a custom serializer?
Would writing equivalent tests to the php serializer be enough?
