### ISSUE TITLE
newrelic extension?

### ISSUE THREAD

**Issue by cscd98** [facebook/hhvm#1255]
We use newrelic which is a plugin for php that monitors our web servers (e.g. browser/page load time, memcache, redis, mysql queries).

There is a php plugin for this - is there any way to use with hhvm?

Thanks

**Comment by chregu** [comment]
Since this ranks high on google: I worked a little bit more on the extension https://github.com/chregu/hhvm-newrelic-ext , it's now compatible with HHVM 3.5 and hopefully 3.6 when it's released in a few weeks (an older branch for 3.4 exists as well). I also made a follow up blog post about it: https://blog.liip.ch/archive/2015/01/19/new-relic-extension-for-hhvm-updated-to-latest-version.html
