### ISSUE TITLE
Server.FileSocket has wrong permissions

### ISSUE THREAD

**Issue by stuartcarnie** [facebook/hhvm#1727]
The permissions for the unix domain socket (when using `Server.FileSocket` option) has permission 755 `rwxr-xr-x` rather than 766 `rwxrw-rw-` when created by hhvm – the latter matches php5-fpm.  This prevents nginx from writing to the socket unless it is running as the same user.

Easy workaround is to change the permissions

**Comment by andrewmclagan** [comment]
Any movement on this, currently running through the full TCP stack with fastcgi. Really would love to use unix sockets

**Comment by pribeh** [comment]
I'm getting a 502 bad gateway and in the logs "connect() to unix:/var/run/hhvm/hhvm.sock failed (111: Connection refused) while connecting to upstream". Could this socket permission issue explain these errors?

**Comment by andrewmclagan** [comment]
It could be, although that is most likely your backend is down. Make sure HHVM is running first. if you are using Nginx add this to your server directive:

```
        fastcgi_intercept_errors        on;
        error_page 404 /error/404.php; # or similar
````

**Comment by pribeh** [comment]
After subsequent testing, it only intermittently happens when attempting to process a particular php library (https://github.com/Lullabot/amp-library) - after several requests have already been made. Sometimes the errors are timeouts and other times they are connection refused. Otherwise, HHVM's socket appears to be working just fine! I guess this rules out the permission issue?
