### ISSUE TITLE
Please Implement "--chroot /to/dir" in hhvm

### ISSUE THREAD

**Issue by Thomas12** [facebook/hhvm#1790]
As in php-fpm (config file command: chroot), allow chrooting the hhvm-server to a subdirectory, too.

php-fpm.conf.default says: "Note: chrooting is a great security feature and should be used whenever possible."

**Comment by bhelm** [comment]
I prefere to use the php-fpm chroot feature because it hardens the web installation (that is also stated by the page that LiraNuna linked). A php-fpm chroot installation can be so minimal that it offers only very minimal libraries, no headers and (if you want) no command line tools for the attackers to work with. It also __does not need /proc and /dev__, which means that it hides critical systeminformations like running processes, config files and logged in users. That IS a feature, as this prevents some/many local root exploits found in the wild to work, and without root they cant break out. It may be true that a genious hacker still can work around all that, but all attacks i had so far were script kids with public exploits, and for them chroot does really the trick!

**Comment by lutel** [comment]
LiraNuna could you please reopen this issue? This feature is needed as it is crucial to virtual hosting environments.

**Comment by LiraNuna** [comment]
cc @paulbiss and @fredemmott

**Comment by simonwelsh** [comment]
Why does this need to be part of HHVM? `start-stop-daemon` and upstart both support providing a chroot path, and you can just run chroot directly too.

**Comment by paulbiss** [comment]
Agree with @simonwelsh, I'm unclear on why this needs to be part of the hhvm binary.

**Comment by Thomas12** [comment]
I think chrooting via chroot or start-stop-daemon is more difficult as then you have to copy all needed files (lib, dev, etc/resolv.conf) in the to-be-chrooted subdirectory which can be a bit annoying and another security risk when you later forget to update the libraries in the chroot-subdir. 

So a chroot by hhvm itself after start-up can be a convenient option.

**Comment by lutel** [comment]
I'm missing php-fpm chroot like feature, where I could isolate php environments in virtual hosting in very efficient way - each php thread could run as a different user, have its own resource and security policy, it works really well, I could create small chrooted enviroments which were consistent with shell and php. If it could be achieved without integrating chroot feature into binary, i'd like to see such implementation with nginx.

**Comment by paulbiss** [comment]
@lutel I'm a little confused, you can't chroot a thread, or run two threads from the same process as different users.

@Thomas12 makes sense. I'm still not totally sold on this feature, but I'd be willing to look at a PR if there's enough interest in adding it. We do have support for setuid so I suppose it's not without precedent.

**Comment by lutel** [comment]
@paulbiss in php-fpm each thread has it's own chrooted directory (eg. per one customer), an it is own by customer user. In php-fpm you can define separate pools, and chroot each of them.

**Comment by fredemmott** [comment]
@lutel: php-fpm uses multiple processes, not multiple threads. Multiple threads can not be chrooted differently. There can only be one chroot per process, which dramatically limits the value of this for HHVM.

**Comment by lutel** [comment]
@fredemmott indeed, its per process. Why is this limitation for HHVM? In terms of resource usage these are almost the same...

xxxx.pl 13285  0.0  0.4 653604 80252 ?        S    06:17   0:01 php-fpm: pool xxxx.pl
hhvm     15013  0.0  0.5 608292 88728 ?        Ssl  Jan11   0:00 /usr/bin/hhvm -m server -c /etc/hhvm/php.ini -c /etc/hhvm/server.ini -u hhvm -vPidFile=/var/run/hhvm/hhvm.pid -vLog.File=/var/log/hhvm/hhvm_error.log -vRepo.Central.Path=/var/lib/hhvm/hhvm.hhbc -vServer.Type=fastcgi -vServer.IP=127.0.0.1 -vServer.Port=9000

**Comment by paulbiss** [comment]
@lutel: hhvm is a jit, and many of the performance benefits come from compiling machine code translations of php and caching them in a translation cache. As each request needs access to the translated machine code and associated data structures we run requests in threads rather than separate processes.

**Comment by lutel** [comment]
@paulbiss yes, but wouldn't be possible to create mechanism to chroot different hhvm processes (not threads), like we have in php-fpm? This feature of php-fpm that you can define multiple pools and chroot each of them is very convenient in virtual hosting. I'd be interested to see if it is already possible to chroot hhvm like @simonwelsh mentioned.

**Comment by paulbiss** [comment]
The problem is that there aren't multiple processes handling requests within hhvm, it's all done in a single multithreaded process. Short of substantially re-architecting both the server and the runtime I don't think a multiprocess solution is going to be possible.

If you want to serve requests from different source trees in separate chroot jails you can always just spin up multiple servers and point them each at the source tree you want them to serve. This is something that should be done in a wrapper script, not implemented in hhvm.

It is possible to run hhvm in a chroot, but as @Thomas12 mentioned you'll need to have the jail setup to contain all of the resources that hhvm will need to start, libraries, shells, etc.

**Comment by lutel** [comment]
@paulbiss with php-fpm implementation, jailing is also required, but it is only what php requires in terms of libs/shells etc - which is perfectly fine. Looking at both php-fpm and hhvm in terms of chroot, i don't see they are that fart apart - it is only that php-fpm supports in its config chrooting, and does chrooting in according to whats configured in pools. Still the process would be isolated to one directory, it doesn't seem like big architecture change...
As you said, it could be achieved with wrapper script, i'll try to work on it.

**Comment by paulbiss** [comment]
@lutel: supporting a chroot jail would be quite doable, in either a wrapper or within hhvm itself. Allowing hhvm to run requests in different processes and chroot them each individually would be a much larger undertaking, that was my point.

**Comment by AcidRaZor** [comment]
I'm seriously considering moving over to PHP7 instead due to the lack chroot jail with hhvm, clients are doing security audits and are threatening to move their services even though I offer some of the fastest and best hosting because of the work facebook's team has done. I would really love them taking this a step further

**Comment by fredemmott** [comment]
You can run an instance of HHVM for each site, with each instance having a different chroot/user.

This is unlikely to require significantly more resources than would be needed if HHVM were rewritten to use multiprocessing rather than multithreading (which is almost certainly not going to happen).

Closing as depending on meaning, this is either easily done by standard administration tools, or is a wontfix.

**Comment by AcidRaZor** [comment]
Thanks fredemmott, any tests that could show how much more hhvm would use in a multiuser environment that does what you suggest? Because if I have to get more RAM or CPU I need to seriously way up the cost vs performance on this one

**Comment by fredemmott** [comment]
Sorry, that's really too dependent on your specific load for general tooling to be practical. As a rough guideline, when using an HHVM process per site:

 - if you have a few big popular sites, it should be efficient
 - if you have lots of rarely-hit tiny sites, it will be inefficient in terms of memory

Fixing the latter would both involve a significant rewrite, and for the reuse_tc functionality to be stabilized.

**Comment by fredemmott** [comment]
If neither of those sounds like your setup (or you want confirmation), sorry, there's not really a better approach than to try both and measure.

**Comment by AcidRaZor** [comment]
Thanks for taking the time to give me feedback on this. Unfortunately I would need to put every site on it's own process since I open my server up to 1 site infecting several other unrelated ones if they all can run under the same process. I'm busy testing out PHP7 and might migrate to that instead
