### ISSUE TITLE
RedisArray is not implemented

### ISSUE THREAD

**Issue by shivaas** [facebook/hhvm#1992]
It seems like the Redis implementation is incomplete. RedisArray allows an app to use a distributed redis cache running on multiple hosts. The C implementation in phpredis is at https://github.com/nicolasff/phpredis/blob/master/redis_array.c

**Comment by aorenste** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by koeninger** [comment]
For what it's worth, this feature is what blocked our initial attempt at migrating to HHVM.  RedisArray has outperformed proxy alternatives for us.

**Comment by aorenste** [comment]
Reopening since you're expressing a recent interest.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The hhvm implementation of the Redis has been removed [recently](https://github.com/facebook/hhvm/commit/db84e0a2314f9865a831f3b6213a031e3cb613cc).
[Blogpost hhvm 4.56](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html) about this removal states the following:
_The Redis extension has been removed. This extension contained no native code, so can be extracted from past versions of HHVM and updated as a standalone library if required, though we do not support this usage._

The code does not pass the typechecker can relies on many php behaviors, so this will require some effort. An alternative to the magic method `__call()` must be found, since that was removed in hhvm 4.57, see [blogpost hhvm 4.57](https://hhvm.com/blog/2020/05/11/hhvm-4.57.html).

It appears like the RedisArray class was not in the removed code, so I am assuming it was not implemented.
