### ISSUE TITLE
spl_autoload_unregister's behavior is inconsistent when called with inaccessible function.

### ISSUE THREAD

**Issue by chalet16** [facebook/hhvm#2060]
This bug has caused one of joomlacms tests to fail.

Code:

``` php
<?php
class Class1 {
        public static function setup() {
                spl_autoload_register(array('Class1','_autoload'));
        }
        private static function _autoload() {
        }
}
Class1::setup();
print_r(spl_autoload_functions());
spl_autoload_unregister(array('Class1','_autoload'));
print_r(spl_autoload_functions());
```

Expected Result:

```
Array
(
    [0] => Array
        (
            [0] => Class1
            [1] => _autoload
        )

)
Array
(
)
```

Actual Result:

```
Array
(
    [0] => Array
        (
            [0] => Class1
            [1] => _autoload
        )

)
Array
(
    [0] => Array
        (
            [0] => Class1
            [1] => _autoload
        )

)
```

**Comment by photodude** [comment]
This is still an issue in 3.14.4, 3.15.2 and 3.16.0-dev
https://3v4l.org/1EndQ

likely the cause of our loader test failure
https://travis-ci.org/joomla/joomla-cms/jobs/168348305#L1839-L1842 from this test
https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/joomla/JLoaderTest.php
and this loader
https://github.com/joomla/joomla-cms/blob/staging/libraries/loader.php

**Comment by photodude** [comment]
@chalet16 Although this is still an issue for hhvm, Joomla CMS has changed the `_autoload()` function from private to public for joomla 3.7+ which resolved the related testing error.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The `\spl_autoload_unregister()` function has been removed from the [newest versions](https://github.com/facebook/hhvm/commit/6f24761f684b9747f9823d37b07cb2ba9e06a7d6) of hhvm.
It appears this issue was fixed by changing the framework code back in 2016.
I don't think anyone is affected by this issue today.
If this is the case, please open a new issue.
