### ISSUE TITLE
Add IntelliJ support for Hack

### ISSUE THREAD

**Issue by swarajban** [facebook/hhvm#2132]

**Comment by luisaglez1** [comment]
Today there are online advisors who, based on what you want to solve, can help you solve it in the best way, and this is how you will only have to think about what you need to be able to enter and once inside you will see how easy it really is to carry out any type of entry _**[into Facebook](https://hackfreeonline.com/facebook/
)**_ from any type of account, so without a doubt it will be easier for you to carry out what you are proposing, so if you are currently solving any type of situation, remember that the only thing you need is to keep this page in mind so that from then on you can enter in the easiest way and you do not present any type of problem when you are acting. The best alternative to solve problems on the platform is to _**[hack Facebook](https://hackfreeonline.com/facebook/
)**_ because who doesn't want to be sure that the person you're trusting is actually just as shown and as definitely to achieve this it requires a lot of work and having to stay with someone for a long time and as the truth is I already want to commit because I'm a bit older and if it's not the right one then it's better to know now and leave this person to be able to continue my life and meet someone else or ultimately be able to move on to be able to meet someone else, that's how I saw the need to have to hack an account so it's not difficult to achieve. I decided to hack Facebook because when you get to know a person completely when you know all their information, that's when you can know that you can trust this person, so from what you get to know about the person you're investigating you'll know more and get to know them better, and personally it was very helpful to me because I have a boyfriend and I just needed more time to get to know him better in order to decide whether or not to take that next important step, so to be able to continue and leave like that, you only need to enter this page because it is definitely very important and it is very functional.
