### ISSUE TITLE
Weak reference support (Weakref extension)

### ISSUE THREAD

**Issue by DHager** [facebook/hhvm#2227]
According to [this page](https://github.com/facebook/hhvm/wiki/Extensions) the Weak References extension is not supported.While you can go far without having to use them, there are certain situations where weak references are invaluable and there is no plausible workaround.

_That said_, I think an even _better_ situation would be to have the same functionality alongside [Hack-language generics](http://docs.hhvm.com/manual/en/hack.generics.php), to get something like this:

```
WeakReference<T>  {    
    public function __construct(T $object){...}
    public function acquire(): bool {...}
    public function get(): T {...}
    public function release(): bool {...}
    public function valid(): bool {...}
}
```

**Comment by evought** [comment]
"... there are certain situations where weak references are invaluable and there is no plausible workaround."

To take what you are saying a bit further, even when there are plausible workarounds, there are very few cases where the workaround is a good design choice. It boggles my mind that any language with garbage collection, especially one used on servers,  does not have readily accessible weak references.

In an application context where you are caching any kind of expensive resource, you can tune the application as a whole to figure out an effective strategy for caching: "OK, I'm going to store up to 20 whatchamajangers and use a LRU algorithm to decide which ones to keep around; that buys me the best combination of performance vs. memory usage" and you can do that with strong references. But in a *component* context, the caching code almost certainly does not have the information on the application-level memory usage and caching strategy to make that decision in any sensible manner: "Do I store 20, 2, or 200? What algorithm do I use for pruning?". Not having weak-references therefore requires irrational design decisions at the component level or it inhibits code reuse. It is almost always better to just hand a reference to an expensive resource off and say "hold onto this for now and hand it back later if it still exists, otherwise I'll just make a new one". Getting in the habit of using weak references for objects you don't actually own or have responsibility for (e.g. links between entities backed by a database or external store or stuff that you could look up but don't always want to) also eliminates a whole class of circular-reference leaks (and it's not like we don't have to test for null values all over the place in PHP anyway...).

Even at the application level, weak references make the caching strategy more resilient in the face of fluctuating load. If you do have 21 watchamajingers cached and end up clearing one of your least-recently-used strong references, then have a request for that exact resource, you now have to recreate it, even if it has not yet been garbage-collected. Even if it is still there, you no longer know how to access it. With a weak reference, you can mark the extras as no-longer needed (by clearing a strong reference to them) but don't actually lose access to them until the garbage collector disposes them. If the garbage collector is triggering infrequently, you can let the cached objects drift upward a bit and if the collector is keeping things tight your code doesn't worry about it. For that matter, the garbage collector may not have disposed of an object because other code still has a strong reference to it, in which case a cache-miss-and-recreate leads to abject stupidity.

What brings me to the issue right now are two things: 1) caching prepared statements for a database connection and 2) caching read entities in a Unit-of-Work. Both of those come squarely under the "component does not know enough about the application context to optimize" and therefore point to using weak references: if I've already read it, and it happens to still be there when I next need it, then don't redo it, otherwise don't worry about it and don't let it interfere with reclaiming memory. If an entity is modified-and-queued-for-write, it will have a strong reference and won't be accidentally collected. At the moment, I have hhvm in my CI-testing run, but given the lack of weak references, I will will either have to take support for hhvm back out, resort to irrational design hacks, or stub out WeakRef _and_ resort to irrational design hacks.

Anyway, if hhvm is trying to position itself to spread to other contexts, WeakRef support is important.

**Comment by edwinsmith** [comment]
There's no Like button here to click but its easy to agree with all this. Most real-world uses of weak references I've seen involve some kind of ad-hoc caching (which is what java "soft" references were meant for), but that's nothing close to comprehensive. As we begin working on better garbage collection, I'm interested in whether this (caching) is the single dominant use case in apps you care about on, or whether you have others to add to the thread?

in java:
weak ref = cleared when the gc notices it
soft ref = cleared when the gc thinks it's a good idea (sort of a cache)
phantom ref = like a weak ref, but impossible to ressurect object from a reference queue
reference queue = for doing other cleanup after the reference is cleared, like removing hashtable key

**Comment by evought** [comment]
"As we begin working on better garbage collection, I'm interested in
whether this (caching) is the single dominant use case in apps you care
about on, or whether you have others to add to the thread?"

Well, as I mentioned briefly, they are also key to breaking circular
references which prevent garbage collection. If you have a user entity with
a list of bugs they have opened and each bug has a reference back to the
user, neither will be garbage collected. If you choose one entity to 'own'
the association, they get a strong reference and the other gets a weak
reference and the problem is solved. Doubly-linked lists can also mess up
garbage collection even when the list head is no longer accessible and,
again, a weak reference can break the chain. In those cases you seldom have
to worry about the weak reference being invalidated because the whole
structure is disposed of when the application is done with it. It is just
there to prevent the back-link from inhibiting disposal.

In many request-oriented PHP applications, people have problems like this
all over the place, but because the request is relatively short-lived, they
don't notice. As soon as the objects stick around for any length of time or
you have to touch a lot of such objects in a request, they start to pile up
and cause memory problems. Since the designer of a component never knows
the context in which they will be used, it makes sense to design
garbage-collect-ability into the component from the beginning.

And yes, as you hint at, Java is where I have had much experience with weak
references, along with a few C++ frameworks and some Smalltalk. Java has a
whole zoo of weak reference types and while that is nice, I'm not sure it's
necessary. Weak references of some type are essential and being able to
additionally hint "I'd like you to keep this around if we're not short on
memory" is nice, but as you get into more ability to fine tune, the API
also gets more complex.

In Java, Smalltalk, and C++, I sometimes wrote simulations or other
long-running programs, sometimes several days for a single run. You *don't*
want a garbage collection problem in something like that, and the analysts
get cranky if they have to wait for you to fix a bug and start over. Long
running server code (enterprise apps) is the same.

**Comment by DHager** [comment]
I believe PHP 5.3's garbage-collection improvements already address the problem of circular references, I'm more concerned with the use-cases of:

1. Collections of listeners. The "tell me when something happens to you" relationship shouldn't prevent garbage-collection of the listener when nothing else can reach it.
2. Object pooling. Weak references provide a way to infer when the object is no-longer-used and can be re-purposed.

**Comment by evought** [comment]
"I believe PHP 5.3's garbage-collection improvements already address the problem of circular references"

My understanding is that some cases are handled, but according to the [PHP manual]( http://php.net/manual/en/features.gc.refcounting-basics.php) it is still a problem (maybe I'm wrong?). But I am simplifying when I say 'circular' as topologies are not often that neat.

Your example of the Listener pattern is perfect as it is one where the garbage collector has no possible way of knowing whether the reference should be collected unless the programmer can tell it what is intended: the Listener may be owned by a View with a well-defined life-cycle or it may not. It is a great example because many of the classes of GC problems can be stated in terms of the Observer/Observable pattern. I mentioned entities which may or may not be dirty and may or may not have been persisted as a potential problem but that can just as fairly be restated as a sticky-Observer issue depending on how it is laid out.

Re: (2), proper support for object pooling would indeed be nice, but that usually requires more than just weak/strong references to do right, so as mentioned above, I would be pleased with just vanilla weak reference support standard across PHP VMs.

So that leaves us with maybe the following use cases?

a) Control of caching objects where it is desirable but not necessary for the object to be left in memory for an arbitrary length of time. The reference holder just wants to know whether the link is still valid before accessing. A strong link can be used to fine-tune the object life time.

a.1) It is a nice feature to be able to hint (as per Java) that the object *should* be maintained if resource limits permit.

b) Breaking other complex reference topologies by clearly indicating Component vs. Uses relationships, where:

b.1) the sticky-Observer is a primary culprit. A Listener relationship should not inhibit garbage collection. Where it should (say, the Listener is owned by a View with a defined lifetime) then a strong link can be used to temporarily inhibit garbage collection during the life of the View.

c) Object pooling where usually some combination of weak links and GC-hooked queueing is applied to capture resources just before they would be collected and recycle them in application code.

My priorities would be (a) and (b) with (a.1) and (c) as nice but lower priority.

For testing purposes, I find it crucial to have weak references be logic-neutral. In other words, I should be able to stub it out for testing and though it will clearly affect performance, it should not change application logic. In use cases (a)(a.1) the stub always returns null and generates a cache-miss. In (b)/(b.1) the stub should be a strong reference and the object is always returned. In (c), objects would never return to the pool, forcing client code to recreate them.

This is relatively easy to do with the WeakRef extension as I can simply substitute another class for the actual reference through dependency injection, an always-null for case (a) and an always-valid for case (b). Case (c) is not supported either way. It is also straight-forward to use (a) as a transparent fallback if (a.1) is not supported.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears that this issue has been fixed.
The WeakRef extension can be found [here](https://github.com/facebook/hhvm/blob/c54aa1a09f474cc7dd62af6923bca0fcac8eae42/hphp/runtime/ext/weakref/ext_weakref.php) in the hhvm source code and the typechecker knows about the `\WeakRef<T>` class.

If there is a problem with the current WeakRef implementation, please let us know.
