### ISSUE TITLE
The ArrayAccess<Tk, Tv> interface raises a Fatal Error

### ISSUE THREAD

**Issue by dhrrgn** [facebook/hhvm#2268]
If you follow the example in the docs (http://docs.hhvm.com/manual/en/class.hack.arrayaccesstktv.php), it raises a Fatal Error:

```
Fatal error: Declaration of Obj::offsetUnset() must be compatible with that of ArrayAccess::offsetUnset() in test.php on line 3
```

After playing around with it for a bit, I found that the only way to get it to work is to use the `mixed` type for all of the offset/key parameters in the implementation.

I am not sure whether this is a documentation, or implementation bug.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The runtime error about the incompatible types is fixed.
ArrayAccess also nolonger provides its special magic behavior since [hhvm 4.45](https://hhvm.com/blog/2020/02/19/hhvm-4.45.html).
The interface is just a normal interface with a generic (non-restrained) Tk and Tv.
