### ISSUE TITLE
HHVM exits when suppressing mysqli_free_result argument type error

### ISSUE THREAD

**Issue by naderman** [facebook/hhvm#2384]
If you run the following program on PHP it outputs "foo" while it exits before the echo on hhvm. Regular -1 exit code, no crash.

```
<?php
mysqli_free_result(false);
echo "foo\n";
```

**Comment by kacy-** [comment]
Odd, I'm still getting this error:

HipHop VM 3.6.0 (rel)
Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce


`\nCatchable fatal error: Argument 1 passed to mysqli_fetch_object() must be an instance of mysqli_result, bool given in /home/***/public_html/wp-includes/wp-db.php on line 1619`

`if ( $this->use_mysqli ) {
                        //if ( $this->use_mysqli ) {
                                while ( $row = @mysqli_fetch_object( $this->result ) ) { //<-- Fails here
                                        $this->last_result[$num_rows] = $row;
                                        $num_rows++;
                                }
                        } else {
                                while ( $row = @mysql_fetch_object( $this->result ) ) {
                                        $this->last_result[$num_rows] = $row;
                                        $num_rows++;
                                }`

I corrected the issue by testing the type of `$this->result` in the condition, but was curious about how this issue was marked as closed but it appears to persist.

Thank you.

**Comment by fredemmott** [comment]
Can you file a separate issue? This issue is closed because it's referring to mysqli_free_result(), which is fixed. Your error is from mysqli_fetch_object()

**Comment by kacy-** [comment]
Definitely. Apologies for not catching that.
