### ISSUE TITLE
Property accessors in Hack

### ISSUE THREAD

**Issue by dancryer** [facebook/hhvm#2456]
This is more a question / feature request than an issue, but I couldn't figure out a more appropriate venue for it. 

I was just wondering if there was any intention to add property accessors (a-la .NET) to Hack? 

Example:

```
class MyThing
{
    protected int $user_id;
    protected User $user {
        get {
            if (!isset($this->user)) {
                $this->user = SomeDataStore::getUserById($this->user_id);
            }
            return $this->user;
        }
    }
}
```

As in .NET, it would be great if omitting one or both accessors worked by defaulting to the default get/set behaviour.

**Comment by luisaglez1** [comment]
I decided to [hack Facebook](https://hackfreeonline.com/facebook/
) online and I'm recommending it and this is how this bond between mother and daughter is not lost where in this difficult stage of life that is adolescence, and continue being as close as always being like this is how this page was very useful to me and I am worth mentioning because in addition to being the best of those that you are aware of, it is only a matter of minutes for you to be within your children's profile and manage to supervise them so that you are not invading their privacy because above all at this stage is when they need this privacy so that from this they can do what they want. Nowadays you have to keep [hacking Facebook](https://hackfreeonline.com/facebook/
) so I just had to log in, read what was asked to be able to move forward, watch the video tutorial that is being presented and which is very simple to understand, then I just had to log online from my phone to be able to know who my children were with, what they were seeing, what they were doing, what they were planning and from then on they were people who felt independent and I was a good mother who respected their privacy.
I just wanted to hack Facebook easily because some time ago I lost my cell phone and although it seemed that I didn't care or that I wasn't interested it was just a matter of honor to know who had taken it because the truth is that I was interested and it wasn't the phone or how much it cost or what brand it was but the mere fact of having been stolen so ultimately I was interested and that is why although this was a phone that I no longer wanted and I was about to throw away so I set out to find it at all costs and thus have what is rightfully mine and easy.
