### ISSUE TITLE
Composer does not prompt for HTTP Basic Auth credentials

### ISSUE THREAD

**Issue by shochdoerfer** [facebook/hhvm#2507]
When running Composer with the php.net implementation of PHP Composer will ask for HTTP Basic Auth credentials in interative mode once it detects that the server resources are protected by HTTP Basic Auth. When running Composer via hhvm Composer does not prompt for the credentials and simply ignore the resource (e.g. not download the packages.json file from the local satis server).

**Comment by aftabnaveed** [comment]
The issue seems to be still there. When I try to install magento 2 via composer it won't prompt for basic auth info and throw this error

```
user@c7847d4dfe97:/var/www/html$ hhvm composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./magento2

                                                                                                         
  [Composer\Downloader\TransportException]                                                               
  The "https://repo.magento.com/packages.json" file could not be downloaded (HTTP/1.1 401 Unauthorized)  
                                                                                                         

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**HHVM info**
HipHop VM 3.18.0 (rel)
Compiler: tags/HHVM-3.18.0-0-g9b285191feb2bb1558bb6682da135263bd2a9e60
Repo schema: cc987335f4691fa6ed98336c2378d8e71a751b22

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html). When installing dependencies for Hack projects, you run composer 1.8.4 or above on php.
This [blogpost of hhvm 4.0.0's release](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) contains the following.

_HHVM is no longer able to execute Composer; Composer 1.8.4 includes support for identifying the HHVM version when executing via PHP, which is how we currently recommend installing dependencies for Hack projects._
