### ISSUE TITLE
Page timeout with FastCGI (> 120 seconds)

### ISSUE THREAD

**Issue by mnapoli** [facebook/hhvm#2531]
So I understand there's a timeout, much like `max_execution_time`, set by default to 120s.

I am trying to configure it to a larger value but with no success. I am running Ubuntu 14.04 and HHVM 3.1 (nightly build).

I first tried to configure it through the `/etc/hhvm/server.ini` file because HDF files are supposed to be gone:

``` ini
...
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.connection_timeout_seconds = 500
...
```

No success…

I then tried with the HDF file:

```
...
Server {
  Port = 80
  SourceRoot = /var/www/
  DefaultDocument = index.php
  ConnectionTimeoutSeconds = 500
}
...
```

Still no success (requests are terminated at 120 seconds).

Everytime I have restarted the fastcgi process with `sudo /etc/init.d/hhvm restart`.

What am I doing wrong?

Thanks

**Comment by Kozzi11** [comment]
I have same issue, every request died after 120 sec. Nginx + hhvm with fastcgi

**Comment by 1pulse** [comment]
I'd the same problem, because hhvm couldn't read my configuration, so it take the defaults.

/usr/bin/hhvm --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini --user www-data --mode daemon -vPidFile=/var/run/hhvm/pid
syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in /etc/hhvm/server.ini on line 79\n

Just commented any line and works great:
; hhvm.log.access.*.format = %h %l %u % t \"%r\" %>s %b
