### ISSUE TITLE
output buffering doesn't capture warnings

### ISSUE THREAD

**Issue by ptarjan** [facebook/hhvm#2672]
```
<?php

error_reporting(-1);
ob_start();
var_dump("GOOD");
var_dump(BAD);
ob_end_flush();
```

```
$ php-5.5 /tmp/a.php
string(4) "GOOD"

Notice: Use of undefined constant BAD - assumed 'BAD' in /tmp/a.php on line 6
string(3) "BAD"
```

```
$ hhvm /tmp/a.php

Notice: Use of undefined constant BAD - assumed 'BAD' in /tmp/a.php on line 6
string(4) "GOOD"
string(3) "BAD"
```

**Comment by tstarling** [comment]
This is the cause of several test failures in zend/bad/tests/output. I was able to resolve them with a proof-of-principle patch to ExecutionContext::handleError() which sends error messages to ExecutionContext::write() instead of Logger::Log().

Anyone have any thoughts on that approach? Logger is used by various things that presumably shouldn't go to the userspace output buffer, whereas ExecutionContext::handleError() is more specific.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

PHP style IO is going to conflict with native hsl-io (which is async to the core). Those ik methods don't mix, because of tearing when O_NONBLOCK is passed by hsl-io.

Output buffering could be implemented in userland as a WriteHandle on top of hsl-io.
