### ISSUE TITLE
Memory Leak in SimpleXML parsing an XML

### ISSUE THREAD

**Issue by nserban** [facebook/hhvm#2854]
SimpleXML leaks memory each time it parses a XML file.

Code to reproduce:

``` php
for ($i=0;$i<10000;$i++) {
        $myFeed = simplexml_load_file('test.xml');
        foreach ($myFeed->entry as $xmlEntry) {
            // Do something for every xml entry
        }
        if ( !($i % 2000) )
            echo round(memory_get_usage(true) / 1024 / 1024) . ' MB' . PHP_EOL;
    }
```

test.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<feed>
    <entry>
        <title>Title 1</title>
        <url>http://hhvm.com/</url>
    </entry>
    <entry>
        <title>Title 2</title>
        <url>http://hhvm.com/</url>
    </entry>
    <entry>
        <title>Title 3</title>
        <url>http://hhvm.com/</url>
    </entry>
    <entry>
        <title>Title 4</title>
        <url>http://hhvm.com/</url>
    </entry>
    <entry>
        <title>Title 5</title>
        <url>http://hhvm.com/</url>
    </entry>
</feed>
```

Output:

```
2 MB
25 MB
49 MB
72 MB
95 MB
```

HHVM Version:

```
HipHop VM 3.2.0-dev+2014.06.02 (rel)
Compiler: heads/master-0-gf43ae21551b3e37ec955bce770ca9a99677388fc
Repo schema: b6cc5eef6685b96a2185a5c1950f6c81ad8583b1
```

Although it can be reproduced with the stable version:

```
HipHop VM 3.1.0 (rel)
Compiler: tags/HHVM-3.1.0-0-g71ecbd8fb5e94b2a008387a2b5e9a8df5c6f5c7b
Repo schema: 88ae0db264d72ec2e2eb22ab25d717214aee568b
```

I try to free the memory using unset() or set the values on variables with NULL, but don't work.

Using PHP

```
PHP 5.4.28-1~dotdeb.1 (cli) (built: May  7 2014 22:16:44) 
```

The output is:

```
0 MB
0 MB
0 MB
0 MB
0 MB
```

Machine info: 

```
Debian 7
Linux donald 3.2.0-4-amd64 #1 SMP Debian 3.2.57-3+deb7u1 x86_64 GNU/Linux
Libxml2 version 2.8.0+dfsg1-7+nmu3  amd64 
```

**Comment by Kozzi11** [comment]
This issue is back with 3.9 version, can someone reopen this issue?

**Comment by JoelMarcey** [comment]
@Kozzi11 Can you provide a test case showing this?

**Comment by Kozzi11** [comment]
@JoelMarcey you can use that one from OP

**Comment by Orvid** [comment]
This is actually a more general problem with NativeData as a whole. Currently, most NativeData calls `sweep` in it's destructor, however, when a NativeData value is freed, it only calls the sweep function, which ends up not destroying any of the references that the NativeData may have acquired.

```C++
struct MyData {
  void* myMem;
  Object obj;
  ~MyData() { sweep(); }
  void sweep() { 
    if (myMem) delete myMem;
  }
}
```

Because of the way NativeData is freed, the reference contained by `obj` doesn't get released until the end of the request. 

If we make it so that the refs are released correctly, which is easiest to do by moving everything in `sweep` into the destructor and removing `sweep` entirely, we uncover even more problems when `obj` points to a NativeData object that was created after `MyData`, because it will be freed regardless of if there are still live references to it, meaning that, when we destruct `MyData`, and it's discovered that `obj` was the last live reference, we then try to destroy that same NativeData object again, resulting in a double free, and usually a segfault.

**Comment by JoelMarcey** [comment]
cc @edwinsmith

**Comment by paulbiss** [comment]
@Orvid: SimpleXML isn't using native-data. It's built on the old IDL system and it exists as an ObjectData subclass.

Native data will call it's destructor when it's associated object is freed, if this isn't happening that's definitely a bug. That being said-- if the object is live at the end of the request then sweep() is called but not the destructor. This is very intentional as request-heap allocated members of the object should not be deallocated explicitly during the sweep phase.

If you're looking for the logic for native-data destruction have a look at nativeDataInstanceDtor, it's stored as the instanceDtor for the native class and called whenever such object-data's are freed during a request.

**Comment by edwinsmith** [comment]
See my final comment on https://reviews.facebook.net/D46479. pretty sure it's a stray sxe->incRefCount() causing the leak.
