### ISSUE TITLE
Typechecker allows require_once $nullable_string

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#2926]
```
[fredemmott@devbig076 ~/hhtest] hh_client
No errors!
[fredemmott@devbig076 ~/hhtest] cat test.php
<?hh

function foo(?string $bar) {
  require_once $bar;
}
```

**Comment by lexidor** [comment]
I am going over old issues against this repository to reduce the amount of open issues.

The issue of `require_once`'s "first argument" not being typechecked is still true in hhvm today.
It joins the other statement keywords in being untyped `echo` f.e.

However, because of changes in the ecosystem, this is becoming less and less relevant. When this issue was made hhvm-autoload did not exist yet, so `require_once`'s in application code were far more common. These days, most Hack applications only require an autoloader `vendor/autoload.hack` and invoke `Facebook\AutoloadMap\initialize()`. Since top-level code (with the exception of declarations) was banned (even in partial mode), requiring a file for its side effects is no longer a thing. The only thing you can achieve using a require call, it bringing named entities into the request. However, because of autoloading, this is rarely if ever needed.
