### ISSUE TITLE
Typechecker should detect invalid key types

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3002]
Even if it doesn't know the type of the key, it could/should complain if it isn't an int or a string.

``` PHP
<?hh

function foo(array $bar): array {
  $bar[1.23] = 'that isnt a valid key';
  return $bar;
}

var_dump(foo([]));
```

```
[fredemmott@devbig076 ~/hhfail] hh_client
Server launched for /home/fredemmott/hhfail
Spawned hh_server (child pid=32209)
Logs will go to /tmp/doctrine2/hh_server_fredemmott/fredemmott-zShomezSfredemmottzShhfail.log
No errors!
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The default for making this a typechecker error for `darray<Tk, Tv>` and `dict<Tk, Tv>` was flipped from on to off a couple weeks ago. This option has existed for a while, but the default was off for a long while. This option did not exist when this issue was made.

The [blogpost for hhvm 4.54](https://hhvm.com/blog/2020/04/21/hhvm-4.54.html) states:
_Containers are now more consistently checked for valid arraykeys; this behavior can be enabled on old releases with the disallow_invalid_arraykey=true .hhconfig setting._
