### ISSUE TITLE
Add Framework TYPO3\Flow

### ISSUE THREAD

**Issue by kaystrobach** [facebook/hhvm#3007]
see https://git.typo3.org/Packages/TYPO3.Flow.git

**Comment by ryzy** [comment]
#2103 is about TYPO3 CMS, not about Flow.

TYPO3 CMS uses Flow internally, but I think Flow should be treated and added separately. It can be and is used separately, as a standalone framework.

@kaystrobach @fredemmott @tmotyl - what's your view?

**Comment by tmotyl** [comment]
hi,
TYPO3 Flow is a different product then TYPO3 CMS.
I can provide a pull request with Flow unit tests.

**Comment by kaystrobach** [comment]
:+1:

**Comment by ryzy** [comment]
Exactly, I'm glad to see consensus here ;-)

@tmotyl would be awesome! I wanted to do it myself, but I guess I'd have to figure out few things before... Ping me if I can help in anything, thanks!

**Comment by tmotyl** [comment]
I've run into the timeout while installing the framework (during composer install). I haven't  got enough time to dig into the issue, so I've just referenced a commit with basic configuration.

**Comment by ryzy** [comment]
Are you able to increase the COMPOSER_PROCESS_TIMEOUT there? The default value 300 usually doesn't work... COMPOSER_PROCESS_TIMEOUT=900 works for me 99.9% times ;)

Also, I would specify branch `3.0` (which is currently in beta - see https://git.typo3.org/Packages/TYPO3.Flow.git). Version 2.3 doesn't work at all with HHVM due to some fundamental incompatibilities.

**Comment by tmotyl** [comment]
Thanks for the hint @ryzy 
I've updated the configuration and created a pull request.
It gives me 99.98% result

**Comment by fredemmott** [comment]
reverting the diff, breaks the test runner
