### ISSUE TITLE
Behavior diff: PDOStatement fetch-class throws an exception when constructor params === array()

### ISSUE THREAD

**Issue by iansltx** [facebook/hhvm#3041]
In Zend-land, supplying _null_ as the second param of PDOStatement::fetchObject(), or third param of PDOStatement::fetchAll(), throws a type mismatch error, but works with an empty array.

https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/ext_pdo.cpp#L755

Thanks to the above, an empty array doesn't work as a parameter in HHVM; null must be used. Omitting the parameter works on both runtimes, but the behavior is inconsistent.

**Comment by lexidor** [comment]
Removing @AlphaStream 's assignment.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version 4.0.0.

The current behavior, although different, is not buggy or broken. The default argument is/has been `null` for a long while. Changing it to allow `vec[]` as well as `null` would be a compatibility fix. As it stands, no callers are passing `vec[]`.

No runtime oblivious code (that runs on a support hhvm version and a supported php version) exists today, so interop is not a compelling reason to equalize. Compatibility with the php dot net docs would be a plus, but hhvm has diverged massively in many other areas. The php dot net docs are on a Trust but Verify basis for extensions and even basic language behavior.
