### ISSUE TITLE
file_exists does_not_exist/../ does not work the same way as PHP5

### ISSUE THREAD

**Issue by huzhiguang** [facebook/hhvm#3148]
replay way:

```
<?php
 $flag = file_exists("a/b/../a.txt");
 var_dump($flag);
 ?>
```

b folder is don't exists.

a.txt real location is a/a.txt 

php  exec result:

bool(false)

hhvm exec result:

bool(true)

**Comment by jesseschalken** [comment]
Simple test: https://3v4l.org/Q59Ms

**Comment by jesseschalken** [comment]
This is also broken in the case of symlinks: if `a/b` is a symlink, `a/b/..` refers to the parent of the symlink destination, not `a/..`.

Example:

```
$ mkdir test && cd test
$ mkdir a
$ mkdir a/b
$ touch a/c
$ ln -s a/b d
$ php -r 'var_dump(file_exists("./d/../c"));'
bool(true)
$ hhvm --php -r 'var_dump(file_exists("./d/../c"));'
bool(false)
$
```
PHP returns `true` (correct) while HHVM returns `false` because it checked `./c` instead of `./a/c`.

As far as I know, the only safe canonicalization that can be done to a POSIX path without consulting the file system is removing trailing `/` chars and collapsing multiple `/` into a single `/`. Replacing `/./` with `/` may also be safe, I'm not sure.

**Comment by huzhiguang** [comment]
@jesseschalken ,we have fixed this bug,I provide PR can solve this problem,I have been verified.

**Comment by binliu19** [comment]
@mofarrell Could you or someone look at @huzhiguang's PR here?  If I understand correctly, this brought a big win for Baidu.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version 4.0.0.

The current behavior, although different, is not buggy or broken. This very similar to this realpath #8298 issue. Hhvm will resolve `..` early. I have explained my rationale for closing the issue there.
