### ISSUE TITLE
Argument 4 to hash_hmac() must be of type ?bool, int given

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#3185]
We have just been trying oauth (with Magento Enterprise 1.14) and we are getting an issue with:

```
oauth_problem=internal_error&message=Recoverable Error: Argument 4 to hash_hmac() must be of type ?bool, int given  in /var/www/vhosts/magento-capistrano/releases/20140714132429/lib/Zend/Crypt/Hmac.php on line 150
```

We are using wget to simulate the request.

```
GET /oauth/initiate?oauth_callback=http%3A%2F%2Fwww.google.com&oauth_consumer_key=xxx=HMAC-SHA1&oauth_nonce=xxx&oauth_timestamp=xxx&oauth_version=1.0&oauth_signature=xxx
```

The following line of code throws the error from Zend/Crypt/Hmac.php:

```
return hash_hmac(self::$_hashAlgorithm, $data, self::$_key, 1);
```

I think the issue is potentially in Zend itself - the documentation say's the last parameter should be a bool but Zend are passing an integer - the question is this a hphp issue or an issue with the Zend code? The exception doesn't seem to get handled (nothing is output in our error logs or browser)

The code works without issue with PHP 5.5

This is my hhvm error log reporting:

```
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
```

**Comment by Mic2005** [comment]
@craigcarnell where can i find this Zend Framework fix? I get the same error: Recoverable Error: Argument 4 to hash_hmac() must be of type ?bool, int given  in /home2/verz/public_html/lib/Zend/Crypt/Hmac.php on line 150
Run@ Magento CE 1.7.0.2 hhvm/redis/fpc

**Comment by craigcarnell** [comment]
@Mic2005 Edit  lib/Zend/Crypt/Hmac.php

Change the last parameter of hash_hmac to true instead of 1

**Comment by fredemmott** [comment]
(we generally want to make HHVM fine with these, and it's one of a category of bugs)

**Comment by Mic2005** [comment]
@craigcarnell do you mean this: return hash_hmac(self::$_hashAlgorithm, $data, self::$_key, 1);
and change it to: return hash_hmac(self::$_hashAlgorithm, $data, self::$_key, true);

**Comment by craigcarnell** [comment]
@Mic2005 Exactly 1 == true

**Comment by Mic2005** [comment]
Works. Error is gone :)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue is still valid in 2020, but for a different reason.
The hhi for `hash_hmac()` is four TAny (unchecked) parameters, but the runtime type of the fourth parameter is `?bool`.
The TypeError is correct behavior, because of a change made back in [hhvm 4.3.0](https://hhvm.com/blog/2019/04/30/hhvm-4.3.0.html), which turned calling a built-in function with incorrect types into TypeErrors instead of coercions.

I will open a new issue for the hhi failure to indicate the runtime type, and refer back to this issue.
This issue will not be fixed as is, but the hhi could be updated to reflect the runtime behavior.
