### ISSUE TITLE
New hack mode: require typehints for definitions in that file, but allow calling non-Hack code

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#3273]
Request from Davey on freenode.

Behavior should be:
- Every definition in that file _requires_ a type hint; same as strict, unlike partial or decl
- Still allow calling untyped functions; like partial or decl, unlike strict

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This matches the current behavior of `// strict` mode. I wasn't involved with hhvm in 2014, when this issue was made, and I have two conflicting ideas about what the issue author could have meant.
Either _untyped_ means, a Hack function in a partial or decl file, with missing parameter / return types _or_ it means an undeclared / php function.

PHP functions can not be called in hhvm anymore, since PHP support was dropped with the release of [hhvm 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
Strict code can call `// partial` and `// decl` code since at least hhvm 3.24.

**Comment by jwatzman** [comment]
Yeah I suspect "calling untyped functions" likely referred to the ancient `assume_php`, which used to be available in partial/decl but not strict. AFAIK it's entirely gone now and has been for a very long time.
