### ISSUE TITLE
Stack overflow on certain DB requests

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#3305]
Loading certain CMS pages on Magento for example, this is difficult to narrow down at the moment

```
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Adapter/Abstract.php on line 980
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Adapter/Abstract.php on line 980
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Select.php on line 843
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Select.php on line 843
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Adapter/Abstract.php on line 980
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Select.php on line 843
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Adapter/Abstract.php on line 980
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Select.php on line 843
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Select.php on line 843
\nFatal error: Stack overflow in /var/www/vhosts/magento-capistrano/releases/20140729142916/lib/Zend/Db/Select.php on line 843
```

**Comment by TheBlaze** [comment]
Hello,

We are also running Magento on HHVM and ran into the same error:

[Mon Mar 21 12:32:35 2016] [hphp] [18947:7f98d8bff700:122:000001] [] \nFatal error: Stack overflow in /mnt/web/magento_1141/htdocs/lib/Zend/Db/Select.php on line 843

We can repeat the error. If you have a certain frontend cookie the error happens every time, on every request. The problem is, that it only happens on the production server. What can I do, to help solve this? What information do you need and how can I get it?

Thank you,
Blaž

**Comment by paulbiss** [comment]
Knowing the PHP stack trace would be a start, if there's a builtin you're calling that sets this off that would also be good to know.

**Comment by aftabnaveed** [comment]
This issue still exists, and consistent with cookies.

**Comment by babar-ali** [comment]
Clearing magento session resolve this issue, but its temporary solution. 
Not yet found the reason how these cookies generated and how to stopped them permanently.

**Comment by ryne-andal** [comment]
Suffering through the same issue here. Not 100% certain on the specific cause, but clearing sessions resolves the issue temporarily, then it happens again.

**Comment by aftabnaveed** [comment]
@ryne-andal try clearing your session container if you are using Redis or Memcache then flush its entire cache.

**Comment by ryne-andal** [comment]
Yeah I've begun transitioning to PHP7 as well, @aftabnaveed. Upon clearing *all* caching and sessions, it still occurs almost immediately. I'm suspecting one of the third-party modules aren't playing nicely with HHVM, since it doesn't occur on my local running PHP7. I'll finish the transition and deploy accordingly, was just hoping to resolve the issue with a minimal amount of work since it's a legacy system.

Appreciate the assistance and good luck with migrations to PHP7.

**Comment by aftabnaveed** [comment]
@ryne-andal we came with a workaround though. If you are using nginx then catch the 500 error response from the upstream and proxy your request internally to another script which clears the corrupted session for you and then redirect the user silently. 

I know that is a dirty hack but this really worked for us during last holiday season and we are still relying on it. The only drawback to that solution is that the customer gets out and has to relogin.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue, since the chances that the owner of this issue wants to invest effort into this seems small. If you are reading this and have a way to reproduce this issue on a modern hhvm version, please reopen the issue and add this repro.
