### ISSUE TITLE
Access log in fastcgi mode

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#3324]
Is this possible? All I see under ini settings are: hhvm.log.access_log_default_format, not where to turn it off/on or set the file location

**Comment by cmthornton** [comment]
Any updates on this?

I'm using the `ini` configuration and I have been maintaining my own init script for hhvm. I have been setting the `access.log` via `hhvm --config /etc/hhvm/server.ini --user www-data -vLog.Access.\*.File=/var/log/hhvm/hhvm.log --mode daemon`.

I don't like this solution and I don't recommend this unless you *really* want an `access.log` and you need to use the `ini` format over `hdf`, or you have another reason for maintaining an init script, e.g. you need to source `/etc/sysconfig/hhvm` too.

**Comment by imacki** [comment]
This is still a problem in 3.11 (in Debian Testing).
I had to create a file "server.hdf" containing the old-style notation given above by ck-on (3 Aug 2014) using Log { ... }, as well as a server.ini file with all my other proxygen settings, and then run:
   hhvm -c server.ini -c server.hdf -m server
in order to get a properly named and formatted access log file when running in server mode. I tried the documented server.ini directive:
   hhvm.log.access[access.log] = %h %l %u %t ”%r" %>s %b 
but what I got was a file literally called "%h %l %u %t \”%r\" %>s %b" with the correctly formatted lines inside. It seems that proxygen is using the format string as *both* the log filename and the log format, regardless of what filename or path you put in the square brackets.
This should be a simple problem to fix, I think.

**Comment by wulftone** [comment]
I can verify @imacki 's issue, I'm seeing the same thing in 3.17.1-0.

I managed to get something by doing 

```
hhvm.log.access["file"]="access.log %h %l %u %t %r %>s %b"
```
It outputs into a file that is literally named `access.log %h %l %u %t %r %>s %b`, and here's a sample log line: 
```
access.log 172.18.0.1 - - [27/Jan/2017:14:01:32 -0800] POST /review HTTP/1.1 200 1405
```

Which includes the word "access.log"... All attempts to use the `["file"]` as a filename holder failed.

I would love to have this access log output on stdout or stderr.  Please advise!

**Comment by wwbmmm** [comment]
I had the same problem. Finally I try use this config and it works:

```ini
hhvm.log.access_log_default_format="%h %l %u %t %r %>s %b"
hhvm.log.access["a"]["file"]=access.log
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue has been resolved in the comments.
