### ISSUE TITLE
HHVM is lacking the PDORow class

### ISSUE THREAD

**Issue by Ocramius** [facebook/hhvm#3432]
See http://3v4l.org/9HBss

`PDORow` is not a defined class in hhvm.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The PDORow class is missing. Hhvm does not implement the lazy data loading as described. I am closing this issue (unresolved).

If any current or future user of hhvm uses PDO in a manner that would benefit from lazy data loading, please open a new issue. I have a strong suspicion that lazy loading data separately from each row would incur high request latencies.
