### ISSUE TITLE
Finish implementing PharData

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/hhvm#3514]
This class is only partially implemented. Many methods throw `Not implemented yet` exceptions.

**Comment by fredemmott** [comment]
Most read stuff is there, most (all?) write stuff is missing.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Support for phars was removed in hhvm [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html)
_The phar extension has been removed, as HHVM does not support building phars and was no longer able to execute PHP phars._
