### ISSUE TITLE
HHVM does not support custom .ini directives through get_cfg_var()

### ISSUE THREAD

**Issue by Swahvay** [facebook/hhvm#3754]
PHP allows you to specify whatever you want in your php.ini file and reference it through `get_cfg_var()`, this doesn't work in HHVM though, as it always returns false.

**Comment by jwwisniewski** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by jwwisniewski** [comment]
+1 for the fix

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not buggy or broken. Any unknown ini directives are ignored. This means get_cfg_var can't access them anymore. Configuring application level state through a runtime ini file is not supported.
