### ISSUE TITLE
ini_set doesn't work for EZC (mongo and yaml, at least)

### ISSUE THREAD

**Issue by rrh** [facebook/hhvm#4073]
This piece of php code gives different results for zend/php vs hhvm.  hhvm doesn't appear to evaluate ini_set correctly.

<?php
printf("yaml.output_indent %d<br>\n", ini_get("yaml.output_indent"));
ini_set("yaml.output_indent", 5);  /\* defaults to 2 */
printf("yaml.output_indent %d<br>\n", ini_get("yaml.output_indent"));

php5 (zend) gives:
  yaml.output_indent 2<br>
  yaml.output_indent 5<br>

but hhvm -dhhvm.enable_zend_compat=true gives
  yaml.output_indent 2<br>
  yaml.output_indent 2<br>

There are no tests, either good or bad, of ini_set for the 3+ EZC packages: pcre, mongo, yaml

@JoelMarcey

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I can't reproduce your issue anymore, since both yaml and mongo are nolonger supported by hhvm.
The `enable_zend_compat` option is nolonger recognized by hhvm either.
If this is a an issue today, could you please add a repro and reopen the issue?
