### ISSUE TITLE
Namespaces and Build-in Classes

### ISSUE THREAD

**Issue by dk-zero-cool** [facebook/hhvm#4106]
So I got this error `Name already bound: Collection` when trying to name a class `Container`. However I did not actually name it `Container` but `MyNameSpace\Container`. The error actually makes sense, since I do not need to add `use ClassName` in order to use the build-in classes, unlike when using PHP's classes. 

It is quite simple to just choose another name, but what about in the future? Some time down the road, you decide to create a new class and name it something that is already used in my own code? Then my code will be broken. This is one of the reasons why I use namespaces. Any chance that HHVM/Hack will get better support for this in the future? Classes should not penetrate namespaces unless explicitly told to by the means of `use ClassName`.

But like I said, for now I don't really care, I will just rename it. I am just a little concerned about future problems. And I really do not want to prefix all classes, since namespaces is already a form of prefix.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It is now possible (but not recommended) to declare entities with the same names as autoimported entities.

You will need to refer to them explicitly in other files though, since using `Container` instead of `\Container` would refer to the `\HH\Container` interface instead.
```
/// file.hack
final class Container {
    public function __construct(string $a) {
        echo $a;
    }
}

/// file2.hack
<<__EntryPoint>>
function main(): void {
    require_once __DIR__.'/file.hack';
    new \Container('a');
}

// With `\`, echoes a
// Without `\` Uncaught Error: Cannot instantiate interface HH\Container
```
