### ISSUE TITLE
Investigate create_function() memory leaks

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4250]
cc @huzhiguang, @reeze, @lbadger, @ibrezac
mentioned in #2851
Memory leak #4 on http://lamp.baidu.com/2014/11/03/hhvm-in-baidu/

**Comment by wjywbs** [comment]
Another leak is to make a static string of "aaa..." as the argument of var_dump.
https://github.com/facebook/hhvm/blob/c5a485f66c07cad8945b4bd6ca3186e1b8c89e40/hphp/compiler/analysis/emitter.cpp#L4508

**Comment by corientdev** [comment]
Guys any solution on this i am still having the issue hhvm stops every 4-5 days.

Wondering if i can edit something in wordpress to stop this..? Because i don't have any plans to run my wordpress set up on php-fpm so i can modify the wordpress script to make it fully compatible with HHV. Please someone help its frustrating..

**Comment by gferon** [comment]
It's actually quite easy, as stated in another ticket, you need to replace `create_function` calls by anonymous functions.

Example: in `wp-includes/pomo/po.php`, you need to replace
```php
$is_final = create_function('$context', 'return $context == "msgstr" || $context == "msgstr_plural";');
```

by
```php
$is_final = function($context) {
	return $context == "msgstr" || $context == "msgstr_plural";
};
```

There is another call to `create_function` in this file, one in `wp-includes/pomo/translations.php`. There might also be more calls in whatever Wordpress plugin you use.

**Comment by corientdev** [comment]
Any clue why hhvm does not support this `create_function`? i mean it seems pretty do able and will enhance the compatibility of hhvm with php.

Curious to know..

**Comment by huzhiguang** [comment]
@corientdev ,hhvm support create_function,but this feature will affect hhvm performance.

**Comment by corientdev** [comment]
let it affect thats not the concern for me but why it causes memory leaks and ultimately stops the daomon?

**Comment by paulbiss** [comment]
8d0bac44832df988cba9f247beaec5e7041ef6ed

**Comment by wjywbs** [comment]
@paulbiss I think the static strings created during `compile_string()` are still not freed, right? In Fred's https://github.com/facebook/hhvm/issues/4250#issuecomment-63901992, a static string of "aaa..." will be   created as the argument of var_dump. This leaks much faster than the bytecode.

(Note that my PR #4607 wasn't accepted. https://reviews.facebook.net/D31263)

**Comment by paulbiss** [comment]
@wjywbs It does, but static strings being leaked is a much broader problem. It's true of eval, as well as in the case of editing or deleting php files containing strings not referenced elsewhere.

I'd like to come up with a solution to this but it's not really within the scope of this issue, and it's probably something for which we'll need to use Uncounted strings instead of StaticStrings (doing this in non-repo mode would probably be acceptable).

I'm currently in the process of addressing the problem of leaks in the TC, but strings are the next thing I plan to go after.
