### ISSUE TITLE
3.4.0 (official hhvm-3.4.0~trusty package) eats all memory+swap

### ISSUE THREAD

**Issue by tat** [facebook/hhvm#4268]
I upgraded my aws instances (c3.large) to 3.4.0 (official packages got from http://dl.hhvm.com/ubuntu) and all of them get killed by oom-killer after eating all RAM and swap in about 5 minutes (getting about 300 requests per minute).

Is there anything I can check to track down the issue?

My server.ini:
pid = /var/run/hhvm/pid
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.resource_limit.max_socket = 10000
hhvm.log.header = true

Thanks,
stefano

**Comment by HumanWorks** [comment]
I had the same problem with HHVM + wordpress, the server was crashing every time we were posting something new. It turns out that the simple solution that works is just disable the "Try to automatically compress the sitemap if the requesting client supports it" setting in XML sitemaps plugin.
Hope this will help (I know it's not a real solution to hhvm but at least it will work for many wordpress installations out there)

**Comment by paulbiss** [comment]
@HumanWorks the problem we were tracking here turned out to be a memory leak in boost that was being triggered in the JIT, it's been fixed since 3.4.1 and isn't present in 3.3. If you're seeing a different leak I would suggest opening a new issue.

**Comment by craigcarnell** [comment]
@paulbiss Any idea on when 3.6.0 will make it's way out of the door?

**Comment by paulbiss** [comment]
@craigcarnell I think the plan is start rolling packages today or tomorrow (our packager isn't the fastest box...), I've got one more cherry-pick I need to push. It's been a busy week for everyone and we haven't had a chance to update the packaging system to push a second LTS.
