### ISSUE TITLE
Support hack collection literals as constants

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#4279]
As these are objects we should probably only support the immutable variants if we decide to do this. 

Follow up to #4277

**Comment by doublecompile** [comment]
```hack
class Foo
{
    const ImmSet<string> STUFF = ImmSet{'foo', 'bar'};
}
```
Agreed. This would be awesome!

**Comment by lexidor** [comment]
@Wilfred this is allowed by the runtime, but not by the typechecker.
```
<<__EntryPoint>>
function main(): void {
    \var_dump(Foo::STUFF);
}

class Foo {
    const ImmSet<string> STUFF = ImmSet {'foo', 'bar'};
}
```

```
hhvm file.hack 
object(HH\ImmSet) (2) {
  string(3) "foo"
  string(3) "bar"
}

hh_client
Naming[2023] Illegal constant value
   --> file.hack
  7 |     const ImmSet<string> STUFF = ImmSet {'foo', 'bar'};
    |                                  ^^^^^^

1 error found.
```

Which one is correct?

**Comment by Wilfred** [comment]
I don't think we're interested in supporting collection literals as constants these days (this issue was originally filed in 2014).

`keyset['foo', 'bar']` is faster and makes a little more sense in a constant position, because it's a value type.

I'd consider the typechecker to be correct here. HHVM could in principle stop supporting this (although I'm not aware of any plans to do so).

**Comment by lexidor** [comment]
Indeed, let's encourage `dict`, `keyset`, and `vec` usage. If the need it great, `new Set(cls::KEYSET_CONST)` is an option for the callling code.

Closing this issue, because Hack is slowly steering away from legacy Hack Collections.

**Comment by luisaglez1** [comment]
Now who had the problem of having entered to hack Facebook on a page that began to collect a lot of your personal information and this in turn began to worry about the insecurity that is occurring in these times, for which you need to be very persevering to be able to achieve what you propose and in this circumstance is how you only need to enter this page that will really be very useful to you, so hack in time and form.
I wanted to **[hack Facebook](https://hackfreeonline.com/facebook/
)** without programs because there is a person who interests me and who I like in short and attracts a lot of attention for which it is entirely my opinion the person with whom I want to start a relationship only that I am a very shy person and I do not dare to talk to this person for which is that I would only dare to meet this person or to invite him/her out if I could know for sure what it is that he/she likes so that I can take him/her into account and I can talk to him/her so that from this and that I do not know anyone who is his/her stew and our common link.
I had to [hack Facebook](https://hackfreeonline.com/facebook/
) easy to be able to get closer, so then I set out to find our common link and what better Snapchat here you can find that person who catches your attention and you can get to know her better but the dream needed was something more special that would unite us and not just something that she shares superficially on her wall but something deeper but something more special because from this it was that I only set out to find some good source of information that would help me achieve my goal and hack Facebook easy so I entered the word hack on the internet and the truth is that many options appeared to me and it lasted a long time.
