### ISSUE TITLE
__DIR__ inside phar file in HHVM is not the same as in PHP5

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4313]
I've create regular phar archive with stub:

``` php
<?php
if (PHP_SAPI == 'cli') {
    Phar::mapPhar('cleverstyle_cms.phar');
    include 'phar://cleverstyle_cms.phar/install.php';
} else {
    Phar::webPhar(null, 'install.php');
}
__HALT_COMPILER();
```

When running from CLI inside `install.php` `__DIR__` constant is not the same.

PHP5:

> $ php distributive.phar.php
> phar:///web/test.com/www/distributive.phar.php

HHVM:

> $ hhvm distributive.phar.php
> phar://cleverstyle_cms.phar

I'm not familiar enough with HHVM codebase to find where it occurs and to fix it.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Support for the phar extension was dropped from hhvm [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
