### ISSUE TITLE
curl_setopt_array complains about invalid option 91

### ISSUE THREAD

**Issue by mmucklo** [facebook/hhvm#4374]
curl_setopt_array is complaining about an invalid option 91.

option 91 is: CURLOPT_DNS_USE_GLOBAL_CACHE

An example warning message would be:

Warning: Invalid argument: option: 91 in /home/someone/src/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php on line 53

Where line 53 simply does this:
```php
        curl_setopt_array($handle, $options);
```

**Comment by reeze** [comment]
it seems that was turned off because of thread-safety issue
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/curl/ext_curl.cpp#L390.

But PHP use it: https://github.com/php/php-src/blob/e3012d0f6c48fc6453d74b3be3556b20a5201448/ext/curl/interface.c#L1841  

if PHP use a multi-thread mode it might have problem too, I  am not sure if there is a good method to support it.   Anyway it is not recommended to use it, http://curl.haxx.se/libcurl/c/CURLOPT_DNS_USE_GLOBAL_CACHE.html

**Comment by mmucklo** [comment]
Ok good to know, thanks.



On Jan 10, 2015, at 5:55 AM, Reeze Xia <notifications@github.com> wrote:

it seems that was turned off because of thread-safety issue
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/curl/ext_curl.cpp#L390
.

But PHP use it:
https://github.com/php/php-src/blob/e3012d0f6c48fc6453d74b3be3556b20a5201448/ext/curl/interface.c#L1841

if PHP use a multi-thread mode it might have problem too, I am not sure if
there is a good method to support it. Anyway it is not recommended to use
it, http://curl.haxx.se/libcurl/c/CURLOPT_DNS_USE_GLOBAL_CACHE.html

—
Reply to this email directly or view it on GitHub
<https://github.com/facebook/hhvm/issues/4374#issuecomment-69456502>.

**Comment by Orvid** [comment]
I believe we were likely defining the constant even though the version of libcurl that HHVM was built against didn't define it. That would have been fixed when things were moved out of IDL.
