### ISSUE TITLE
gzinflate fails in hhvm not in php

### ISSUE THREAD

**Issue by Migueleneo** [facebook/hhvm#4406]
Hello
This program:
<?php
$file=file_get_contents("test.zip");
echo gzinflate(substr($file,10,-8));
echo file_get_contents('compress.zlib://data:who/cares;base64,'. base64_encode($file));
?>
works in php fine both echoes. Both fail in hhvm 3.4

I think this is something related with the way Servlet does compress not compatible in hhvm

Test.zip is a zipped XML text I got from an external website, I stripped off the headers and saved it to disk.
The headers of this call are:
Date: Mon, 08 Dec 2014 12:51:28 GMT
Server: Apache/2.2.15 (CentOS) X-Powered-By: Servlet 2.4; JBoss-4.3.0.GA_CP08 (build: SVNTag=JBPAPP_4_3_0_GA_CP08 date=201004202136)/JBossWeb-2.0
Connection: close
Content-Type: text/xml;charset=UTF-8^M
Vary: Accept-Encoding
Content-Encoding: gzip

any help?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I can't download your zip from http://www.keepandshare.com/doc14/6534/miguelprueba-zip-112k?da=y anymore. I can't see if the problem in gzinflate still exists. I am closing this issue, since the repro is lost. If you still have that file and the problem still occurs, could you please reupload it and reopen the issue?

![image](https://user-images.githubusercontent.com/31805625/82371088-e67c7f00-9a19-11ea-8ead-7b008af44183.png)
