### ISSUE TITLE
stat(), is_dir(), realpath() have absolutely terrible performance

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4431]
``` PHP
<?php

function main() {
  $start = microtime(true);
  for($i = 0; $i < 100000; ++$i) {
    is_dir(__FILE__);
    realpath(__FILE__);
    stat(__FILE__);
  }
  $end = microtime(true);
  var_dump($end - $start);
}

main();
```

```
[fredemmott@devbig076 ~] php5 test.php
float(0.24126386642456)
[fredemmott@devbig076 ~] phpng test.php
float(0.17168688774109)
[fredemmott@devbig076 ~] hhvm -v Eval.Jit=1 test.php
float(3.3344538211823)
[fredemmott@devbig076 ~] hhvm -v Eval.Jit=0 test.php
float(4.2481589317322)
```

Based on xhprof and 'perf', this is a major issue for Drupal7, Magento, and SugarCRM.

I'll be working on this. The user functions do not use statcache, but even if I forcibly change that, performance does not improve.

**Comment by joshuataylor** [comment]
Just wanted to make a note anyone stumbling across this issue and is using Drupal.

If you're doing profiling with Drupal, and seeing thousands of dir finds with PHP, it's because there is probably a missing module somewhere.

You can use drush to find and remove missing modules:
`drush dl clean_missing_modules
drush clean-modules`

This should remove those thousands of calls.

**Comment by alex-moreno** [comment]
this Drupal problem that you mention @joshuataylor should be mitigated by this patch: https://www.drupal.org/node/1081266?page=1

Just for the sake of information. We had some performance issues recently that were solved or mitigated by this.
