### ISSUE TITLE
Since yesterday, HHVM cpu isnow 99.9% and causing 504 errors every few seconds

### ISSUE THREAD

**Issue by tarsupin** [facebook/hhvm#4434]
Until yesterday, this wasn't an issue (or at least not one I'd identified, and certainly not happening every few seconds). If I restart hhvm now, it basically crashes immediately. I have a script to restart HHVM automatically when "service hhvm status" is set to not running, but HHVM apparently is running for this issue, so I'm doing it manually... and really only for the sake of debugging at this point, since it's clearly breaking.

What's happening is that I'm getting 504 errors constantly. Every few seconds, HHVM will just fail to deliver. I can't find anything in the hhvm error logs that are out of the ordinary - just failures to connect to the database when it's down and "Finished singleJitRequest #"

A "top" command shows that HHVM is running at 99.x% CPU and 16%-ish memory usage.

We're running about 15 other servers just like this (literally almost identical). About 13 of them are $10 linode servers (including this one), and another two are on more powerful linodes. However, this one is the only one that is having the issue every few minutes. It's one of the higher traffic servers, but not the highest. All of the others appear to be fine. I've tried googling the issue, but haven't found anything that really identifies why this particular server is causing any trouble.

It began happening yesterday and I did "apt-get upgrade hhvm" and got a more recent version. That has not resolved the issue - in fact, the issue is recurring faster than it was last night.

I'm on Ubuntu 14.04 LTS, A reset did not resolve the issue - it's happening with the same frequency.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue, since asking for more info and adding a _`needs-more-info`+`no-isolated-repro`-combo_ would turn a large percentage of hhvm's issues into this kind of issue. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.
