### ISSUE TITLE
"Throws" annotation

### ISSUE THREAD

**Issue by kilahm** [facebook/hhvm#4482]
Sometimes keeping track of which methods possibly throw various types of exceptions is difficult, allowing some exceptions to be thrown completely uncaught.

Would it be possible to add a feature to the Hack language where we can annotate a function or method as being allowed to throw a particular class of exception, or list of exceptions.  Could this be exposed through a magic annotation `<<__Throws(string ExceptionClass, ...)>>`?

The type checker can then detect if an uncaught exception could be thrown from the calling code.  This type of checking would only occur in strict mode files.

As an example:

```php
<?hh // strict

<<__Throws(ExceptionSubClass::class)>>
function it_throws() : void
{
  throw new ExceptionSubClass();
}

function safe_through_try() : void
{
  try{
    it_throws();
  } catch(Exception $e) {
    // Do stuff
  }
}

<<__Throws(Exception::class)>>
function safe_through_annotation() : void
{
  it_throws();
}

function not_safe() : void
{
  it_throws();
}
```

Type checking the above code should produce an error that says `not_safe()` should either handle exception `ExceptionSubClass` or annotate that `not_safe()` may throw `ExceptionSubClass`.

Java has a similar language construct through the keyword `throws`.

**Comment by jwatzman** [comment]
> The magic annotation `<<__Throws(...)>>` attached to a function or method would be a white list of exceptions that that function or method may throw when it is invoked.

The problem with this (i.e., with checked exceptions) is that this is the transitive closure of all exceptions that you or anything you call (or that calls etc) might possibly throw that isn't immediately handled -- which for a lot of functions, is most types of exceptions. As said above, if you can't handle an exception, you shouldn't... except checked exceptions lead to adding a huge list of stuff you don't deal with, you easily end up with the entire world in your `throws` list.

Let me give a concrete example, pulling from how FB's feed is put together. (I used to work on feed here, so it's my usual example for everything :-P)

Consider how the profile picture in the upper-left of every news feed story is rendered. From the top down, we have

1. Page render function
2. News feed render function
3. Individual feed story render function
4. Header render function
5. User fetch function (so we can get a user's profile picture)

Each of those steps is probably 2-3 different functions, I'm dramatically oversimplifying here. The way feed works, you can't always see every story the backend returns, so it's possible for the user fetch to fail if you can't actually see the user. If this happens, we want to remove the story. The way this works is that the user fetch function checks privacy and throws a `CannotSeeException` if you're trying to load something you can't see. There's nothing many of the layers above this can do about it -- if you can't see the user that posted the story, you can't do much. So this exception percolates all the way up to the news feed render function, which catches it, skips that story, and moves on to the next one. (This what I mean by error boundary -- the news feed render function contains an "error boundary" which just catches most classes of exceptions, logs them, kills the story that threw them, and moves on to the next one.)

Without checked exceptions, this works well, each layer doesn't have to worry about the failure -- most `CannotSeeException`s aren't locally recoverable, so you just let it get thrown on up. But with checked exceptions, every single one of the functions in those two layers have to declare it may throw a `CannotSeeException` -- and that's a *lot* of functions, since it's not just the ones in my example, but *any* function which may fetch a user in news feed (which is basically all of them).

And it's not just `CannotSeeException`. Similar things happen with `DatabaseDownException` -- you can't do anything but let that go up to the error boundary and kill the news feed story that threw it. Etc etc, there are a long list of these. Not all of them fit under the same hierarchy, so you can't just declare that you throw some superclass, and now you have a laundry list of exceptions that basically every function in the codebase may throw. Super ugly.

> I just realized I didn't address the issue of languages other than Java having this construct... in my 10 minutes of googling I didn't find any. However I don't think this is a valid reason for not including the construct in Hack.

Agreed, no other language picking it up is definitely not a sole reason we shouldn't include it, but it definitely gives me pause.

> I find Java's checked exceptions horrible. Most of the time they produce one of the two lines of code

Yeah, that's basically my thought, with an addition of a third case: a laundry list of exceptions which can be thrown.

**Comment by kilahm** [comment]
@jwatzman, it looks to me like you reiterated your arguments in more words, but that the contents of your arguments have not changed.  This tells me that we simply disagree on the utility of this feature.  To make sure I understand our different beliefs:

You believe the list of allowed exceptions could become excessively long, making for many lines of code that are difficult to read and maintain.  I believe the list of allowed exceptions should never be longer than 3 or 4 with proper grouping of exceptions through an exception class hierarchy which would be small enough to make burden of maintaining this list worth the value to the consumer of the function.

We both believe that if a function can't handle an exception, it shouldn't catch it.  You believe exceptions should be able to bubble up through the function without the function knowing about them at all.  I believe the function should explicitly declare that it cannot handle exceptions of a particular type when it is possible for the exception to be thrown from the function or a function it calls.

Unless I am mistaken in my characterizations of our beliefs, or there is another argument, it seems like this feature has been considered and rejected.

**Comment by jwatzman** [comment]
> This tells me that we simply disagree on the utility of this feature.

Yeah, I think this is fair.

> I believe the list of allowed exceptions should never be longer than 3 or 4

I think that even this is way too many if it's attached to basically every function. It's completely meaningless if the same N exceptions are attached to every function, for any value of N.

> it seems like this feature has been considered and rejected.

I'm certainly pretty against adding this feature -- but I'm not the only one responsible for making decisions about features in Hack :) Other folks on the team could still be convinced, and they could convince me, not that I have to sign off on everything anyways.

So I'm going to actually keep this open, in case anyone else has any further discussion, but there are no plans to add this feature, and if you're interested in writing a PR for it, please get an OK from us *beforehand* to make sure that it would be accepted. (Even if we won't build it, I wouldn't be against taking a PR for it if it could be built in such a way that didn't get in the way of anyone who didn't want to use the feature, but this also includes maintenance cost of a feature we don't care much about.)

**Comment by paulbiss** [comment]
There's a lot of good discussion here. Unfortunately I don't think that anyone is particularly excited about having this in the language. I'm going to close this for now but if there are strong dissenting opinions I'm happy to hear new arguments.

**Comment by gdbentley** [comment]
Sorry for the late addition to a now closed issue, but for completeness of the discussion I just want to point out that Java also has unchecked exceptions. Any Throwables that extend Error or RuntimeException do not need to be declared in a throws clause. The intention is to eliminate the need to have a throws clause for something that nearly every method could throw (like OutOfMemoryException).

Just playing devil's advocate, Hack could likewise offer both checked and unchecked classes of exceptions.
