### ISSUE TITLE
zlib.deflate stream filter returns empty results

### ISSUE THREAD

**Issue by donatj** [facebook/hhvm#4492]
I receive empty reads from a file stream after having attached `zlib.deflate` and reading from the stream.  This same code works fine in PHP.

You can see the code in action here: http://3v4l.org/rr4Nj

``` php
<?php

error_reporting(E_ALL);

$original_text = str_repeat("This is a test.\nThis is only a test.\nThis is not an important string.\n", 100);
$fn = tempnam(sys_get_temp_dir(), "bbq");
$fh = fopen($fn, 'w+');
fwrite($fh, $original_text);
rewind($fh);

$filter = stream_filter_append($fh, 'zlib.deflate', STREAM_FILTER_READ, 6);
while (!feof($fh)) {
    $data = fread($fh, 100);
    echo "\n:" . strlen($data);
}
```

**Comment by dolfelt** [comment]
:+1:

Any progress on this @paulbiss

**Comment by paulbiss** [comment]
I don't think anyone is currently working on zlib streams.

**Comment by maennchen** [comment]
Can we expect this to be solved anytime soon? @paulbiss

**Comment by donatj** [comment]
Still broken in current releases.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm 4.56 does not support `\STREAM_FILTER_READ`, nor `\stream_filter_append()`.
I was told on May the 16th of 2019: _filters are gone, wrappers that can re-enter the VM are gone_.
I believe that this issue does not apply to modern hhvm versions.

If this issue is still applicable, then #4255 also ought to be reopened too.
