### ISSUE TITLE
MySQLi abstract layer dont works with hhvm, PHP without hhvm its works

### ISSUE THREAD

**Issue by LeoHijin** [facebook/hhvm#4505]
This mysqli abstract layer  work very well with php-fpm and nignx. But when Im trying to implement it with HHVM + nginx there isn't way to got working correctly.

I think the problem is around the Reflection class to pass the arguments to be bind (bind params, bind results) as arrays.

<?php
        abstract class DBModel {
            protected static $conn;
            protected static $sql;
            protected static $stmt;
            protected static $reflection;	 
            protected static $data;
            public static $results;
       
        protected static function open() {
            self::$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
            if (self::$conn->connect_errno) {
                print("Página no disponible. Intente de nuevo más tarde.");
                exit();
            }
        }

        protected static function prepare() {
            self::$stmt = self::$conn->prepare(self::$sql);
            self::$reflection = new ReflectionClass('mysqli_stmt');
       }
    
       protected static function setParams() {
           $method = self::$reflection->getMethod('bind_param');
           $method->invokeArgs(self::$stmt, self::$data);
       }
    
       protected static function getData($fields) {
           self::$results = array();
           $method = self::$reflection->getMethod('bind_result');
           $method->invokeArgs(self::$stmt, $fields);
           while(self::$stmt->fetch()) {
               self::$results[] = unserialize(serialize($fields));
           }
       }

       protected static function close() {
           self::$stmt->close();
           self::$conn->close();
       }

       public static function execute($sql, $data, $fields=False) {
           self::$sql = strtolower($sql);
           self::$data = $data;
           self::open();
           self::$conn->set_charset("utf8");
           self::prepare();
           self::setParams();
           self::$stmt->execute();
           if($fields) {           
               self::getData($fields);
               return self::$results;
           } 
           else {
               if(strpos(self::$sql, strtolower('INSERT')) === 0) {
                   return self::$conn->insert_id;
           }
       }
       self::close();       
    }
}
?>

example :

$sql = "SELECT user_id, name FROM user WHERE user_id > ?";
    $data = array("i",0);
    $fields = array('ID'=>'', 'NAME=>'');
    $fields = DBModel::execute($sql, $data, $fields);
    var_dump($fields);

The error log display:
\nWarning: Argument 1 not passed as reference
\nNotice: Array to string conversion in /var/www/core/DBModel.php on line 49
\nNotice: Array to string conversion in /var/www/core/DBModel.php on line 49
Core dumped: Aborted
Stack trace in /tmp/stacktrace.11929.log

And then HHVM crashes!

I'm not the author of this layer. more infor about http://pastebin.com/SHwDkQzL

**Comment by wjywbs** [comment]
Part 1

The function definitions of bind-param() and bind-result() in http://php.net/manual/en/mysqli-stmt.bind-param.php and http://php.net/manual/en/mysqli-stmt.bind-result.php expect variable references (mixed &$var1). You are passing number 0, which is not a reference. So you can try:
```
$num = 0;
$data = array("i", &$num);

$id = '';
$name = '';
$fields = array(&$id, &$name);
$fields = DBModel::execute($sql, $data, $fields);
```
Both hhvm 3.3 and 3.4 work.

Part 2

If I only correct $data but not $fields, for example `$fields = array($id, $name)`, I get "\nWarning: Argument 1 not passed as reference in \xe8\x95E-m\x7f on line 0". I get different file names and corrupted results from var_dump() in different runs. After this, all other php files will have corruption and return various errors. When using `$fields = array($id, &$name)`, hhvm crashes in serialize().

However, hhvm shouldn't crash. Adding some checks about if the variable has the correct type in bytecode.cpp to stop executing the function from reflection or in ext_mysqli.cpp (line 129) can prevent from toInt64Helper() crashing and corruption.

Part 3

If I change the lines `$method = self::$reflection->getMethod('bind_param'); $method->invokeArgs(self::$stmt, self::$data);` to `$num = 0; self::$stmt->bind_param("i", $num);` to remove the reflection and use the normal way to call bind_param(), hhvm 3.4 will not show any results. hhvm 3.3 is fine. I did a bisecting and found that https://github.com/facebook/hhvm/commit/b104d5e960c76ea998b2bd82b067a734a4cc8f64 caused the problem. I didn't see any leak with extraArgs without this commit.

My understanding is that bind_param_helper() in ext_mysqli.cpp stores all the arguments in a vector and calls arReturn() at the end. The reference variables are freed in arReturn() due to this commit, so update_result() in mysql_common.cpp can't set the result later (`*m_arr[i]->getRefData() = v;`).

Part 4: Memory leak

Since that commit was about fixing memory leak, I reverted that commit and did a stress test. I found that the memory leaked so fast that somewhere else must be leaking. jemalloc profiling dumps showed MySQLStmt::bind_result() leaked. It turned out that ~MySQLStmt() and ~MySQLStmtVariables() were never called. The buffer will also leak if the result has strings.

Every time hhvm runs your scripts above, it will be gradually leaking memory (about 1gb/5000 requests in my testing).

I have an internal fix for part 4 and a testing fix for part 2. The corporate CLA was signed yesterday, but I'm not sure how long it will take effect.

**Comment by paulbiss** [comment]
@wjywbs: nice debugging, thanks!

https://reviews.facebook.net/D31095
