### ISSUE TITLE
HHVM crashes on drupals xmlsitemap module

### ISSUE THREAD

**Issue by keepxtreme** [facebook/hhvm#4511]
HHVM crashes on drupals xmlsitemap module without any hint. Increasing the error level to "verbose" didn't show anything in the logs (seems like it crashes before anything is written to the logs).

This crash occurs both: if the regeneration of the libks is triggert by cron or manual. HHVM just will crash and exit (systemctl status hhvm --> not running)

Compare bug report for the drupal module: https://www.drupal.org/node/2385289

**Comment by julitroalves** [comment]
Hi, in my tests I can see that error that crashes hhvm occurs when <strong>XMLWriter::endDocument() in xmlsitemap.xmlsitemap.inc file</strong> is called.

To perform this tests I put watchdog's function in function that generates xml files and see what was executed line by line. The lines that is not executed was because crashes hhvm and I finally find to XMLWriter::endDocument().

I using Ubuntu 14.04 64 bits and HHVM 3.7.0

**Comment by fredemmott** [comment]
3.7.0 isn't supported any more; are any of you able to reproduce the problem on a more recent supported version, 3.9?

**Comment by d0dge** [comment]
Can confirm this is still happening on HHVM 3.12.0-dev.

**Comment by Orvid** [comment]
D3635715 is up internally to fix this, it was caused by a missing `VMRegAnchor`, in combination with the writer being opened against a URI who's stream type is implemented in the PHP side of HHVM's systemlib.
