### ISSUE TITLE
HHVM and hh_server disagree about argument variance

### ISSUE THREAD

**Issue by steelbrain** [facebook/hhvm#4566]
Hack Type checker reports error if we set the argument type of unserialize to mix. It says it should be a string, however HHVM works the other way.
POC: http://3v4l.org/AZIc7 http://3v4l.org/JiG9F

**Comment by jwatzman** [comment]
Yeah this is a rather unfortunate longstanding inconsistency between how HHVM and hh_client see the type system. As far as hh_client is concerned, functions can be overridden and change parameter/return types via the usual rules of co/contravariance. In HHVM, it follows PHP's rules for argument types -- if the type is in an interface method or abstract method, then it must be textually the same in any implementations. (Otherwise you can do whatever.)

We need to resolve this, by relaxing HHVM's enforcement of this PHP rule in Hack code, but it turns out to be tricky. The recent PHP RFC for return types originally specified covariance but went back on that after they ran into similar implementation difficulties :)

So we'll fix eventually, but for now, you'll have to drop the type, or change it to something such as `mixed` that HHVM itself doesn't enforce. Sorry :(

**Comment by jwatzman** [comment]
(And I thought there was already an issue on github about this, but I can't find it, so keeping this one open.)

**Comment by thijsw** [comment]
Slightly better than using `mixed` for the time being, is using a nullable string, IMHO. Just like `mixed`, it won't give a fatal error in hhvm (but an error in type checker nonetheless).

**Comment by steelbrain** [comment]
@jwatzman As a workaround, shouldn't we update the HHI file and make it the argument to the serialize method a nullable string.
It would allow us to use the serialize class in strict mode.

**Comment by jwatzman** [comment]
Hm, using `?string` still kinda seems like a hack, I thought HHVM still was able to enforce that? Removing the annotation in the hhi seems like the safest thing for now, if someone wants to send a PR.

**Comment by int3** [comment]
Why can't we have runtime require `string` instead of `mixed` -- is it for PHP compatibility?

**Comment by jwatzman** [comment]
Yes, almost certainly. Any type annotations in systemlib are enforced, even for PHP code. There's various levels of compat stuff that AIUI means they don't quite do what you always expect, but we can't be very cavalier about changing type annotations in systemlib.

**Comment by jwatzman** [comment]
The one instance was fixed, but this is still a general problem.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The runtime and typechecker don't require invariant typehints anymore.
```HACK
interface IFace {
  public function doIt(string $_);
}

class MyClass implements IFace {
  public function doIt(mixed $_): int { return 0; }
}
```

This is allowed under Hack's rules, since you can use a wider parameter type `string -> mixed` and a narrower return type `mixed -> string`.

I cannot find the blog post that announces this "nicer" behavior, but it has at least been like this since 3.30.
