### ISSUE TITLE
stack overflow when using a self-referencing constant

### ISSUE THREAD

**Issue by jakoch** [facebook/hhvm#4569]
Using a self-referencing constant leads to a stack overflow.
Please take a look at http://3v4l.org/fRkS2

Expected result: "Fatal error: Cannot declare self-referencing constant" (PHP 5.6+).

---

Using "static::" to access a const in a class
leads to "Fatal error: syntax error, unexpected T_STATIC in" on hhvm-3.2.0 - 3.4.0 
and No Message on hhvm-3.4.1.
Please see http://3v4l.org/vVMLA

Expected result: "Fatal error: "static::" access is not allowed to compile-time constants.".

**Comment by Zenexer** [comment]
Changing `self::` to `parent::` works fine in your example.  The error just isn't very descriptive, as the problematic state isn't detected.  HHVM isn't all that great for debugging errors like that at the moment.

**Comment by jesseschalken** [comment]
The first one (https://3v4l.org/fRkS2) produces the same result on HHVM as of 3.19.0.

Regarding the second (http://3v4l.org/vVMLA), I'm not sure the distinction between the errors HHVM and Zend produces is meaningful. They're both effectively fatal.

**Comment by Zenexer** [comment]
I would consider it a very low priority issue, but the Zend error message is definitely more descriptive.  Experienced developers are plenty familiar with those `syntax error, unexpected T_SOMETHING` errors, though.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue seems to have been fixed at some time ago.

The error message for [the first case](https://3v4l.org/fRkS2) is textually very similar. It refers to `b::k` instead of `self::k`, which is actually quite helpful.

The [second case](http://3v4l.org/vVMLA) produces this error: _Cannot use static or parent::class in constant declaration_.
Php informs you of the error like this _static::" is not allowed in compile-time constants_.
This case is also caught by the typechecker.
