### ISSUE TITLE
Call-time pass-by-reference is deprecated

### ISSUE THREAD

**Issue by SiebelsTim** [facebook/hhvm#4609]
http://3v4l.org/sIt8L
```
<?php

function f($a) {}

$b = 1;
f(&$b);
```

php:

    Fatal error: Call-time pass-by-reference has been removed; If you would like to pass argument by reference, modify the declaration of f().

php7 (sept. 2014) issues a parse error

    Parse error: syntax error, unexpected '&'

**Comment by Zenexer** [comment]
I think what's being pointed out here is that according to the mentioned link, HHVM 3.4.1 does **not** issue an error for call-time pass-by-reference syntax.  However, according to [this test](http://3v4l.org/v5SMS), call-time pass-by-references are, in fact, not supported.

It's worth noting that PHP5 itself is a bit inconsistent here, as we can see with [this test](http://3v4l.org/0kBBK), which uses `call_user_func_array` instead of a direct invocation.  HHVM appears to treat the two methods of invocation identically, which is what I would expect from PHP5.  Given this inconsistency, it may be ideal that the current behavior remain.
