### ISSUE TITLE
update hhvm-third-party on 3.5 branch

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#4629]
update to https://github.com/facebook/hhvm/commit/d4bf5b02a6958d9e1ef9e16c47d1c0e88cd0c04a
filed on request of @jwatzman

**Comment by jwatzman** [comment]
Can you link me again the relevant rev(s) that bump this hash that I should cherry pick? I'd be much more comfortable setting this to something that existed at one point, instead of some rev that might never have actually seen builds done against it.

**Comment by jrobeson** [comment]
isn't that what i did?

**Comment by jwatzman** [comment]
Blech yes, I totally misparsed your original message.

**Comment by jwatzman** [comment]
OK, revs to pick are

- 343c4f5837559c0476928f167f8e337f828439a6
- 5827a07d0f9f63f5dd2bab9de50d4b5e34307fa9
- d4bf5b02a6958d9e1ef9e16c47d1c0e88cd0c04a

Gonna hold off on picking quite yet since the internal branch corresponding to 3.5 hasn't finished stabilizing yet, and I'm afraid picking the extra revs will confuse the sync script.

**Comment by jrobeson** [comment]
in this won't won't picking the last one also pick the other two?

**Comment by jwatzman** [comment]
Just picking the third is a conflict, which is obvious to resolve, but it's easier to just pull all 3 without conflicts :)

**Comment by jrobeson** [comment]
hah, sure.  just let me know as soon as you do. i'm ready to get started on 3.5 builds :)

**Comment by jwatzman** [comment]
ETA isn't until the end of the week, but yeah will close this task when I've done the picks.

**Comment by jwatzman** [comment]
Merged.
