### ISSUE TITLE
HHVM fails silently if required file does not have read permissions

### ISSUE THREAD

**Issue by kristapsk** [facebook/hhvm#4656]
``` PHP
<?php
file_put_contents('testi.php', "<?php\necho 'blah';\n");
chmod('testi.php', 0000);
require_once 'testi.php';
```

PHP output:

```
PHP Warning:  require_once(/home/neonz/testi.php): failed to open stream: Permission denied in /home/neonz/testr.php on line 4

Warning: require_once(/home/neonz/testi.php): failed to open stream: Permission denied in /home/neonz/testr.php on line 4
PHP Fatal error:  require_once(): Failed opening required 'testi.php' (include_path='.:/usr/share/php5:/usr/share/php') in /home/neonz/testr.php on line 4

Fatal error: require_once(): Failed opening required 'testi.php' (include_path='.:/usr/share/php5:/usr/share/php') in /home/neonz/testr.php on line 4
```

HHVM does not output anything.

**Comment by Majkl578** [comment]
It outputs *something*: http://3v4l.org/nebVh

**Comment by paulbiss** [comment]
@Majkl578 that's because the directory isn't writable (notice the preceding warning for line 3). If the files does exist and is inaccessible then we appear to silently fail on master.

**Comment by jesseschalken** [comment]
On HHVM 3.19.1 the test script produces

```

Fatal error: require_once(testi.php): File not found in /home/ubuntu/test.php on line 6
```

while PHP 7.0.15 produces

```
PHP Warning:  require_once(/home/ubuntu/testi.php): failed to open stream: Permission denied in /home/ubuntu/test.php on line 6
PHP Stack trace:
PHP   1. {main}() /home/ubuntu/test.php:0
PHP Fatal error:  require_once(): Failed opening required 'testi.php' (include_path='.:/usr/share/php') in /home/ubuntu/test.php on line 6
PHP Stack trace:
PHP   1. {main}() /home/ubuntu/test.php:0
```

I'm not sure why PHP issues both a warning and a fatal, but HHVM is at least not silent.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm does indeed produce a standard `require_once` failure with `File not found`.
I agree that php's `Permission denied` is a helpful piece of information when debugging.
I am hesitant to decide whether to close this issue, since we don't _have_ to match php here, since they both end up producing a fatal error.

If anyone reading this believes that I should not have closed this issue, `@lexidor` me or create a new issue about the missing `Permission denied` warning.
