### ISSUE TITLE
HH\autoload_set_paths interacts poorly with namespaces

### ISSUE THREAD

**Issue by v-borg** [facebook/hhvm#4693]
I'm in trouble with some functions such as get_class(), get_called_class() and call_user_func_array() when I use them together with hh\autoload_set_paths on hhvm 3.5.0. When they are used by classes that contains namespace, the failure function of autoload_set_paths is called and shows the name of the function preceded by class namespace like: "Foo\Bar\get_called_class".
If I add a backslack before the function's name, it runs correctly.

**Comment by jwatzman** [comment]
Can you elaborate on what exactly the expected behavior was, and what actually happened? I'm not totally sure I follow your description.

But we don't use namespaces much internally at FB, so it would not surprise me if there were some edge case here we were handling wrong.

**Comment by victor-borges** [comment]
Every time I use a function inside a class scope and it has a namespace, the standard behavior of class is broken and hh\autoload_set_paths failure's callback is called. The kind of error passed is `class` and the name of the "class" is the name of function preceded by namespace of class that wrapped it.

For Example:

`namespace Foo;

class Bar
{

}

**Comment by victor-borges** [comment]
Every time I use a function inside a class scope and it has a namespace, the standard behavior of class is broken and hh\autoload_set_paths failure's callback is called. The kind of error passed is `class` and the name of the of supposed not found "class" is the name of the function preceded by namespace of class that wrapped it.

For Example:

//Foo/Bar.php
namespace Foo;

class Bar
{
    public function baz() : string
    {
         return get_class($this);
    }
}

$map = [
   'class' => [
       'foo\bar' => 'Foo/Bar.php'
    ],
    failure => ($kind, $class) ==> { echo sprintf('kind error: %s and not found class: %s', $kind, $class); exit(); }
]
hh\autoload_set_paths($map, '/');


It will broke the expected behavior and print the message "kind error: class and not found class: Foo\get_class($this)";

**Comment by victor-borges** [comment]
Every time I use a function inside a class scope and it has a namespace, the standard behavior of class is broken and hh\autoload_set_paths failure's callback is called. The kind of error passed is `class` and the name of the of supposed not found "class" is the name of the function preceded by namespace of class that wrapped it.

For Example:

*/Foo/Bar.php*
```
<?hh // strict

namespace Foo;

class Bar
{
    public function baz() : string
    {
         return get_class($this);
    }
}
```
*/index.php*
```
<?hh

$map = [
   'class' => [
       'foo\bar' => 'Foo/Bar.php'
    ],
    failure => ($kind, $class) ==> {
            echo sprintf('kind error: %s and not found class: %s', $kind, $class);
            exit(); 
   }
]
hh\autoload_set_paths($map, '/');


$bar = new Foo\Bar();
echo $bar->baz();
```

It will broke the expected behavior and print the message "kind error: class and not found class: Foo\get_class($this)";

**Comment by jwatzman** [comment]
Interesting, thanks for the repro case! Someone will take a look when they get some time. (Or, if you are interested, feel free to send a PR!)

**Comment by victor-borges** [comment]
Thank you very much!

**Comment by jwatzman** [comment]
Reopening since the issue sounds like a real one, we still want the issue open to track, even if we have no immediate plans to work on it.

**Comment by jwatzman** [comment]
@dabek ran into this internally this week

**Comment by jwatzman** [comment]
Current behavior: when using autoloading via `HH\autoload_set_paths`, the failure function will be called if the function cannot be found in the current namespace. *Then* we will try to find the function in the global namespace.

Exepected behavior: we should look for the function in the global namespace before calling the failure function, and only call the failure function if it exists in neither place (current or global namespace).

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue relies on global function(/constant) fallback, which was removed in hhvm version [3.26](https://hhvm.com/blog/2018/05/07/hhvm-3.26.html).
