### ISSUE TITLE
Drupal Commerce incompatibility

### ISSUE THREAD

**Issue by vying1** [facebook/hhvm#4706]
Steps to reproduce:

1) Install Drupal Commerce
2) Add something to the cart
3) View checkout

Message received is "Access denied" even though all permissions are set correctly.

Checked on two servers, HHVM 3.5 on Debian 7 x64, using lighttpd and nginx.  Fresh installs of Commerce Kickstart from https://www.drupal.org/project/commerce_kickstart

**Comment by jrobeson** [comment]
i think more logging information from the webapp would be required, so you can tell exactly where this access denied is coming from.

**Comment by vying1** [comment]
This is all I have.  I tried using the module Access Denied Backtrace, but that isn't working either.

TYPE	access denied
DATE	Sunday, January 25, 2015 - 05:28
USER	lpadmin
LOCATION	http://104.156.231.54/commerce/?q=checkout/5
REFERRER	http://104.156.231.54/commerce/
MESSAGE	checkout/5
SEVERITY	warning

**Comment by jwatzman** [comment]
Yeah, we're unfortunately going to need something more to go on than "this doesn't work". If you can trace it down to some function or even small block of code that behaves differently between PHP5 and HHVM, we'd be happy to take a look. But as-is, this could just as easily be a database misconfiguration as a bug in HHVM.

**Comment by vying1** [comment]
Well, it is not a database misconfiguration.  I've tried an entirely clean install of Commerce on both the MySQL and SQLite backends.  Having tried different servers and different databases, the only commonality is HHVM.

I'm not skilled enough at either Drupal development or PHP to narrow down a specific part of code myself, any suggestions on how to proceed?

**Comment by jwatzman** [comment]
> Well, it is not a database misconfiguration. I've tried an entirely clean install of Commerce on both the MySQL and SQLite backends. Having tried different servers and different databases, the only commonality is HHVM.

Have you tried a configuration otherwise identical to your HHVM setup, but using php-fpm or similar? The information here still hasn't ruled out some misconfiguration or other issue that would affect both runtimes.

> I'm not skilled enough at either Drupal development or PHP to narrow down a specific part of code myself, any suggestions on how to proceed?

I don't have any great ones, sorry. If the commerce plugin has a set of unit tests, running the tests with HHVM and again with PHP5 and noting any differences might be a good place to start.

**Comment by vying1** [comment]
Yes I have tried php-fpm and it works fine.  Guess I'm stuck for now.

**Comment by jwatzman** [comment]
The plugins' unit tests, if any, might be a quick way to narrow things down ("unit test XYZ passes on PHP5 but not HHVM" is very likely to be actionable). Other than that, unless anyone else wants to jump in with easy suggestions, I don't know what to tell you if you're not familiar enough with the app to dig in yourself and figure out what's different, I'm certainly not familiar enough with Drupal or this plugin myself :(

**Comment by wannesderoy** [comment]
I'm having the same issue. A Drupal commerce site running on Ubuntu 14.04, nginx/1.4.6 and hhvm 3.5

In the hhvm logs there is this error: \nFatal error: Failed to initialize storage module: user (path: /var/lib/php5) in /var/www/html/commerce-demo/includes/session.inc on line 287

This is the function containing line 287:

```php
/**
 * Starts a session forcefully, preserving already set session data.
 *
 * @ingroup php_wrappers
 */
function drupal_session_start() {
  // Command line clients do not support cookies nor sessions.
  if (!drupal_session_started() && !drupal_is_cli()) {
    // Save current session data before starting it, as PHP will destroy it.
    $session_data = isset($_SESSION) ? $_SESSION : NULL;

    session_start(); // this is line 287
    drupal_session_started(TRUE);

    // Restore session data.
    if (!empty($session_data)) {
      $_SESSION += $session_data;
    }
  }
}
```

In the Drupal commerce_checkout.module (a php file) there is a function which checks if the user can access the Checkout page based on session data. I assume that down the (drupal) line this comes down to the drupal_session_start() function.

Could it be that hiphop fails to create a session in this particular situation?

Just like vying1 the checkout page works without any problem using php-fpm.

On the drupal.org site there is no issue related to this problem. Not in Drupal Core or in the Commerce module.

I hope this info can help you along. If you have any other questions, or you need more info, please do ask!

**Comment by wannesderoy** [comment]
I found a solution!

On Ubuntu or Debian machines, if `session.save_path` is not set, then session files are saved in `/var/lib/php5` by default. But this location does not exist or is not known to hhvm or nginx within our setup.

In my Drupal settings.php file I added to the bottom
```php
ini_set("session.save_path", "");
```
This resets the path to `""` (an empty string), by default this evaluates to the temp folder of the system. 
This helped me: http://stackoverflow.com/questions/4927850/location-for-session-files-in-apache-php

To find the current session save path, you can use ```session_save_path() ``` (Get and/or set the current session save path).

Why drupal failed to create only the sessions related to the checkout page is not clear to me, but now it works ;)

**Comment by wannesderoy** [comment]
I found out that there is a difference between how Zend and HHVM interprete the php key() function.

In the Drupal commerce_checkout module there is a function that returns the first key of an array by using the php key() function (commerce_checkout.module, line 480). 
```php
/**
 * Returns the page ID of the first checkout page sorted by weight.
 */
function commerce_checkout_first_checkout_page() {
  return key(commerce_checkout_pages());
}
```
On the default Zend rendering engine this returned the desired result of the first array key. But in HHVM this returned nothing. I believe this is because the pointers of the array were not flushed by HHVM (maybe for performance reasons), and they were flushed in the Zend engine.

I don't think it was a good idea of the creaters of this module to use the key() function to get the first key of the array anyway

I now rewrote this function to this:
```php
/**
 * Returns the page ID of the first checkout page sorted by weight.
 */
function commerce_checkout_first_checkout_page() {
 return reset(array_keys(commerce_checkout_pages()));
}
```
Getting the keys of the array first and then with reset() rewind the array's internal pointer to the first element and return the value of that first array element.
Of course the key() function did the job on the standard Zend engine, but for HHVM this didn't.

I will report this issue to the maintenance crew of the drupal commerce module, and hopefully it will be commited into the next release. I don't think there is anything wrong with the way HHVM interprets the key function (if I am right in thinking this is the root of the problem). I think the key() function just shouldn't be used like this in this situation.

**Comment by paulbiss** [comment]
@wannesderoy: Thanks for the thorough investigation! We do indeed handle array cursors differently (it's in our (inconsistencies)[https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L15] document). Please keep us posted on the bug report with drupal commerce so we can close this issue.

@vying1: Can you confirm that this fixes your issue?

**Comment by vying1** [comment]
Confirmed.  Thanks!

**Comment by wannesderoy** [comment]
@paulbiss On the drupal.org commerce issue I get asked why HHVM does not follow the normal (Zend) operation of the key() function. In the [inconsistencies](https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L15) document you explain what differs, but not why. Is it because other languages behave more in the same way when copies of arrays are made? (php is [not famous for being consistent](http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/)

**Comment by paulbiss** [comment]
@wannesderoy IIRC this particular inconsistency was an optimization to make array duplication faster. Unlike PHP 5, we don't box all of our types, so updating the cursor for every copy of the array was a potentially expensive operation, since the cursor is stored with the rest of the array-metadata that we generally only copy-on-write (and so updating the cursor would be a write, necessitating duplication of the entire array). It also saves us an extra check every time an array is copied, which can happen quite frequently.

**Comment by paulbiss** [comment]
Looks like this was fixed: https://www.drupal.org/node/2430337
