### ISSUE TITLE
hhvm loses the systemlib during debuginfo package generation on Fedora/RHEL 7 systems

### ISSUE THREAD

**Issue by jrobeson** [facebook/hhvm#4724]
When i enable debuginfo package generation on Fedora 20 - 21, CentOS 7, and RHEL 7 systems, then i end up with this error:

Failed to find/load systemlib.php

This seems to occur due to the code on line 134 of /usr/lib/rpm/find-debuginfo.sh
```bash
eu-strip --remove-comment $r $g -f "$1" "$2" || exit
```

Here is the paste of the complete file for reference:
http://pastie.org/9866707

This seems to be the result of eu-strip removing the systemlib and ext.* sections of the elf file that get added in https://github.com/facebook/hhvm/blob/cb02e599fab0e24c0f8e90b2cfd64c6e72fb7c6f/CMake/HPHPFunctions.cmake#L100

This probably also breaks here: https://github.com/facebook/hhvm/blob/57ed40f3881458313b6e1f0bdacfb6c794039e3a/hphp/hack/src/Makefile#L125 but i have not verified that.

**Comment by jwatzman** [comment]
`eu-strip` needs to not do that. It's removing a section of the binary that it doesn't understand what it does -- but just because `eu-strip` doesn't grok something doesn't mean it isn't important!

A solution proposed to this is to mark these sections as ALLOC, but that's also wrong. That would map them into memory when the image is loaded, but that's not how we use them. We directly `open` our image and read them back out with libelf. Sure, it would probably be cleaner if we did this, but we don't, and our approach is perfectly valid.

So yeah, either `eu-strip` needs to be fixed to not remove random parts of binaries, or you need to figure out how to not make the RPM packaging scripts call `eu-strip` in this way.

**Comment by jrobeson** [comment]
Here's the link the to filed ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1186563

**Comment by jrobeson** [comment]
We've come up with a part of a fix for this, but the binary is about 69MB. a bit bigger than we'd like it to be.

**Comment by glensc** [comment]
mine is 32M:

```
-rwxr-xr-x 1 root root 32M 2014-11-19 21:23:31.000000000 +0200 /usr/bin/hhvm*
```
why don't you disable fedora's strip and use objcopy trick that pld does?

**Comment by jrobeson** [comment]
I'd like to keep everything else that find-debuginfo.sh does (dwarf compression, minidebug), so I'd have to figure out how to make it work in that case too.

**Comment by jrobeson** [comment]
which package has the PLD version of find-debuginfo.sh ? i thought it was rpm-build, but it's not that.

**Comment by glensc** [comment]
```
$ rpm -qf /usr/lib/rpm/find-debuginfo.sh 
rpm-utils-5.4.15-13.x32
```

**Comment by Orvid** [comment]
As this is external, I'm going to close this.
