### ISSUE TITLE
Lowercase names required in autoload_set_paths; failure emits raw name

### ISSUE THREAD

**Issue by caipre** [facebook/hhvm#4742]
The `autoload_set_paths` function compares class keys to the lowercased class name. This should be documented. If possible, the second argument to the failure callable should reflect the actual key that was tried.

``` php
<?php  # ~/test.php
\HH\autoload_set_paths([
    'class'   => [ 'Foo' => 'foo.php' ], # "Foo" will never match; must use "foo"
    'failure' => function ($kind, $name) { print "failure! $kind $name"; }
], '/home/caipre/');

\Foo::bar();
```

``` php
<?php # ~/foo.php
class Foo {
    public static function bar () {
        echo "bar!";
    }
}
```

``` shell
$ hhvm ~/test.php
failure! class Foo  # <-- would be more helpful / accurate as "foo"
Fatal error: Class undefined: Foo in /test.php on line 8
```

**Comment by SiebelsTim** [comment]
@paulbiss I would consider this a bug. And it's probably easy :)

**Comment by paulbiss** [comment]
We don't really have a "bug" tag, but I suppose we could call this a hack issue.

**Comment by caipre** [comment]
@paulbiss : I can take this, depending on the direction you want to go with it. Adding a phrase to the function comment is trivial; what were your thoughts regarding my second suggestion?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue is still very accurate in hhvm 4.56. However, it is no longer required to interact with `\HH\set_autoload_paths()` manually. [hhvm/hhvm-autoload](https://github.com/hhvm/hhvm-autoload) takes care of generating the autoload map. Hhvm has passed a non-normalized name to the callback for so long, that changing it now may lead to issues in third party failure handlers.

People who follow psr-4, for example, rely on the capitalization of the class and namespace name. They expect the namespace path and classname to be a valid path to a file that contains the class definition. On linux systems (where filenames are case sensitive), you must know the capitalization of the name to require the file. The name can always be normalized in the failure handler by calling `Str\lowercase()`, but if hhvm did this in the autoloading machnism itself, the failure handler could not restore the original name.
