### ISSUE TITLE
Unexpected code coverage notice error.

### ISSUE THREAD

**Issue by jails** [facebook/hhvm#4752]
The code bellow generates an unexpected `Notice: Calling xdebug_start_code_coverage from a nested VM instance may cause unpredicable results` error in some circumstances only.

Indeed:
- If the namespace is commented out, no notice is generated.
- If the closure is runned using the `$callback()` syntax no notice is generated

```php
<?php
namespace coverage; // <- Works if this line is commented out

function nestedVMError()
{
    $callback = function() {
        xdebug_start_code_coverage(0);
    };
    //$callback(); // <- This kind of call works
    call_user_func_array($callback, []); // <- It generates a notice error.
}

nestedVMError();
```

This notice error is also generated using `fb_enable_code_coverage()` .
Does somebody know what is the meaning of [this check](https://github.com/facebook/hhvm/blob/4d9b5b19afc0581856c79298f0672d7b55df9339/hphp/runtime/ext/xdebug/ext_xdebug.cpp#L564) ?

Thanks !

PS: by the way, no notice error is generated with PHP.

**Comment by Dragonrun1** [comment]
Just wanted to say I'm getting this error with one of my github projects as well when ran on travis ci. I'm using phpspec instead of phpunit in case that matter through I don't think it should.

**Comment by cerbero90** [comment]
I have the same problem of @Dragonrun1

**Comment by paulbiss** [comment]
The reason for this notice is that enabling code-coverage requires that the program be executed within the interpreter. To do this we immediately fixup the PHP frames currently on the stack and reenter via the interpreter.

The problem is that if the VM is nested (which can happen when the VM is reentered through a builtin, e.g. call_user_func) we only pop the top nesting level off the VM. This means that some of the frames still on the stack may be executed in the JIT and as a result will lack coverage data.

The safest thing to do here is to as much as possible try to enable code coverage at or near the top of your stack. NB: if you end up disabling code coverage before you exit the VM nesting (in this case before the function call_user_func_array invoked) you should be fine.

**Comment by jails** [comment]
Thanks @paulbiss  for the head up.
