### ISSUE TITLE
short_open_tag always Off but ignored

### ISSUE THREAD

**Issue by garwat82** [facebook/hhvm#4758]
<?xml version="1.0" ?>
<?php var_dump(ini_get('short_open_tag')); ?>

reports bool(false) but a notice is printed so unit tests will fail:
Notice: Use of undefined constant xml - assumed 'xml' in test.php on line 1

**Comment by keradus** [comment]
It would be great to have it fixed.
Any news on that ?

**Comment by paulbiss** [comment]
Grep-ing doesn't turn much up, looks like we haven't bound that setting? cc @JoelMarcey

**Comment by keradus** [comment]
ping ping?

**Comment by paulbiss** [comment]
Don't think anyone has had a chance to look at this. If you'd like to send us a PR it doesn't look particularly complicated.

**Comment by keradus** [comment]
I do not know HHVM source at all and cannot work with it easily (no support to run on Windows).
But I am happy to hear that fix would be ease and I am counting that bug will be fixed soon ;)

**Comment by danslo** [comment]
I once started working on this:
https://reviews.facebook.net/D21945?vs=on&id=108033&whitespace=ignore-most#toc

But it requires some more effort...

**Comment by fredemmott** [comment]
We've got hhvm.enable_short_tags documented instead - does this work? If so we should just make the standard name for the option work.

**Comment by paulbiss** [comment]
Aliasing Eval.EnableShortTags should be pretty straightforward.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Short opening tags only apply to php code. Hack code must either be in a `.hack` file, which does not allow an opening tag, or in any other file start with and optional shebang followed by `<?hh`.
