### ISSUE TITLE
mb_ereg_replace_callback does not seem to be implemented

### ISSUE THREAD

**Issue by ShadowPhrogg32642342** [facebook/hhvm#4766]
**_Test document:**_
&lt;html>&lt;body>
  &lt;?php $in = "121221" ?>
  &lt;p>Input: &lt;?= $in ?>&lt;/p>
  &lt;p>Output: &lt;?= mb_ereg_replace_callback("/(\d{2})(\d{2})(\d{2})/",
    function ($hits)
    {
      return "20".$hits[1]."-".$hits[2]."-".$hits[3];
    }, $in); ?>
&lt;/p>&lt;/body>&lt;/html>

**_Fatal error:**_
Call to undefined function mb_ereg_replace_callback() in /www/test/public/testin_mb_ereg_r_cb.php on line 4

**Comment by ShadowPhrogg32642342** [comment]
now that docs is online I can see that it's not supported :C
anyway, it would be a nice thing to have for people who have to cope with accented letters (and especially for non-latin scripts)

**Comment by tamtamchik** [comment]
+1 please add this feature

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

PHP7.0 dropped support for `ext/ereg`. Hack strongly prefers the `HH\Lib\Regex` api's introduced in the hsl around hhvm 3.29.0's release window. Support for PHP code has been dropped with hhvm version 4.0.0. I don't think this issue is likely to be worked on for these reasons.
