### ISSUE TITLE
How to use php code in HTML with HHVM?

### ISSUE THREAD

**Issue by cottonBlue** [facebook/hhvm#4787]
I wrote php code in a HTML file, like this "<?php ?>".
I know hh code in HTML is not recommended, but I just want php code in some HTML files. 
Therefore, I modified hhvm.conf in /etc/nginx.
**location ~ \.(hh|php)$ {** 
to 
**location ~ \.(hh|php|html)$ {**
and I restarted nginx, opened the HTML file on Chrome browser, and the file was downloaded.
It didn't working.
what I should modify?

**Comment by fredemmott** [comment]
You can change this via PhpFile.Extensions in an hdf file: https://github.com/facebook/hhvm/wiki/runtime-options

cc @JoelMarcey  - is there an ini equivalent?

**Comment by JoelMarcey** [comment]
A quick glance at it, you could probably set `hhvm.php_file.extensions` in an ini file; however we haven't done the binding yet to be able to do things like `ini_get()`.

```
hhvm.php_file.extensions[phpt] = application/x-phpt
hhvm.php_file.extensions[hphp] = application/x-hhvm-php
```

**Comment by r3wt** [comment]
wow. ive seen it all now.

**Comment by JoelMarcey** [comment]
@r3wt What have you seen?

**Comment by Rainha** [comment]
you mean to set ```hhvm.php_file.extensions``` in the /etc/hhvm/php.ini ?
I tried but not working...Am I missing something?

**Comment by iansltx** [comment]
An alternate solution here is to use .php for your template extensions. Assuming you're using a front controller and are storing templates outside your webroot, this doesn't present any issues with rendering and I know for a fact that this works, because That's almost exactly how I'm doing templating in an app that I'm building.

The standard PHP-within-HTML syntax works fine, including short echo (<?= $var ?>) syntax.
