### ISSUE TITLE
Empty response body on fatal errors

### ISSUE THREAD

**Issue by Yogu** [facebook/hhvm#4818]
For reasonable error pages, we register a shutdown callback that will output a nice page when it detects that the script has not terminated gracefully. This works fine with the normal php engine, but in hhvm, it only works for non-fatal errors. For fatal errors, like calling an undefined function, the response body is not sent.

The following script:

```
<?php
echo "before\n";
register_shutdown_function(function() {
        header('Test: Header');
        echo "shutdown\n";
});
call_undefined();
```

sends the header, but suppresses the whole response body:

```
< HTTP/1.1 500 hphp_invoke
< Server: nginx/1.6.2
< Date: Tue, 10 Feb 2015 23:42:16 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: HHVM/3.5.0
< Test: Header
< 
```

I'm using the hhvm package on ubuntu 14.04 via fastcgi with nginx and the defaults for `server.ini` and `php.ini`.

See also [this stackoverflow question](https://stackoverflow.com/questions/23086903/hhvm-fastcgi-nginx-how-to-make-it-display-fatal-errors-in-the-browser) which has 12 upvotes but no satisfying answer.

**Comment by iansltx** [comment]
There are a couple config changes that you need to make, and then you can use set_error_handler() to catch things and print out a nice error page. If your code fatals before your handler is set then you've got issues there, but it works a lot of the time...

hhvm.error_handling.call_user_handler_on_fatals	= 1

The above should be in your php.ini.

There are a few other useful flags that you can set this way, see here:

https://github.com/facebook/hhvm/blob/4d9b5b19afc0581856c79298f0672d7b55df9339/hphp/runtime/base/runtime-option.cpp#L840

As a heads-up, whereas the Zend runtime won't call the error handler on fatals, HHVM will, with an error code of 16777217. So you'll handle full-on fatals a bit different than you would under Zend, but that way is actually more consistent.

Thing is, the config options have defaults that don't patch Zend, so that needs fixing. I'll create an issue for that now...like I should've a few weeks ago when I figured this stuff out.

If you've got any more questions about setting this up, I'm on #hhvm on Freenode, and I've run into (and largely solved) this exact issue in my code...would love to help.

**Comment by paulbiss** [comment]
@iansltx has the right idea. Not leaking errors to the browser is something we do intentionally, though you're more than welcome to setup an error handler that does this for you.

**Comment by iansltx** [comment]
Lack of implicit flush may be what I was running into with my error handling issues. Will do some more testing later to verify.

**Comment by Yogu** [comment]
@paulbiss @iansltx Thanks for the tip with `implicit_flush`, that did the trick.

@iansltx Thanks for `call_user_handler_on_fatals`. I need to use it because `error_get_last()` does not report the source of fatal errors if called in the shutdown function, we need to capture those details in the error handler for fatal errors.

In case anyone is interested, this is the gist of our error handling code:

```
class ExceptionHandling {
	private static $uncaught_exception = null;
	private static $fatal_error = null;

	public static function shutdown_callback() {
		if (defined('GRACEFUL_SHUTDOWN')) {
			// everything went fine
			ob_end_flush();
			return;
		}

		header('Status: 500 Internal Server Error');
		include(APP_PATH.'/errors/500.php');
	}

	// turn errors into exceptions
	public static function exception_error_handler($errno, $errstr, $errfile, $errline) {
		if (error_reporting() === 0) {
			return false; // codefatal used @ to suppress errors
		}

		$exception = new ErrorException($errstr, 0, $errno, $errfile, $errline);

		// hhvm can report fatals as errors. We can not convert them to exceptions, however, because they will
		// not trigger the exception handler and the stack trace is wrong, anyway. We need to save the errfile and
		// errline here because they are not available in the shutdown function.
		// for the errno, see https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/runtime-error.h#L57
		if ($errno & (1 << 24)) {
			self::$fatal_error = array(
					'message' => $errstr,
					'type' => $errno,
					'file' => $errfile,
					'line' => $errline
			);
		}

		throw $exception;
	}

	public static function exception_handler($exception) {
		var_dump('exHandler');
		self::$uncaught_exception = $exception;
	}

	/**
	 * @return Exception|null the exception that caused the app to crash, or null if there was none
	 */
	public static function get_uncaught_exception() {
		return self::$uncaught_exception;
	}

	/**
	 * Gets the last error that has occurred, be it fatal or non-fatal
	 * @return array with the fields message, type, file and line
	 */
	public static function get_last_error() {
		if (self::$fatal_error) {
			return self::$fatal_error;
		}
		return error_get_last();
	}
}
register_shutdown_function(array('ExceptionHandling', 'shutdown_callback'));
set_error_handler(array('ExceptionHandling', "exception_error_handler"));
set_exception_handler(array('ExceptionHandling', 'exception_handler'));
```

`500.php` then either uses `ExceptionHandling::get_uncaught_exception()` or `ExceptionHandling::get_last_error()`, whichever is present.

**Comment by dieend** [comment]
for people that still have problem with empty error response, you might interested in looking https://github.com/facebook/hhvm/issues/4055
