### ISSUE TITLE
Allow newtype in SystemLib

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#4831]
I'm about to make the typechecker aware of \HH\FormatString (instead of just \FormatString, which is being deprecated); ideally, we wouldn't require user code to define:

```PHP
namespace HH {
  newtype FormatString<T> = string;
}
```

... like we currently do for \FormatString.

Unfortunately, newtype is a pseudomain instruction, so we can't put this in systemlib.

cc @elgenie

**Comment by paulbiss** [comment]
We also need to fix allowing top-level consts in systemlib. I'd be okay with newtype itself being a declaration in systemlib but I don't particularly care for allowing systemlib functions to be annotated that way. It adds a lot of unnecessary complexity to the parameter coercion logic for systemlib, and it would have to be done carefully to not effect performance because of the way we look these up and cache them. I suppose doing the type-alias -> type substitution at emission time might work though.

**Comment by fredemmott** [comment]
For builtins, it should be typed as string, however the HHI should use this.

The type itself needs to be exposed so that it can be used in end-user code, without the typechecker complaining that it's declared twice.

**Comment by fredemmott** [comment]
https://gist.github.com/fredemmott/7d8958ab43fb5be47c52 is an example.

**Comment by Orvid** [comment]
Any notes on why this was closed? Was it implemented, or is it no longer needed?

**Comment by fredemmott** [comment]
Implemented in the referenced commit.
