### ISSUE TITLE
natcasesort sorts Å incorrectly

### ISSUE THREAD

**Issue by AshleyPinner** [facebook/hhvm#4884]
The [HHVM Docs for natcasesort](http://docs.hhvm.com/manual/en/function.natcasesort.php) do not list any functional differences over the native PHP function, so the expected behaviour is the same as PHP.

[Å's usual place in alphabetical ordering is after Z](http://en.wikipedia.org/wiki/%C3%85#Place_in_alphabet), but we can see in [this snippet of code](http://3v4l.org/1creB#vhhvm-331) that it's being sorted to above the A's.

**Comment by AshleyPinner** [comment]
Just popping a note here that this still affects the 3.7.0 release of HHVM.

**Comment by paulbiss** [comment]
Well, 3.7 is no longer supported, and 3.3, 3.8 are about to go out of support, but it looks as though no one has had a chance to do this yet.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not buggy or broken. As long as hhvm is consistent in the order (if A < B and B < C, then A < C), the function still does what it advertised. Equivalent code would yield a different (equally valid) result on PHP.
