### ISSUE TITLE
It would be interesting to add OwnCloud tests to the tests suite

### ISSUE THREAD

**Issue by castarco** [facebook/hhvm#4885]
It would be interesting to add OwnCloud tests to the tests suite

**Comment by paulbiss** [comment]
Does OwnCloud have PHPUnit tests?

**Comment by castarco** [comment]
I hope yes : https://github.com/owncloud/core/tree/master/tests

**Comment by bauerj** [comment]
Looks a bit complicated.

First you need to do a `git submodule update --init --recursive` after cloning and I don't know if the current test runner can do something like that and you also need to modify some of the config files.

**Comment by fredemmott** [comment]
Sorry, this isn't going to happen because of the submodules; we support using composer for dependencies.

While a framework override could be added to make this work in the simplest case by shelling out to git, we cache dependencies for our continuous runs (so that they're reproducible), and this system is not compatible with submodules.

**Comment by castarco** [comment]
Mmmm... ok. But, if I create a simple repository without submodules with all the needed code to run the tests? I can maintain it for a long time since it's not a difficult task.
