### ISSUE TITLE
Please add license header to FindLibDwarf.cmake

### ISSUE THREAD

**Issue by arsenm** [facebook/hhvm#4888]
Since random find cmake find modules like this typically get copied into other projects, it is customary to include a license header  in them. For example, FindLibElf.cmake already does

**Comment by lexidor** [comment]
third-party/folly/src/CMake/FindLibDwarf.cmake does have a license header, but CMake/FindLibDwarf.cmake does not.

**Comment by amanjha8100** [comment]
Can I work on this? 
If I am getting it right it is about adding a copyright header in the cmake files right?
@lexidor, @Orvid , @paulbiss

**Comment by lexidor** [comment]
You could definitely submit a PR for this. I do not work for Facebook, nor do I have merge rights on this repository. Stuff in third-party comes from other repositories. So you'd have to submit it in the right place.

**Comment by lexidor** [comment]
Is this file still present in the repository? I can't find it under the path I commented in May of 2020. If this file does not exist, feel free to ping me again and I'll close this issue.

**Comment by fredemmott** [comment]
HHVM still has a copy.

> add a copyright header

This can't be done directly without more information from @scottmac as the history does not make it clear where it came from.

If it was hand-written by @scottmac in 3b481737e968ead9eb56efef5d7861be1c729553, then this should be the usual Facebook MIT license header; if not, we probably copied it from somewhere else that did not have a license header. If that's the case (or we can't get confirmation on the source), we should probably replace it with Folly's version (and fix any incompatiblities), rather than just adding a header here.

**Comment by fredemmott** [comment]
If we don't get more information, copying folly's file whole is probably the right way to go.

**Comment by scottmac** [comment]
I think I wrote these but it was almost 10 years ago, I did leave some debug coding in the original commit which makes me think I didn't really know what I was doing :)

Did some quick splunking and I can find other files that look like this but they were added in 2015+

**Comment by amanjha8100** [comment]
So, @scottmac should I add the copyright header in your name? If yes please do provide details!

**Comment by fredemmott** [comment]
Thanks @scottmac, @amanjha8100 ; I'll add the current FB license header today - I don't think we're able to take a PR for it from a non-FB employee.

**Comment by amanjha8100** [comment]
No, problem happy to point it out.
