### ISSUE TITLE
mysqli_stmt: exceeding memory limit in bind_param with using Reflection

### ISSUE THREAD

**Issue by DmitrySoshnikov** [facebook/hhvm#4890]
Running this test currently fails with exceeding available for a request memory:

```
test/slow/ext_mysqli/test_mysqli_bind.php
```

Result:

```
Fatal error: request has exceeded memory limit in test/slow/ext_mysqli/test_mysqli_bind.php on line 32
```

**Comment by paulbiss** [comment]
Hmm, sounds like it may still be leaking, I'd recommend profiling it with jemalloc.

**Comment by Orvid** [comment]
Actually, I believe this is caused by the `LONGTEXT` column, as the bind tries to allocate the max possible size of the result. In this case, it's trying to allocate 4gb for the result. If you try this on a machine that doesn't have 4gb of memory, this will just cause a different error, due to there simply not being enough memory to be able to allocate it.

**Comment by Orvid** [comment]
O_o... Why did this just claim I unassigned someone?

**Comment by paulbiss** [comment]
It's a glitch in github. The issue is currently unassigned.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm dropped support for hhvm in version [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html).
