### ISSUE TITLE
Strict Standards and method overriding

### ISSUE THREAD

**Issue by robstoll** [facebook/hhvm#4896]
```
<?php
error_reporting(E_STRICT);
class A{
    function foo(){}
}
class B extends A{
    function foo($a){}
}
```

the above could should output:

```
Strict Standards: Declaration of B::foo() should be compatible with A::foo() in /in/eiAiR on line 9
```

**Comment by paulbiss** [comment]
Looks like we're just missing a check [here](https://github.com/facebook/hhvm/blob/c711da2cf1273c27bb3ce880b034ac10b22eceb9/hphp/runtime/vm/class.cpp#L1214).

**Comment by DmitrySoshnikov** [comment]
Seems PHP doesn't wan here as well.

We could potentially do this in HACK mode, however, could be there valid cases when a signature of an overridden method differs from the parent one?

**Comment by Majkl578** [comment]
PHP does, see http://3v4l.org/nUDU8

> could be there valid cases when a signature of an overridden method differs from the parent one?

Yes, subclass may expand parameters list with additional optional params.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

In Hack code, these methods are incompatible. The arity must be preserved. This code is invalid without a default value for the `$a` parameter.
