### ISSUE TITLE
Feature request: libevent, libev or libuv available in PHP code

### ISSUE THREAD

**Issue by nazar-pc** [facebook/hhvm#4909]
Using ReactPHP allows relatively easily create HTTP server in PHP, where HHVM performs quite well and get significant performance boost, but might do even more if ReactPHP will be able to use any of those instead of `stream_select`

**Comment by paulbiss** [comment]
We have a libevent server, but unfortunately it's deprecated and not built by default. At FB we use a builtin proxygen sever, which we plan to open source once the library support for it is available in our open source proxygen. In the meantime you can build the libevent server to use a builtin webserver.

**Comment by nazar-pc** [comment]
I think you understand me wrong, ReactPHP uses those libraries for more efficient event loop, for instance, libevent: https://github.com/reactphp/event-loop/blob/master/src/LibEventLoop.php

I do not need built-in server from HHVM instead (I remember times when I've used it and then it was dropped).

**Comment by paulbiss** [comment]
Ah, I see. Certainly seems like a reasonable feature to add, although I think async already has its own scheduler, and should be even faster for anything potentially I/O bound.

**Comment by nazar-pc** [comment]
What do you mean under "async already has its own scheduler"? I'm not ReactPHP developer, I'm just using it together with HHVM.

**Comment by paulbiss** [comment]
Well, async is a language feature in hack that allows you to do asynchronous I/O efficiently, and it uses an internal scheduler/event loop to handle pending I/O. I'm not sure how much it relates to what you're trying to do with ReactPHP, but I thought it might be worth mentioning.

http://docs.hhvm.com/manual/en/hack.async.php
http://hhvm.com/blog/7091/async-cooperative-multitasking-for-hack
http://hhvm.com/blog/8405/coming-soon-in-hhvm

**Comment by nazar-pc** [comment]
Yeah, I saw that, but async you've mentioned is Hack-specific, while I'm working on generic solution which should be compatible with both PHP and HHVM, it currently uses `stream_select` for event-loop, which is not fastest possible solution (though, pretty fast already comparing to regular use of HHVM in Fast-CGI mode).
Maybe, @cboden or @igorw can add something here?

**Comment by cboden** [comment]
I'm a little out of the loop (harrr) in my HHVM knowledge, so please correct me if any of my assumptions are wrong. 

Hack's async syntax and React's event loop accomplish the same thing: providing async I/O to the developer (non HTTP specific). How they expose this is how they differ. As @paulbiss stated Hack's scheduler is internalized where as React has adapters that tie to different extensions as stated in the title. These extensions expose new user land classes and functions to PHP that React uses to create a user land event loop. 

What I believe @nazar-pc is looking for are bindings/extensions for these in HHVM. [Ruslan Osmanov](https://bitbucket.org/osmanov) has done work on this. 

All these extensions provide access to epoll as opposed to the older stream_select which has better performance with concurrent connections. I believe (this is speculation) since most async features in Hack are client oriented they're not having to worry about the C10K problem. 

In the future Facebook could replace their internal scheduler with another I/O engine, such as LibUv, with us end-users being unaware and our `async` style code would not have to change. See #2047.

Something I'll look into as well is seeing if I can bridge the Hack async syntax into a React EventLoopInterface; allowing existing React applications to use Hack's scheduler with React's libraries. I'm currently waiting on streams to be async capable in Hack, which I believe is being worked on.

**Comment by paulbiss** [comment]
This feature request is not actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.
