### ISSUE TITLE
hhvm static linking

### ISSUE THREAD

**Issue by gopedib** [facebook/hhvm#4955]
Hi, I am trying to statically compile hhvm. I have added the following in CMake/HPHPCompiler.cmake:

  +  if(STATIC_LIB)
  +    set(CMAKE_EXE_LINKER_FLAGS "-static")
  +  endif()
    if(STATIC_CXX_LIB)
  -    set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
  +    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libgcc -static-libstdc++")
    endif()

I also added in CMake/Options.cmake
+  option(STATIC_LIB "Statically link libraries" OFF)
    option(STATIC_CXX_LIB "Statically link libstd++ and libgcc." OFF)
and compile hhvm with:
cmake -DSTATIC_LIB=ON -DSTATIC_CXX_LIB=ON .

However, the final hhvm binary turns out to be not statically linked for few libraries (for eg. libglog and 38 more). The CMakeCache.txt shows that it is picking the *.so version from the respective library repos (for eg, here for libglog's, although it has *.a version present there)

//Path to a file.
LIBGLOG_INCLUDE_DIR:PATH=../../include

//Path to a library.
LIBGLOG_LIBRARY:FILEPATH=../../lib/libglog.so

So how am I supposed to force the cmake to pick the *.a version of those libraries while building the CMakeCache.txt? Any idea?

**Comment by mancvso** [comment]
Any updates on this?
I'm trying to get a static version to include on Alpine Linux (for use in Docker containers)

**Comment by Orvid** [comment]
I've done this on my windows build by explicitly setting the `LIBGLOG_LIBRARY` value to the static library. In my case, due to using a generation target that supports multiple configurations, my cache value for `LIBGLOG_LIBRARY` looks like this:
```
LIBGLOG_LIBRARY:FILEPATH=optimized;F:/Libraries/libglog/lib/libglogMT.lib;debug;F:/Libraries/libglog/lib/libglogMTd.lib
```

It's worth noting that I don't do a normal CMake config process, as I do out of tree builds, and copy in a partially pre-populated cmake cache before doing the configure. This is primarily because passing in what is currently 76 different variables on the command line isn't exactly practical.
