### ISSUE TITLE
setrawcookie now erroring on base64encoded string

### ISSUE THREAD

**Issue by simoncast** [facebook/hhvm#4967]
After upgrading to PHP 5.5.22-1+deb.sury.org~trusty+1 and HHVM-3.5.1-0-gb723e67c88bc008676687a04dff00db1faf250b3 setrawcookie is now erroring with the following message
Cookie values can not contain any of the following '=,; \\t\\r\\n\\013\\014'
When a base64encoded string is used as the value of the cookie.
I've checked both HHVM and PHP documentation and it seems setrawcookie() should not have a problem with = in the string but now it seems to.

**Comment by fredemmott** [comment]
Can you give an example? This appears to work fine: http://3v4l.org/BIR9U

Also, I can't find that error message in HHVM.

**Comment by fredemmott** [comment]
php-src however, does raise similar errros in a slightly different circumstance: http://3v4l.org/2LPc6

Please provide isolated example code and output, that also outputs the value of the PHP_VERSION constant.

**Comment by simoncast** [comment]
I’ve not be able to produce code on my local that replicates the behaviour. I put in place something that strips out the == at the end of the cookies and that seems to have worked on production.


On 6 March 2015 at 19:57:05, Fred Emmott (notifications@github.com) wrote:

php-src however, does raise similar errros in a slightly different circumstance: http://3v4l.org/2LPc6

Please provide isolated example code and output, that also outputs the value of the PHP_VERSION constant.

**Comment by josephscott** [comment]
I've run into the `Fatal error: Cookie values can not contain any of the following '=,; \\t\\r\\n\\013\\014' in` as well, with `setrawcookie()`.  HHVM version info:

```
HipHop VM 3.7.2 (rel)
Compiler: tags/HHVM-3.7.2-0-gfc9f29b2799933d8215faaadfa83de722df64e26
Repo schema: 34f16546e395aed44ad434467b6f96c89b0d8a8b
```

Triggering the problem is very simple, create a PHP page with:

```php
<?php
setrawcookie( 'thing', 'foo=bar' );
```

You then need make a regular web request to that page.  The error condition doesn't happen when testing via the CLI ( no browser, no cookies ).  The HHVM error log entry looks like:

```
Fatal error: Cookie values can not contain any of the following '=,; \\t\\r\\n\\013\\014' in /var/www/index.php on line 2
```

@fredemmott I suspect this is a result of https://github.com/facebook/hhvm/commit/261737423f469d26a79500897568c81824f186e5.

Prior to that change the `=` was only considered an invalid character for the name field.

https://github.com/facebook/hhvm/blob/86ae9d014a3d329203bef6fe5ded9c6688cec620/hphp/runtime/server/transport.cpp#L546-L557

After that change the `=` is now considered invalid for name, value, and path fields.  `validateCookieString()` is called for all three of those fields and only has one black list, which includes the `=` character.

**Comment by fredemmott** [comment]
We're looking into fixing this, taking into account https://bugs.php.net/bug.php?id=69948

We're likely to match the new PHP7 behavior instead of PHP5, though that should be sufficient for this case.
