### ISSUE TITLE
Hack: Traversable without generics doesn't match array

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#4980]
Hack is saying that array is incompatible with `Traversable`, but is passing as expected when `Traversable` has type arguments.

Reproduction:

``` hack
<?hh

function a(Traversable $val): void {}
function b(Traversable<string> $val): void {}
function c(): void {
  a([]);
  b([]);
}
```

Output:

```
/root/projects/xhp-foundation/test.php:6:5,5: Invalid argument (Typing[4110])
  /root/projects/xhp-foundation/test.php:3:12,22: This is an object of type Traversable
  /root/projects/xhp-foundation/test.php:6:5,5: It is incompatible with an array
```

**Comment by paulbiss** [comment]
I would imagine this is intentional but @jwatzman would know better.

**Comment by jwatzman** [comment]
Yeah torn on this. We typically allow interfaces to be missing their type parameters in partial mode. This was done to ease conversion, since we added type params to some preexisting interfaces. But we allow it //everywhere// instead of just on those preexisting interfaces, which was probably a mistake.

But `Traversable<T>` is one of those interfaces -- but arrays matching it is a purely Hack thing, so I'm more reluctant to fix it.

Not super hi pri anyways IMO.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm used to have `\Traversable` and `\HH\Traversable<T>` until hhvm [4.32](https://hhvm.com/blog/2019/11/19/hhvm-4.32.html). `\Traversable` has been removed. The `\Traversable` type did not allow for arrays (just like PHP's `\Traversable`).
