### ISSUE TITLE
Shopping Cart Price Rules failed to apply in grand total,  magento 1.9.1

### ISSUE THREAD

**Issue by jjone** [facebook/hhvm#5001]
![hhvm3 6bug](https://cloud.githubusercontent.com/assets/8607130/6600671/58d89238-c7e7-11e4-89c1-ecec8905f222.png)

Shopping Cart Price Rules failed to apply in the grand total. 
something is wrong here. help please. Thank you very much.
server: HHVM 3.6, Magento 1.9.1 and nginx 1.6.2

**Comment by danslo** [comment]
You should set ``hhvm.enable_zend_sorting = 1`` in your ``/etc/hhvm/php.ini`` and then flush your Magento cache.

**Comment by jjone** [comment]
Hi Danslo

You are the best ! Thank you so much for your help.

Justin

**Comment by liquidia** [comment]
is there any permanent solution? or we have to keep modifying default php.ini

**Comment by SiebelsTim** [comment]
That is the permanent solution :P 

The root of that bug is that Magento depends on undefined sorting behaviour. Using the algorithm php uses by default would result in a performance penalty. 

Anyway, the php.ini is there to configure your runtime. I think most of the time you would want to adjust some setting, resulting in a modified php.ini. Modifying configuration files shouldn't hinder you in any way.

**Comment by akshatmalikcoc** [comment]
Would this solution apply for Magento 1.7.0.2?
