### ISSUE TITLE
HHVM 3.6 binary packages have incorrect mysql socket path

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5002]
- Need rebuilding with mysql-server installed
- Given we're now building a mysqlclient, we should probably error if cmake can't figure out where the socket is

See discussion in #4987

**Comment by r3wt** [comment]
damnit. damnit. damnit! GRRR

!(http://puu.sh/gxWmi/dbd6dd7cba.png)

**Comment by PDowney** [comment]
For those early upgraders that ended up killing their wordpress-based websites (like me), you can temporarily get around this issue by switching your server from using unix sockets. Just return hhvm.conf and server.ini to their defaults, and then edit wordpress' wpconfig.php file to use 127.0.0.1 instead of localhost.

**Comment by r3wt** [comment]
@PDowney what about someone running an ORM like Redbeans? do we have options

**Comment by PDowney** [comment]
I have no experience with Redbean whatsoever, but i imagine you'd just change it to point to 127.0.0.1 instead of localhost in the same way.

So if the text below is how it's set up, just replace localhost I guess, and then change hhvm.conf and server.ini back to defaults. 
R::setup('mysql:host=localhost;dbname=mydatabase',
        'user','password'); //mysql

**Comment by frijsdijk** [comment]
Even if I set hhvm.mysql.socket=/var/run/mysqld/mysqld.sock in /etc/hhvm/php.ini, which shows up in a hhvm-phpinfo, it still seems to look for /tmp/mysql.sock in stead.

Btw, this works as well as a quick work-around (but dirty):

ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

**Comment by fredemmott** [comment]
@frijsdijk : probably #5003

**Comment by fredemmott** [comment]
This will be fixed in 3.6.1 - #5003 won't be, but is less of an issue once this is.

**Comment by fredemmott** [comment]
Fixed in 3.6.1
