### ISSUE TITLE
message crypt() no salt parameters specified.you must use a randomly generated salt  and strong hash function  to a produce secure hash

### ISSUE THREAD

**Issue by samaiyan** [facebook/hhvm#5021]
message crypt() no salt parameters specified.you must use a randomly generated salt  and strong hash function  to a produce secure hash

**Comment by paulbiss** [comment]
I don't understand this issue. The notice means you did not specify a hash for crypt(), PHP 5 raises the same notice http://3v4l.org/8K3Ob, what do you want us to do?

**Comment by ash-rain** [comment]
I'm using Laravel 5.1 on the latest stable HHVM and I'm thrown an ErrorException instead of a notice. Is that by design? It's frustrating.

**Comment by paulbiss** [comment]
Is there a message attached to the exception? I just had a look at crypt and it doesn't look like it throws.

**Comment by ash-rain** [comment]
Yes, I think it's the default notice, but used as exception message. It reads:
```
ErrorException in line 0:
crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.
```

I see in the stack trace it's called like so:
`crypt('somePass', '')`

**Comment by paulbiss** [comment]
That's definitely only raised as a notice in the engine. Maybe you have an error handler that's promoting it to an exception?

**Comment by ash-rain** [comment]
That was my first guess but I "turned it off" and it still does the exact same thing. It's an exception thrown from `crypt()` AFICT.

**Comment by paulbiss** [comment]
I can't see how that's possible looking at the source of crypt, but if you have an isolated repro that isn't tried to a framework I'd be happy to dig into it.

**Comment by ash-rain** [comment]
I don't and I can't find the time to recreate it standalone, but I'm on this for 24 hours and I'll post any updates. I think it should be HHVM-related, but considering what you said the problem must be elsewhere.

**Comment by paulbiss** [comment]
Yeah, the only place we have that error string is [here](https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/runtime/base/string-util.cpp#L447-L450) and that definitely wouldn't trigger an exception. Looking at the crypt function [here](https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/runtime/ext/string/ext_string.cpp#L1698), [here](https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/zend/zend-string.cpp#L173), and [here](https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/zend/crypt-blowfish.c#L819) it doesn't look like it throws exceptions of any kind.

**Comment by deeppatel** [comment]
Any updates to this error?
I am also facing this error since few days!
Below is the error message and stack trace

"EXP_MESSAGE":"crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.",

"stack":"exception 'ErrorException' with message 'crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.' in :0\nStack trace:\n#0 (): Illuminate\\Exception\\Handler->handleError()\n#1 (): crypt()\n#2 /home/forge/default/vendor/laravel/framework/src/Illuminate/Hashing/BcryptHasher.php(45): password_verify()\n#3 /home/forge/default/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(108): Illuminate\\Hashing\\BcryptHasher->check()\n#4 /home/forge/default/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(371): Illuminate\\Auth\\EloquentUserProvider->validateCredentials()\n#5 /home/forge/default/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(352): Illuminate\\Auth\\Guard->hasValidCredentials()\n#6 (): Illuminate\\Auth\\Guard->attempt()\n#7 /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/Manager.php(138): call_user_func_array()\n#8 /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Manager->__call()\n#9 /home/forge/default/app/controllers/UserController.php(373): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#10 (): UserController->login()\n#11 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array()\n#12 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\\Routing\\Controller->callAction()\n#13 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\\Routing\\ControllerDispatcher->call()\n#14 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\\Routing\\ControllerDispatcher->dispatch()\n#15 (): Closure$Illuminate\\Routing\\Router::getClassClosure()\n#16 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array()\n#17 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\\Routing\\Route->run()\n#18 /home/forge/default/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\\Routing\\Router->dispatchToRoute()\n#19 /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Routing\\Router->dispatch()\n#20 /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\Application->dispatch()\n#21 /home/forge/default/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\\Foundation\\Application->handle()\n#22 /home/forge/default/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\\Session\\Middleware->handle()\n#23 /home/forge/default/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\\Cookie\\Queue->handle()\n#24 /home/forge/default/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle()\n#25 /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\\StackedHttpKernel->handle()\n#26 /home/forge/default/public/index.php(49): Illuminate\\Foundation\\Application->run()\n#27 {main}"

**Comment by ash-rain** [comment]
I still haven't figured this out. Since it broke an app in production I've put the Auth call in a `try { } catch (ErrorException $e) { }` block.
My best guess so far is that Laravel 5.1 is still too poorly tested for release. It's a framework issue AFAIK.

**Comment by ash-rain** [comment]
Just for your information, I also had overlooked that I was trying to authenticate a user with an empty `password` field. That also causes the very same results, but is a completely different matter.

**Comment by MarkVaughn** [comment]
Same issue, how is this a laravel issue if the function throwing the exception is crypt() / password_verify() (native php methods)

**Comment by fredemmott** [comment]
These are *not* throwing exceptions. Something else in your code or Laravel is converting notices into exceptions.

**Comment by MarkVaughn** [comment]
I see your point, but I can not reproduce this on regular PHP, it only get's thrown on HHVM, why would Laravel only behave this way on HHVM?

**Comment by paulbiss** [comment]
It's possible it's some subtle incompatibility in the way the error message is processed in the error handler. I would start by looking there. This isn't really actionable for us until we know what the incompatibility is.

**Comment by fredemmott** [comment]
To clarify: We are not saying this is a bug in Laravel. We are saying that the problem is not HHVM's implementation of these functions.

It's likely that HHVM is doing something different (possibly wrong) in Laravel's error handling code, and that in general, it is not a good use of our time to learn frameworks well enough to trace through and isolate the root cause - that's better done by someone with experience with Laravel.

**Comment by MarkVaughn** [comment]
From https://github.com/laravel/framework/issues/9428
>This appears to only be an issue with php 7.0 which is why laravel doesn't support it yet. HHVM seems to be implementing bits and pieces from php 7 which is why we observe this error.

If that is true this issue could be closed here, that is if @samaiyan was using laravel and that is the cause of his issue

**Comment by ash-rain** [comment]
@MarkVaughn This looks very promising. I'll try it out tomorrow and add feedback to this issue for reference.

**Comment by fredemmott** [comment]
IIluminate was converting it to an error:

```
stack":"exception 'ErrorException' with message 'crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.' in :0\nStack trace:\n#0 (): Illuminate\Exception\Handler->handleError()\n#1 (): crypt()\n#
```

Fix was https://github.com/laravel/framework/pull/9651

**Comment by ash-rain** [comment]
I came to the same conclusion. It's definitely caused by Laravel. Sometimes their docs/support can really, really suck.

**Comment by shahbazmh** [comment]
Notice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.

Pass a parameter.
crypt(1234,'');

**Comment by mazud21** [comment]
> Notice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.
> 
> Pass a parameter.
> crypt(1234,'');

I don't know how, but works
