### ISSUE TITLE
Extra warning on data_seek empty mysql_result

### ISSUE THREAD

**Issue by vearutop** [facebook/hhvm#5025]
```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
echo $nonexistent;
$mysqli = new mysqli('127.0.0.1', 'root', 'password', 'test', null, null);
if (!$mysqli->connect_errno) {
        // query with 0 rows
	$res = $mysqli->query("SHOW VARIABLES LIKE '%hhvm_rocks%'");
	var_dump($res->data_seek(0));
}
```
HHVM 3.7.0-dev
```
Notice: Undefined variable: nonexistent in /root/test-php/test-data-seek-0.php on line 6
Warning: Unable to jump to row 0 on MySQL result index 7 in /root/test-php/test-data-seek-0.php on line 12
bool(false)
```

PHP
```
Notice: Undefined variable: nonexistent in /root/test-php/test-data-seek-0.php on line 6
bool(false)
```

So in PHP you don't need to check `$res->num_rows` before calling `$res->data_seek(0)`, but you need to do it in HHVM. That seems a bit incompatible.

**Comment by bjornpost** [comment]
Can a repo collaborator shine a light on this and let us know if this is by design or a bug?

**Comment by paulbiss** [comment]
Our mysqli implementation differs substantially from PHP 5, which is probably the root cause of the difference. I see no reason why fixing this to special case seeking to row zero in an empty result to not raise a warning would be an issue. Looks like we would just need to make the change [here](https://github.com/facebook/hhvm/blob/c16a7655e47ec04a27f7aec38e00a92a10862041/hphp/runtime/ext/mysql/mysql_common.cpp#L756).
