### ISSUE TITLE
Different behaviour when memory is exhausted

### ISSUE THREAD

**Issue by chmeldax** [facebook/hhvm#5049]
Hi,

consider this code:

```php
ini_set('memory_limit', '1K');

set_error_handler(function () {
    print 'Error handler'.PHP_EOL;
});

register_shutdown_function(function () {
    print 'Shutdown'.PHP_EOL;
});

$x = str_repeat('x', 1024 * 1024 * 2);
```

PHP5 outputs sth like this:
```
Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 2097153 bytes) in /in/WYMID on line 12
Shutdown
```
But, HHVM outputs this:
```
Fatal error: request has exceeded memory limit in /in/WYMID on line 12
Error handler
Fatal error: request has exceeded memory limit in /in/WYMID on line 9
Error handler
```

Apparently, PHP 5 does not invoke error handler when this kind of Fatal Error occurs (not very systematic, so, is it desirable to change this behaviour in HHVM?).
But, strangely, HHVM tries to invoke shutdown function, but fails to invoke anything in it. This applies even to any function call inside error handler.

Therefore I fail to use custom logging logic when this fatal error occurs :).

Haven't got deep into the HHVM's code, but would be happy to help to solve it somehow, if somebody wants to guide me a bit :)

**Comment by paulbiss** [comment]
I believe OOMing in the shutdown handler is by design, ordinarily unwinding the stack during the fatal would reduce the memory pressure enough to run the shutdown handler but since you OOM by filling a global there's still too much memory allocated when the shutdown handler tries to run and it surprises as well when we check status flags at function invocation (doing anything else would be unsafe).

An OOM is a `FatalErrorException` and unless `hhvm.call_user_handler_on_fatals` is set we aren't supposed to run PHP error handlers for those, so that looks like a bug (it's also probably a bug that the error handler doesn't surprise as there's still no memory).
