### ISSUE TITLE
Extend namespace support

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5051]
I'm happy to do this, but want to start some discussion first. Features I've seen requested against PHP:

 - easy way to import multiple classes from the same namespace
 - easy way to import *everything* from another namespace
 - aliasing - eg 'namespace HerpDerp = Foo\Bar\HerpDerp; new HerpDerp\MyClass(); creates an instance of Foo\Bar\HerpDerp\MyClass()

**Comment by nikic** [comment]
Regarding the last point, how does this differ from usual namespace aliasing with `use`?

**Comment by fredemmott** [comment]
TIL that exists.

**Comment by jwatzman** [comment]
We should be pretty sparing and careful here; since FB doesn't use namespaces, anything we do is going to be much less well tested and supported.

I generally don't feel that strongly about namespaces, happy to chat in person; my main thought is not to hurt grepability/readability. (Python's `from blah import *` is my usual example of an anti-feature, too easy to hurt readability.)

**Comment by fredemmott** [comment]
So, this is related to XHP. I'd really like to have 'use xhp\html\*;' or similar.

**Comment by fredemmott** [comment]
Plan is here: https://gist.github.com/fredemmott/1e65842fadb9e66e2359

**Comment by fredemmott** [comment]
Going to track this at facebook/xhp-lib#64
