### ISSUE TITLE
Custom session handler corrupted by session_destroy, "Failed to initialize storage module"

### ISSUE THREAD

**Issue by anomiex** [facebook/hhvm#5072]
The symptoms here are the same as in [PHP bug 32330](https://bugs.php.net/bug.php?id=32330).

Test code:
```
<?php

ob_start();
echo PHP_VERSION . "\n";

// These implement a do-nothing session handler
function s_open( $path, $name ){ return true; }
function s_close(){ return true; }
function s_read( $id ){ return ''; }
function s_write( $id, $data ){ return true; }
function s_destroy( $id ){ return true; }
function s_gc( $t ){ return true; }
session_set_save_handler( 's_open', 's_close', 's_read', 's_write', 's_destroy', 's_gc' );

// Test
session_start();
session_destroy();
session_start();

echo "ok\n";
```

Zend has correct behavior:
```
$ php5 test.php
5.5.9-1ubuntu4.5
ok
```

HHVM throws an error on the second session_start() call:
```
$ php test.php
[Tue Mar 24 20:58:53 2015] [hphp] [13390:7fc71ec27bc0:0:000001] [] 
Warning: Invalid argument: function: not a valid callback array in /path/to/test.php on line 18
[Tue Mar 24 20:58:53 2015] [hphp] [13390:7fc71ec27bc0:0:000002] [] 
Fatal error: Failed to initialize storage module: user (path: ) in /path/to/test.php on line 18
5.6.99-hhvm
[Tue Mar 24 20:58:53 2015] [hphp] [13390:7fc71ec27bc0:0:000003] [] 
Warning: Invalid argument: function: not a valid callback array
```

Same results if implementing SessionHandlerInterface.

**Comment by DmitrySoshnikov** [comment]
Yeah, HHVM currently doesn't support this prototype of the `session_set_save_handler`. The only prototype of this function which is supported is: 

```
function session_set_save_handler ( SessionHandlerInterface $sessionhandler [, bool $register_shutdown = true ] ): bool
```

It also doesn't support passing actual callback functions, so the documentation here is actually misleading: http://docs.hhvm.com/manual/en/function.session-set-save-handler.php.

I guess for backward compatibility we can fix it, although since PHP 5.4. seems a preferred way is to use a handler class that implements `SessionHandlerInterface`, which prototype HHVM supports (at least it can be used as a workaround for now for custom handlers).
