### ISSUE TITLE
Using 'setAll' in Map of Maps yields different results depending on how outer map was declared

### ISSUE THREAD

**Issue by deltaxfx** [facebook/hhvm#5161]
Creating a Map of Maps by setting $outer[$key] = $existingMap; gives a different result when using 'setAll' at a later point vs $outer[$key] = Map{}; $outer[$key]->setAll($existingMap); and then adding additional key/values later with setAll.
Consider the following:
```
<?hh

$outer = Map{};

$m1 = Map{"m1-1" => "m1-one",
            "m1-2" => "m1-two"};
            
$m2 = Map{"m2-1" => "m2-one",
            "m2-2" => "m2-two"};             

// incorrect results
$outer[100] = $m1;
$outer[200] = $m1;

// correct results                
/* $outer[100] = Map{};
$outer[200] = Map{};

$outer[100]->setAll($m1);
$outer[200]->setAll($m1); */


echo "\nBefore\n" . var_export($outer, true);

$outer[200]->setAll($m2);

echo "\n\n\nAfter\n" . var_export($outer, true);
echo "\n";

```
outputs:
```
Before
HH\Map {
  100 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
  },
  200 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
  },
}


After
HH\Map {
  100 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
    'm2-1' => 'm2-one',
    'm2-2' => 'm2-two',
  },
  200 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
    'm2-1' => 'm2-one',
    'm2-2' => 'm2-two',
  },
}
```

By setting both $outer values to empty Maps first, the seemingly correct output is yielded:
```
<?hh

$outer = Map{};

$m1 = Map{"m1-1" => "m1-one",
            "m1-2" => "m1-two"};
            
$m2 = Map{"m2-1" => "m2-one",
            "m2-2" => "m2-two"};             

// incorrect results
/* $outer[100] = $m1;
$outer[200] = $m1; */

// correct results                
$outer[100] = Map{};
$outer[200] = Map{};

$outer[100]->setAll($m1);
$outer[200]->setAll($m1);


echo "\nBefore\n" . var_export($outer, true);

$outer[200]->setAll($m2);

echo "\n\n\nAfter\n" . var_export($outer, true);
echo "\n";

```

Outputs:
```
Before
HH\Map {
  100 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
  },
  200 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
  },
}


After
HH\Map {
  100 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
  },
  200 =>
  HH\Map {
    'm1-1' => 'm1-one',
    'm1-2' => 'm1-two',
    'm2-1' => 'm2-one',
    'm2-2' => 'm2-two',
  },
}

```

Is the first example the intended result? Why would setting only a single inner Map with 'setAll' end up setting both inner Maps in the first example?

**Comment by oyamauchi** [comment]
Sorry, this slipped under my radar for a few days.

Yes, that's the intended result. I think the reason for your confusion is that Maps are objects, so they have reference semantics, unlike arrays, which have value semantics.

In this code...

```hack
$outer[100] = $m1;
$outer[200] = $m1;
```

... you're making the two keys in the $outer Map point to *the same object*. That map, $m1, is not copied at any point. So, when you later do `$outer[200]->setAll($m2)`, you're doing setAll on that one object, and you see the changes through both keys in the outer map.

If $m1 were an array instead of a Map, the end result would be what you're expecting.

In this code...

```hack
$outer[100] = Map{};
$outer[200] = Map{};

$outer[100]->setAll($m1);
$outer[200]->setAll($m1);
```

... there are two separate Map objects (each `Map {}` expression creates a new one) that happen to have the same contents. So changing one doesn't affect the other.

Does that make sense? I can explain more if you want.

**Comment by deltaxfx** [comment]
It makes perfect sense now, thanks for the great explanation!
