### ISSUE TITLE
return from `finally` block is not supported

### ISSUE THREAD

**Issue by reeze** [facebook/hhvm#5162]
http://3v4l.org/LZ0Mq

```
Fatal error: Return inside a finally block is not supported in /in/LZ0Mq on line 12

Process exited with code 255.
```

**Comment by SiebelsTim** [comment]
Duplicate #4234

We might want to discuss about the spec though.

**Comment by reeze** [comment]
It seems Python & Java behave the same as PHP. It was just implemented just for consistent with other languages' sake from the mailing achieve.

**Comment by Orvid** [comment]
See the issue above for why.

**Comment by SiebelsTim** [comment]
@Orvid It's in the spec though and PHP7 implements it that way. Should we at least include this in the docs somewhere?

**Comment by nikic** [comment]
There is a standard pattern that can be used to circumvent language-enforced limitations on finally:

```
<?php

class ControlRedirection extends Exception {}

function test() {
    try {
        try {
            return 24;
        } finally {
            throw new ControlRedirection;
        }
    } catch (ControlRedirection $e) {
        return 42;
    }
}

var_dump(test());
```

It works simply by redirection control flow from the finally into a catch clause, which does not have flow limitations.

Of course, writing the code directly in the finally is a bit more ergonomic.

**Comment by Orvid** [comment]
You shouldn't be writing a return in the finally to begin with; It isn't needed. Catch the exception and return after the catch block.

Supporting returning from a finally requires significant amount of extra complexity to be added to the handling of the control flow, and also makes handling exceptions more expensive.

Take this for instance (https://3v4l.org/gKkua):
```
<?php
function test() {
  try {
    throw new Exception;
  } catch(Exception $e) {
    return 2;
  } finally {
    return 5;
  }
}
var_dump(test());
```
This returns `5`, not `2` as you might expect. This is non-trivial to implement, and counter-intuitive to use, so much so that .Net (and all languages that compile to it; C#, VB.Net, F#, etc.) doesn't allow it at all.
