### ISSUE TITLE
Supporting "const" for objects and methods

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5169]
Coming from a C++ background, I've found "const" to be of great help in reasoning about programs, and help catching silly bugs.

For example (using PHP syntax):

```
class Test
{
  public function f(): void
  {
    $this->something="Test";
    $this->g();
    echo $this->something; // Prints "Test", regardless of what g() may do [1]
  }

  public function g() const: void // [2]
  {
    $this->something="Overwrite"; // Error, attempting to change a const object
 }

  private string $something;
}
```

I know this is a large change, but I just wanted to open an issue to ask if it has been, or is being considered?

One of the advantages of functional programming is no mutable state, which helps to reason about programs. With "const" we may enforce immutability, and in the same way aid reasoning about the program.

This would also take care of issue #3816: Just make the parameters "const".

[1]  g() is "const", so I know that no member data has been changed by the g() function call
[2]  "const" makes $this inside the function implicitly point to a const object

**Comment by oyamauchi** [comment]
We can consider this, but I'll first point out that in PHP, it can be really really hard to ensure that anything is const in this way.

```hack
class C {
  public function f() const {
    some_function();
  }
}
```

We can't be sure this is correct, because `some_function()` might throw an exception (even indirectly) or otherwise raise an error, and then the `$this` object from `f()` would be accessible in the backtrace, and you could do anything with it. We could introduce a concept of a "const" reference to an object to close this loophole (by making the reference stored in the backtrace "const"), but that would go way beyond a typechecker-level feature; it requires runtime support.

**Comment by tslettebo** [comment]
Thanks for your reply.

**Comment by jwatzman** [comment]
We've talked about the ability to make general objects immutable, which is somewhat easier to support in the runtime. (There might even be a github issue about it somewhere?) We don't have anyone working on it right now, and there are some interesting design questions, e.g., does it need to be transitive? (More restrictive, but allows some cool optimizations.) But I think it would get the gist of what you're getting at here, with the added bonus of being much easier to implement :)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

👋🏻 from the future. A lot has happened in the last 6 years. Hack is getting a `readonly` feature. It is still experimental in the docs, but the hhvm team is removing the flags and it will be released as stable soon. https://docs.hhvm.com/hack/experimental-features/read-only
