### ISSUE TITLE
3.6.1 compilation fails when mysql server is not installed

### ISSUE THREAD

**Issue by burner1024** [facebook/hhvm#5186]
```
-- Performing Test LIBICONV_CONST
-- Performing Test LIBICONV_CONST - Failed
CMake Error at CMake/HPHPFindLibs.cmake:86 (message):
  Could not find MySQL socket path - if you install a MySQL server, this
  should be automatically detected.  Alternatively, specify
  -DMYSQL_UNIX_SOCK_ADDR=/path/to/mysql.socket ; if you don't care about unix
  socket support for MySQL, specify -DMYSQL_UNIX_SOCK_ADDR=/dev/null
Call Stack (most recent call first):
  CMake/HPHPSetup.cmake:97 (include)
  third-party/CMakeLists.txt:18 (include)
```
Why would mysql socket be required for building binaries? If it's not available, just assign some default value.

**Comment by paulbiss** [comment]
I believe we were having issues with assigning the wrong default and then causing problems when people actually did install a MySQL server. @fredemmott would have more context on this though.

**Comment by jwatzman** [comment]
IIRC the problem is the default value depends very heavily on what distro you're on and what version of the distro you're using. We can figure it out from a mysql server, otherwise you have to tell us where your distro wants to put it.

**Comment by burner1024** [comment]
If you refer to #4987, I believe that the issue is actually that HHVM had (or has?) socket path hardcoded. This is not the same as having wrong default value.

"Wrong default" doesn't make much sense, anyway. It's just default. If it can be changed, there should be no problem. (And it's package maintainer's job to provide a config with sensible defaults for the distro).

If you're going to keep the path hardcoded, then yes, it does make sense to try and determine the socket path. Otherwise, I would say it doesn't.

**Comment by fredemmott** [comment]
" Could not find MySQL socket path - if you install a MySQL server, this
  should be automatically detected.  Alternatively, specify
  -DMYSQL_UNIX_SOCK_ADDR=/path/to/mysql.socket ; if you don't care about unix
  socket support for MySQL, specify -DMYSQL_UNIX_SOCK_ADDR=/dev/null"

The value is distro-dependent. Resolutions are provided in the error message.

**Comment by fredemmott** [comment]
As for why:
 - we build, and statically link against webscalesql-client, instead of the system mysqlclient/mariadbclient or whatever else is available.
 - All C mysql clients (and derivatives) have a socket path hardcoded, and as we're building our own, we need to figure out what it is
 - we're building our own because the async mysql extension depends on functionality that doesn't exist in maria or mysql, and existing packages for webscaleclient conflict with system client packages; they don't need to any more as the shared object name has changed, but it takes a while for this to actually be reflected in the packages.

**Comment by fredemmott** [comment]
Upstream's default value is '/tmp/mysql.socket' or something like that, which works pretty much nowhere. Building a per-distribution lookup-table didn't seem like something that would be reasonable for us to maintain.

**Comment by burner1024** [comment]
> All C mysql clients (and derivatives) have a socket path hardcoded

That's certainly not the case. mysqlclient socket path can be configured.

> and as we're building our own, we need to figure out what it is

If it's configurable, there's no *need*, although you can *try*.

Up to your judgement, of course.

**Comment by fredemmott** [comment]
There is a default hardcoded. Users of the library can reconfigure this to some other path (though hhvm has another open issue about that not working :( ).

When 3.6.0 went out, we found out a lot of apps have 'localhost' hardcoded - no centralized database configuration - so, even if the options did work in HHVM (and it should be changed so that they should), realistically, we need to get the defaults right.

A build error:
 - means that we don't accidentally ship packages with a bad default
 - gives a much clearer error than the runtime error you get if you just say 'localhost' and that uses the wrong default socket path
 - affects a much smaller, more technically-minded group of people than a bad default

**Comment by fredemmott** [comment]
#4987 was really several issues that kept on getting confused:
 - #5002: bad defaults. This mattered to a lot of people
 - #5003, #5004: can't change the defaults. No-one even noticed until we messed the defaults up. Still open
