### ISSUE TITLE
$this from incompatible context

### ISSUE THREAD

**Issue by sanxiyn** [facebook/hhvm#5192]
http://3v4l.org/QqIOU

[XpressEngine](http://www.xpressengine.com/), THE most popular PHP CMS in South Korea, depends on this behavior.

**Comment by jwatzman** [comment]
HHVM optimizes based on the types of variables. Outside repo mode, one of the few things that we know statically is that `$this` is a subtype of the declaring class, and the JIT assumes this in a bunch of places. This would break that assumption, meaning

- it would be messy to clean up
- it would be a big perf loss
- or, it would be a giant, annoying, hard-to-maintain bit of code to make it not a perf loss
- all for a feature of very very questionable usefulness (old/messy/broken frameworks aside)
- especially since PHP7 might kill this anyways

So, I don't think we're going to fix this. We should explicitly add it to https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies

**Comment by jesseschalken** [comment]
This raises an `E_STRICT` in PHP 5.1-5.5, an `E_DEPRECATED` in PHP 5.6, and causes a fatal `E_ERROR` in PHP 7.0-7.1.

Might as well close this as wont fix.
