### ISSUE TITLE
Unable to install HHVM in Ubuntu 15.04

### ISSUE THREAD

**Issue by cortopy** [facebook/hhvm#5203]
Ubuntu 15.04 stable version is just out and I upgraded. However, the tutorial at the wiki is creating unmet dependencies issues when trying to install HHVM. 

This is the error I get

```
dpkg: dependency problems prevent configuration of libgnutls26:amd64:
 libgnutls26:amd64 depends on libgcrypt11 (>= 1.4.5); however:
  Package libgcrypt11 is not installed.

dpkg: error processing package libgnutls26:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.21-0ubuntu4) ...
Errors were encountered while processing:
 libgnutls26:amd64
```

**Comment by jwatzman** [comment]
Yeah the "tutorial" has you install 14.10 packages on 15.04, which is probably a really bad idea, liable to break your system, and might just not work (like here). I added a somewhat stronger warning to the wiki page.

Getting proper 15.04 support shouldn't be too hard, but not sure when someone will get to it.

I bet that building from source will lead to more success and less likelihood of system breakage -- you'll be following the 14.04 directions, but that's safe, since it only installs system packages, and things haven't changed much since 14.04 build-wise.

**Comment by cortopy** [comment]
I'm afraid installing from source for 14.04 doesn't work either @jwatzman 

By chance, last weekend I was reading http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html 

Libgcrypt11 has been upgraded to libgcrypt20 so HHVM is currently uninstallable in the latest Ubuntu unless the library is installed manually. 

Is there any chance this is added to HHVM?

**Comment by jwatzman** [comment]
We don't build with libgcrypt20?

**Comment by bardiharborow** [comment]
:+1:

**Comment by jwatzman** [comment]
I just pushed working control files for vivid into the packaging repo. (The build-from-source directions work as-is.) We still need to get a build VM set up to start running nighties, not sure when that will happen.

**Comment by jwatzman** [comment]
Closing this in favor of https://github.com/hhvm/packaging/issues/119 which is actually the right repo for this.
