### ISSUE TITLE
Anonymous function doesn't match 'callable' type

### ISSUE THREAD

**Issue by Nattfarinn** [facebook/hhvm#5211]
According to documentation ( http://docs.hhvm.com/manual/en/language.types.callable.php ):

> Callbacks can be denoted by callable type hint as of PHP 5.4. This documentation used callback type information for the same purpose. (...) Apart from common user-defined function, anonymous functions can also be passed to a callback parameter.

But type checker disallow such construction:

```hh
<?hh

function callable_test(callable $function) : void
{
    $function();
}

callable_test(
    function() : void
    {
        // ...
    }
);
```

And complains about:
> test.hh|5 col 5 error|  This call is invalid, this is not a function, it is an object of type callable (Typing[4009])

**Comment by paulbiss** [comment]
A callable annotation is a PHP feature, but the error is from Hack not the runtime. The problem is that for your code to typecheck hh_server needs to know the signature of `$function` (e.g. `$function()` should be a type error if you pass a function that requires arguments). For Hack you need to type the callable,

```php
<?hh

function callable_test((function(): void) $function): void {
    $function();
}

callable_test(function(): void { /* ... */ });
```

For more information see: http://docs.hhvm.com/manual/en/hack.annotations.functiontypes.php

**Comment by fredemmott** [comment]
We allow it in PHP code, but it's documented as not being allowed in Hack.
