### ISSUE TITLE
File-local function names?

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#5254]
Since type-checking only happens for classes and functions, not for top-level code, and since top-level code is not allowed in strict mode, we were thinking of wrapping the top-level code for each file we have in a `main()` function.

However, we ran into a problem: It appears that function names need to be globally unique for the type checker to work, so if you have more than one file with `main()`, it complains about duplicate definitions.

I guess there's no way to make it treat a function as file-local?

**Comment by steelbrain** [comment]
Ever heard of namespaces?

**Comment by tslettebo** [comment]
Someone suggested namespaces (but the comment appears to be gone now): Yes, I've thought of it, but the thing is, if you have code like this:
```
<?hh

main();

function main(): void
{
  ...
}
```

and you change it to use namespaces, adding e.g. `namespace login;``at the top, then everything inside `main()` will have to explicitly state the global namespace "\" for anything outside the file.

If we had anonymous namespaces (like in C++) that would mean you could have a main() in each file, and they wouldn't be confused with each other by the typechecker.

Maybe something to consider for HHVM/Hack?

**Comment by lexidor** [comment]
I feel this issue has become less pressing with the introduction of `<<__EntryPoint>>` and the subsequent removal of pseudo mains.

```HACK
<<__EntryPoint>>
async function main_anything_goes(): Awaitable<void> {}
```

You don't have to invoke this function. The runtime will involve it at request start. Although I don't recommend it, keyboard smash would be valid. The name appears in stack trace.

Someone noted this idea a long time ago, which is why I didn't close this issue before.

```
<<__EntryPoint>>
async function __FILE__(): Awaitable<void> {}
```

This function would not be callable, `__FILE__()` would be invalid. At name at runtime would be the file path mangled to be a valid function name. (Slashes are invalid in function names for example.)

This idea didn't end up going anywhere.

The one-entrypoint-per-url style has gone out of style since more setup is needed to get a request started. A request router makes single / one-hand-countable entrypoints per application very tenable.

Hack is experimenting with modules, where functions, contants, and types can be made explicitly `public`. Anyone interested in this issue for implementation hiding could track that progress.
