### ISSUE TITLE
Optimize dynamic properties

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5266]
There are a few things we can try to optimize dynamic properties:
* Infer properties and augment declared properties in HHBBC
* Avoid the double indirection by finding a way to cache the dynprop table on classes known to have dynamic properties
* Separate out the loading of the dynprop table and teach load-elim to optimize it
* Cleanup frameworks to declare properties where easy to do

**Comment by edwinsmith** [comment]
indexing the dynproptable using oid might be faster than the hashtable.

**Comment by jwatzman** [comment]
> Infer properties and augment declared properties in HHBBC

Looked at this in Drupal briefly. Most if not all of the places I saw were on `stdClass`, as far as I could trace back -- in any event, HHBBC had no idea what the type of the object would have been in order to add the properties as declared. One place in Drupal was particularly hot -- this object is responsible for much of the dynamic property access: https://github.com/drupal/drupal/blob/7.31/includes/bootstrap.inc#L2773 We actually could silently make that object-cast-of-array-literal into a real sublcass of `stdClass`. I tested this with a small patch:

```
diff --git a/includes/bootstrap.inc b/includes/bootstrap.inc
index c2a84a1..2ecc94b 100644
--- a/includes/bootstrap.inc
+++ b/includes/bootstrap.inc
@@ -2763,6 +2763,20 @@ function language_list($field = 'language') {
   return $languages[$field];
 }
 
+class localeObj extends stdClass {
+       public $language = 'en';
+       public $name = 'English';
+       public $native = 'English';
+       public $direction = 0;
+       public $enabled = 1;
+       public $plurals = 0;
+       public $formula = '';
+       public $domain = '';
+       public $prefix = '';
+       public $weight = 0;
+       public $javascript = '';
+}
+
 /**
  * Returns the default language used on the site
  *
@@ -2770,7 +2784,7 @@ function language_list($field = 'language') {
  *   Optional property of the language object to return
  */
 function language_default($property = NULL) {
-  $language = variable_get('language_default', (object) array('language' => 'en', '
+  $language = variable_get('language_default', new localeObj());
   return $property ? $language->$property : $language;
 }
```

That was maybe maybe a very small perf win on Drupal... but implementing this in HHBBC would be so specialized and annoying that I'm reluctant to do it. Gonna focus on other stuff instead, writing up here for benefit of others :)

**Comment by paulbiss** [comment]
I did get_object_vars and clone along with COW dynamic property arrays. Looks like 2% in wordpress, noise elsewhere. I suspect there's something to be gained with drupal but I'm not sure what I'm missing.
