### ISSUE TITLE
See if any of the memcpys in string-data can be wordcpy (t3211108)

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5297]
Concat is hot and this may be an easy thing for us to try out.

**Comment by JoelMarcey** [comment]
I looked at this and there is no measurable thing that can be done with wordcpy that isn't already being tried with @binliu's memcpy work.

**Comment by apinski-cavium** [comment]
If you are finding memcpy is slower than wordcpy then there is a bug which should be fixed on the GCC/glibc side.  Please don't try fixing this in isolation, it is wrong to do and the performance can be different on newer processors too.

**Comment by paulbiss** [comment]
@apinski-cavium: we have our own implementation of memcpy in hphp/util, it is unrelated to glibc. That being said I don't think @JoelMarcey saw much from this, we do have a few other ideas that may stack nicely on top of this change though.

**Comment by apinski-cavium** [comment]
Yes I understand that you have a currently your own implementation.  What I trying to say is that you should try to combine it with the upstream instead of having your own implementation.  If you don't do this, it won't be good for other stuff you run on the machine and also could hurt you in the future with different cores.  Also the glibc version has multiply different versions each for a different core.

**Comment by paulbiss** [comment]
I wouldn't be against upstreaming it if we can demonstrate it's sufficiently general to be worth using in other projects, though iirc it's still being actively iterated on so it wouldn't make any sense to do that in its current state.

Regardless, I think it makes sense to study these optimizations within the scope of hhvm so we can experiment rapidly and remain flexible to changes not necessarily compatible with other projects with the idea that at some point we may upstream them to glibc (though, importantly, being sufficiently general to do this is not at all a goal).
