### ISSUE TITLE
Experiment with pcre2 (t6514506)

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5302]
Given how hot pcre is we should definitely try this one out, the new pcre library is supposed to be faster/better supported.

**Comment by JoelMarcey** [comment]
The API for PCRE2 is a non-trivial difference than PCRE, which will require a bunch of changes on the HHVM end to implement. My hunch still tells me there is something to be gained here. I will look at some possible smaller wins for a while though too.

**Comment by JoelMarcey** [comment]
I commented on the internal task, but the gist is that after modifying our PCRE implementation to use the new PCRE2 API, there was no fruitful perf win. I contacted the designer of PCRE and he said that PCRE2 was more of an API and design change than a perf change -- that conforms to what I found.

That said, we should move using PCRE2 since it doesn't seem to be a perf degradation. All was within the noise. Or we should look at RE2 as well.
