### ISSUE TITLE
HHBBC's ConcatN optimization looks broken (t6599959)

### ISSUE THREAD

**Issue by paulbiss** [facebook/hhvm#5304]
We definitely want to fix this one. Concat is hot pretty much across the board.

**Comment by jwatzman** [comment]
There are a few problems.

- Diff is up internally to fix generating ConcatN in HHBBC
- However, it will only do it if it can statically figure out the vars are strings. Need to remove that restriction and have the JIT look at the runtime types, falling back on successive Concat's if they are not actually strings.

The first part is neutral for Durpal. Just removing the restriction in HHBBC is negative for Drupal, probably because we punt to the interpreter too much. Making it smarter should be a win.

**Comment by jwatzman** [comment]
Diff is up for all of this... it's in the noise though AFAICT, on all of FB, Drupal, and Wordpress. Suspicion is that we were already reserving enough space that we could just append (via mutation) in a lot of cases, and in particular for the very hot `file_scan_directory`, the way it uses `$dir` means that we have to do a full set of copies anyways.

Might still be a small win in some cases anyways, so it's worth doing, but not as nice as I'd hoped.

**Comment by paulbiss** [comment]
@jwatzman should this be closed now or are there outstanding diffs?

**Comment by jwatzman** [comment]
There is an outstanding diff (internal id D2070233) -- but its perf implications are unclear. Pretty sure it's neutral on OSS code, and the experiments on FB are inconclusive. I haven't taken the time to finish it up since it wasn't an OSS win, probably will talk to the JIT folks next week and figure out what the experiments really mean.

So yeah, closing this, no result :(
