### ISSUE TITLE
PHP5 incompatible fastcgi parameter matching order

### ISSUE THREAD

**Issue by lukvdborne** [facebook/hhvm#5320]
When overwriting fastcgi_param entries (in nginx, but most probably also in combination with other web server software), there appears to be a mismatch between the matching order in hhvm and in php5. Given the following configuration file with fastcgi parameters:

```
...
fastcgi_param  SERVER_SOFTWARE    string_a;
fastcgi_param  SERVER_SOFTWARE    string_b;
...
```

In PHP5, $_SERVER['SERVER_SOFTWARE'] will be populated with "string_b" (last match wins), whilst with hhvm that same environment variable is populated with "string_a" (first match wins). 

HipHop VM 3.7.0 (rel)
Compiler: tags/HHVM-3.7.0-0-gc8baf9cd3cb603e030969bfe24634d5e85549915
Repo schema: 1988ce75e6a571ce9c79c60fd7dc3ca8a5a5d403

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not buggy or broken. Changing the order around after having been stable on "the first one wins" might break users who depended on this behavior unknowingly.
