### ISSUE TITLE
Unbound name: DOMDocument (an object type) (Naming[2049])

### ISSUE THREAD

**Issue by arzeth** [facebook/hhvm#5322]
``` hack
<?hh // strict
class Example
{
    public function test(): void
    {
        $dom = new \DOMDocument('1.0', 'UTF-8');
    }
}
```

I use DOMDocument/DOMElement/DOMNode classes without problems in my project (Hack in strict mode).
Except that the typechecker says:
`Unbound name: DOMDocument (an object type) (Naming[2049])`
So I add `// UNSAFE`, but that's not beautiful.

```
HipHop VM 3.7.0 (rel)
Compiler: 1430225359_311382370
Repo schema: bab2fb342e0e21b096813ebb19860646b8eaa0d2
```

**Comment by paulbiss** [comment]
Looks like we don't have an hhi for DOMDocument yet to teach hack what the interface is. You can send us a PR if you'd like.

https://github.com/facebook/hhvm/tree/master/hphp/hack/hhi/stdlib

**Comment by jwatzman** [comment]
Isn't DOMDocument one of the PHP models where the API is to access (undeclared) properties on it? In that case, having an hhi for it would actually be bad, since you couldn't access any of those properties. It can't be made typesafe... in general, most XML/HTML parsing APIs can't, for similar reasons. So we let it slide in partial, you can do what you want, but are, well, stricter in strict mode :)

**Comment by paulbiss** [comment]
I think you're thinking of SimpleXML (there's a separate issue for that and we should probably support it via type-checker magic). DOMDocument/DOMNode have properties that we implement using native-prop-handlers but we know statically what they are. Some of them are readonly, so having Hack support to prevent accidental writing to them might be nice.

http://php.net/manual/en/class.domnode.php

**Comment by jwatzman** [comment]
Ah yeah must have gotten those mixed up. Would be happy to take a PR for an hhi here.
