### ISSUE TITLE
Add Magento2 or Symfony2 to  HHVM Lockdown

### ISSUE THREAD

**Issue by kandy** [facebook/hhvm#5333]
Since these frameworks  greatly different by the use of functional of php (Fully OOP) with Wordpress/Drupal, results of performance improvement for them can (theoretically) be very different.
Will be excellent to add some of these to benchmark scripts.
Thanks

**Comment by danslo** [comment]
I have been meaning to add Magento 2 (after already having done so for Magento 1) to https://github.com/hhvm/oss-performance. Just need to find the time. @fredemmott are there public results for that project yet?

**Comment by fredemmott** [comment]
We're /very/ unlikely to add anything more to this lockdown - two weeks is a short period of time, and this would nearly double the number of things we're looking at. Symfony2 is particularly unlikely as it's a framework rather than a site - as a general rule profiling the example pages for these gives identical results to just ```<?php echo "hello, world";```, and for larger sites built on them the application-specific code overwhelms the framework.

Sorry, there aren't - I expect we'll release something once lockdown's finished.
