### ISSUE TITLE
Calling isset() on the subkey of a non-existant ArrayObject key triggers an undefined index notice

### ISSUE THREAD

**Issue by Renegade334** [facebook/hhvm#5338]
If `$ao` is an `ArrayObject` object, and `$ao['key1']` does not exist, calling `isset($ao['key1']['key2'])` returns a notice in HHVM, whereas it does not in PHP, nor would it if `$ao` were a true array.

``` php
<?php
$ar = array(
    'foo' => ['bar' => true],
);
$ao = new ArrayObject($ar);

var_dump(isset($ao['foo']));
var_dump(isset($ao['bar']));
var_dump(isset($ao['foo']['bar']));
var_dump(isset($ao['bar']['foo']));
```

```
renegade@ochre:~$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

renegade@ochre:~$ hhvm --version
HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-gf5d2c501115ee8dba1f6968e30f2beb2f1bf553c
Repo schema: 2eb94b605808de96a5c4be57202b6c660855ffb7

renegade@ochre:~$ php aotest.php 
bool(true)
bool(false)
bool(true)
bool(false)

renegade@ochre:~$ hhvm aotest.php 
bool(true)
bool(false)
bool(true)

Notice: Undefined index: bar in /home/renegade/aotest.php on line 10
bool(false)
```

**Comment by filips123** [comment]
Is there any update? There is still similar error with `ArrayAccess`. See https://stackoverflow.com/questions/51697914/php-5-6-arrayaccess-function-isset-calls-offsetget-and-causes-undefined-index and https://3v4l.org/7C2Fs.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears ArrayObject was removed from hhvm in January of 2020 in this [diff](https://github.com/facebook/hhvm/commit/6cf35c3ec4408eab3e4ffe1c8132c529a25d81ea#diff-cf73158617a5d4d976eda8e2f5132659). This roughly to hhvm 4.42-ish, but the blogpost does not mention this breaking change.
ArrayAccess does not have magic behavior anymore since hhvm [4.45.0](https://hhvm.com/blog/2020/02/19/hhvm-4.45.html).
