### ISSUE TITLE
Calling unset() on a nested array key within an ArrayObject has no effect

### ISSUE THREAD

**Issue by Renegade334** [facebook/hhvm#5339]
If `$ao` is an `ArrayObject` object, and `$ao['key1']` is an array, then calling `unset($ao['key1']['key2'])` has no effect.

``` php
<?php
$ar = ['foo' => ['bar' => true]];
$ao = new ArrayObject($ar);

var_dump($ao['foo']['bar'], $ao);

echo "\n";

unset($ao['foo']['bar']);
var_dump($ao['foo']['bar'], $ao);

echo "\n";

unset($ao['foo']);
var_dump($ao['foo'], $ao);
```

```
renegade@ochre:~$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

renegade@ochre:~$ hhvm --version
HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-gf5d2c501115ee8dba1f6968e30f2beb2f1bf553c
Repo schema: 2eb94b605808de96a5c4be57202b6c660855ffb7

renegade@ochre:~$ php aotest.php 
bool(true)
object(ArrayObject)#1 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    ["foo"]=>
    array(1) {
      ["bar"]=>
      bool(true)
    }
  }
}

PHP Notice:  Undefined index: bar in /home/renegade/aotest.php on line 10
NULL
object(ArrayObject)#1 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    ["foo"]=>
    array(0) {
    }
  }
}

PHP Notice:  Undefined index: foo in /home/renegade/aotest.php on line 15
NULL
object(ArrayObject)#1 (1) {
  ["storage":"ArrayObject":private]=>
  array(0) {
  }
}

renegade@ochre:~$ hhvm aotest.php 
bool(true)
object(ArrayObject)#1 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    ["foo"]=>
    array(1) {
      ["bar"]=>
      bool(true)
    }
  }
}

bool(true)
object(ArrayObject)#1 (1) {
  ["storage":"ArrayObject":private]=>
  array(1) {
    ["foo"]=>
    array(1) {
      ["bar"]=>
      bool(true)
    }
  }
}

Notice: Undefined index: foo in /home/renegade/aotest.php on line 15
NULL
object(ArrayObject)#1 (1) {
  ["storage":"ArrayObject":private]=>
  array(0) {
  }
}
```

**Comment by SiebelsTim** [comment]
Looks like php is doing some magic with `ArrayObject`. Plain `ArrayAccess` classes can't do that, because only the first key is passed.

**Comment by kadet1090** [comment]
I'm amazed that this was not fixed in about year... @SiebelsTim You're wrong, plain ArrayAccess can do it - just return reference instead of copy. And this is probably wrong with hhvm too: https://github.com/facebook/hhvm/blob/master/hphp/system/php/spl/miscellaneous/ArrayObject.php#L251 The only thing that is necessary to do to put little & before function name - and assuming that ArrayAccess is compatible with php - it will work just fine. I can make pull request but i'm unable to build it as i'm working on windows. Can any one do that?

**Comment by jesseschalken** [comment]
Shorter test code: https://3v4l.org/uiedX

```php
$a = new ArrayObject(['key' => [0 => 1]]);
unset($a['key'][0]);
var_dump($a['key']);
```

PHP:

```
array(0) {
}
```

HHVM:

```
array(1) {
  [0]=>
  int(1)
}
```

https://3v4l.org/9Jp5p

**Comment by jesseschalken** [comment]
@kadet1090 Did you ever submit your PR?

**Comment by kadet1090** [comment]
@jesseschalken yes, it's even referenced in this issue, but it fails on other tests and i have no linux machine to test it out and it's not something that is so important for me to create linux development environment only for HHVM. Here is PR: https://github.com/facebook/hhvm/pull/6995 you can fix that if you'll

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It appears ArrayObject was removed from hhvm in January of 2020 in this [diff](https://github.com/facebook/hhvm/commit/6cf35c3ec4408eab3e4ffe1c8132c529a25d81ea#diff-cf73158617a5d4d976eda8e2f5132659). This roughly to hhvm 4.42-ish, but the blogpost does not mention this breaking change.
ArrayAccess does not have magic behavior anymore since hhvm [4.45.0](https://hhvm.com/blog/2020/02/19/hhvm-4.45.html).

**Comment by lexidor** [comment]
Whoops, tried to close the issue, but ended up just leaving a comment.
