### ISSUE TITLE
Missing "News" information for 3.6 branch

### ISSUE THREAD

**Issue by photodude** [facebook/hhvm#5364]
The [news file](https://github.com/facebook/hhvm/blob/HHVM-3.6/NEWS) for the HHVM 3.6 branch lacks details on the 3.6.1 (Mar 23, 2015) and 3.6.2 (Apr 27, 2015) releases.

**Comment by paulbiss** [comment]
The newsfile is updated to track interesting commits in our internal releases (every two weeks). As each 3.x.0 external release has a corresponding internal release (but not vice-versa) it also tracks interesting commits in external releases. We've never updated the newsfile for 3.x.y releases.

The incremental releases to LTS and latest release branches are not tracked in the newsfile mostly because there are generally so few cherry-picks it would be pretty easy to just look at the commit summaries.

In 3.6.1 we added a CMake error if we can't determine where to look for a mysql socket, fixed HTTPS detection in FastCGI, and fixed an ASAN error in FastCGI.

In 3.6.2 we fixed a mcrouter related compilation error, added an HHI for async curl, and fixed a crash in DOMDocument (CVE related security fix).

The upcoming 3.6.3 release has picks to fix connection pooling in async mysql and fix a crash in persistent PDO connections.
