### ISSUE TITLE
Reason why execheap access is needed

### ISSUE THREAD

**Issue by rodehoed** [facebook/hhvm#5375]
Hi,

It seems HHVM is trying to access execheap memory which is not a good idea (security wise and is not allowed with POSIX standard). 

An SELinux AVC was telling me that HHVM wants access to execheap and hhvm will crash. The crash will occur after the cache is warming up (like 10 reloads on a webpage).

Only if you allow hhvm to access execheap with an SELinux boolean it will work.

I tested this on a RHEL 7.1 box with the rpm from jrobeson.

Is this intended behaviour?

Cheers

**Comment by fredemmott** [comment]
Security: not relevant, we're a JIT - executable + writable memory is a strict requirement. Same goes for the JVM, and the various javascript JITs in browsers.

There may be more portable ways to achieve this, but we currently target a limited number of platforms so that's not a current concern. More portable ways would still have the same security implications.

**Comment by rodehoed** [comment]
Well I for what it's worth I don't agree. eg JVM works fine (and runs on a lot of different POSIX systems). mmap should be the proper way to make memory exectable instead of mprotect.

**Comment by paulbiss** [comment]
It's not as simple as using mmap to grab executable pages for the TC. We currently rely on the entire TC being in low memory (addresses < 2GB), so we either need to use sbrk or jemalloc's low_malloc to allocate the pages we write the TC into.
