### ISSUE TITLE
weird notice after upgrade from 3.5 to 3.7

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5379]
```
\nNotice: ps_files_cleanup_dir: opendir(/var/lib/hhvm/sessions) failed: Permission denied (13)
```

additional info:

website files are owned by `ftpuser`. `ftpuser` is a member of group `www-data`

**Comment by paulbiss** [comment]
I'm guessing `ftpuser` is running hhvm? Can they write to `/var/lib/hhvm/sessions`? Do you have some example code to repro this? Generally saying something stopped working between versions of hhvm isn't enough for us to go on.

**Comment by steelbrain** [comment]
You might want to run this everytime you upgrade your HHVM
```
chown -R ftpuser.ftpuser /var/log/hhvm
chown -R ftpuser.ftpuser /var/run/hhvm
chown -R ftpuser.ftpuser /var/lib/hhvm
```

**Comment by r3wt** [comment]
@paulbiss hhvm runs under `www-data`. `ftpuser` is just a convenience login. so `ftpuser` owns scripts in the public directory.

**Comment by paulbiss** [comment]
I'm confused. Can the user running hhvm write to: `/var/lib/hhvm/sessions`?

**Comment by r3wt** [comment]
@paulbiss i went and chown -r that dir and the problem subsided

**Comment by RalphCorderoy** [comment]
@paulbiss, I think chown is just hiding the problem here, and probably opening a security hole.

Here's that directory on Ubuntu 14.10 after installing the packages from http://dl.hhvm.com/ubuntu.

    $ ls -ld /var/lib/hhvm/sessions
    drwx-wx-wt 2 root root 4096 Jun 12 15:40 /var/lib/hhvm/sessions

The website's backend runs as www-data and so has no problem writing to the directory to create new sessions, and searching the directory for a session with a known name thanks to execute permission.  What it can't do, by design, is list all the sessions in the directory.  Thus the only way to access a session of unknown name is to guess it, unless you're root with his read permission.  chown removes that protection.

PHP's session_start() will occasionally try and garbage collect old sessions by scanning the directory for old files.  It doesn't have permission and burps the 'ps_files_cleanup_dir' error seen above.  AIUI, the normal Debian/Ubuntu method for PHP is to set `session.gc_probability = 0` by default in an ini file and have a cron job that runs as root to do the clean.  HHVM needs to adopt this method AFAICS.

**Comment by mattyglover** [comment]
so what is the right way to deal with this issue?
