### ISSUE TITLE
Documentation of minimum versions of HHVM build requirements 

### ISSUE THREAD

**Issue by samveen** [facebook/hhvm#5403]
There is very little documentation about what are the minimum versions of the dependencies required to build HHVM. 

It would be great if  REQUIREMENTS document can be added that contains the minumum required version of all dependencies. For example:
```Boost  >= 1.50.0```
and so on.

I can get some of the information from [CMake/*](https://github.com/facebook/hhvm/tree/master/CMake) but this information is fragmented and incomplete, and sometimes downright confusing. For example in [CMake/HPHPFindLibs.cmake](https://github.com/facebook/hhvm/blob/master/CMake/HPHPFindLibs.cmake#L30#L34), lines 30-34:
```
# boost checks
find_package(Boost 1.51.0 COMPONENTS system program_options filesystem context REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})
link_directories(${Boost_LIBRARY_DIRS})
add_definitions("-DHAVE_BOOST1_49")
```
Is the boost requirement for version 1.49, or for version 1.51? 

This leads to lots of unnecessary headache for builders and downstream packagers. An explicit statement of the requirements will help with these issues a lot.

My exact problem: I need to find exact version requirement for ImageMagick/libmagicwand (is it >= 6.6.0?)

**Comment by jwatzman** [comment]
We depend on so many things, and the versions change so frequently, I'd be afraid any such file like this would bit rot. The CMake files at least have to be kept vaguely up to date, or the build won't work. Is there you can't get from running `cmake` until it's happy with everything? Our [Debian control files](https://github.com/hhvm/packaging/tree/master/hhvm/deb) also contain the sort of dependency information that you would need for packaging.

For Boost specifically, it's 1.51. The fact that we define `HAVE_BOOST1_49` just an implementation detail that has to do with some quirk of FB's internal build system. (It's certainly weird though.)

**Comment by samveen** [comment]
@jwatzman , Josh, First thing I did was to take a look at [the control file for trusty](https://github.com/hhvm/packaging/blob/master/hhvm/deb/trusty/DEBIAN/control) before I opened this issue(`trusty` being the oldest of all the distribution versions listed in the packaging repo). I didn't see any version information there, which led me to opening this ticket.

However, taking your response into consideration, is it valid to claim that `The minimum required versions of all dependencies are those versions that are part of Ubuntu Trusty`? If so, even this statement in a `REQUIREMENTS` document should be good enough, but it is required.

**Comment by jwatzman** [comment]
That's... not quite right either. I happen to know that there are some libs that you can get away with older stuff than in trusty -- it has boost 1.54, for example, but 1.51 is new enough. Not sure about much else, boost is just the one that tends to give us trouble so I know exact versions :)

Basically our minimum version requirements are whatever the cmake stuff accepts. We don't have in our heads the various features of different versions of libraries -- so we don't know when we use something from an older/newer version, or a PR requires something, etc etc, until either our CI system yells at us, or someone else does, and we either fix the code or tweak our cmake files. This means that the cmake stuff is reasonably up to date -- because if it isn't, our CI will fail and/or people will yell at us when the build fails. But any list we write up is inevitably going to fall out of date.

I'm curious why you're running into this -- it hasn't been a problem for any packaging up until now.

**Comment by samveen** [comment]
I'm working on preparing hhvm RPMs for our production environment testing (where we plan to migrate 5% of our machines to hhvm instead of the RH bundled php on Centos 6.6. As we're running multiple things on the machines(including some stuff with dependencies that cannot be upgraded), I am forced to build packages of HHVM-3.6 branch for Centos 6.6, such that dependency updates do not destroy our infrastucture when using `yum install/update`. However, as you already know, walking on coals is easier. 

If I had the minimum required versions of everything, this process would be a whole lot easier as I could test our existing systems to check what would break, and thus find workarounds quicker.
