### ISSUE TITLE
Items in DOMNodelist not of registerNodeClass'd type

### ISSUE THREAD

**Issue by theseer** [facebook/hhvm#5412]
Using HHVM 3.7.0 the DOMNodelist returned by an XPath query does not honor the replacement of DOMElements via registerNodeClass.

```php
class SampleElement extends \DOMElement {}

$dom = new DOMDocument();
$dom->registerNodeClass('DOMElement', 'SampleElement');
$dom->loadXML('<?xml version="1.0" ?><root />');

$xp = new DOMXPath($dom);
$list = $xp->query('/root');

var_dump(get_class($list->item(0)));
```

***Running it against php***
PHP 5.6.9 (cli) (built: May 15 2015 10:04:17) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

string(13) "SampleElement"

***Running it against hhvm***
HipHop VM 3.7.0 (rel)
Compiler: 1432365749_210873458
Repo schema: de2ad6572c3e61a7c559656fe50ddb42d096626d

string(10) "DOMElement"

**Comment by theseer** [comment]
Quick update to the sample code, now without XPath:

```php
<?php

class SampleElement extends \DOMElement {}

$dom = new DOMDocument();
$dom->registerNodeClass('DOMElement', 'SampleElement');
$dom->loadXML('<?xml version="1.0" ?><root />');

$list = $dom->childNodes;

var_dump(get_class($list->item(0)));
```

**Comment by paulbiss** [comment]
Okay, looks like I broke this when I changed the libxml memory model. I think we're failing to copy over the classmap (and other associated data) to the new domdoc when we loadXML() (and loadHTML()). Should be a pretty easy fix if someone wants to send a PR (otherwise I'll try to get to it soon).

[dom_parse_document](https://github.com/facebook/hhvm/blob/d1f2b9bc2453d8c0d3b4246107e0de5e72fcfb6d/hphp/runtime/ext/domdocument/ext_domdocument.cpp#L817)
[dom_load_html](https://github.com/facebook/hhvm/blob/d1f2b9bc2453d8c0d3b4246107e0de5e72fcfb6d/hphp/runtime/ext/domdocument/ext_domdocument.cpp#L851)

**Comment by theseer** [comment]
That means a potential workaround would be to simply re-register the nodeclass replacements after loading until this is fixed.

**Comment by paulbiss** [comment]
Yeah, that still works. We should really fix this though. http://3v4l.org/ITRfI
