### ISSUE TITLE
SlowTimer at curl

### ISSUE THREAD

**Issue by motiejuss** [facebook/hhvm#5492]
Hi. I'm getting this issue:

```
SlowTimer [60001ms] at curl: http://domain.com/image.jpg
```

Couldn't find any resource on this.

**Comment by paulbiss** [comment]
Looks like the curl request is timing out after 60 seconds. You could check to see that the url you're curling is valid.

**Comment by motiejuss** [comment]
URL was valid. Accidentally found out that DNS settings for the server were wrong. Although `curl_getinfo` didn't return any useful info and `CURLINFO_HTTP_CODE` was always `0`.

**Comment by sachinbanugariya** [comment]
SlowTimer [2197ms] at curl: http://domain.com/image.jpg
i get this error with hhvm, if i restart hhvm error is not came for some time then again it seems same and hhvm takes much load in top command 118.8 CPU and more then this also.

the thing is before that its working fine and because of this site also taking load and some time gives nginx error,

can anyone have solution as because also RAM is free sometime more that 500MB still getting error.

i also get one solution from internet to increase hhvm timeout but then also get error after that time,

and if i fire manually that api from backend from that serer itself then it gives proper result,
and also working if fire from browser but from my website it gives some time curl time out error.
