### ISSUE TITLE
Language Extension

### ISSUE THREAD

**Issue by infusion** [facebook/hhvm#5518]
Hi,

I wonder if the following language features could be added to hack. Changing the behavior of PHP doesn't make too much sense I think.
- negative string offsets: $str[-1] // gives last character
- foreach over strings: if a string gets iterated with foreach, it result in a character-wise processing
- logical xor operator like ^^

And a question about optimization: Does HHVM optimize `strlen('constant')` to a constant number as well? This could help to improve cases like `for ($i = 0; $i < strlen("foo"); $i++)`.

Thanks

**Comment by Orvid** [comment]
While supporting negative string offsets might seem like a good idea at first, it would likely hide many other errors.
When doing a foreach over a string, are you suggesting iterating over codepoints, bytes, or code units?

**Comment by infusion** [comment]
Shouldn't it be the user who checks for valid input ranges? `substr()` works the same and if people know about that they can use it for themselves. I know that it could be more error prone but it gives a really neat feature on the other hand.

Iterating over strings with `foreach` should result in a character-wise dissection, as every native function in PHP works on a per-byte basis.

**Comment by paulbiss** [comment]
I'm inclined to agree with @Orvid on negative offsets, though there are languages that support this already (e.g. python), so it's not out of the question. I think changing arraying indexing in hack mode is something we'd want to be very careful about though.

**Comment by lexidor** [comment]
Sorry for the ghost post.
`strlen()` is currently not marked with a `__IsFoldable` attribute. So the string length will still be read at runtime.

**Comment by lexidor** [comment]
I am going over older issues, and closing those which are not likely to be worked on.

 - negative string offsets: $str[-1] // gives last character
The `idx()` function used to do this, but this behavior was removed at some point. This can be done with `$str[\strlen($str) - 1]`, which isn't pretty, but it performs well, or `Str\slice()`(with the benefit that you can also select ranges) in cases where legibility is more important.

 - foreach over strings: if a string gets iterated with foreach, it result in a character-wise processing
This would require strings to implement the `Traversable<string>` interface. In order to stay consitent with the rest of the language, it would most likely be byte-wise. In this UTF-8 world, the best solution is to write a custom Iterator.

 - logical xor operator like ^^
This is `$a !== $b`, casting to bool if needed.

**Comment by lexidor** [comment]
If negative indexing is something we'd want to (re)introduce, opening a new issue could spark a fresh discussion.
