### ISSUE TITLE
Don't understand type checker

### ISSUE THREAD

**Issue by xvw** [facebook/hhvm#5544]
I'm really sorry but why this code is well compiled ("No Errors" from hh_clients)? 

```php
<?hh 

function f (int $x) : int {
  return $x * 2;
}
echo f('AAAA');
```

Thanks a lot !

**Comment by danslo** [comment]
Toplevel statements aren't typechecked. Throw it in a function and you'll get the result you want.

```php
<?hh 

function f (int $x) : int {
  return $x * 2;
}

function g() {
  echo f('AAAA');
}
```

**Comment by xvw** [comment]
yeah thanks a lot. Is there a particular reason (for not typecheck the toplevel?)

**Comment by danslo** [comment]
I'm not sure if there is a technical reason (there might be, someone from FB could clarify here), but toplevel statements are banned in strict mode anyway (try with ``<?hh // strict``).

**Comment by fredemmott** [comment]
The main reason is because 'locals' in pseudomains aren't really locals - they can be modified from anywhere via the 'global' keyword for example. Given we allow a mix of PHP and Hack code in the same project, this means we can't really make any guarantees about safety.

While we could theoretically detect some cases (eg when parameters are literals), we're not sure of the benefits outway the costs - eg it seems more likely to lead to people assuming that the typechecker will catch problems that it doesn't.
