### ISSUE TITLE
Why isn't Hack's strict mode more strict?

### ISSUE THREAD

**Issue by olleharstedt** [facebook/hhvm#5607]
Asked this on stackoverflow but got shut down, of course.

There's a lot of quirks that could have been forbidden using Hack's strict mode. To name a few:

* Why still allow the == operator?
* Why not warn when functions that return values aren't stored in a variable at call?
* Still allow negation of non-booleans, like !"0"?
* Why allow other values than bool in if-statements?

In one word, why isn't strict mode more strict?

**Comment by Orvid** [comment]
To pull in the arguments made on the IRC, a brief log of the conversation. The log has been edited to remove DC's, make it readable on Github (I may backtick quote code, but not everyone does), and remove an unrelated message near the end.

First, for a point of reference, not all of the points presented in this issue are the same as was responded to on the IRC. The exact set of points that this conversation was in response to is as follows:
1. Why still allow the `==` operator?
2. Why not warn when functions that return values aren't stored in a variable at call?
3. Why still allow magic quotes like `"bla bla $foo"`?
4. Mix int and float like in `$a = 10 + 1.2`.

Now the actual log:
**ollehar**: why isn't hack strict mode more strict? http://stackoverflow.com/questions/31281740/why-isnt-hacks-strict-mode-more-strict
**aatch**: ollehar, because where do you cut off? Some of those would be actually be kinda annoying.
**Orvid**: All of those things are things that even strongly typed languages support.
**aatch**: ollehar, Like the second point. You might be calling the function for some side effect and not care about the return value.
**ollehar**: aatch: then you should explicitly ignore the result.
**aatch**: ollehar, and that'd be really annoying.
**Orvid**: The magic quotes is a bit of a different issue, but otherwise all of those are present in other strongly typed langauges, via implicit conversion.
**ollehar**: compare ocaml, they do it.
**simon_w|air**: ollehar, but then you've got an unused variable
**aatch**: ollehar, seriously, even Rust doesn't force it.
**Orvid**: D will actually warn you if you don't use the return value of a strongly pure function, one which has been determined to have no side effects
**ollehar**: (I was thinking cast to void, like `(void) foo()` )
**aatch**: ollehar, the `==` is a different operator to `===`, `$a == $b` might be true when `$a === $b` isn't.
**ollehar**: aatch: yeah, that's why `==` should go...
**ollehar**: no?
**aatch**: ollehar, no.
**simon_w|air**: No
**ollehar**: when is it useful?
**aatch**: ollehar, because they're different operators.
**Orvid**: In the PHP context I can see reason for `==` to potentialy go, but that would need a nice clean generic conversion API to be viable.
**aatch**: ollehar, `"blah blah $foo"` isn't "magic quotes", it's string interpolation, and Hack does restrict it.
**simon_w|air**: ollehar, `Vector {1, 2} == Vector {1, 2}` but Vector `{1, 2} !== Vector {1, 2}`
**Orvid**: `===` is instance comparison isn't it?
**simon_w|air**: On objects, yeah
**ollehar**: simon_w|air: vector = array?
**Orvid**: C# handles that by having that meaning when explicitly compared with `Object.Equals(a, b)`
**simon_w|air**: ollehar, no, arrays are different
**ollehar**: Orvid: mm, that's what I thought.
**aatch**: ollehar, as for float/int implicit conversion, I personally agree with it not existing, but it's very subjective.
**simon_w|air**: aatch, can you imagine having to write `10.0` all the time? :p
**Orvid**: For value types, `===` is a deep comparison between the two, but for reference types it compares the references themselves...
**aatch**: simon_w|air, yes, yes I can. Since I have.
**aatch**: simon_w|air, and yes, it is annoying.
**simon_w|air**: (Most annoying conversion is int/int == float)
**Orvid**: `int/int = int; int/float = float; float/float = float;` is roughly how C# handles it
**aatch**: simon_w|air, agreed, fortunately it's rare that truncating the result causes errors since you're normally within reasonable accuracy for floats.
**aatch**: Orvid, yeah, that's fairly common. The middle case is the one that tends to vary.
**simon_w|air**: aatch, at least Hack doesn't auto-promote to float past INT_MAX
**Kazanir**: heh
**fredemmott**: simon_w|air: we do now recognize `$_` for unused variables (eg `list($a, $b, $_) = HH\Asio\va(awaitFoo(), awaitBar(), awaitBaz())`)
**simon_w|air**: fredemmott, yeah, but that seems like a waste when you can just ignore the return value entirely
**aatch**: Rust has an annotation for types `#[must_use]` to indicate that the return type *should* be used. Generally just for pointing out when you've forgotten to do error handling somewhere.
**aatch**: And Hack does warn you when you don't do anything with an `Awaitable`.

**Comment by jwatzman** [comment]
Yeah, basically, these things don't break the type system, and can be used usefully with only a little bit of care. (I personally actually hate `==` less than most folks.) If we were designing a language from scratch, we'd probably omit most (all?) of them, but we're not, and the restrictiveness of banning them now was considered to outweigh the benefits.

This isn't really a bug report, and I don't think it's useful to keep open, so going to close it. If you have a more specific question, feel free to ask, and we can give the best answer we can, though since we didn't do any sort of ultra-formal design process here, I'm not sure how satisfying the answers will be, beyond just "we thought this was the right tradeoff".
