### ISSUE TITLE
Add mechanism for hh_format to ignore certain directories, or ignore vendor/

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#5611]
Composer installs third-party libraries to vendor/, and as well as conceptual issues, now complains if there are local changes to any libraries. This makes hh_format unusable for projects using composer (which is the majority of modern open-source PHP projects).

**Comment by jwatzman** [comment]
@int3 how does `hh_format` work right now -- does it do the same "everything under the `.hhconfig`" that `hh_server` does? If so, we might want to solve this in some more generic way than an exclusion list specific to `hh_format`. Hack projects in general right now have problems like this all over the place with imported composer libraries; thinking it through properly (an exclusion list is maybe not the right solution at all?) is something I want to look at in Q3/Q4.

**Comment by int3** [comment]
When you pass `hh_format` a directory as an argument, it simply formats all the files in it recursively. It doesn't care to look for .hhconfig, except in `--diff` mode, when it tries to use that file's location to determine the root of all the paths in the diff. (Arguably, it would make more sense to look for .git/.hg... but that's a separate issue).

Unlike hh_server, though, there is no "shared state" in hh_format, so one could just as well do `find . | xargs -P 0 -n 1 hh_format` and achieve the same result and performance as `hh_format .`. Since `find` can be passed arguments to ignore certain directories, I'm not sure this issue is that important to fix. But if you have some sort of general directory traversal and exclusion library then we could certainly use that.

**Comment by fredemmott** [comment]
hh_format is dead
