### ISSUE TITLE
PHP 7 doesn't allow empty list()

### ISSUE THREAD

**Issue by jazzdan** [facebook/hhvm#5758]
See here: http://3v4l.org/pom2r

Looks like this doesn't exactly work in PHP 5 either, so it's interesting that HHVM allows it.

**Comment by jazzdan** [comment]
Furthermore this [violates the spec](https://github.com/php/php-langspec/blob/master/spec/10-expressions.md#list)

**Comment by lexidor** [comment]
@Wilfred This could very easily be turned into a typechecker error.
The runtime does not care about having more elements in your tuple than variables in your list.
```HACK
$one = tuple(1);
list() = $one; // This is fine to the runtime, but not fine for the typechecker.
$two = tuple(1, 2);
list($_1) = $two; // Again, fine to the runtime, but not for the typechecker.
list($_1, $_2) = $two; // Fine for both.
```

The only way to make an empty list intrinsic typecheck is by assigning a `vec`-like type.
However, this is a noop, since no elements will be accessed.

**Comment by Wilfred** [comment]
@lexidor this is already banned by the typechecker?

```
function foo(): void {
  $one = tuple(1);
  list() = $one;
  $two = tuple(1, 2);
  list($_1) = $two;
  list($_1, $_2) = $two;
}
```

Produces:

```
$ hh
Typing[4105] Invalid assignment
   --> x.php
  5 |   $one = tuple(1);
    |          ^^^^^^^^ Definition is here
  6 |   list() =
    |   ^^^^^^^^
    |   ^^^^^^ Too many arguments (expected 0 but got 1)

Typing[4105] Invalid assignment
   --> x.php
  8 |   $two = tuple(1, 2);
    |          ^^^^^^^^^^^ Definition is here
  9 |   list($_1) = $two; // Again, fine to the runtime, but not for the typechecker.
    |   ^^^^^^^^^^^^^^^^
    |   ^^^^^^^^^ Too many arguments (expected 1 but got 2)
```

**Comment by lexidor** [comment]
> The only way to make an empty list intrinsic typecheck is by assigning a vec-like type.
However, this is a noop, since no elements will be accessed.

`list() = $vec;` is valid Hack code and a noop at runtime.

We would match the spec if we issued an error for this.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I have come around on the usefulness of emitting an error here. Yes, `list() = ...;` is a "useless" noop. Allowing it does not cause harm, since hhvm can't run PHP code at all anymore. Special casing `list()` with zero bound variables would not do Hack a favor. Closing the issue, since Hack does not follow the PHP spec.
