### ISSUE TITLE
Any plans for LLVM back-end for Hack?

### ISSUE THREAD

**Issue by olleharstedt** [facebook/hhvm#5811]
Hi! This is more of a question: Does the team have any plans on implementing an LLVM back-end for Hack, to compile PHP/Hack to binary code?

**Comment by olleharstedt** [comment]
Already info here: http://hhvm.com/blog/3743/hhvm-the-next-six-months

**Comment by jwatzman** [comment]
HHVM is going to remain a JIT -- we're not going to produce standalone binaries for PHP or Hack. (The ancient HPHPc did that, and it turns out a JIT can optimize better.)

There are continuing experiments in using LLVM as part of the JITting process -- basically, after we go through our bytecode and IR, instead of emitting x64 assembly, we emit LLVM bitcode, which LLVM can then optimize and generate x64. LLVM is pretty slow, so we'd only do this for the hottest of hot code.

The experiments are ongoing, @edwinsmith can comment if he wants; last I heard, they had gotten the LLVM pipeline to performance parity with the existing one, and were working on making it actually generate *faster* code :)

But again, this is all internal performance work; there won't be any user-visible implications of this other than faster code.

**Comment by olleharstedt** [comment]
Thanks for your answer! It's interesting that a JIT gives better performance result than a conventional compiler - I better google some more about that. :) Have a good one!

**Comment by jwatzman** [comment]
The benefit is all in type information -- since you're compiling the code just-in-time, you know what the types of everything are, since you have everything right there. Being able to type-specialize the code so well turns out to be a big deal -- you can do this easily with a statically typed language like C, but for PHP (or Python or Ruby etc etc), having a JIT is a huge win due to this.

**Comment by Orvid** [comment]
It is technically possible for an AOT compile  process, used in the context of repo-authoritative,  and not generating PIC code, and generating for a specific arch, such as the known configuration of a production server, to produce faster code, primarily because time becomes far less of a factor in what optimizations can be done. HHBBC does this to some extent I believe, but it operates at the bytecode level, and doesn't AOT compile code.

**Comment by Orvid** [comment]
IIRC HHVM actually does, up to a point, generate PIC code currently, but I believe that is only for the purpose of re-ordering hot functions close together in memory.

**Comment by paulbiss** [comment]
@Orvid we actually emit highly optimized translations for hot code paths based on PGO data collected using profiling translations. These take longer to compile and use type information and branch profiling collected at runtime. In theory an AOT compiler could do the same PGO but it would require multiple deployments and would be unable to adapt to changing execution paths without a further profile-restart cycle.

HHBBC does do some of this analysis ahead of time for any time information that can be inferred before collecting profile data. HPHPc (the previous incarnation of this project) transpiled PHP to C++ and used gcc to generate highly optimized binaries. We found it to be quite efficient, but have discovered that the ceiling on performance for a language as dynamic as PHP is much higher with a JIT than an AOT compiler. Additionally, we've been able to support an array of language features that were basically impossible under an AOT model bringing HHVM much closer to PHP 5 than HPHPc ever got.

**Comment by Orvid** [comment]
How stable is HHBBC? What are the requirements for the code to actually run it on? How much of a difference does it make in performance? There isn't any documentation on it on the Wiki.

**Comment by paulbiss** [comment]
It runs facebook and has worked with most of the open source code I've tested it with, so I think it's pretty stable. As it's repo-mode it only supports a subset of PHP, in particular it doesn't support eval, and a handful of the more dynamic PHP features. As for performance it depends on a lot on the code-base, the power of HHBBC is going to depend a lot on how much it can infer from context, which in turn is going to depend on how cleanly and clearly the code is written. We should document it better.

**Comment by jwatzman** [comment]
> We should document it better.

We should, but OTOH, most people don't need to know about it, since it automatically runs when building a repo. If you're using repo-auth, you almost certainly built your repo with HHBBC unless you did something very weird and undocumented.

**Comment by paulbiss** [comment]
Yeah, it would be nice to add some notes to the docs directory though https://github.com/facebook/hhvm/tree/master/hphp/doc/hackers-guide

**Comment by olleharstedt** [comment]
In Hack strict mode, don't you have all the type information needed to make it as fast as, say, Java? In theory.

**Comment by Orvid** [comment]
Java doesn't have complete type information, because you can load more things at runtime. In some ways, you do have more type information in hack strict mode, assuming you're also in rope-authoritative mode, as you know every piece of code that it's possible to execute. That assumes however that the core PHP functions are strictly declared, and, for the most part, they aren't.

**Comment by jwatzman** [comment]
You also don't necessarily have info about any partial mode functions you call, and there's always UNSAFE. The entire type system of Hack is built up such that if information is missing we go "I guess you know what you're doing" and admit it. In HHVM, you can't do this, since if you're wrong you'll segfault, which is why HHBBC has its own much more conservative inference engine (which uses the Hack type annotations when it can).

**Comment by paulbiss** [comment]
Aha, I thought there was an overview of how it worked somewhere: https://github.com/facebook/hhvm/blob/master/hphp/hhbbc/README

**Comment by DemiMarie** [comment]
@jwatzman would it be possible to have an "all strict mode" in which only `// strict` functions are allowed?
