### ISSUE TITLE
weird errors when starting hhvm after changing username

### ISSUE THREAD

**Issue by r3wt** [facebook/hhvm#5859]
if i start hhvm with sudo, no unix socket(hhvm.sock) is created and hhvm groans that it can't load the schema and database:

`Failed to initialize central HHBC repository:\n  Failed to initialize schema in /var/run/hhvm/hhvm.hhbc: \n  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file\n`

if i start hhvm without sudo, the unix socket (hhvm.sock) is created but i get this message:

`cap_set_proc failed`

with this message in console:

`chown: changing ownership of '/var/run/hhvm/pid': Operation not permitted`

**Comment by jwatzman** [comment]
>  Failed to open /var/www/.hhvm.hhbc: 14 - unable to open database file

HHVM will change users down to whatever is set on the command line with `--user` or similar (there may be an INI option, and the Debian `init.d` scripts do set `--user`). Did you set it to a user that can't read/write to that directory? Try removing the file, or making sure `/var/www` exists.

> chown: changing ownership of '/var/run/hhvm/pid': Operation not permitted

This one seems pretty self explanatory to me, we're trying to `chown` that directory to the user that you're running HHVM as, and can't (probably because typically only root can `chown`). Does the right user own that file? Try just removing it and making sure the user you're running as can write to `/var/run/hhvm`.

For both of these, there are options to change these directories if you want -- I think `hhvm.repo.central.path` and `pid` are the options respectively (cf. https://github.com/hhvm/packaging/blob/master/hhvm/deb/skeleton/etc/hhvm/server.ini).

**Comment by r3wt** [comment]
@jwatzman You were right. i went into the init script and due to running with nginx its starting with `adm www-data` instead of the file owners. thanks for the lesson. closing.
