### ISSUE TITLE
Make SQL injection impossible by tagging strings as "dirty"

### ISSUE THREAD

**Issue by olleharstedt** [facebook/hhvm#5879]
Would it be possible to once and for all get rid of SQL injection by tagging strings that are built up out of concatenation as "dirty"? Dirty strings cannot be used in query functions. So

    $q = "SELECT bla FROM bla";
    $result = mysql_query($q);

would work, but

    $q = "SELECT bla FROM " . $a;
    $result = mysql_query($q);

would not.

Strings that are concatenated with itself should not be marked as dirty, so you can build up a query dynamically using if-statements and `$q .= "WHERE bla = bla"`.

**Comment by Orvid** [comment]
The problem is one of how do we analyze this? I can see many use cases where `$a` is known to already be escaped in the core function, meaning that it is perfectly safe to allow this. I think this would break too many use cases to be practical. If you really want to though, it might be reasonable as a config option that defaults to being off.

If this were to exist, I believe a better way to achieve what you were wanting with the exception there is to allow concats of strings going into queries only if both sides ultimately originated from a string literal with no interpolation.

**Comment by paulbiss** [comment]
In hack we have the notion of a FormatString<>, which must be created from a string literal, and is always checked for correctness based on a generic parameter indicating the use for the string. Generally I think the problem with marking strings as clean and then allowing them to be manipulated is that you can still generate garbage or unsafe strings from concatenations of safe strings.

For SQL I'd use either prepared statements or [queryf](http://docs.hhvm.com/manual/en/hack.async.mysql.asyncmysqlconnection.queryf.php) (note that the documenation is incorrect, queryf takes a FormatString).

**Comment by DerPapst** [comment]
There is a pretty old [RFC](https://wiki.php.net/rfc/taint) about "Taint support for PHP" in the PHP wiki but it is inactive. However it has been implemented as a [pecl extension](http://pecl.php.net/package/taint). 
Maybe you can try to compile that as hhvm extension using [ext_zend_compat](https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext_zend_compat).

**Comment by olleharstedt** [comment]
@DerPapst Good tip, I'll look into that!

**Comment by jwatzman** [comment]
You might also want to look into using [Hack's opaque type aliases](http://docs.hhvm.com/manual/en/hack.typealiasing.php) to track taint with the type system.
