### ISSUE TITLE
Dot instead of arrow (->) for class elements

### ISSUE THREAD

**Issue by jeyemwey** [facebook/hhvm#5909]
Hej guys,

I would love to use the dot-operator instead of the arrow (`->`) when working with **classes**, like you can see in almost every language but PHP/HHVM.. For concatenating strings, you could use the `&` char like in [ASP](http://www.tizag.com/aspTutorial/aspString.php) alternatively..

I know that this thing won't be realized ever, but after working in PHP with this annoying arrow so many years, I think it's time to change something.

Best regards,
- Jannik.

**Comment by paulbiss** [comment]
Well, C and C++ both use `->` in addition to `.`, and I'm sure there are other languages. In this case though we can't use a `.` for member access without changing the concatenation operation (as it would otherwise be ambiguous), and using `&` would require that we find an alternative for bitwise-and. I'd argue using `->` for member access is superior to not being able to use `&` for bitwise operations.

Anyway, all other points aside we're not interest in introducing such a massive BC break.
