### ISSUE TITLE
Foreach behavior

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6045]
https://wiki.php.net/rfc/php7_foreach

We already didn't match PHP5. Some of the ways we didn't match PHP5 do match PHP7, others don't. Most (all?) of this is so edge-case that it might not be worth it, a lot of this stuff has very deep perf implications for HHVM, so much so that we just can't take the massive perf hit to match stupid edge cases.

We should see where we actually differ, how hard it would be to change, and then document the rest as deliberate inconsistencies.

**Comment by jwatzman** [comment]
Basically, I expect most of the work here to be just carefully reading the RFC and testing HHVM's behavior, and then documenting where and why we differ.

**Comment by nikic** [comment]
By-value foreach over arrays in HHVM already matches the PHP 7 behavior (rather than PHP 5).

For by-reference iteration one significant difference is that PHP 7 will never modify the internal array pointer:

```php
$a = [1,2,3];
foreach($a as &$v) {
    echo $v . " - " . current($a) . "\n";
}
// PHP 7
1 - 1
2 - 1
3 - 1
// PHP 5 + HHVM
1 - 2
2 - 3
4 -
```

If I remember your implementation correctly, doing this shouldn't be problematic for you.

**Comment by jwatzman** [comment]
Ah, thanks for the info @nikic! For the foreach-by-reference, then, we'll need it to be gated by the PHP5 vs PHP7 option.

**Comment by jwatzman** [comment]
@paulbiss suggests we should just make the change, so we just match PHP7 across the board, without any config option. (Since we don't match PHP5 anyways.) My only concern is FB's internal code which might rely on it, though we can prob just fix that. (Not worried about external code since we already don't match on this edge case.)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The non-reference behavior was already correct at the time that this issue was created.
HHVM removed [`&$references`](https://hhvm.com/blog/2019/10/01/deprecating-references.html) from the runtime.
