### ISSUE TITLE
Some GMP functions are missing in v3.9 Ubuntu 14.04 package

### ISSUE THREAD

**Issue by amirlivneh** [facebook/hhvm#6065]
gmp_pow() for example is not defined. It is defined in the v3.6 package.

**Comment by rubensayshi** [comment]
Having same issue, missing `gmp_strval`, seems like something went wrong big time with this ...

@MaideCa I hope you don't mind me pinging you but I recalled you did some stuff for GMP issues before, maybe you can easily spot what went wrong because I can't seem to figure it out by digging through commit history

**Comment by paulbiss** [comment]
Hmm it doesn't look like either of these functions are conditionally defined. Maybe the extension failed to build entirely, are any of the gmp functions present?

**Comment by fredemmott** [comment]
```
=extension_loaded('gmp')
false
```

**Comment by fredemmott** [comment]
Also no gmp functions at all in get_defined_functions()

**Comment by fredemmott** [comment]
Closing.
