### ISSUE TITLE
'use function' not understood by typechecker

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6081]
```Hack
<?hh

use function Foo\Bar\my_function;
```

```
test.php:3:14,32: Expected Namespace use list (Parsing[1002])
```

**Comment by fredemmott** [comment]
this would be really nice for using HH\Asio

**Comment by jwatzman** [comment]
I bet we don't support `use const` either -- I think the way the typechecker does namespaces unfortunately might not be super amenable to this right now. I'll take a look later if I get time.

**Comment by jwatzman** [comment]
Taking a crack at this.

**Comment by fredemmott** [comment]
:D AWESOME

cc @JoelMarcey  - what version are we targetting with the docs site now? If it's 3.11, we should include htis (And group use) in the Asio utiltites exampes.

**Comment by jwatzman** [comment]
I haven't done group use yet in the typechecker, and may not get around to it. (The diffs for group use in HHVM are up internally if anyone wants tor review them :))

**Comment by JoelMarcey** [comment]
@fredemmott I did verify that something like `use HH\Asio\v` does work, but it would be somewhat of a forced thing to use them in the examples because we only call each function once in those examples, so it would actually be more typed characters. For future examples, if we use the functions a bunch in a particular example, then `use` would be useful.
