### ISSUE TITLE
Official Dockerhub repo?

### ISSUE THREAD

**Issue by ihsw** [facebook/hhvm#6126]
There's one for PHP -- why isn't there one for HHVM?

https://hub.docker.com/_/php/

**Comment by fredemmott** [comment]
There hasn't been one because there hasn't been sufficient demand in the past.

We're planning on turning https://hub.docker.com/r/fredemmott/hhvm-proxygen into an official package (with https://hub.docker.com/r/fredemmott/hhvm/ as a base package for people to build on who do not wish to use proxygen). If you have feedback on those, please file issues at https://github.com/fredemmott/hhvm-docker/issues

Closing as anything further either belongs there, or on https://github.com/hhvm/packaging/issues
