### ISSUE TITLE
error: use of deleted function 'HPHP::Variant::Variant

### ISSUE THREAD

**Issue by no1youknowz** [facebook/hhvm#6133]
I have an extension that uses Variant.

For example: Variant php_zmq_context_create(int io_threads)

    Line: https://github.com/no1youknowz/hhvm-zeromq-ext/blob/master/zmq/ext_zmq.cpp#L132

What should variant be changed to?

Here is the error message:

    /root/rpmbuild/BUILD/hhvm-ext-zeromq-1.0/hhvm-ext-zeromq/zmq/ext_zmq.cpp: In function 'HPHP::Variant HPHP::php_zmq_context_create(int)':
    /root/rpmbuild/BUILD/hhvm-ext-zeromq-1.0/hhvm-ext-zeromq/zmq/ext_zmq.cpp:135:53: error: use of deleted function 'HPHP::Variant::Variant(const void*)'
         return newres<ZmqContextResource>(io_threads);

Thanks

**Comment by fredemmott** [comment]
`Variant` is not deleted - `Variant::Variant(void*)` is deleted because G++ automatically used it in inappropriate situations - for example, you either want to make a variant of a bool or a variant of a resource in this situation. Before this function was deleted, what you think is a variant containing a resource would actually be a variant containing bool(true).

You want to use one of the other constructors defined in type-variant.h

newres also doesn't exist any more. If you're building against a recent version, you want HPHP::req::make<T>() instead
