### ISSUE TITLE
3.10-dev trunk from 8/21 suddenly forgot date.timezone

### ISSUE THREAD

**Issue by ck-on** [facebook/hhvm#6145]
I had a machine running the trunk from 8/21 and someone reported the timezone had reverted to UTC (was America/New_York set in ini)

Checked and this was global, not just one session or one cached piece of code.

Restarted HHVM and timezone magically fixed itself.

Not sure if this helps:

HHVM Version    3.10.0-dev
HHVM compiler id    heads/master-0-g953ca9d7ccc767c5fb83ee4578e2d​e004e4b989b

No idea how to reproduce but will keep an eye on that machine.

**Comment by ck-on** [comment]
Yup, it keeps happening.  Minutes after HHVM is restarted it reverts to UTC - but initially for a minute or two, it is okay.

I am not aware of anything in PHP that can change the master value, only the session value (ie. ini_set)

**Comment by MartinAmps** [comment]
We're hitting this issue too,

# hhvm --version
HipHop VM 3.8.0-dev (rel)
Compiler: heads/master-0-g2463825071ec41d91400238244b5ed82a30f02b4
Repo schema: 7f6a154592bc9f65a969e7c2ecf8f8cc10961924

HHVM invoked by:
 hhvm --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini --user www-data --mode server -vPidFile=/var/run/hhvm/pid_9010 -p 9010 -d hhvm.admin_server.port=9011

# cat /etc/hhvm/php.ini  | grep 'date'
date.timezone = America/Los_Angeles

(I tried php.ini, hhvm.ini, and both.. just because)

Logs:
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 4
Finished singleJitRequest 5
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead
\nStrict Warning: It is not safe to rely on the system's timezone settings. Please use the date.timezone setting, the TZ environment variable or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'UTC/0.0/no DST' instead

**Comment by ck-on** [comment]
@MartinAmps interesting you are seeing it back with 3.8 too

So apparently they broke something with that ini setting at some point this year and very few people have even noticed.

**Comment by MartinAmps** [comment]
@ck-on indeed. Have you managed to create a repro? I'm going to have a shot at that tonight, I fear maybe it happens when using a certain \DateTime function which may make it hard to track down.

**Comment by JoelMarcey** [comment]
Hmmm... @MartinAmps @ck-on Are you finding this happening on simple code snippets at all? Were you successful in coming up with a repro of this.

Our client unit tests that use the `date.timezone` ini setting are passing. So I am wondering if this is a server side problem.

**Comment by ck-on** [comment]
@JoelMarcey it's happening on a live "production" server right now, unfortunately whatever code is triggering the change/leak/break is happening so fast I cannot hunt it down. 

But here's the thing, absolutely nothing should be able to change the master value for `date.timezone` (ie. via `ini_set`) for all of hhvm, only the local value for that currently running php code, no?

So, something is definitely broken. 

We have regular php setup as a fallover and it doesn't happen when php is running.

Will build the newest trunk tomorrow and test it.

**Comment by MartinAmps** [comment]
I'm not surprised the tests pass, my CLI works fine too and the fcgi server does most of the time.. I just set `hhvm.log.header = true` hopefully I can correlate the warnings to the access logs and find the  endpoint to narrow down my search.

**Comment by ck-on** [comment]
Right now on the server 

hhvm
```
Directive	Local Value	Master Value
date.timezone	UTC		UTC
```

php
```
Directive		Local Value		Master Value
date.timezone	America/New_York	America/New_York
```

(and they both have `date.timezone` set to America/New_York in .ini)

Something, somehow, is resetting the value in HHVM, because for a few moments after startup I can see it does set to `America/New_York`

**Comment by ck-on** [comment]
For what it is worth, this is on a fully updated CentOS 7.1 server, not sure if any part of hhvm relies on the OS timezone data, I doubt it does.

(and we set TZ just in case but that doesn't change anything)

Maybe hhvm suddenly cannot find/access the timezone data for some reason and decides all declared timezones are invalid and defaults back to UTC

**Comment by MartinAmps** [comment]
I'm on a fully updated Debian Jessie server. I found some endpoints by correlating access logs / error logs and unfortunately the error is not reproducible by just hitting them again. So, I suspect it isn't code related.

**Comment by MartinAmps** [comment]
FWIW I tried adding:

    date_default_timezone_set('America/Los_Angeles');

In the code too, as a workaround, and the warning still happens. Still trying to make a repro

**Comment by ck-on** [comment]
Still experiencing this bug in the latest trunk as of October

Cannot believe no-one else notices or cares or doesn't have this problem.

Very annoying.

**Comment by jwatzman** [comment]
I quickly skimmed the code for an obvious threading issue, but we store the data in RID so that's fine. A repro for this would be really useful to help track it down.

**Comment by soundslocke** [comment]
I don't have a repro but this has started affecting us as well since the most recent update.

Right now we're working around it by adding `date_default_timezone_set('America/New_York');` at the top of our index.php which counteracts the incorrect global timezone (which is still set correctly in the ini file).

**Comment by ck-on** [comment]
@MartinAmps @soundslocke  any chance either of you are also running it on CentOS or something else?

good to know I am not crazy, this is going to be really interesting the month they finally figure it out

**Comment by soundslocke** [comment]
We spent a while trying to narrow it down without success. Our live server is Ubuntu 14.04, HHVM 3.10.1. Sometimes the timezone will "reset" after just a few requests. Sometimes it'll take a while longer. A lone development machine running Ubuntu 14.04 on OSX with Vagrant is encountering the same problem but when testing things we weren't able to correlate it with anything... quite baffling.

**Comment by MartinAmps** [comment]
We’re on debian, so it doesn’t seem OS specific

**Comment by soundslocke** [comment]
We've been running HHVM-3.12.0 and continue to be confused/affected by this.

**Comment by ck-on** [comment]
@soundslocke - same here, still no proper time zone inherited, has to be manually set on every script load

wish more people would report if this is happening to them but I guess the masses are using pre-built versions

maybe it is the age/version of one of the libraries we are using

**Comment by soundslocke** [comment]
@ck-on We're actually using the pre-built/packaged version for Ubuntu. Perhaps it is some system library that causes it.

**Comment by photodude** [comment]
@Orvid could this be related to #7543 and the issues connected to "PHP hard-codes the time table into the library, and a few distros patch PHP specifically to have it use the system timezone info. HHVM's copy of timelib was also patched to use the system timezone database, " and the specific patch failing to be applied to HHVM's copy of timelib.

**Comment by Orvid** [comment]
I don't believe so, as this issue has been a longstanding one that has existed both while the patch has been applied and also while it wasn't. This is likely due to a race condition somewhere that we haven't managed to track down :(

**Comment by soundslocke** [comment]
Glad to see some new comments here. I periodically double check this on our live servers and just did so again (we're using HHVM 3.15.3 now). It continues to happen and we continue to work around it by adding `date_default_timezone_set('America/New_York');` at the top of our app.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue, since asking for more info and adding a _`needs-more-info`+`no-isolated-repro`-combo_ would not be helpful. If you are reading this and are experiencing this issue in a modern hhvm version, feel free to open a new issue.
