### ISSUE TITLE
HHVM socket timeout on long-running requests

### ISSUE THREAD

**Issue by effeks** [facebook/hhvm#6157]
Hi,

I'm having issues with HHVM socket closing towards nginx even though data is streamed from HHVM. Basically it's a report pushing data in chunks to the clients web browser by using output buffers. This works well, but at 120 seconds nginx looses the connection with HHVM with the message:
`upstream prematurely closed connection while reading upstream`

I've tried to use strace on the HHVM child process, and at 120 seconds data stops hitting the clients web browser, but in strace the HHVM process runs for another 13-14 seconds and completes successfully. In the strace output there's no indications at 120 seconds to why the nginx connection is lost.

I'm running HHVM with `-v ResourceLimit.SocketDefaultTimeout=300`.

The SocketDefaultTimeout seem to work because if I set a very low SocketDefaultTimeout, say 15 seconds, I get a timeout message in nginx instead:
`upstream timed out (110: Connection timed out) while reading response header from upstream`

This has been tested on 3.9.0 and 3.8.1.

As I can easily reproduce, how can I proceed to debug this further?

Thanks!

**Comment by codeaken** [comment]
I had the same problem with long running connections timing out. You need to adjust timeouts on both the HHVM side and the NGINX side.

First on the HHVM side you need to add the following to your server.ini file:

    hhvm.server.connection_timeout_seconds = 300

By defining this variable you will avoid the 2 minute timeout (https://github.com/facebook/hhvm/blob/d534aa254e07457a632519f4c8f43dc5bbc704ac/hphp/runtime/server/fastcgi/fastcgi-server.cpp#L92-L97)

Next you need to tell NGINX to wait longer for a response from the fastcgi server. In your case this might not be needed since you are periodically sending chunks of data back. But I will leave this step here also for reference.

    fastcgi_read_timeout 300;

This value can be defined in the http, server or location context.

**Comment by effeks** [comment]
Ok, found the issue, turns out ConnectionTimeoutSeconds is sneaky...

In runtime-options.cpp, ConnectionTimeoutSeconds is set to:
`int RuntimeOption::ConnectionTimeoutSeconds = -1;`
which I looked at earlier but as it was set to "-1" I interpret that as there is no connection timeout.

However, in fastcgi-server.cpp around line 92, ConnectionTimeoutSeconds is defaulted to 120 seconds:
`if (RuntimeOption::ConnectionTimeoutSeconds > 0) {
    timeout = std::chrono::seconds(RuntimeOption::ConnectionTimeoutSeconds);
  } else {
    // default to 2 minutes
    timeout = std::chrono::seconds(120);
  }`

I think it would be great if the default setting for ConnectionTimeoutSeconds would be located in runtime-options instead of in the fastcgi-server code.
