### ISSUE TITLE
Full PHP tag required when including files

### ISSUE THREAD

**Issue by jjeising** [facebook/hhvm#6183]
Under some circumstances it looks like a full PHP tag `<?php ?>` is required somewhere in a file to be interpreted as PHP (when included). I found this error with template files that only use the short echo syntax `<?= ?>`.

Testcase: `index.php`:

``` php
<?php echo '1'; ?>
<?= '2'; ?>
<?php include '3.php'; ?>
<?php include '4.php'; ?>
```

`3.php`:

``` php
<?= '3'; ?>
```

`4.php`:

``` php
<?php ?>
<?= '4'; ?>
```

Output when run with `hhvm --mode server -vServer.Type=fastcgi -vServer.Port=9100 -vRepo.Central.Path=/usr/local/var/run/hhvm/hhvm.hhbc`(no other config):

```
12<?= '3'; ?>4
```

Output when run on cli:

```
$ hhvm index.php
1234
```

I've also tried `hhvm -vEval.Jit=1 index.php`, but this doesn't change anything in the later case.

Note that `4.php` also works with the PHP tag behind the short echo tag. When `<?= '2'; ?>` is the only statement in `index.php` it also works as expected. This is only an issue with includes.

Version `HipHop VM 3.9.1 (rel)`
Plattform `Mac OS X`

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hack files with non `.hack` extensions are required to start with `<?hh` or a sheebang, followed by `<?hh`. `.hack` files do not permit an opening tag.
