### ISSUE TITLE
Trying to serialize a closure causes a warning (vs. Exception in zend php)

### ISSUE THREAD

**Issue by filbertkm** [facebook/hhvm#6206]
on php 5.3:

> $x = function() { echo "hi"; };
> 
> $y = serialize( $x );
> Caught exception Exception: Serialization of 'Closure' is not allowed
> # 0 /srv/mediawiki/php-1.26wmf21/maintenance/eval.php(78) : eval()'d code(1): serialize(Object(Closure))
> # 1 /srv/mediawiki/php-1.26wmf21/maintenance/eval.php(78): eval()
> # 2 /srv/mediawiki/multiversion/MWScript.php(97): require_once('/srv/mediawiki/...')
> # 3 {main}

(still need to check php 5.6, but think it's the same there)

on hhvm:

$x = function() { echo "hi"; };

> serialize( $x );
> Warning: Attempted to serialize unserializable builtin class Closure$;1015959387$f88ca0d4c5acd3a5845a6d32d20783ef$ in /srv/mediawiki/php-1.26wmf21/maintenance/eval.php(78)(8f0647e4a0360628842a5258eac04a18) : eval()'d code on line 1

**Comment by filbertkm** [comment]
MediaWiki depends on this behavior in some of the phpunit tests:

https://github.com/wikimedia/mediawiki/blob/master/tests/phpunit/MediaWikiTestCase.php#L341-L351

When running tests with verbose error reporting, then I run into this issue.

https://phabricator.wikimedia.org/T111641

**Comment by karpa13a** [comment]
@filbertkm https://3v4l.org/1f86o

**Comment by filbertkm** [comment]
@karpa13a thanks for checking other versions

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hack developers may depend on hhvm's behavior. Changing it now would cause churn with little perceived benefit.
