### ISSUE TITLE
Typechecker not supporting object iteration

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6287]
PHP supports object iteration (http://docs.hhvm.com/manual/en/language.oop5.iterations.php).

However, when using the same kind of code in Hack, the code runs, but the typechecker complains:
```
<?hh // strict

class Test
{
  public function __construct(public int $a,public int $b,public int $c) {}
}

f();

function f(): void
{
  $test=new Test(1,2,3);

  foreach($test as $key => $value)
  {
    echo "Key=$key, value=$value\n";
  }
}
```
test.php:14:11,15: Invalid foreach (Typing[4110])
test.php:14:11,15: This is an object of type KeyedTraversable because this is used in a foreach statement
test.php:12:9,23: It is incompatible with an object of type Test

Is there a way to make this code pass the typechecker, e.g. by making the class implement some interface?

Maybe the object needs to implementing an interface like KeyedIterator, and if so, does this mean that general object iteration (without explicitly implementing an interface) isn't supported by the typechecker?

**Comment by SiebelsTim** [comment]
You can implement `Iterator` or `IteratorAggregate` to make an object iterable. 
However, that probably doesn't do what you would like to achieve, as HHVM has no internal pointers to current elements (that's why `current(object)` doesn't work).

That being said, foreaching an object works in the runtime even though it can't be typechecked. So you could put an `// UNSAFE` above your foreach.  (http://docs.hhvm.com/manual/en/hack.modes.unsafe.php)

You could compile an array or better collection of elements you want to iterate over to make this work in `// strict`. That would introduce a lot of boilerplate code though.

**Comment by fredemmott** [comment]
yeah, you want to implemented KeyedIterator. The PHP interfaces aren't enough to know:
 - the types of keys/values
 - if keys actually make sense.

You want KeyedIterator instead of Iterator because you care about keys.

**Comment by fredemmott** [comment]
Closing as this is documented on the KeyedTraversable page.

**Comment by tslettebo** [comment]
Thanks for your replies. @SiebelsTim and @fredemmott.

Yes, it makes sense to me that this either needs ```// UNSAFE ``` or implementing the KeyedIterator interface to pass the typechecker.

I'm a little confused about KeyedIterator vs KeyedIterable, as they both seem to applicable to this, how to choose between them?
