### ISSUE TITLE
Unexpected typedef error message

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#6308]
```
<?hh // strict

type TestAlias = Test;

function f(): void
{
  $test=new TestAlias();
}

class Test
{
}
```

The above code gives the error message:

test.php:7:13,21: Unexpected typedef (Naming[2052])
test.php:3:6,14: Definition is here

If `TestAlias` is changed to `Test` in the `new` expression, it passes the typechecker.

Why is the typechecker complaining about this?

**Comment by Orvid** [comment]
My guess is that there's a difference of when the names are bound. Does it work if you move the typedef after the declaration of `Test`?

**Comment by tslettebo** [comment]
Hi @Orvid. I tested it, and it makes no difference.

**Comment by sgolemon** [comment]
The rundown I just got from @jwatzman is that types (including TypeAliases) can't actually be new'd up.  The underlying technical reason is that there are a large class of typedefs for which trying to use `new` would never make sense.  In this specific case it would, but the typechecker isn't currently smart enough to distinguish the two.  So for now `new SomeAlias` is invalid hack.

**Comment by SiebelsTim** [comment]
I just want to point out that you can "create" a type of `SomeAlias` when you wrap it in a function

```
 <?hh // strict

type SomeAlias = Test;

class Test {}

function getSomeAlias(): SomeAlias {
  return new Test();
}

```

**Comment by tslettebo** [comment]
@sgolemon and @SiebelsTim: Thanks for your replies and suggestions.

**Comment by tslettebo** [comment]
@sgolemon I wonder why this case was closed, which I assume means "Not desirable or practical to fix"?

I thought the purpose of the type aliases was to be able to use them in the same way you would the original type, just like "typedef" works in languages like C++.

Being able to create an object using a typedef seems like a very simple case, which makes me wonder why this is so hard, it's not even considered a valid feature request or issue worth fixing.

As it is, typedefs aren't really useful for us, and the only practical alternative is to use inheritance:

class TestAlias extends Test
{
}

$test=new TestAlias(); // Now ok

**Comment by jwatzman** [comment]
> I thought the purpose of the type aliases was to be able to use them in the same way you would the original type, just like "typedef" works in languages like C++.

Yes, that's the hope, except unlike C++, Hack doesn't have reified generics. So while this would be fine:

```
class C {}
type TD = C;
$x = new TD();
```

we can't really do this:

```
class C<T> {}
type TD = C<int>;
$x = new TD();
```

We could compile both of those the same at runtime, but that would be super misleading: when you do `new`, there is absolutely nothing enforcing the `int` generic. A contrived example, but imagine this one:

```
type Matrix = Vector<Vector<int>>;
```

Would you really expect `new Matrix()` to compile to the same thing as `new Vector()`?

Being unable to do this properly is why we don't allow `new` with typedefs -- we figured it would be less confusing to just rule it out entirely than have a weird rule for when it's allowed (classes but no generics anywhere). And it relying on reified generics to fix is why we're exceedingly unlikely to see it fixed anytime soon, and why this issue was closed.

That said, cc @dlreeves in case he wants to take a second look at this or otherwise has a different perspective.

**Comment by tslettebo** [comment]
Thanks for your reply, I didn't realise that generics was the reason a type alias can't simply be considered an alias for a type.
