### ISSUE TITLE
Continue output buffering

### ISSUE THREAD

**Issue by jwatzman** [facebook/hhvm#6319]
https://wiki.php.net/rfc/continue_ob

Unclear if this was implemented? Looks low-pri anyways.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

PHP style IO is going to conflict with native hsl-io (which is async to the core). Those ik methods don't mix, because of tearing when O_NONBLOCK is passed by hsl-io.

Output buffering could be implemented in userland as a WriteHandle on top of hsl-io.
