### ISSUE TITLE
Hack: array used as shape not allowing append of child

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#6361]
I can only get this error to replicate when running `hh_client`. `hh_single_type_check` reports no errors.

``` hack
<?hh

trait A {
  abstract public function getEmployeeName(
    array<string, string> $record,
  ): string;
  abstract public function getExportCodeIndex(): string;
  abstract public function getLeaveTypes(): array<string>;

  public function entitlementImport(array $arrRecords): array {
    $users = array();
    $today = new DateTime();
    $arrLeaveColumns = $this->getLeaveTypes();
    $exportCodeIndex = $this->getExportCodeIndex();
    foreach ($arrRecords as $record) {
      $exportCode = idx($record, $exportCodeIndex);
      if (empty($exportCode)) {
        continue;
      }
      if (empty($users[$exportCode])) {
        $users[$exportCode] = array(
          'details' => array(
            'export_code' => $exportCode,
            'name' => $this->getEmployeeName($record),
          ),
          'entitlements' => array(),
        );
      }
      foreach ($arrLeaveColumns as $leaveType) {
        if (empty($record[$leaveType])) {
          continue;
        }
        $entitlementEntry = array(
          'details' => array('name' => $leaveType),
          'adjustments' => array(
            array(
              'date' => $today,
              'amount' => round($record[$leaveType], 4),
            ),
          ),
        );
        $users[$exportCode]['entitlements'][] = $entitlementEntry;
      }
    }
    return array('users' => $users);
  }
}
```

```
test.php:42:9,45: an array (used like a hashtable) does not allow array append (Typing[4006])
  test.php:22:24,28: You might want to check this out
test.php:42:9,45: an array (used like a hashtable) does not allow array append (Typing[4006])
  test.php:22:24,28: You might want to check this out
```

This is complaining about the line `$users[$exportCode]['entitlements'][] = $entitlementEntry;`. However, `$users[$exportCode]['entitlements']` is always an array used as a vector.

If I switch the construction of the `$users[$exportCode]` to using `shape`, then it works as expected.

**Comment by jwatzman** [comment]
@dlreeves this seems related to your recent array typing improvements.

**Comment by dabek** [comment]
@jwatzman I think you wanted me

@HRMsimon : php arrays are in general treated like homogeneous containers by Hack. In particular 
```
  $users[$exportCode] = array(
    'details' => array(
      'export_code' => $exportCode,
      'name' => $this->getEmployeeName($record),
    ),
    'entitlements' => array(),
  );
```

makes $users[$exportCode] an array, which first element is a hashtable array, and second element is an unknown array type, but since we assume that the arrays are going to be homogeneous it unifies it with the first one and thinks that that all the elements are are hashtable arrays, and gives your error. 

There are few heuristics that try to "detect" such cases of arrays used as shapes, and (to avoid annoying errors) just gives up on typing them - in this particular case it doesn't work, because of "unknown array type" unifying with "hashtable array". When it doesn't work, you should just explicitly use shapes.

This is a pre-existing issue, and unrelated to my recent changes, but in fact those changes make the shape-like heuristics a bit smarter and solves it: hh with https://github.com/facebook/hhvm/commit/52845c0814724362f9c15c67af82be02944d7ebc applied makes the error go away even without explicitly using shapes.

> hh_client. hh_single_type_check reports no errors.

That's unlikely, maybe you forgot to recompile one of them, or you have some dependencies on other files that makes hh_single_type_check give up (it just checks one file in isolation).

**Comment by lexidor** [comment]
In hhvm [4.65.0](https://hhvm.com/blog/2020/07/06/hhvm-4.65.html) the `array()` literal was banned.
In hhvm [4.44.0](https://hhvm.com/blog/2020/02/10/hhvm-4.44.html) the `[]` literal was banned.

This makes it so that all arrays are either hashtable-like (darray, dict) or vector like (varray, vec).
Hack will never have to guess array types from empty literals.
You are now required to say:
```HACK
  $users[$exportCode] = darray[
    'details' => darray[
      'export_code' => $exportCode,
      'name' => $this->getEmployeeName($record),
    ],
    'entitlements' => varray[],
  ];
```

Meaning that there can't be ambiguity.
This type is not very useful `darray<string, (varray<nothing>|darray<string, string>)>`, since not all the members of the union allow array append, so shapes are still recommended.
