### ISSUE TITLE
HHVM and WordPress - "Bulk Actions" button is missing

### ISSUE THREAD

**Issue by ivanyord** [facebook/hhvm#6379]
When HHVM is enabled, the button "Bulk Actions" in Posts, Pages, Comments, etc pages in the WordPress admin area are missing. I have tested this on a plain, default WordPress installation:

HHVM:

<img width="1132" alt="hhvm" src="https://cloud.githubusercontent.com/assets/9335668/10542084/46c08b76-741e-11e5-8964-d7f341fb2011.png">

PHP:

<img width="1207" alt="php" src="https://cloud.githubusercontent.com/assets/9335668/10542091/4d7bd254-741e-11e5-8884-991ce818a277.png">

You can use the installation provided using hosts file:

109.73.232.149 ivan-yordanov3.com www.ivan-yordanov3.com

Username: admin
Pass: pass@1234

Does anyone experience the same issue or has a solution for that?

**Comment by jwatzman** [comment]
You may want to remove that login/password -- remember that these issues are publicly visible.

As for the "bulk actions" button missing, it would be a lot easier for us to fix this if we knew exactly what the lower level incompatibility is. (And it's going to be very hard to tell that from your own install.) Notably, I just checked the WordPress backend for hhvm.com, which is running on HHVM 3.6, and there is indeed a "bulk actions" button. Do you know what's different about your install?

**Comment by ivanyord** [comment]
The only different thing (maybe) is that the site is running on CentOS. I am also using HHVM 3.6. There are no custom changes on application level and the environment is CentOS, Apache + Nginx, MySQL, PHP/HHVM.

**Comment by ivanyord** [comment]
Any Updates? The issue seems to be with HHVM 3.6 on CentOS. Does anyone else have the same issue ?

**Comment by CrimsonGuard** [comment]
Same thing here.
I was in a pain to figure out why the bulk action dropdown was missing. Thanks to this report, I deactivated HHVM and it's back!
FYI, I have a Cloud Hosting at SiteGround. I don't know wich version of HHVM is used.

I hope you'll be able to fix this soon. 
Keep up the good work! Thx

**Comment by CrimsonGuard** [comment]
Last night, I remembered that I had another Wordpress running on the same SiteGround hosting, with HHVM activated, and the bulk dropdown is present.
I tried a few settings to test the 2 installs in similar contexts but failed to find an explanation... :(

**Comment by CrimsonGuard** [comment]
The only notable difference I can see between the two installs is that the one with the issue is a multisite install (no plugin activated, default theme).
Ivan, is your WP on multisite too?

**Comment by jwatzman** [comment]
hhvm.com (where everything works fine) is a multisite install, so that's probably not the issue.

**Comment by CrimsonGuard** [comment]
Left a ticket at SiteGround.
It seems they just added PHP version declaration on my .htaccess and now the dropdown is back.
`AddHandler application/x-httpd-php55 .php .php5 .php4 .php3`

I suppose it should have been there from the beginning, but is not written by Softaculous.
Just don't know how to check if HHVM is running or not now... Hope it is.

**Comment by CrimsonGuard** [comment]
Sorry for the mixup, of course it didn't solve anything and just deactivated HHVM (sets php 5.5).
SiteGround support says this may be related to HHVM not supporting CentOS (which matches Ivan's suppositions).
I hope this will help solve the issue someday.

**************************
"I have checked this case carefully and first, I would like to note that this is the second time I see the problem in question.
Sadly - we suspect that it is caused by some incompatibility between the application itself and HHVM, still - we really were not able to find a fix or solution for the problem.

In the past - we opened a discussion on GitHub regarding this, however no solution was presented there.

As you know HHVM is relatively new software. It is possible that some of the functions which are working as expected with PHP are unavailable with HHVM, as it is in this case. What we suspect is that the issue could be related to the OS running on the server as HHVM is officially compatible for Debian and Ubuntu only and we are running centOS - still this is just a speculation.

Unfortunately, we cannot do much on our end, since we are not the developing party of HHVM or WordPress. As HHVM is constantly updated, this might be fixed in some of the future releases. Until then, I would suggestion you to use PHP."

**Comment by jwatzman** [comment]
Yeah, this is *probably* a bug in HHVM, just figuring out where is super difficult, especially since it seems to work for us in our on vaguely similar install on hhvm.com. My suggestion might be:

- With HHVM enabled, use your web browser's console to see if any CSS or JS files are failing to load. MIME type issues have been a source of problems in the past, HHVM and PHP's defaults can be slightly different depending on exact version and configuration. If we're lucky, the markup is already there, just not getting used to some MIME issue which means the JS or CSS fails to load.
- Disable HHVM. Figure out what code is supposed to render the dropdown, and how it gets called.
- Enable HHVM. Trace the code execution to see where it diverges. Get more detailed until you have a small example that behaves differently on HHVM and PHP.

**Comment by fredemmott** [comment]
As an aside, it's extremely unlikely to be caused by CentOS (both in principle, and because we use a centos derivative internally) - though as that means they're not using one of our packages, it's possible that certain extensions are disabled.

**Comment by CrimsonGuard** [comment]
Well, not sure it helps, but I've checked if any JS or CSS is failing to load. Nothing here.
I am not a php dev so I won't be able to dig very far. 
On the browser console, I can see that the div 
`<div class="alignleft actions bulkactions">  </div>`
is empty, whereas it contains `<label>`, `<select>` and `<input>` when HHVM is disabled.

I can only track the code up to wp-admin/includes/class-wp-list-table.php, line 1120, where the matching div lies, with this php bit of code: 
`<?php $this->bulk_actions( $which ); ?>`

Why is this code not rendering is beyond my skills. :s

**Comment by jwatzman** [comment]
Yeah, it's useful to know that it is in the markup, which indicates a PHP-level issue, but we need to know more than that to fix it :(

**Comment by CrimsonGuard** [comment]
I can understand that.
Let me know if I can be of any help.

**Comment by Orvid** [comment]
Closing, still needs more info (https://github.com/facebook/hhvm/wiki/Human-Timeouts) - will reopen if provided.
