### ISSUE TITLE
Downgrade from 3.10 to 3.9.1

### ISSUE THREAD

**Issue by alex-mashin** [facebook/hhvm#6385]
How can I downgrade hhvm and hhvm-dev from 3.10 to 3.9.1 under Ubuntu 14.04?

HHVM 3.10 breaks something (see https://phabricator.wikimedia.org/T115779); there's no chance it will be corrected soon; and I don't see the version 3.9.1 among available ones in `apt-cache showpkg hhvm`.

**Comment by r3wt** [comment]
```sh
cd ~ &&
apt-get autoremove hhvm &&
wget http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/hhvm_3.9.1~trusty_amd64.deb &&
sudo dpkg -i hhvm_3.9.1~trusty_amd64.deb
```

**Comment by alex-mashin** [comment]
Thank you, it worked.

But the issue remains: older versions should be installable with apt.

**Comment by simonwelsh** [comment]
That's an issue for hhvm/packaging, rather than this repo.

**Comment by jwatzman** [comment]
> older versions should be installable with apt.

In the general case, older versions become unsupported the moment the new version is out, so it would be bad to provide an easy way to do this. We of course do have all the old debs still on dl.hhvm.com if you really need one.

For 3.9 specifically, since it's an LTS release, it does continue to be supported, you just have to change the apt configuration to pin to that release. [Our page on LTS releases](https://github.com/facebook/hhvm/wiki/Long-term-support-%28LTS%29) has info on how to do this.

I'm going to close this out since I think your question was answered? LMK if there's something else to do here.
