### ISSUE TITLE
how to compile hack alone by ocaml  source code in hhvm or flowtype ?

### ISSUE THREAD

**Issue by joostshao** [facebook/hhvm#6387]
there is no docs to tell us how to  compile hack alone by ocaml  source code in hhvm or flowtype ?
I think someone may be help me .

it looks depends L4Z.

```
heap/hh_shared.o：在函数‘decompress’中：
/mnt/data/flow/hack/_build/heap/hh_shared.c:1083：对‘LZ4_decompress_fast’未定义的引用
heap/hh_shared.o：在函数‘hh_save’中：
/mnt/data/flow/hack/_build/heap/hh_shared.c:1055：对‘LZ4_compressHC’未定义的引用
heap/hh_shared.o：在函数‘hh_save_dep_table’中：
/mnt/data/flow/hack/_build/heap/hh_shared.c:1161：对‘LZ4_compressHC’未定义的引用
heap/hh_shared.o：在函数‘hh_load_dep_table’中：
/mnt/data/flow/hack/_build/heap/hh_shared.c:1192：对‘LZ4_decompress_fast’未定义的引用
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
Command exited with code 2.
Compilation unsuccessful after building 622 targets (621 cached) in 00:00:06.
make: *** [_build/hh_server.native] 错误 10
```

AND by the way, what's the relationship between flow and hacklang?
i know hacklang typechecked by hh_server and hh_client .

**Comment by joostshao** [comment]
i   am thinking how make hack-lang  transform to hhbbc  code ?

**Comment by jwatzman** [comment]
- I can't help you with building flow. Sorry! The Hack typechecker and flow share a lot of code. But, they have their own build system. I don't know how it works. You will have to ask the flow team.
- I can help with the Hack typechecker. It isn't designed to be built separately from HHVM. Since it is the typecheker for the Hack language, it's expected you will need a runtime too. You will need to follow the directions to build HHVM. This wiki page has directions: https://github.com/facebook/hhvm/wiki/Building-and-Installing-HHVM

> i am thinking how make hack-lang transform to hhbbc code ?

I don't understand. What are you trying to do? HHVM already transforms Hack into HHBC when it runs Hack code. The HHBBC optimizer can then run on that code. (It can run on any HHBC code.)

**Comment by joostshao** [comment]
i try build hack alone in HHVM repo and success.

-rwxrwxr-x 1 ubuntu ubuntu 2.5M 10月 18 23:48 h2tp
-rwxrwxr-x 1 ubuntu ubuntu 3.6M 10月 18 23:48 hh_client
-rwxrwxr-x 1 ubuntu ubuntu 3.2M 10月 18 23:48 hh_emitter
-rwxrwxr-x 1 ubuntu ubuntu 3.7M 10月 18 23:48 hh_format
-rw-rw-r-- 1 ubuntu ubuntu  96K 10月 18 23:48 hhi.tar.gz
-rwxrwxr-x 1 ubuntu ubuntu 2.5M 10月 18 23:48 hh_match
-rwxrwxr-x 1 ubuntu ubuntu 3.7M 10月 18 23:48 hh_server
-rwxrwxr-x 1 ubuntu ubuntu 3.5M 10月 18 23:48 hh_single_type_check

not runtime, not include the transform period , just language  typecheck tools client and server.


thanks.  i think hack-lang repo  should be third-party repo and depended.

**Comment by jwatzman** [comment]
> thanks. i think hack-lang repo should be third-party repo and depended.

Thanks for the suggestion, but we aren't going to do this. There is very little use for building the typechecker without the runtime. (Why check your code if you can't run it?)

It sounds like your problem is solved? I'm going to close this issue. If your problem isn't actually solved, respond here, and we can reopen it.
