### ISSUE TITLE
HHVM 502 Bad Gateway

### ISSUE THREAD

**Issue by stevedien** [facebook/hhvm#6511]
I installed HHVM prebuilt on Debian 8 and I configured NGINX to talk with HHVM via Fast-CGI but after restart NGINX, I see 502 bad gateway

**Comment by r3wt** [comment]
@lulzsecd a few general problems that might cause this:

hhvm failed to start because the sessions directory doesn't exist or isn't writeable. check php.ini/server.ini
hhvm failed to start becauser /var/run/hhvm isn't writeable. generally just nose around the hhvm installation and see what it isn't starting.

**Comment by lulzsecd** [comment]
I chmod 777 for /var/run/hhvm and sessions directory still exist and writeable
I still see 502 bad gateway after  change nginx configuration from php5-fpm to hhvm
