### ISSUE TITLE
Add option to cache hhbc repo in memory

### ISSUE THREAD

**Issue by Eagle-X** [facebook/hhvm#6525]
Can anyone help me?
Recently I frequently encounter this error:
"Failed to initialize central HHBC repository:\n  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file\n" or "Failed to initialize schema in /var/run/hhvm/hhvm.hhbc" when the network jitters.

My env:

``` sh
web sever: nginx1.6.2
```

``` sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
```

``` sh
$ /opt/bin/hhvm --version
HipHop VM 3.6.3-dev (rel)
```

``` sh
$cat php.ini
; php options
session.save_handler = files
session.save_path = /var/run/hhvm
session.gc_maxlifetime = 1440

; hhvm specific
hhvm.log.level = Error
hhvm.log.use_log_file = true
hhvm.log.use_cronolog = false
hhvm.log.file = /data/log/hhvm/error.log
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.log.header = true
```

``` sh
$cat server.ini
; php options

pid = /var/run/hhvm/hhvm.pid

; hhvm specific

hhvm.server.file_socket = /var/run/hhvm/hhvm.sock
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.log.use_log_file = true
hhvm.log.file = /data/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
hhvm.server.thread_count = 128
hhvm.server.connection_limit = 1024
hhvm.server.connection_timeout_seconds = 5
hhvm.http.default_timeout = 5
hhvm.admin_server.port = 9100
```

**Comment by FightingMan** [comment]
May be your disk has no space,or disk io to high

**Comment by Eagle-X** [comment]
I've checked. There are enough disk space and io is also OK.

**Comment by apaloma** [comment]
We used to hit this. Our problem was the limit on the number of open file descriptors was too low. What's the output of `sysctl fs.file-max`? Try increasing it. Also check `ulimit -n` and `/etc/default/hhvm`

**Comment by Eagle-X** [comment]
```
# sysctl fs.file-max
fs.file-max = 655360
```

```
# echo 'ulimit -n' | su www-data -s /bin/bash
655360
```

```
# lsof | grep "^hhvm" | wc -l
53457
```

```
# lsof | grep "^hhvm" | fgrep anon_inode | wc -l
32136
```

```
hhvm.server.connection_timeout_seconds = 5
```

Is it big enough? Or other problems?

**Comment by apaloma** [comment]
Seems big enough. Probably something else going on then.

**Comment by wake-up-neo** [comment]
The same problem under network high-load (let's say 5000 parallel requests to hhvm through nginx-fastcgi). I assume that there are enough file descriptors in OS configs, actually - millions. Even if I have extra processor time of 12 cores, tens of RAM GB free, SSD with hardware RAID - after tons of testing I probably found that file system replies 'file not found' under i/o high-load and hhvm goes down immediately. 

`Failed to initialize central HHBC repository:\n  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file`

 The only temp. solution I could suggest especially in your case is to significantly decrease  hhvm.server.thread_count. 
But still looking for more correct solution and appreciate any suggestions to fix this because I'm stuck in scaling hhvm. Except just scaling the servers and limiting number of possible requests to the instance which seems to be worse solution.

**Comment by wake-up-neo** [comment]
btw I can reproduce this error

**Comment by paulbiss** [comment]
Hmm, if the system is having trouble finding the file under highload I'm not sure there's an easy solution on the HHVM side. Right now we need to be able to load the repo to extract information that isn't cached in memory such as line number<->bytecode maps. Adding an option to cache everything in memory may be one option but the right answer here is probably going to be to investigate why your file system is having difficulty under load, or reduce the load to a point that things work more smoothly.

**Comment by wake-up-neo** [comment]
Thanks @paulbiss, agree regarding file system, this should be investigated and fixed. 

> Adding an option to cache everything in memory may be one option

btw, this would be great, since not every system have SSD and tuned OS. In this case in-memory repo would improve overall speed and stability of the virtual machine, it needs less kernel and doesn't rely on a filesystem.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Nothing has happened on the implementation for many years. I am not sure if hhvm should take on this feature anymore. Spinning up a RAM disk with the repo on there would have almost the same effect.

Open to have my mind changed on this one.
