### ISSUE TITLE
hhvm gives Class undefined after code uploaded

### ISSUE THREAD

**Issue by edwh** [facebook/hhvm#6584]
I'm working with PhpStorm, which uploads code to my server when I save it.  Fairly regularly, this causes HHVM to complain that the class is not defined, or give syntax errors in it, which are spurious - if I restart HHVM it works fine.

I'm guessing that HHVM is noticing that the file has changed halfway through the upload, and picking up an empty or half-written version of the file.

Are other people seeing this?  Any suggestions?

**Comment by Norbyte** [comment]
Unchecking "Preserve file timestamps" in the PhpStorm deployment options tab fixed this issue for me.

**Comment by edwh** [comment]
Thanks, I'll try that.

**Comment by edwh** [comment]
I did that, but I've still seen the same issue.  Any other ideas?

**Comment by edwh** [comment]
I'm still seeing this quite regularly.  It's more inconvenient when patching live servers.  Is there any way to disable HHVM's auto-check of the files and kick it manually when I know they've changed?

**Comment by karpa13a** [comment]
@edwh i have same deploy procedure and have same question.
or how to notice hhvm reload repo in repoauth mode?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This seems like an issue with your setup instead of an issue with hhvm perse. A Class is either registered in the AutoloadMap or it is not. If it is not, you'll have to regenerate it. In repo auth mode, the AutoloadMap is always up to date. If you are having issues with AutoloadMaps, please open a new issue against hhvm-autoload if appropriate.
