### ISSUE TITLE
Hack type error in different directory

### ISSUE THREAD

**Issue by baptistemarchand** [facebook/hhvm#6610]
Hi,

We have a server where there are different directories containing different versions of our source code.
There are hh_server instances running in each directory.
Sometimes we see that the source code in one directory affects the output of hh_client in another directory. Using `hh_client restart` solves the problem.

This is the error we get:

`Catchable fatal error: Hack type error: Too few arguments at /home/user_1/src/MyClass.php line N in /home/user_2/vendor/composer/autoload_real.php on line 58`

Both user_1 and user_2 directories contain a .hhconfig file.

Is that a bug with hh_server? Or is something wrong with our setup?

We are using hhvm 3.10.1.

Thank you for your help!

**Comment by jwatzman** [comment]
Are there symlinks between the two, or do you otherwise move paths around in a way that might confuse incremental mode? Do you have nested `.hhconfig` files? The way `hh_client` works is that it takes the working directory and moves up until it finds an `.hhconfig` file, and then all directories recursively under that `.hhconfig` are checked. So this gets weird if you have nested directories with `.hhconfig` files.

**Comment by fredemmott** [comment]
No response.
