### ISSUE TITLE
Allow user attributes on closures

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#6620]
Would be useful to be able to use user attributes on closures. Would allow me to use `__Memoize` on something without having to create what amounts to a single-use function or method.

**Comment by lexidor** [comment]
Footnote: attributes are allowed on lambda's, but there is a special error for `__Memoize`.
Also, I can't find a way to reflect on the attributes using a `\Reflection...` class.

Typechecker
```
Parsing[1002] <<__Memoize>> attribute is not allowed on lambdas or anonymous functions.
   --> file.hack
  3 |     $x = <<__Memoize>> () ==> 4;
    |            ^^^^^^^^

1 error found.
```

Runtime
```
Uncaught Error: <<__Memoize>> attribute is not allowed on lambdas or anonymous functions. in /path/to/file.hack:3
Stack trace:
#0 {main}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I am closing this issue, because user attributes are allowed on lambda functions. You may wish to open a new issue specifically about the Memoize attribute interaction. I expect there to be an implementation reason for the lack of Memoize support on lambda functions.
