### ISSUE TITLE
TypeCheck issue with builtin return type

### ISSUE THREAD

**Issue by dk-zero-cool** [facebook/hhvm#6733]
I know that adding type safety to PHP can be a tricky thing, especially since many builtin functions make use of the fact that PHP don't care much about data types by default. One such function is `zip_entry_read` that returns `FALSE` on error or a `string` on success. The problem is that you have defined `string` as the data type for this function, which means that the type checker complaints when I try to check `$var !== FALSE`. The best way would be to change the return type to `?string` and change the function to return `NULL` on failure. But I don't know what your policy is regarding changing PHP's default behavior.

**Comment by SiebelsTim** [comment]
> The best way would be to change the return type to ?string and change the function to return NULL on failure.

exactly! And every function would behave like this if there wouldn't be this problem: PHP compatibility. 

The solution probably is to have this untyped, so the typechecker doesn't complain. However, that means you catch fewer bugs because the typechecker doesn't know about the type anymore.

I think this is typed as string on purpose. `zip_entry_read` returns false on failure if I see correctly. Rarely do you want to actually check on the false case. Most error will be caught by `zip_open`.
In general functions like this are typed to the success case because failure almost never happens.

You can always /* HH_FIXME */ or /* HH_IGNORE_ERROR */ this, which probably is the solution you  should be using.

**Comment by dk-zero-cool** [comment]
Yes well hiding errors, setting it untyped, avoid checking for errors etc. are all not very good solutions. PHP has a lot of functions that returns various data types on success and FALSE on error or other reasons. How about adding something similar to PHP's `empty()`, only simply checking for `FALSE` on `mixed` type.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hack now allows comparisons that are always false. So `string === bool` is allowed. The underlying problem is that the built-in hhi declarations are not checked at runtime and they are a best effort. Certain functions are optimistically typed. For example preg_match https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_preg.hhi#L30. If you are still having issues with zip_entry_read specifically, please open an issue about this hhi entry.
