### ISSUE TITLE
HHVM logging frequent slow queries that run very fast through mysql client

### ISSUE THREAD

**Issue by pjv** [facebook/hhvm#6740]
I'm very ignorant about the low-level plumbing between HHVM and MySQL, but I would like to figure out / work around an issue I am seeing on a production WordPress server.

The server is running an HHVM (3.11.0) nginx (1.8.0) MySQL (5.5.46) stack and overall performance is great, but I see a lot of lines in the HHVM error log that look like this:

`[Mon Jan 11 11:49:22 2016] [hphp] [23157:7f37c93ff700:23714:000001] [] SlowTimer [1703ms] at runtime/ext_mysql: slow query: SELECT  wp_comments.* FROM wp_comments JOIN wp_posts ON ( wp_comments.comment_post_ID = wp_posts.ID ) WHERE post_status = 'publish' AND comment_approved = '1'  ORDER BY comment_date_gmt DESC LIMIT 12`

When I paste that exact query into the MySQL client running on the same server, it completes in 58 ms. so it doesn't seem to be a problem with the query or an index thing. It seems like there is some issue between HHVM and the database.

What could I do to try to figure out why/how/where it's happening?

**Comment by fredemmott** [comment]
HHVM's mysql client is a *very* thin and highly tested wrapper around the C client, and it's extremely unlikely to be a problem here. Most likely is that something is happening on the system that makes that MySQL temporarily be slow for that query.

To investigate:
 - if this is happening reasonably frequently (eg every few seconds to few minutes) use tools like `top` to check general system state and `mytop` to look into what mysql is doing. As HHVM and mysql are on the same system in your case, you can use `perf` without specifying a process or PID to get a profile of both HHVM and MySQL - if you are running a debug build of HHVM, that will both show the time spent in the mysql_query() and related client functions, and how much time is spent on the server
 - if it's happening less frequently, use any standard system monitoring tool to look for CPU and IO spikes  that correlate
 - if the system is a VM, look at host-level metrics to see if something on the host or another VM is slowing it down. If you're on a hosted VM (AWS, Linode, etc) you're basically limited to the previous two options

**Comment by pjv** [comment]
Thanks for the suggestions @fredemmott. I'll close this for now to not add to the big pile of lingering open issues. If my investigations turn up anything that seems specific to HHVM, I'll re-open.

**Comment by ubergarm** [comment]
I'm seeing a potentially similar issue when switching between:
* HHVM: `HipHop VM 3.14.4 (rel)`
* PHP: `5.6.25-2+deb.sury.org~xenial+1`

Both are running behind Apache2: `Apache/2.4.18 (Ubuntu)` on an AWS EC2 VPS Ubuntu 16.04 Xenial instance.

In my testing, it seems like queries are cached with `php` but not with `hhvm`.  Initial page load times are similar, but reloading the page `php` is *much* faster due to known slow mysql queries being slow.

Database is AWS Aurora (MySQL 5.6) with all caching stuff on with default values.

Anyway, I can't find any `HHVM` mysql knobs to tweak when it comes to caching queries. Maybe this is an application level issue... 

My two cents...

Thanks!
