### ISSUE TITLE
ArrayAccess::offsetGet() should return nullable

### ISSUE THREAD

**Issue by dk-zero-cool** [facebook/hhvm#6743]
```
system/core/utils/Collapsible.hh:26:33,43: It is incompatible with this object of type ArrayAccess
    because some declarations are incompatible.
    Read the following to see why:

  system/core/utils/Collapsible.hh:26:53,53: This is a value of generic type T
  /tmp/hh_server/hhi_e3e5fa3/interfaces.hhi:825:39,40:   via this generic Tv
  system/core/utils/Collapsible.hh:153:46,47: It is incompatible with a nullable type
```

``` php
public function offsetGet(string $name): ?T {
    return $this->$mMap->get($name);
}
```

Accessing an object via `$obj["key"]` should have no problems with a `NULL` value.

**Comment by fredemmott** [comment]
Not entirely sure this would be correct, just re-titling to describe what you're reporting better.

**Comment by dk-zero-cool** [comment]
Let's see. `array[""]` can return `NULL`, `Map[""]` can return `NULL`. Since your own Map even uses `NULL` as default if a key does not exist, and allows keys to be set to `NULL`, it seams as if this is a valid option for any array like object. It also makes it quite difficult to extend Map's and other classes if you can't support their own return types.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

ArrayAccess no longer provides its magical `$obj['key']` behavior. See blogpost for [4.45.0](https://hhvm.com/blog/2020/02/19/hhvm-4.45.html).
Accessing something out of bounds has started throwing `OutOfBoundsException`s since hhvm [4.9.0](https://hhvm.com/blog/2019/06/10/hhvm-4.9.0.html) _accessing a container with an invalid key now raises an error instead of a notice. This was already the case for Hack arrays._

This interface is fully generic, so if a user would like to retain the nullable behavior, they ought to make `Tv` nullable themselves.
