### ISSUE TITLE
Provide apcu_* functions

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#6784]
apcu_\* are the new names for apc_\* functions in PHP 7
See https://github.com/krakjoe/apcu

**Comment by nazar-pc** [comment]
Wanted to implement myself, but it is all in C++ code.
Should be pretty straightforward though.

**Comment by fredemmott** [comment]
If this can be done by wrapping the existing ones, can be implemented in php easily - the php files with <<__Native>> in can also contain non-native functions.

**Comment by fadimko** [comment]
@fredemmott Since v5.1.0 (first version compatible with PHP7) `apcu_inc()` and `apcu_dec()` create non existing keys, and apc versions return error in that case. https://github.com/krakjoe/apcu/commit/5c9e477fa620f096debbd76adb860b0093166636

Does it mean that apcu extension should be written in c++?

**Comment by photodude** [comment]
I also think it would be nice to have APCU

**Comment by paladox** [comment]
+1 for this since apc is not supported in php 5.5+ but apcu is.

**Comment by paladox** [comment]
This problem is because hhvm only supports apc per https://github.com/facebook/hhvm/search?q=apc&type=Code&utf8=%E2%9C%93

**Comment by paulbiss** [comment]
Are these just alternate names for the apc functions? If there are notable differences could someone here outline them? It should be pretty easy to supply aliases for these names.

**Comment by paladox** [comment]
@paulbiss no, apc was removed in php 5.5 and apcu was then created.

**Comment by nazar-pc** [comment]
Maybe we could just invite @krakjoe to this discussion to outline the differences in behavior between `apc_*` and `apcu_*` functions (if there are any).

**Comment by paulbiss** [comment]
@paladox right, but the hhvm implementation of apc is completely distinct from the php implementations of both apc and apcu. What I'm getting at is, were there any API level changes besides `s/apc_/apcu_/` or was it just a new set of names and a shiny new implementation?

The hhvm implementation of apc is highly tuned for speed and memory efficiency, it's unlikely we would want to replace it wholesale, but if there are functions that need to be added or aliased that's something we can certainly do.

@nazar-pc good idea!

**Comment by paladox** [comment]
Oh, would we be able to add an apcu version? or at least add alias for apcu, so if users use apcu functions they would alias to apc, as apcu is just the same as apc just it works only on php 5.5+?

This would benefit Wikimedia's https://gerrit.wikimedia.org/r/#/c/299498/ since then we could possibly drop apc functions and go with apcu since we wont need backward compat for hhvm.

**Comment by paulbiss** [comment]
Yeah we could definitely do that! I'd like to hear from @krakjoe or someone else familiar with any potential behavioral differences, but adding aliases or new entry points with slightly modified behavior as appropriate is totally doable.

**Comment by paladox** [comment]
Oh, thankyou :), would you know when that can be done?

**Comment by photodude** [comment]
@paulbiss I am under the understanding that `APCu` is just the userdata component of the old `APC`, without the bytecode caching. 

For a full replacement of APC in PHP 5.5+ you need both `APCu` and `OpCache` which now the standard bytecode caching for PHP

So if we are aliasing the userdata component of `HHVM-APC` to `APCu` I think it makes sense to consider also aliasing the `HHVM-APC` bytecode caching to `OpCache` (although `OpCache` has more features than APC did so that may suggest a different course of action)

**Comment by nazar-pc** [comment]
@photodude, I believe you don't need opcache-related part of APC, since HHVM already uses JIT and works very differently internally. Only user data part is relevant here.

**Comment by paulbiss** [comment]
We don't actually do any OpCode caching in APC. HHVM has its own bytecode cache (stored to disk as an sqlite repo and persisted in memory during execution, persists between server restarts), as well as a translation cache (persists only in memory during process execution, persists between requests). There's also no way to turn it off, the VM will only execute bytecode from the cache and the frontend writes there first.

**Comment by photodude** [comment]
@nazar-pc @paulbiss Thanks for the clarification. 

I took a quick look and it seems APCu does have an additional method that APC does not have
[`apcu_entry`](http://php.net/manual/en/function.apcu-entry.php) — Atomically fetch or generate a cache entry

I didn't dig deeper into the other 22 methods in both APCu and APC to see if all the details of the methods match up.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hhvm has diverged from the apcu api and now has its own flavor of apc.
