### ISSUE TITLE
Proxygen route all request to one file

### ISSUE THREAD

**Issue by raeesiqbal** [facebook/hhvm#6812]
I was previously using nginx + hhvm but I've decided to remove nginx because its not needed anymore as static files will be served from a different domain.
So, there is one `Main.hh` to where all requests were routed previously, which is basically interface to all of app. I'm not sure how can this be achieved in Proxygen configuration. Route all requests to one file ignoring request uri.

**Comment by fredemmott** [comment]
This does the trick: https://github.com/hhvm/hhvm-docker/blob/master/hhvm-latest-proxygen/server.ini#L9-L10

**Comment by raeesiqbal** [comment]
thanks

**Comment by raeesbhatti** [comment]
This does not really solve my problem. `hhvm.server.default_document=index.php` just sets default document but does not force all requests to `index.php`.

**Comment by fredemmott** [comment]
You want `hhvm.server.error_document404 = index.php` too, and index.php should be the only thing in your web root. Then, `/foo` is a 404, so it loads index.php, effectively making everything go to XHP without having to use rewrite rules.

**Comment by raeesbhatti** [comment]
Yes, I figured that too. Are there no rewrite rules in Proxygen?

**Comment by fredemmott** [comment]
IIRC they're unsupported/deprecated, but yes there are: https://docs.hhvm.com/hhvm/configuration/INI-settings - not properly documented, but there are examples of them

**Comment by seyedip** [comment]
Proxygen should have a built-in feature to route all requests to a default_document.

The above solution (hack) is not a real solution. It's still possible to access files if you guess the path and also I think it's slower than a simple rewrite rule because it has to check if requested file exist before sending the request to error_document404.

And I think putting Nginx in front of Proxygen for a simple rewrite rule is an overkill.
