### ISSUE TITLE
preg_match with hex-chars fails

### ISSUE THREAD

**Issue by SebastianKleine** [facebook/hhvm#6817]
Hello,

the following regular expression fails in a preg_match (it works using php):

<?php
$result = preg_match('/^[a-z0-9\x{00EO}-\x{00F6}\x{00F8}-\x{00FF}\x{0153}\x2d]{1,63}$/iu', 'gmx');

echo (int)$result;

**Comment by Orvid** [comment]
That does work in PHP up until v5.5.10, when they [upgraded to PCRE 8.34](http://php.net/ChangeLog-5.php#5.5.10), however no version after that supports it.

That regex isn't valid to begin with because, as the error says, O is not a valid hex character. Earlier versions of PCRE were allowing this when they shouldn't have been.

https://3v4l.org/stgTH
