### ISSUE TITLE
better performance compare to php-fpm

### ISSUE THREAD

**Issue by fahimeh2010** [facebook/hhvm#6827]
Hello all

I am using hhvm in docker container and the web server is nginx in another container. before i was using php-fpm but now hhvm instead of it.
now when i use apache benchmark(ab) I see that the performance of php-fpm+ nginx is better than hhvm+nginx, how can I tune server.ini and php.ini to have a better performance?

thank you

**Comment by SiebelsTim** [comment]
Make sure to warm up the jit (i.e. making a few request before benchmarking).
HHVM should perform better on CPU heavy code. If you are mostly IO bound, you shouldn't see much gain without using hack features such as `async`.
Also hhvm probably performs worse when you have a lot of top level code, because that can't be optimized very well.

**Comment by fahimeh2010** [comment]
our code is cpu intensive. any other idea to change in server.ini or php.ini?

**Comment by Orvid** [comment]
Do you have any specifics of which parts of the code are slower under HHVM?

**Comment by aorenste** [comment]
This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
