### ISSUE TITLE
HHVM/PHP discrepancy of DateTime microseconds handling

### ISSUE THREAD

**Issue by mwjames** [facebook/hhvm#6899]
A discrepancy [0] is encountered between HHVM and PHP for:

```
<?php

$dateTime = new \DateTime( '1300-11-02 12:03:25.8884999' );
echo( $dateTime->format( 'Y-m-d H:i:s.u' ) );
```

Output for hhvm-3.6.1 - 3.12.0
1300-11-02 12:03:25.888499

Output for 5.5.0 - 7.0.4
1300-11-02 12:03:25.888500

https://3v4l.org/s3eRL

**Comment by fredemmott** [comment]
This looks like a PHP bug to me...

PHP: https://github.com/php/php-src/blob/master/ext/date/php_date.c#L1158
HHVM: https://github.com/facebook/hhvm/blob/51e3f4463f0651aea923711d2c459622787c95a4/hphp/runtime/base/datetime.cpp#L660

... I'm not sure why that +0.5 is there in PHP. @derickr , any thoughts?

**Comment by fredemmott** [comment]
Ah, floor(... + 0.5) is the same as standard rounding.

**Comment by derickr** [comment]
Yeah, this was added as a bug fix: https://bugs.php.net/bug.php?id=63435

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not buggy or broken. If hhvm always consistently acts as if the input is floored to the nearest microsecond, this is fine. Php rounds, but compatibility with PHP is a non goal since hhvm version 4.0. If hhvm is inconsistent, please open a new issue.
