### ISSUE TITLE
\PlainSprintf should be \HH\PlainSprintf

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6909]
### HHVM Version

3.13-dev (fb-latest)
### Standalone code, or other way to reproduce the problem

```
[fredemmott@devbig349.prn1 /tmp/out] cat root_plain_sprintf.php
<?hh

namespace RootPlainSprintF;

function my_format_func(
  \HH\FormatString<\PlainSprintf> $format_string,
  ...$args
): void {}
[fredemmott@devbig349.prn1 /tmp/out] cat hh_plain_sprintf.php
<?hh

namespace HHPlainSprintF;

function my_format_func(
  \HH\FormatString<\HH\PlainSprintf> $format_string,
  ...$args
): void {}
```
### Expected result
- no errors for hh_plain_sprintf.php
- unbound name \PlainSprintf for root_splain_sprintf.php
### Actual result

```
hh_plain_sprintf.php:6:20,35: Unbound name: HH\PlainSprintf (an object type) (Naming[2049])
```

**Comment by lexidor** [comment]
I suspect you made this issue with unmodified php projects in mind. Hhvm's internals should not create name collisions with php code. In a hack-only world, this is far less of a concern. Every hack app/library out there doesn't declare a type with this name.

If this issue is still worth fixing, please reopen this issue.
