### ISSUE TITLE
Typed variadics not supported in PHP code

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6954]
```
<?php

function test(int ...$numbers) {
    echo array_sum($numbers);
}

test(1, 2, 3);
```

```
Fatal error: Parameter $numbers is variadic and has a type constraint (int); variadic params with type constraints are not supported in non-Hack files in /tmp/hhtest/test.php on line 3
```

Currently not supported in PHP as Hack's enforcement is in the typechecker - we have no support for run-time enforcement, which is required to implement this feature for PHP.

**Comment by BenMorel** [comment]
@fredemmott Just to emphasize the importance of this issue, I wanted to react to [your comments](https://github.com/facebook/hhvm/issues/4858#issuecomment-164530444) on its parent issue:

>  we've not came across any real-world examples of people typing variadics in PHP code

I personally maintain a few projects where this is really useful. See for example:

- [LineString::__construct()](https://github.com/brick/geo/blob/master/src/LineString.php#L41)
- [LocalDateTime::minOf()](https://github.com/brick/date-time/blob/master/src/LocalDateTime.php#L137)

This avoids the burden of having to check for the type of each objet manually. I do not want to blindly accept any variable either, as if a bad object is given, I want it to fail early, instead of getting an error in an arbitrary piece of code later, that would be hard to debug.

> the runtime verification that PHP requires is very expensive

I just verified that this is not true. I created a quick [benchmark ](https://gist.github.com/BenMorel/7acd6f2c0ae11d3cce7208a330cff372) that you can use to check by yourself. On my laptop with PHP 7, I get the following results when calling 1000 times a function with 1000 arguments:

```
$ php variadics-benchmark.php 
Without type-hinting: 0.015783 s
With type-hinting: 0.017840 s
With manual type check: 0.074122 s
Type-hinting overhead: 13.0 %
Type-hinting improvement over manual check: 315.5 %
```

As you can see, it's still very fast even with **a lot** of arguments. The type-hinting overhead is just about `+13%` in CPU time (this drops to barely `+1%` with a more reasonable number of arguments). This is to be balanced with the cost of *manually* checking every argument: `+315%` compared to the type-hinted variadic!

So the performance is a non-issue in PHP 7, the variadics type checks actually **greatly improve performance** of code that requires a type check anyway.

And for those who want to get the most of every CPU cycle, they can just choose not to use type-hinted variadics. This is not a reason for not implementing it.

As [@jurchiks said](https://github.com/facebook/hhvm/issues/4858#issuecomment-167539723),

> If PHP 7 supports it, you have to support it eventually.

Which is true if I believe [@paulbiss](https://github.com/facebook/hhvm/issues/3651#issuecomment-58943704) on another issue:

> Yes, we'd like to be compatible going forward.

**Comment by fredemmott** [comment]
I basically agree, except for our definition of 'expensive'; even something most people would consider irrelevant can cost a huge amount of money at our scale. I'd guess support for this would have to be optional (on by default for compatibility), and generate different bytecode. By comparison, the Hack support has *no* runtime cost.

I especially agree on the importance of compatibility - however, I'm not directly working on HHVM any more, so don't have much time to push for this.

**Comment by raeesiqbal** [comment]
Bump... Any ideas on when will this be fixed. Or any workaround for this?

**Comment by stof** [comment]
To be clear, this is also a PHP 5.6 incompatibility if you change the typehint to ``array`` instead. See https://3v4l.org/m5gdA

**Comment by photodude** [comment]
Just like @stof I'm also seeing this with php 5 mode on 3.15.2 with type constraint (array)
```php
Fatal error: Parameter $argv is variadic and has a type constraint (array); variadic params with type constraints are not supported in non-Hack files in /doctrine/dbal/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(345)(c26a62d6b8349ddbaa7782b3f4afa3ef) : eval()'d code on line 255
```
@fredemmott @aorenste Please add the php5 incompatibility label

**Comment by photodude** [comment]
@aorenste thanks for adding the php5 incompatibility label, I look forward to this issue being resolved.

**Comment by photodude** [comment]
Another issue on php 5 mode on 3.15.3 with type constraint (callable)
```php
Fatal error: Parameter $callbacks is variadic and has a type constraint (callable); variadic params with type constraints are not supported in non-Hack files in /lstrojny/functional-php/src/Functional/Partition.php on line 41
```

**Comment by NinoSkopac** [comment]
I'm [also using this feature](https://github.com/read2me-online/itunes-podcast-feed-php/blob/f1d76d63d779921263a65c52441c5239b6d604b1/src/FeedGenerator.php#L32) and [it is making my HHVM tests fail](https://travis-ci.org/read2me-online/itunes-podcast-feed-php/jobs/373801788).

**Comment by cgogolin** [comment]
I ran into the same problem. This makes phpunit-6.5.2 and HHVM incompatible, as far as I can see.

**Comment by Danon** [comment]
As @cgogolin said, lack of support for `...$variadic` makes PhpUnit 6.4+ tests fail and thus fail all hhvm builds.

Is there any way to make it work, except from rewriting all tests to another framework?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
