### ISSUE TITLE
Syntax check of php files is very slow with hhvm compared to php

### ISSUE THREAD

**Issue by swehner** [facebook/hhvm#6979]
### HHVM Version

3.12.1
### Standalone code, or other way to reproduce the problem

Running syntax check on php files is very slow compared to regular PHP (even a totally empty file as in this case).
$touch x.php
$time hhvm -l x.php 
real    0m0.178s
$time php -l x.php
real    0m0.008s

php -l only supports syntax checks on one file at the same time, so there's no way to amortize the higher startup time.
Maybe allowing to check several files at the same time would ease this problem.

**Comment by dpaneda** [comment]
+1, The start penalty of HHVM is a problem to completely replace PHP. I also found this problem with some kind of PHP unit tests executors which spawn a new process to isolate the tests, but any kind of short live scripts will be affected by this problem.

**Comment by fredemmott** [comment]
@dpaneda : for quick things, you can try running with `-d hhvm.jit=0` ; this is a large reduction in startup costs, but reduces performance significantly. IME for scripts, the break-even point tends to be ~ 1 minute of runtime.

**Comment by dpaneda** [comment]
For the unit test we are already using that setting. It is indeed significantly faster running it that way. Startup cost doesn't seem really affected, though.

It was a surprise for me that even with the jit disabled, the `.hhvm.hhbc` file was still created and populated, and you need to set `hhvm.repo.commit = false`.

Is not really related but it would be nice to know why the hhbc file grow beyond control, even without code changes, and it seems that having it populated doesn't improve performance. ¿What is the purpose of this file then? ¿Shouldn't be the repo.commit disabled by default?

**Comment by Orvid** [comment]
The .hhvm.hhbc is for the systemlib in HHVM itself, it does not contain any user code. Disabling it is not a good idea. In an end-user scenario (ie. one where you aren't repeatedly building and testing HHVM itself) it should never grow after it is initially created.

**Comment by 626Pilot** [comment]
hhvm appears to run scripts twice as slow as php. The -d hhvm.jit=0 saved one tenth of a second, which is not particularly useful.

Regular PHP:
```
$ time php -q ./KISSCoast.php --coast=4 --primePillarCoast=8 --file="cube4_a cube4_b.gcode" 

real    0m6.255s
user    0m6.167s
sys     0m0.036s
```

HHVM with and without the -d flag:
```
$ time hhvm -d hhvm.jit=0 ./KISSCoast.php --coast=4 --primePillarCoast=8 --file="cube4_a cube4_b.gcode" 

real    0m13.794s
user    0m13.672s
sys     0m0.060s
```
```
$ time hhvm ./KISSCoast.php --coast=4 --primePillarCoast=8 --file="cube4_a cube4_b.gcode" 

real    0m13.812s
user    0m13.665s
sys     0m0.084s
```

**Comment by 626Pilot** [comment]
Here's a test where I have my script process a much larger file. hhvm STILL takes close to TWICE as long. This doesn't seem right!

In case it helps, this program is doing tons of string processing. The code is available in one of my repos on GitHub.
```
time php -q ./KISSCoast.php --coast=4 --primePillarCoast=8 --file="626 Effector.gcode" 

real    13m9.688s
user    13m7.795s
sys     0m0.723s
```
```
time hhvm ./KISSCoast.php --coast=4 --primePillarCoast=8 --file="626 Effector.gcode" 

real    25m4.791s
user    24m51.422s
sys     0m11.259s
```

**Comment by dpaneda** [comment]
@Orvid Maybe there is some bug because that affirmation does not seem correct to me. I've seen hhbc grow over 30G. Also. check this out:

Starting with an empty hhbc file, I run some unit test...

```
sqlite> .tables
FileMd5_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8       
Func_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8          
GlobalData_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8    
Litstr_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8        
PreClass_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8      
UnitArray_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8     
UnitLineTable_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8 
UnitLitstr_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8    
UnitMergeables_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8
UnitSourceLoc_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8 
Unit_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8          
magic_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8         
writable_f2e5f39b2ad4a08bcbd90b5d8bcb580f40fba6c8      
$ ls -lh ~/.hhvm.hhbc
-rw-r--r-- 1 dpaneda dpaneda 57M Apr 15 10:41 /home/dpaneda/.hhvm.hhbc
```

The contents of the file clearly contains information about my code. Now I run the same code again (no changes).

```
$ ls -lh ~/.hhvm.hhbc
-rw-r--r-- 1 dpaneda dpaneda 88M Apr 15 10:47 /home/dpaneda/.hhvm.hhbc
```

The file is now larger. On jenkins, this file was growing about 500m on each CI run, which was not acceptable for us. On live, we run on repo authoritative mode, so this is not an issue.

**Comment by Orvid** [comment]
HHVM takes longer to parse and compile the code, and also spends time profiling the code. If you're only ever executing the code once during the lifetime of HHVM, it's going to be slow because HHVM doesn't have the opportunity to compile an optimized version of it.

Unless you've explicitly set the Auth-mode repo to be the same file, and are building it each time, it shouldn't grow. Which version of HHVM are you testing with?

**Comment by dpaneda** [comment]
I'm using the last LTS (3.12.1), but the behavior was the same con 3.9 version. I'm not changing the default value for the auth-mode repo file, or any other config which seems relevant for this. This is my config:

```
session.save_handler = files
session.save_path = /var/lib/php5
session.gc_maxlifetime = 1440

hhvm.log.level = Info
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false

hhvm.enable_zend_compat = true

hhvm.jit = false
hhvm.error_handling.call_user_handler_on_fatals = true
include_path = /usr/share/php/
hhvm.error_handling.assert_active = true
hhvm.error_handling.assert_warning = true
date.timezone = Europe/Berlin
hhvm.resource_limit.serialization_size_limit = 5485760
mbstring.substitute_character=none
```

**Comment by Orvid** [comment]
As this is a separate issue from the main one, could you open a new issue for it? That repo file should not be growing in the normal use-case, if it is then there's something wrong.

**Comment by dpaneda** [comment]
Sure! I will create an example as isolated as possible and create another issue with this problem.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Syntax checking (and running) PHP files is no longer supported since [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html) and the typechecker syntax checks Hack files. The typechecker validates all the files in your codebase at once. For checking a handful of files `-l` will still be faster than the typechecker, but for checking whole codebases `hh_client` is the better tool.
