### ISSUE TITLE
It is not resolved hh_client error by using empty function

### ISSUE THREAD

**Issue by endam** [facebook/hhvm#7004]
e.g. code first.

```
<?hh
    function sample() : void
    {
        $test = null;
        if (!empty($test)) {
            $test["a"] = 1;
        }
    }
```

Though array valuable is checked by `empty` method whether null or not ,hh_client error come up as below.

```
You are trying to access an element of this container but the container could be null. : 
This is what makes me believe it can be null: 
```

This error is resolved by using  `is_null` or  `isset` method instead of `empty` method.
But is it correct to occur error?

**Comment by Orvid** [comment]
The typechecker is correct in this case, because `empty` isn't doing what you think it is. For instance,
```
$test = true;
var_dump(empty($test));
```
Outputs `bool(false)`.

**Comment by hiromaily** [comment]
What do you mean?
Though I tried that to make sure, it seems to not work well.
Because empty function has feature to check not only if variable is empty but isset function as well.

Here is document about empty.
http://php.net/manual/en/function.empty.php

According to that explanation,
```
No warning is generated if the variable does not exist. That means empty() is essentially the concise equivalent to !isset($var) || $var == false.
```
No offense, what's more, I couldn't get it what your example show.

I think empty() function has multiple features as official document.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`empty()` has been removed from the runtime in hhvm version [4.7.0](https://hhvm.com/blog/2019/05/28/hhvm-4.7.0.html), use `$test is KeyedContainer<_, _>` instead.
