### ISSUE TITLE
HHVM php5 incompatibilities in fastcgi to numerous to use in production environment

### ISSUE THREAD

**Issue by belldandu** [facebook/hhvm#7009]
This issue is reiterating this issue https://github.com/facebook/hhvm/issues/6996

All information needed to reproduce this issue is in that issue.

I understand that facebook doesn't use fastcgi however with the number of incompatibilities with php5 that are so bad they break image uploading i'm suprised it even runs at all.

Well for now i am forced to switch back to php5 until this issue is actually fixed fully. As it seems there is more then one bug in hhvm thats causing php5 incompatibility and breaking piwigo. 

I really don't need these kinds of issues on my production server.

Also Please Note that I have also opened an issue over at Piwigo as well about these bugs.

https://github.com/Piwigo/Piwigo/issues/465

**Comment by Orvid** [comment]
If we don't know the specific issue, we can't fix it.

**Comment by kamijoutouma** [comment]
It always says 0kb as if it cant see the value and uploading is broken (probably because of this). I get no errors in the error log for hhvm or nginx. Piwigo has no errors in its debug log. I'm not really sure what to say.

If someone wants to Install hhvm in fastcgi mode and use it with nginx + install piwigo and test this than please do. However i can't keep my users waiting by allowing hhvm to interfere with my production environment.

**Comment by Orvid** [comment]
This issue has been waiting for more info for more than 2 weeks. Closing for now, feel free to re-open it if you can provide more info.

https://github.com/facebook/hhvm/wiki/Human-Timeouts
