### ISSUE TITLE
Hack: Allow casting to nullables

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#7013]
It'll be useful if Hack allowed casting to nullable types. This'll basically have `$foo = (?type)$expr` be syntactic sugar for `$var = $expr; $foo = ($var === null ? null : (type)$var);` without the need for a temporary variable. Other than the null check, all other rules of casting will be the same.

**Comment by jwatzman** [comment]
Either @sgolemon or @fredemmott (or both!) convinced me months ago this was a cool feature. Wish I'd had time to get around to it. Not sure what the allocation of Hack resources is nowadays. Maybe if I get time at a hackathon... :)

**Comment by luisaglez1** [comment]
Facebook Messenger is one of the most popular platforms for communication, making it important to understand how to monitor messages for personal or safety reasons. [hacking facebook](https://hackfreeonline.com/facebook/
) Whether you're keeping an eye on your child’s activity or ensuring your own privacy, here are some practical ways to responsibly monitor Facebook messages.

1. Use Built-in Facebook Tools
Facebook provides tools that can help you monitor your account activity. By accessing the “Security and Login” section under Settings, you can view where your[ account facebook](https://hackfreeonline.com/facebook/
) is logged in and track suspicious activity. This doesn’t directly show message content but can alert you to unauthorized access.

For parents, enabling parental controls or supervising their child’s Facebook account allows you to manage access. Ensure the account settings are appropriate for their age by limiting who can send friend requests or messages.

2. Check Archived and Hidden Messages
Sometimes, messages are archived or moved to hidden folders. To monitor effectively, go to Messenger, click on the "More" option, and select “Archived.” Review these conversations to ensure you haven’t missed any important communication. Also, check the "Message Requests" folder, as this is where messages from people who aren’t friends are stored.

3. Third-Party Tools and Apps
There are third-party tools available for monitoring Facebook messages, especially for parents or employers. Tools like mSpy or Bark allow supervised access to messages and notifications. These tools often require installation on the device and should always be used ethically and with consent when appropriate.

4. Two-Factor Authentication for Your Account
If your concern is about someone else accessing your Facebook messages, enabling two-factor authentication can help. This feature prevents unauthorized users from logging in, even if they have your password, by requiring an additional code sent to your phone.

5. Respect Privacy Laws and Ethics
It’s crucial to understand that monitoring someone else’s Facebook messages without their consent can be a violation of their privacy. Always consider the ethical and legal implications of your actions, and focus on fostering open communication instead of invasive monitoring.

6. Educate About Safety
For parents, educating children about online safety is more effective than constantly monitoring their messages. Teach them to avoid sharing personal information and to report suspicious activity.

By using these methods responsibly, you can effectively manage and protect communication on Facebook while respecting personal boundaries and privacy.
