### ISSUE TITLE
Identifying constrained type violations from method arguments?

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7042]
Consider:

``` PHP
<?hh // strict
class Base {}
class Derived extends Base {}
class A<T, TDerived as T> {
    public static function constrained(T $base, TDerived $derived): void {}
}
```

Annotations that require specifying A's generic types with the angle bracket syntax, like variable, parameter, inheritance and return declarations, allow the typechecker to identify violations like `class B extends A<Derived, Base> {}`. However, calls like `A::constrained(new Derived(), new Base())` did not spawn any errors even if they are in the same function, which came as a surprise to me. Of course, when the generic types are spread across multiple function signatures and variables, no violations are caught either.

C# is able to weasel this discrepancy out even when the types are inferred from generic methods:

``` C#
class Base {};
class Derived : Base {};
class A {
    public static void foo<T, TDerived>(T b, TDerived d) where TDerived : T {}
}
class B {
    public static void Main(string[] args) {
        A.foo(new Derived(), new Base());
    }
}
```

plus being able to be explicit about the concrete types for that instance of the generic class with the angle bracket syntax should make all violations of this nature impossible. Is there a Hack-ish way to get around this?

**Comment by dlreeves** [comment]
@andrewjkennedy may want to take a look at this

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This behavior may be really surprising, but it is actually correct.
The generic type for `T` in `A::constrained(new Derived(), new Base())` is not `Derived`.
The typechecker widens the type of T to `(Derived | Base)` which simplifies to `Base`.
`TDerived as Base` is correct, since the argument passed for `TDerived` is an instance of `Base`.

It does however get even hairier.
Because the typechecker is allowed to widen the type of the first argument as much as it wants, this would also be a valid inference `A::constrained(0, new Base())`.
Even through `int` obviously has no relation to base, the typechecker can widen `T` to be `(int | Base)`.

The confusion occurs because passing an argument of type X, does not mean that the type of that generic must also be exactly X.
It could be that you were trying to call `A::constrained` like this, `A::constrained<mixed, mixed>(0, new Base())`, which the typechecker shouldn't prevent you from doing.
The `T` and `TDerived` are (when you don't supply them yourself explicitly) unbounded, since they can always be widened to `mixed`.

If you want to write a function like that in a way that you are forced to do it right, you can add `<<__Explicit>>` to one or both of the generics.
Support for `<<__Explicit>>` was added in hhvm [4.19.0](https://hhvm.com/blog/2019/08/19/hhvm-4.19.0.html).
You also need to move the generics to the method, instead of the class level, since a generic on a class is associated with an instance of this class.
By placing the generics on the method, you associate them with the method instead, achieving your expected result.

```HACK
class A {
    public static function constrained<<<__Explicit>>T, <<__Explicit>>TDerived as T>(T $base, TDerived $derived): void {}
}
```

This generates the following typechecker error.
```
Typing[4347] Generic type parameter T must be specified explicitly
   --> src/file.hack
  3 |     A::constrained(0, new Base());
    |        ^^^^^^^^^^^
 10 |         <<__Explicit>> T,
    |                        ^ Definition is here

Typing[4347] Generic type parameter TDerived must be specified explicitly
   --> src/file.hack
  3 |     A::constrained(0, new Base());
    |        ^^^^^^^^^^^
 11 |         <<__Explicit>> TDerived as T,
    |                        ^^^^^^^^ Definition is here
```

Keep in mind that this does not prevent you from just calling `A::constrained<mixed, mixed>(0, new Base())`.
Picking good types for `T` and `TDerived` will be left as a responsibility to the programmer.
