### ISSUE TITLE
Returning Map<Tk, Tv> in KeyedIterable<Tk, +Tv> and "See #6853603"

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/hhvm#7072]
In `interfaces.hhi`, the 4120 error from the variance violation is expressly suppressed to allow `KeyedIterable<Tk, +Tv>` and many other similar interfaces to be covariant on their type parameter[s]:

``` hack
interface KeyedIterable<Tk, +Tv> {
  // snip
  /* HH_FIXME[4120]: While this violates our variance annotations, we are
   * returning a copy of the underlying collection, so it is actually safe
   * See #6853603. */
  /**
   * Returns a `Map` based on the keys and values of the current
   * `KeyedIterable`.
   *
   * @return - a `Map` that has the keys and associated values of the current
   *           `KeyedIterable`.
   */
  public function toMap(): Map<Tk, Tv>;
  // snip
}
```

What about returning a _copy_ of the underlying representation makes this type-safe? I was hoping to find out wherever and whatever "#6853603" is, but unfortunately haven't been able to decipher what that refers to.

Extending this a bit, if HH_FIXME[4120] were applied to `toImmMap()`, then `KeyedIterable` could be covariant on both `Tk` and `Tv`. Is there a particular reason why it's not? Slightly related to an [earlier issue](https://github.com/facebook/hhvm/issues/6962).

**Comment by jwatzman** [comment]
I believe `toImmMap` doesn't always return a copy; `toMap` returning a copy is what makes this safe. (The mutation of the underlying object by using `Tv` in a contravariant position is what breaks things IIRC -- my understanding here is a bit sketchy and I'm not the best person to explain.)

6853603 almost certainly refers to an FB-internal task number. I'll try to remember to look it up when I get back into the office tomorrow and summarize it here for you.

**Comment by jwatzman** [comment]
Internal task 6853603 is:

---
**Consider adding a __Const attribute to methods**

This would indicate that they don't modify the value (and therefore type) of the class members, which would allow them to use covariant types in otherwise invariant positions. In particular, this would allow us to properly type toMap, toVector, etc.

---

Probably isn't going to happen anytime soon (or at all), especially since it's been open for over a year with no movement, but that's the context.

**Comment by acrylic-origami** [comment]
If I've read the type signatures properly, `ConstIndexAccess::get(Tk $k) : Tv` and `ConstIndexAccess::at(Tk $k) : Tv` are the only reasons why ImmMap is invariant on `Tk`. Even if `toImmMap` doesn't return a copy, nothing should be able to modify it's type, right?

`__Const` sounds awesome! How would it be used to make `toMap` type-safe? I can't imagine this alone would suffice:

```hack
<__Const>
public function toMap() : Map<Tk, Tv>;
```

since not modifying class members has nothing to do with whether or not a copy is returned — i.e. I don't see how that would guarantee the new container couldn't modify those values in the future with its own non-`__Const` methods.

**Comment by jwatzman** [comment]
Yeah I'm not sure of the details of `__Const`, the above was just an idea someone was tossing around.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

In hhvm [4.29.0](https://hhvm.com/blog/2019/10/29/hhvm-4.29.html) the methods `toMap()` and friends were removed from the `Iterable<+Tk>` interface. The reason cited in the blogpost is that they were unsafe. _$c->toVector(), $c->toSet(), $c->toMap() have been removed from Hack collections; use new Vector($c) etc or Hack Arrays instead; this is because they are not type-safe, as variance checks were added for generics_

I believe this addresses this issue.
