### ISSUE TITLE
mysqli_real_connect() must be of type ?string, bool given

### ISSUE THREAD

**Issue by netroby** [facebook/hhvm#7078]
```
 Argument 5 to mysqli_real_connect() must be of type ?string, bool given
 Argument 4 to mysqli::real_connect() must be of type ?string, bool given
 Your PHP MySQL library version 5.6.24 differs from your MySQL server version 5.7.12. This may cause unpredictable behavior.
```

### HHVM Version

3.13.1
### Standalone code, or other way to reproduce the problem
Using hhvm to run phpmyadmin 4.6.1
### Expected result
no warning
### Actual result
error reporting mysqli_real_connect and

**Comment by Orvid** [comment]
PHP should not actually be allowing false as a valid alternative for false, and we don't. Null is what is documented as an allowed value, and is what should be getting used.

[These](https://github.com/phpmyadmin/phpmyadmin/blob/1132e53f285cd0aadf81b97223a30621a585a998/libraries/dbi/DBIMysqli.php#L184) lines are the issue, because they are passing `false` as a parameter that they've even explicitly documented themselves as accepting `string`.
