### ISSUE TITLE
GLOB_BRACE in glob() is not implemented

### ISSUE THREAD

**Issue by wjywbs** [facebook/hhvm#7093]
### Standalone code, or other way to reproduce the problem
```
touch composer.json
mkdir update
touch update/composer.json
<?php
var_dump(glob("{*composer.json,*/*composer.json}", GLOB_BRACE));
```
http://php.net/manual/en/function.glob.php

This bug blocks hhvm from running magento2: https://github.com/magento/magento2/issues/2191

https://github.com/magento/magento2/blob/develop/setup/config/application.config.php#L18
https://github.com/magento/magento2/blob/6ea7d2d85cded3fa0fbcf4e7aa0dcd4edbf568a6/lib/internal/Magento/Framework/Filesystem/Driver/File.php#L272

### Expected result
```
array(2) {
  [0]=>
  string(13) "composer.json"
  [1]=>
  string(20) "update/composer.json"
}
```
### Actual result
```
array(0) {
}
```

**Comment by apeabody** [comment]
I tested this with the master branch of HHVM and it returned the expected result.  Perhaps you can confirm what version of HHVM you are running and the OS as the underlying glob is provided by libc.

**Comment by Orvid** [comment]
I believe this might be because we currently have hard-coded values for `GLOB_*` rather than pointing them to the actual macros. (they had to be hard coded originally because they were in IDL, which doesn't have access to any C++ macros) I do have a diff up internally (D2870023) that switches ext_std to use the const registering macros, and also switches away from those hard-coded values in the process.
