### ISSUE TITLE
Coredump running composer with hhvm-nightly on Ubuntu 14.04

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#7104]
### HHVM Version

3.14.0-dev (rel) hhvm-nightly installed on 2016-05-25
### Standalone code, or other way to reproduce the problem

Standard composer phar installed from get-composer
$ cat composer.json
{ "name": "test/test" }
$ hhvm /usr/local/bin/composer install
### Expected result

Composer runs, finds nothing to install, exists
### Actual result

Segmentation Fault

```
#0  0x000000000355dcec in HPHP::jit::FixupMap::fixupWork(HPHP::ExecutionContext*, HPHP::ActRec*) const ()
#1  0x000000000355dc9b in HPHP::jit::MCGenerator::syncWork() ()
#2  0x00000000035d3199 in HPHP::createBacktrace(HPHP::BacktraceArgs const&) ()
#3  0x0000000002821a39 in HPHP::debug_string_backtrace(bool, bool, long) ()
#4  0x00000000015aa3e7 in HPHP::bt_handler(int) ()
#5  <signal handler called>
#6  0x00000000035428ac in HPHP::StringData::release() ()
#7  0x00000000048002e3 in ?? ()
#8  0x00007fe40437ef60 in ?? ()
#9  0x0000000000000034 in ?? ()
#10 0x00000000048003bf in ?? ()
#11 0x000000000844dde0 in ?? ()
#12 0x000000000480004f in ?? ()
#13 0x00007fe4124e8110 in ?? ()
#14 0x00007ffde95fcfd0 in ?? ()
#15 0x00000000023ea00b in HPHP::jit::x64::enterTCImpl(unsigned char*, HPHP::ActRec*) ()
```

**Comment by Orvid** [comment]
Humm... Which OS/GCC version? I just tried trunk on Debian 8 (after fixing an issue with the build that has apparently been there since the conversion from IDL...) and it worked fine.

**Comment by sgolemon** [comment]
OS is Ubuntu 14.04 (per the issue title).
gcc version is whatever is on the Mac build VM near your desk.  gcc 4.8.something iirc.

**Comment by Orvid** [comment]
Well, I got it reproducing... Now to figure out why...

**Comment by Orvid** [comment]
:((((((( It isn't reproducing in a debug build :(((((

**Comment by Orvid** [comment]
I have it reproducing consistently and am working to identify the exact cause.

**Comment by nazar-pc** [comment]
Ubuntu 15.10 build works fine on Ubuntu 16.10 (so 15.10 and 16.04 should be also good I think), thus this is something specific to older Ubuntu versions

**Comment by t8erjoe** [comment]
so what now

**Comment by t8erjoe** [comment]
lets see what can happen

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

[4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html)
_HHVM is no longer able to execute Composer; Composer 1.8.4 includes support for identifying the HHVM version when executing via PHP, which is how we currently recommend installing dependencies for Hack projects._
