### ISSUE TITLE
Slow string operations in tight loops (ucwords, strtoupper, strtolower)

### ISSUE THREAD

**Issue by daxtens** [facebook/hhvm#7133]
Calling built in string operations such as `ucwords`, `strto(upper|lower)` and friends are incredibly slow in tight loops.

### HHVM Version
```
HipHop VM 3.14.0-dev (rel)
Compiler: heads/master-0-g6566f01044cda3bec18ac2c4cc8f1d54e7363f34
Repo schema: 1cd15dba5ef1cae0e98620603280c5eedc5e6a37
```
#### PHP 5 version
```
PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```
#### PHP 7 version
```
PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

### Standalone code, or other way to reproduce the problem

```
<?php
function ouch($count = 900000) {
        $time_start = microtime(true);
        $string = str_repeat("the quick brown fox jumps over the lazy dog", 100);
        for ($i=0; $i < $count; $i++) {
                $r = ucwords($string);
        }
        return number_format(microtime(true) - $time_start, 3);
}

for ($i=0; $i<2; $i++) {
        print("Time taken (run $i): " . ouch() . "\n");
}

```

### Expected result

HHVM runs no slower than php5.

### Actual result

HHVM runs several times slower than php5.

#### PHP 5

```
Time taken (run 0): 17.947
Time taken (run 1): 15.178
```

#### HHVM

```
hhvm/hhvm -vEval.Jit=true ~/hhvm.php 
Time taken (run 0): 56.302
Time taken (run 1): 55.826
```

#### PHP 7
````
php ~/hhvm.php 
Time taken (run 0): 18.485
Time taken (run 1): 16.711
````

**Comment by jwatzman** [comment]
Do you have an example of real-world code with a performance issue that you traced to this root cause? HHVM historically doesn't do well on microbenchmarks vs PHP5 and PHP7, but microbenchmarks like this are not representative of real-world code in most cases (most webapps don't do things like this in a tight loop).

**Comment by daxtens** [comment]
Fair enough. (FWIW, I run a set of microbenchmarks that are quite a bit
broader than this, and in those HHVM beats both 5 and 7 for everything
except string ops.)

In my macro-benchmark, HHVM loses out to PHP7 reasonably narrowly: I will
trace through it and see if this is the root cause or if something else is
to blame.

Feel free to close this - if I can root cause real workload slowness to
this I can open a new bug with more info.

**Comment by wjywbs** [comment]
ucwords in hhvm is O(n^2) using `delimiters.find()`, and 30% of the time is spent in `memchr`. php uses a mask which is O(n). This is similar to #6014. Slower builtin functions are my main suspect for hhvm losing to php7.

https://github.com/facebook/hhvm/blob/2f8fc6fc997c922c87863d74fe696939e6d2feca/hphp/runtime/ext/string/ext_string.cpp#L430
https://github.com/php/php-src/blob/23790b1e91fb0322d6248531455942546250934a/ext/standard/string.c#L2869

**Comment by wjywbs** [comment]
strtoupper in php is much simpler:

```
       │    0000000000000000 <php_strtoupper>:
       │      push   %rbp
       │      mov    %rdi,%rbp
       │      push   %rbx
  0.09 │      lea    (%rdi,%rsi,1),%rbx
       │      sub    $0x8,%rsp
       │      cmp    %rbx,%rdi
       │    ↓ jae    37
       │    → callq  __ctype_toupper_loc@plt
       │      mov    %rbp,%rdx
       │      nop
       │20:   movzbl (%rdx),%r8d
 16.70 │      mov    (%rax),%rcx
  0.27 │      add    $0x1,%rdx
 33.04 │      mov    (%rcx,%r8,4),%ecx
 16.96 │      mov    %cl,-0x1(%rdx)
 32.86 │      cmp    %rbx,%rdx
       │    ↑ jne    20
       │37:   add    $0x8,%rsp
  0.09 │      mov    %rbp,%rax
       │      pop    %rbx
       │      pop    %rbp
       │    ← retq

```

hhvm's strtoupper is longer and calls libc's toupper
```
       │    0000000000000000 <HPHP::f_strtoupper(HPHP::String const&)>:
......
       │      nop
  0.38 │58:   movsbl (%rbx),%edi
       │      add    $0x1,%rbx
       │      add    $0x1,%r12
 48.62 │    → callq  toupper@plt
  0.09 │      mov    %al,-0x1(%r12)
 50.62 │      cmp    %r13,%rbx
       │    ↑ jne    58
......
```

```
       │    0000000000000000 <toupper>:
 13.10 │      lea    0x80(%rdi),%edx
       │      movslq %edi,%rax
       │      cmp    $0x17f,%edx
       │    ↓ ja     2a
       │      mov    _IO_file_jumps+0x720,%rdx
 12.36 │      mov    %fs:(%rdx),%rdx
  0.02 │      mov    (%rdx),%rdx
  0.23 │      mov    0x48(%rdx),%rdx
 13.31 │      mov    0x200(%rdx,%rax,4),%eax
 60.98 │2a:   repz   retq
```

@daxtens What other string operations are slow?

**Comment by daxtens** [comment]
Hmm - I'm struggling to read the x86 asm, sorry - I'm more of a ppc person :/ 

Slow string ops include: ucwords, strto(upper|lower), 
addslashes is also slower, but not as dramatically (2x rather than 6x slower).
strrev is about the same speed on php7 as hhvm.

It looks like both HHVM and PHP are calling out to toupper/tolower (at least in PHP7: https://github.com/php/php-src/blob/23790b1e91fb0322d6248531455942546250934a/ext/standard/string.c#L1503), so it isn't that PHP is doing some sort of unicode-unsafe bit flipping.

**Comment by daxtens** [comment]
Other slow functions:

- bin2hex (to be fair, I really don't care how fast this function goes)

Much faster than php:

- htmlentities
- str_shuffle

Roughly same speed as php:

- wordwrap
- quoted_printable_encode

**Comment by jwatzman** [comment]
I looked into `strtoupper`/`strtolower` a bit and what's going on there.

[PHP7 directly calls `toupper`](https://github.com/php/php-src/blob/adc95c511495f00cd1a90feff5fff7968e38fc4a/ext/standard/string.c#L1415-L1462) in a loop on the underlying character buffer. [glibc contains an optimisation for direct calls like that](http://osxr.org:8080/glibc/source/ctype/ctype.h?v=glibc-2.14#0203) which cause them to be direct indexes into a table returned by `__ctype_toupper_loc`. This table is constant for the thread and GCC is smart enough to lift the call to `__ctype_toupper_loc` out of the loop, so the assembly is just one call to that function followed by repeated subscript lookups into the table in the loop, avoiding repeated function calls in the loop.

[HHVM implements these functions by passing a function pointer into a generic looping construct](https://reviews.facebook.net/diffusion/HHVM/browse/master/hphp/runtime/ext/string/ext_string.cpp;00aa638773bc88f184e1591b3a78409362107de2$397-405). This means the compiler has to generate a call to `toupper`/`tolower` for each character. Even if enough gets inlined so that the compiler can see the call to the function directly (I did this manually but upon further inspection our compiler directives might force the compiler to do this anyway), the above optimisation still doesn't work. For some reason it's disabled in C++ code!

So I came up with this super disgusting patch (for `strtoupper` but the same approach would work for `strtolower`):

```
diff --git a/fbcode/hphp/runtime/ext/string/ext_string.cpp b/fbcode/hphp/runtime/ext/string/ext_string.cpp
--- a/fbcode/hphp/runtime/ext/string/ext_string.cpp
+++ b/fbcode/hphp/runtime/ext/string/ext_string.cpp
@@ -401,7 +401,27 @@
 
 String HHVM_FUNCTION(strtoupper,
                      const String& str) {
-  return stringForEachFast(str, toupper);
+  if (str.empty()) {
+    return str;
+  }
+
+  uint32_t len = str.size();
+  String ret = String(len, ReserveString);
+
+  auto srcSlice = str.slice();
+
+  const char* src = srcSlice.begin();
+  const char* end = srcSlice.end();
+
+  char* dst = ret.mutableData();
+
+  const int32_t **evil = __ctype_toupper_loc();
+  for (; src != end; ++src, ++dst) {
+    *dst = (*evil)[(int32_t)(*src)];
+  }
+
+  ret.setSize(len);
+  return ret;
 }
 
 template <class OpTo, class OpIs> ALWAYS_INLINE
```

This relies on unportable and undocumented glibc functions and behaviour and is generally evil and disgusting. But it does help: it seems to drop HHVM's time take on a hot loop around `strtoupper` to a hair faster than PHP7's behaviour. This seems to matter even for fairly short strings -- I'd expect the extra call overhead to matter only for long strings, but that isn't true.

@daxtens, the patch above is nasty enough I'm reluctant to even propose it for review. I know this helps a microbenchmark, but have you tracked down any real-world perf issues to `strtoupper`/`strtolower`? That would help me make the case for its inclusion.

@paulbiss, @wjywbs, do you have any thoughts here, or any deeper understanding of this issue than I have that might convince GCC to emit the faster lookups without resorting to undocumented functions? Do you have any idea why this define might have been turned off for C++ code in the first place? (I'd expect it to be for good reason, and blindly re-doing that is also worrisome.)

Here is the test script I've been using:

```php
<?php

function doit() {
  $s = 'The quick brown fox jumps over the lazy dog.';

  $start = microtime(true);
  for ($i = 0; $i < 10000000; $i++) {
    $s2 = strtoupper($s);
  }
  $end = microtime(true);
  echo 'Done: '.number_format($end-$start, 3)."\n";
}

doit();
doit();
doit();
```

In my very unscientific testing testing on a machine which is notoriously bad for benchmarking, PHP7 seems to take about 1.1-1.2 seconds for each run; this patch improves HHVM from about 2.1 seconds down to just over 1.0 seconds.

**Comment by jwatzman** [comment]
Smaller patch:

```
diff --git a/fbcode/hphp/runtime/ext/string/ext_string.cpp b/fbcode/hphp/runtime/ext/string/ext_string.cpp
--- a/fbcode/hphp/runtime/ext/string/ext_string.cpp
+++ b/fbcode/hphp/runtime/ext/string/ext_string.cpp
@@ -396,12 +396,24 @@
 
 String HHVM_FUNCTION(strtolower,
                      const String& str) {
-  return stringForEachFast(str, tolower);
+#ifdef __GLIBC__
+  const int32_t **table = __ctype_tolower_loc();
+  auto tolower_fast = [table](int c) { return (*table)[(int32_t)c]; };
+#else
+  auto tolower_fast = tolower;
+#endif
+  return stringForEachFast(str, tolower_fast);
 }
 
 String HHVM_FUNCTION(strtoupper,
                      const String& str) {
-  return stringForEachFast(str, toupper);
+#ifdef __GLIBC__
+  const int32_t **table = __ctype_toupper_loc();
+  auto toupper_fast = [table](int c) { return (*table)[(int32_t)c]; };
+#else
+  auto toupper_fast = toupper;
+#endif
+  return stringForEachFast(str, toupper_fast);
 }
 
 template <class OpTo, class OpIs> ALWAYS_INLINE
```

**Comment by markw65** [comment]
It looks like we could get the same result by defining __USE_EXTERN_INLINES at compile time (either specifically at the top of ext_string.cpp, or as part of the build rules for every file), which seems a lot cleaner/safer.

**Comment by jwatzman** [comment]
Thankfully @wjywbs was absolutely right about `ucwords` and a simple `std::bitset` helps with it. Internal diff D3522296 up for that.

@markw65 oh good call, I was so focused on the macro I missed that. Let me see how that macro is supposed to get defined and why it isn't in our case.

**Comment by markw65** [comment]
Its even easier. If you include ctype.h, it gets inlined properly (https://godbolt.org/g/eoBHky). If you include <cctype> it doesn't (https://godbolt.org/g/d7YDte). So this was actually broken by various rewrites to use the "proper" c++ functions...

**Comment by jwatzman** [comment]
@markw65 Huh, I wonder why `<cctype>` doesn't have the same optimisations. In any event, using `<ctype.h>` does indeed fix it. D3522442 is up internally to do just that. Thanks for the pointers!

**Comment by daxtens** [comment]
Amazing work @jwatzman. I haven't been looking very hard for a real-world case because I got sucked in to powerpc code-gen (https://github.com/PPC64/hhvm/pull/143#issuecomment-230775203) but I will try @markw65's approach and see if that makes a difference in my testing.

**Comment by jwatzman** [comment]
I have fixes landing into HHVM master for these issues now (though the OSS push is blocked and so it might be a bit before you can see them).

**Comment by jwatzman** [comment]
The fixes for `strtoupper`, `strtolower`, and `ucwords` are in master. Although they do help microbenchmarks, they unfortunately don't seem to materially affect the drupal7 and wordpress targets in the oss-performance repo runs that I did locally. Oh well, still a fun hackathon project to fix this :)

**Comment by daxtens** [comment]
Looks good to me - my x86 jobs haven't been running for long enough to see if it makes a real difference to my MediaWiki or WordPress benchmarks, but it looks good.

Interestingly, the effect on PPC is huuuuuge:

Old hhvm:
```
Run 0
-----
strtoupper: 19.630
strtolower: 18.830
Run 1
-----
strtoupper: 19.623
strtolower: 18.826
```

New HHVM:
```
Run 0
-----
strtoupper: 3.331
strtolower: 3.321
Run 1
-----
strtoupper: 3.318
strtolower: 3.338
```

PHP7:
```
Run 0
-----
strtoupper: 3.224
strtolower: 3.232
Run 1
-----
strtoupper: 3.229
strtolower: 3.232
```

(I haven't run the macrobenchmarks on ppc64 yet.)

Thanks!

**Comment by wjywbs** [comment]
For `std::bitset`, I would use [`string_charmask`](https://github.com/facebook/hhvm/blob/36515cdf50086b580871da1b03c9aefe20110ab0/hphp/runtime/ext/string/ext_string.cpp#L116) because it has special processing for masks like 'a..z', and ucwords in php-src also uses [php_charmask](https://github.com/php/php-src/blob/23790b1e91fb0322d6248531455942546250934a/ext/standard/string.c#L2893).
