### ISSUE TITLE
Shapes::idx incorrectly dropping nullable

### ISSUE THREAD

**Issue by simonwelsh** [facebook/hhvm#7148]
### HHVM Version

3.13.2
### Standalone code, or other way to reproduce the problem

``` hack
<?hh // strict

type Foo = shape('foo' => ?int);

function a(Foo $in): string {
  return b(Shapes::idx($in, 'foo', 7));
}

function b(int $val): string {
  return chr($val);
}

function c(): string {
  return a(shape('foo' => null));
}

/* HH_FIXME[1002] */
c();
```
### Expected result

`hh_client` should complain the value being passed to `b` is a nullable.
### Actual result

```
root@4:~/test# hh_client
No errors!
root@4:~/test# hhvm test.php 

Catchable fatal error: Argument 1 passed to b() must be an instance of int, null given in /root/test/test.php on line 11
```

This is something we've actually run into, with `Shapes::idx` being used to get an optional value, but still returning `null` since an optional field can have `null` as a valid value.

**Comment by simonwelsh** [comment]
May need to figure out a way to have shape fields be optional without nullable.

The array version of this works as expected:
```hack
<?hh // strict

type Foo = array<string, ?int>;

function a(Foo $in): string {
  return b(idx($in, 'foo', 7));
}

function b(int $val): string {
  return chr($val);
}

function c(): string {
  return a(array('foo' => null));
}

/* HH_FIXME[1002] */
c();
```
```
$ hh_client
test.php:6:12,29: Invalid argument (Typing[4110])
  test.php:9:12,14: This is an int
  test.php:3:26,29: It is incompatible with a nullable type
```

**Comment by jwatzman** [comment]
Hey @dlreeves and @dabek -- this looks like a real hole in the shapes stdlib, figured you'd want to take a look.

**Comment by dlreeves** [comment]
@simonwelsh - Thanks for reporting. I believe the underlying issue is there isn't a way of expressing a shape field that is nullable, but not optional. I've seen enough issues/confusion with this that I believe we should no longer conflate the two concepts.

For this case I believe the `??` operator would be better than using `Shape::idx`. The function was added before the `??` operator was added to the language and at least in this case would be the thing I suggest to use.

Definitely  a larger problem we should look into though.

**Comment by simonwelsh** [comment]
Looks like the type checker now complains about this
