### ISSUE TITLE
PHP 7 incompatibility: Calling functions from XSLT

### ISSUE THREAD

**Issue by tslettebo** [facebook/hhvm#7167]
[Test.zip](https://github.com/facebook/hhvm/files/320294/Test.zip)

Hi.

We're using HHVM 3.13.1, running in PHP mode, using hhvm.php7.all = true, and during our transition to HHVM, the code needs to be compatible with both PHP 7 and HHVM.

When using strict_types=1, the attached example code runs fine on PHP 7 and displays "Result= 1 234", but on HHVM it gives an error message:

Catchable fatal error: Argument 2 passed to number_format() must be an instance of int, float given

The reason for this is that XSLT doesn't support the integer type, only float.

It may be argued that HHVM does the right thing, reporting this as an error when running in strict mode, but it creates a problem as there's no way we can make the XSLT call PHP with an int type.

One possible workaround could be to call  a user-defined function which forwards to the library function, but that creates an extra indirection.

Given that PHP 7 gives no errors for this case, maybe consider changing HHVM accordingly, at least when running in PHP 7 mode?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

There is a difference between PHP's `float` and Hack's `float`.
[PHP docs for strict mode](https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict):
_It is possible to enable strict mode on a per-file basis. In strict mode, only a variable of exact type of the type declaration will be accepted, or a TypeError will be thrown. The only exception to this rule is that an integer may be given to a function expecting a float._

Hack intentionally doesn't model this behavior.
