### ISSUE TITLE
Uncaught exception: /etc/hhvm/extensions/pgsql.so was built for HHVM 3.14, and cannot be loaded with HHVM 3.15

### ISSUE THREAD

**Issue by donutloop** [facebook/hhvm#7215]
HipHop VM 3.15.0-dev (rel)
Compiler: heads/master-0-g00aa638773bc88f184e1591b3a78409362107de2
Repo schema: 59d9a08878e63351dbe86248b2032b04a41d6282

Hey, i cannot any more load the postgres extension ( https://github.com/PocketRent/hhvm-pgsql )

Uncaught exception: /etc/hhvm/extensions/pgsql.so was built for HHVM 3.14, and cannot be loaded with HHVM 3.15

Best regards,

Marcel

**Comment by jwatzman** [comment]
The exception says it all:

> Uncaught exception: /etc/hhvm/extensions/pgsql.so was built for HHVM 3.14, and cannot be loaded with HHVM 3.15

You can't use extensions with different versions of HHVM. You'll need to either rebuild the extension yourself, talk with whoever built the binary of the extension, or otherwise update it yourself if it doesn't compile. The core team doesn't maintain external extensions (though I think this one may move into core at some point).
