### ISSUE TITLE
General slow down comparing to previous versions

### ISSUE THREAD

**Issue by schien-dong** [facebook/hhvm#7236]
### HHVM Version
3.14.12 (rel)
### Standalone code, or other way to reproduce the problem

<?php

function fib($n)
{
    if ($n <= 2)
        return 1;
    else
        return fib($n-1) + fib($n-2);
}

$n = 36;
$a=microtime(1);
fib($n, 2);
$b=microtime(1);
echo 'Fib36:'.sprintf('%.3f',($b-$a)*1000);

### Expected result
Previous versions, (e.g. 3.7.2) computed the 36th digit in about 300ms. The same hardware, same configuration (after upgrade) took over a second to run. JIT Interop warmup is set to 3.

Here's how I start HHVM:

/usr/bin/hhvm --mode daemon --user web -vServer.Type=fastcgi -vServer.Port=9000 -vServer.ExposeHPHP=false -vDebug.ServerErrorMessage=true -vEval.Jit=true -vEval.JitProfileInterpRequests=3

### Actual result
Took over a second to run. Initial run took 6 seconds. After JIT warm up it took 1.2 seconds. Why is this version so much slower?

**Comment by Orvid** [comment]
Ignoring the HHVM side of the issue for now (I'll address it further down), and working under the assumption that this is a function who's performance you care about,
```
<<__Memoize>>
function fib($n)
```
Is enough to put the performance in interpreter-only mode faster at 36-digits than PHP7 is at 15 digits. (0.085s on a random test on 3v4l.org, which only runs interp mode). In this particular case, setting `hhvm.hack.lang.ints_overflow_to_ints` to `true` should also give a performance boost, as the JIT compiled code won't have to account for the possibility of the subtractions underflowing or the addition overflowing.

As-far as why it would be getting slower, the answer is probably that, although you have warmed up the JIT in-that it has JIT-compiled the code, it's probably still running in profiling mode, which requires several thousand requests by default before it will generate the optimized version. Between 3.7.2 and now we've been progressively adding more profiling counters in various locations so that we can generate better optimized code based on the types of things that go through it.

**Comment by schien-dong** [comment]
Thank you for the insights. I have tried ints_overflow_to_ints without apparent gain. I'm benchmarking a PHP file, not Hack, if that makes a difference. For one, I can't memoize it. Is there a way to bypass the thousand profile requests? The testing script is simple; a static analysis (with type safety assumptions) wouldn't be too complex. I'm therefore puzzled why JIT would take that many iterations. There aren't many on the fly branching; also as the JIT "stalks" the execution, little variation would be observed. Thanks again for shedding light in this matter!

**Comment by Orvid** [comment]
The default configuration is tuned for a normal PHP website, which takes many different possible code paths across many different requests. A benchmark like this is the exact opposite of that. Running the code in repo-authoritative mode can also help. I believe there are some ini settings that you can change to adjust the number of profiling requests used before compiling the optimized translations, but I don't remember what they are off the top of my head.

Also, it's worth noting that in most cases, optimizing the algorithm makes much more of a difference than optimizing the code itself. In this case, it's possible to do the calculation in direct linear time:
```
function fib($n)
{
    $a = 1;
    $b = 1;
    for ($i = 2; $i < $n; $i++) {
        $c = $a + $b;
        $a = $b;
        $b = $c;
    }
    return $b;
}
```
Which PHP7 manages an `$n` of 36 in 0.007 seconds. HHVM can also optimize this version significantly better than it can the original, because it has the whole context.
