### ISSUE TITLE
unserialize() should require semicolon after 's:' string value

### ISSUE THREAD

**Issue by plstand** [facebook/hhvm#7255]
The PHP bug that allowed the byte after the closing double quote in an 's:' string value to be anything, not just a semicolon, was fixed in php/php-src@6f241f5fad3a26810c96d5b634bfbceaeac10176. Currently, HHVM [matches the old behavior](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/variable-unserializer.cpp#L740-L747); see #4647. Perhaps HHVM should match the new behavior.
### HHVM Version

HipHop VM 3.15.0-dev (rel)
Compiler: heads/master-0-g17e1c0b1425733e5f34287b674f2456978c9008b
Repo schema: 7457716dbd7150059b4a315d3f986266d72e8ad8
### Standalone code, or other way to reproduce the problem

Use `ext/standard/tests/serialize/bug71840.phpt` from PHP:

```
<?php
var_dump(unserialize('a:1:{s:0:""0a:0:{}}'));
?>
```
### Expected result

A Notice, then:

```
bool(false)
```
### Actual result

```
array(1) {
  [""]=>
  array(0) {
  }
}
```

**Comment by jwatzman** [comment]
https://3v4l.org/tJcGZ

Someone on the current team should make a call here -- IMO we should keep the current behaviour for maximum PHP5 compatibility, especially since someone complained about the other behaviour, and doing it this way probably isn't hurting anything (?) other than just being silly.

**Comment by TJ09** [comment]
I mean, #4647 wasn't anything of a "my code relied on Zend PHP's strange behavior and broke on HHVM" sort, more of a "this is technically incompatible so I should probably report it" thing.

**Comment by aorenste** [comment]
Looks like Zend fixed this in 5.6.21 and 7.  I would say that we should probably fix this.

**Comment by aorenste** [comment]
This is D3650714 internally.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not buggy or broken. The compatibility for unserializing serialized data from the PHP runtime in HHVM has been broken by the removal of the untyped array [^1]. Hhvm will never serialize a string with a closing byte other than `;` nor did the PHP runtime. So if uniserialize is ever encountering a string with a closing byte other than `;`, it wasn't data serialized by hhvm. Unserializing untrusted data is ill-advised from a security perspective.

If the permissive unserializing is causing trouble, don't be discouraged from opening a new issue.

[^1]: In Hack, arrays are either associative or vector like, but not both. The array change isn't the point, but it demonstrates that unserializing anything from the PHP realm is unlikely to work.
