### ISSUE TITLE
Yield expression from within if statement throws syntax error

### ISSUE THREAD

**Issue by Sazpaimon** [facebook/hhvm#7261]
When using a yield statement inside of an `if` statement, a syntax error is thrown. Yields done like this is useful for coroutines in promise libraries.
### HHVM Version

3.10.0 - 3.12.0
### Standalone code, or other way to reproduce the problem

https://3v4l.org/8tkt2
### Expected result

string(4) "true"
### Actual result

Fatal error: syntax error, unexpected T_YIELD

**Comment by Orvid** [comment]
HHVM currently supports the yield statement, but doesn't quite support the yield expression. What you're trying to do here is using the yield expression, not the yield statement.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hack syntax does not have a yield expression, only a yield statement. HHVM has departed from PHP some years ago. It doesn't seem likely the hhvm team will copy a syntax feature over anymore. There is no PHP code to be compatible with and all Hack code uses the statement variant. If you are still using hhvm and Hack by extension, you may wish to submit a feature request for yield expressions.
