### ISSUE TITLE
Redis Sort Problem

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#7317]
I am using Ubuntu server and install HHVM 3.14.5.
Recently I am try using the Redis to sort the result and i get the error.

Please help.

This is piece of code.

```
   `$this->redis->lpush('id', 1);  
    $this->redis->set('name_1', 'tank');  
    $this->redis->set('score_1',89);  

    $this->redis->lpush('id', 2);  
    $this->redis->set('name_2', 'zhang');  
    $this->redis->set('score_2', 40);  

    $this->redis->lpush('id', 4);  
    $this->redis->set('name_4','ying');  
    $this->redis->set('score_4', 70);  

    $this->redis->lpush('id', 3);  
    $this->redis->set('name_3', 'fXXK');  
    $this->redis->set('score_3', 90);  

    $sort=array('BY'=>'score_*',  
                'SORT'=>'DESC',  
                'GET'=>array('name_*','score_*')
                );  
    $a = $this->redis->sort('id',$sort);
    var_dump($a);`
```
### Expected result

**Array ( [0] => 3 [1] => 1 [2] => 4 [3] => 2 )**   
### Actual result

![screenshot_1](https://cloud.githubusercontent.com/assets/1627923/18301911/5af1d7c2-7507-11e6-99b4-58627cbd8dd5.png)

**Comment by imashino** [comment]
After the debugging to fix the VAL issue, first i find out that line **1741** which - 

` if (is_array($val) AND (count($val) == 2)) {`

should change to

` if (is_array($v) AND (count($v) == 2)) {`

But at the end i still get the NULL result.

And wirh the same code running in apache2 + php5 + redis is fine, result array has returned.

**Comment by imashino** [comment]
Ok i found the problem, I try copy the hhvm redis file and include in my code to debugging.

Here is the problem -

Line 697  `public function eval($script, array $args = [], $numKeys = 0)`
- in PHP, **eval** is a native function, so the function name of eval cannot be re-declare.
- i temporary changed the function name to **eval1** `public function eval1($script, array $args = [], $numKeys = 0)`

because of the function name of **eval** changed to **eval1**, so the some part has related to function eval should update as well. Affected Line is 693 until 703 , which mean

`  public function evaluate($script, array $args = [], $numKeys = 0) {
    return $this->doEval('EVAL', $script, $args, $numKeys);
  }
  public function eval($script, array $args = [], $numKeys = 0) {
    return $this->doEval('EVAL', $script, $args, $numKeys);
  }
`

change like

`  public function evaluate($script, array $args = [], $numKeys = 0) {
    return $this->doEval('EVAL1', $script, $args, $numKeys);
  }
  public function eval1($script, array $args = [], $numKeys = 0) {
    return $this->doEval('EVAL1', $script, $args, $numKeys);
  }
`

Finally the result is appear. T..T

**Comment by Orvid** [comment]
Could you submit a Pull request with the fix?

**Comment by imashino** [comment]
For the sorting part i still find out some problem.
When using sort in parameter it will return result syntax error, i fixed the syntax issue as well as I can see the count number of array in the redis result.
But nothing data can be list out.

Right now i have no idea how to fix it.
i stuck at ` protected function processLongResponse() {`

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Support for this Redis extension has been removed as of hhvm version [4.56.0](https://hhvm.com/blog/2020/05/04/hhvm-4.56.html).
