### ISSUE TITLE
Building HHVM with afl-clang-fast

### ISSUE THREAD

**Issue by the-st0rm** [facebook/hhvm#7336]
I am trying to build HHVM 3.15.0-dev with afl-clang-fast (https://github.com/mirrorer/afl) but I keep getting the following error
`/home/test/hhvm/third-party/folly/src/folly/experimental/symbolizer/Symbolizer.cpp:26:10: fatal error: 'ext/stdio_filebuf.h' file not found`

I am sure that I have the ext/stdio_filebuf.h

```
# ~/f/h/build> locate stdio_filebuf.h
/usr/include/c++/4.7/ext/stdio_filebuf.h
/usr/include/c++/4.8/ext/stdio_filebuf.h
/usr/local/include/c++/7.0.0/ext/stdio_filebuf.h
```

This is the cmake command I am using for the build

```
cmake -DCMAKE_REQUIRED_INCLUDES='/usr/include/c++/4.8/' -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock -DCMAKE_C_COMPILER=/home/storm/fuzzing/afl-2.3/afl-clang-fast -DCMAKE_CXX_COMPILER=/home/storm/fu
zzing/afl-2.3/afl-clang-fast++ -DCMAKE_BUILD_TYPE=DEBUG  ../
```

I have also replaced the`-DCMAKE_REQUIRED_INCLUDES`with `-DCMAKE_InCLUDE_PATH=` but it is not working. 

Any ideas? 

PS: The normal build with normal gcc works fine but when I use the wrapper I get this issue of not finding the header file stdio_filebuf.h

**Comment by Orvid** [comment]
I'm not really sure what could cause this unless that has some hard-coded include paths?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones unlikely to be resolved.

This issue demonstrates a build error. This issue is very, very old. Chances are that this error does not occur with a modern checkout of hhvm. If it still does, it is likely not recognizable because of the changes made since the filing date of this issue.

If you are experiencing build errors, don't let the closing of this issue discourage you from filing a new issue.
