### ISSUE TITLE
nums should be Stringish

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7341]
### HHVM Version

3.15.0
### Standalone code, or other way to reproduce the problem

``` hack
<?hh

$value = 7;
echo <input type="number" value={$value} />;
```
### Expected result

``` html
<input type="number" value="7" />
```
### Actual result

```
 attribute `value` of type `integer` supplied to element `input`, expected `Stringish`.
```

This particular example throws a Hack error, but it's just a simplified version of what we ran into. Not having `num` be of type `Stringish` is rather annoying for this particular case (`value` of a `number` input) as it requires wrapping the variable in a string, which Hack doesn't like.

The way I see the `Stringish` type is that it represents a value that can be safely casted to a string.  A `num` certainly fulfils that condition.

**Comment by HRMsimon** [comment]
cc @fredemmott as we've only had this issue while using XHP and their might be something that can be done there to work around this.

**Comment by fredemmott** [comment]
XHP won't be special-casing this; consistency with Hack's type system is a goal of 2.x+.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Although `Stringish` hasn't been ouright removed yet. The hhvm team has been trying to get rid of it since hhvm [3.30.0](https://hhvm.com/blog/2018/12/17/hhvm-3.30.html), but this has taken quite a bit longer than expected.

 - [3.30.0](https://hhvm.com/blog/2018/12/17/hhvm-3.30.html) Casting objects to strings will no longer be supported (`hhvm.fatal_on_convert_object_to_string`); this includes removal of support for `__toString()`.
 - [4.19.0](https://hhvm.com/blog/2019/08/19/hhvm-4.19.0.html) The Stringish interface is deprecated, and can not be converted to a string without a typechecker error.
 - [4.44](https://hhvm.com/blog/2020/02/10/hhvm-4.44.html) string casts of Stringish objects will change to raise a runtime exception; the `hhvm.notice_on_implicit_invoke_to_string` option can be used to detect this. 
 - [4.52](https://hhvm.com/blog/2020/04/07/hhvm-4.52.html) Runtime support for casting objects to strings via `__toString` will be removed shortly; this includes `(string) $obj`, `print($obj)`, `sprintf('%s', $obj)` among others. The `hhvm.notice_on_implicit_invoke_to_string` INI setting can be used to find calls that will break.

The only changes being made to `Stringish` are those that aid in its removal.
