### ISSUE TITLE
Add enumname<T> as alias for classname<\HH\BuiltinEnum<T>>

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7357]
While I understand it's considered an implementation detail, unless there's a plan to replace it, I'd like that to be changed.

We have a lot of references to it internally, and I'm not sure what kind of abuse it's trying to avoid; if it's merely to stop people depending on an implementation detail, it's failed, and will as long as there's no other replacement.

Otherwise, it should be moved to the __SystemLib namespace like other internals.

**Comment by paulbiss** [comment]
> We have a lot of references to it internally

I count nine, and one of them is a comment

> I'm not sure what kind of abuse it's trying to avoid

I imagine it has something to do with enums being classes and enum values not being instances of those classes, and having a hierarchy of enum classes and a distinct type lattice for enum values being confusing. Or maybe there's no reason at all. Maybe @jwatzman knows?

**Comment by fredemmott** [comment]
Sorry, yeah, looks like some things that used to be/should[?] be `classname<\HH\BuiltinEnum>` just take `string` instead now :(

**Comment by jwatzman** [comment]
> I imagine it has something to do with enums being classes and enum values not being instances of those classes, and having a hierarchy of enum classes and a distinct type lattice for enum values being confusing.

Yep, that's basically it. We didn't want people to think of enums as classes, both because their values don't behave that way when matching type annotations... and also just because they *aren't* classes, they are enums, and the fact that they are actually classes behind the scenes is an implementation detail.

Added to that, there are extremely limited legitimate reasons to refer to `BuiltinEnum` -- nearly any code that does that is wrong and wants to be doing something else. Codegen and complicated reflection/introspection are the only cases I can think of offhand.

Explicitly admitting to `BuiltinEnum` and allowing code to talk about it easily gets people to think of enums as classes, which we were explicitly trying to avoid, given the shitshow that the `Enum` class was at FB. (For non-employees: it was a convention using `const` members and a lot of fancy reflection to simulate enums. Messy but not bad in and of itself... until you start subclassing them, overriding methods, adding new methods, and making the behaviour confusing and inconsistent.)

**Comment by fredemmott** [comment]
Is there an alternative type-safe way to make a class that deals with T where T is 'some enum'?

> nearly any code that does that is wrong and wants to be doing something else

https://github.com/fredemmott/hack-router/blob/master/tests/UriParametersTest.php#L76-L94 is there a better way?

> That FB only has eight references in our tens of millions of lines of code attests to this.

At least some code is just using strings for enum names instead to avoid this message, which seems worse. I'd rather have type-safe code with an ignored warning than unsafe code like that.

> the shitshow that the Enum class was at FB.

Couldn't these issues be avoided just by banning 'extends \HH\BuiltinEnum', not all references to it?

# Possible alternative?

Would all of these be addressed by:
 - keeping \HH\BuiltinEnum banned (and moving to `\__SystemLib`)
 - adding `\HH\EnumName<T>` as a not-banned alias

e.g.:

```Hack
<?hh

enum Foo: string {
  HERP = 'derp';
}

/* HH_FIXME[2053] - put this in systemlib + HHI */
type enumname<T> = classname<\HH\BuiltinEnum<T>>;

function do_stuff<T>(
  enumname<T> $enum,
  T $value,
): void {}

function main() {
  do_stuff(
    Foo::class,
    Foo::HERP,
  );
}
```

**Comment by fredemmott** [comment]
^ also possibly add an alias for '::class' for enums...

**Comment by fredemmott** [comment]
> That FB only has eight references in our tens of millions of lines of code attests to this.

Yep, 8 actual usages, but I'm guessing > 200 unsafe workarounds to avoid it - regexp found 250 (messaged link), though there'll be some false positives there.

**Comment by jwatzman** [comment]
`enumname` seems like a good idea to me, from my historical-curmudgeon-not-on-the-team-anymore perspective :-P

**Comment by fredemmott** [comment]
Had a quick attempt at doing this myself. Gave up for now when strict mode disallowed calling $enum_name::assert()

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`\HH\enumname<T>` was added in hhvm [4.42.0](https://hhvm.com/blog/2020/01/27/hhvm-4.42.html).

```HACK
enum Ship: int {}

function ship(): \HH\enumname<Ship> {
    return Ship::class;
}
```
