### ISSUE TITLE
Hack: $x[..][] doesn't force values of $x to be an array

### ISSUE THREAD

**Issue by jesseschalken** [facebook/hhvm#7377]
### HHVM Version

```
HipHop VM 3.16.0-dev (rel)
Compiler: heads/master-0-ge9eb3fc414fbae9b2c999a4f11390e23050b23b7
Repo schema: 9cc0ebe15bc9d2ba3609c5e4458deeef9ed86dcc
```
### Standalone code, or other way to reproduce the problem

This is a simple function that groups elements of an array. It deliberately has the wrong return type (`array<Tk, \PDO>` should be `array<Tk, array<Tv>>`), but the type checker doesn't report an error.

``` php
<?hh // strict

function group_by<Tk, Tv>(
  array<Tv> $a,
  (function(Tv): Tk) $f,
): array<Tk, \PDO> {
  $res = [];
  foreach ($a as $v) {
    $res[$f($v)][] = $v;
  }
  return $res;
}
```
### Expected result

Something like:

```
Invalid return type: test.php:11
This is an object of type PDO: test.php:6
It is incompatible with an array (used like a vector): test.php:9
```
### Actual result

Code passes without error. The function is also reported to have full type coverage.
### Discussion

I think the problem is that the code exploits PHP's "feature" of automatically creating arrays when doing array operations on things which aren't set. After `$res = [];`, Hack doesn't know the type of values, and so `$res[..][] = ...;` is an array append on a type that Hack has no information for, so it lets it pass. It can't see that this could have the effect of creating a new array, which will be incompatible with `PDO`.

I can make it fail correctly by explicitly initialising uninitialised arrays in `$res`:

``` php
<?hh // strict

function group_by<Tk, Tv>(
  array<Tv> $a,
  (function(Tv): Tk) $f,
): array<Tk, \PDO> {
  $res = [];
  foreach ($a as $v) {
    $i = $f($v);
    if (!\array_key_exists($i, $res)) {
      $res[$i] = [];
    }
    $res[$i][] = $v;
  }
  return $res;
}
```

```
Invalid return type: test.php:15
This is an object of type PDO: test.php:6
It is incompatible with an array (used like a vector) because a value is appended to it: test.php:13
```

Or by forcing the type of `$res` using the return type of another function:

``` php
<?hh // strict

function group_by<Tk, Tv>(
  array<Tv> $a,
  (function(Tv): Tk) $f,
): array<Tk, \PDO> {
  $res = map_of_vectors();
  foreach ($a as $v) {
    $res[$f($v)][] = $v;
  }
  return $res;
}

function map_of_vectors<Ta, Tb>(): array<Ta, array<Tb>> {
  return [];
}
```

However, couldn't the type checker also take the return type of `group_by()` and work backwards to see that an array append operation is invalid on type `PDO`?

**Comment by paulbiss** [comment]
Hack basically ignores this particular PHP-ism. I'm not sure if it was deliberate or not though. cc @andrewjkennedy

**Comment by andrewjkennedy** [comment]
Good catch. This is a type loophole. I'll look into it.

**Comment by jesseschalken** [comment]
I think it's fine that Hack ignores the way PHP automatically creates arrays. After all, you don't want `$x[..][] = ..;` to turn `$x` from `array<string, ThingWithArrayAccess>` into `array<string, array | ThingWithArrayAccess>`, just because the offset might not have been set.

However, I think this particular example could be fixed by taking the return type and working backwards to see that `PDO` doesn't support `ArrayAccess`. I don't know if that's hard for the type checker to do, though.

**Comment by lexidor** [comment]
The runtime behavior of hhvm has changed.
This issue relies on falsey array promotion.
The typechecker behavior is sound, however extremely unintuitive.

Repro
```HACK
<<__EntryPoint>>
function main(): void {
    array_append_to_nothing(1);
}
final class DefinitelyNotAnInt {}
function array_append_to_nothing(
    int $int,
): dict<string, vec<DefinitelyNotAnInt>> {
    $res = dict[];
    $res[''][] = $int;
    return $res;
}
```

The culprit (in modern Hack) is the [nothing](https://docs.hhvm.com/hack/built-in-types/nothing) type.
When the `dict[]` is created, the keys are of type `nothing` and the values are of type `nothing`.
`$res['']` retrieves a value of type `nothing` from `$res`, which is required to fail, because if it would succeed you would have to produce a value of the `nothing` type, which is impossible.
This fails with an exception (unlike php and hhvm around the time this issue was made).

For arrays
_Uncaught exception 'OutOfBoundsException' with message 'Lval on missing array element'_
For dicts
_Uncaught exception 'OutOfBoundsException' with message 'Out of bounds dict access: invalid index ""_

Proof that this is a `nothing` related issue.
The only thing that has changed is the explicit generics on the empty dict (making it non-empty to the typechecker).
Now both the keytype and the value type are updated to `string` and `vec<int>` respectively.
```HACK
function array_append_to_nothing(
    int $int,
): dict<string, vec<DefinitelyNotAnInt>> {
    $res = dict<nothing, vec<nothing>>[];
    $res[''][] = $int;
    return $res;
}
```
```
Typing[4110] Invalid return type
   --> src/file.hack
  9 |     int $int,
    |     ^^^ But got int
 10 | ): dict<string, vec<DefinitelyNotAnInt>> {
    |                     ^^^^^^^^^^^^^^^^^^ Expected DefinitelyNotAnInt
 13 |     return $res;
    |            ^^^^
1 error found.
```

After creating a `nothing`, Hack is allowed to not report errors, because the branch is dead code `[terminal]`.
Hack is not required to update the type of `dict<nothing, nothing>`, since it involved doing something impossible.

The code after `res['']` is dead code, so Hack is not required to give errors on that code.
Hack will however try its best for cases that are most likely still wrong and do not involve `$res`.
So it will still catch things like `i_dont_exist()` being called, but it is not required to diagnose this error.
Hack chooses to report errors, if it is convenient to the programmer and doesn't require to much hoop jumping.

Hack cannot tell you that you are doing something that you don't expect.
`$res['']` throws, and it knows that, however, maybe you wanted to throw.
Throwing isn't a violation of the typesytem.
So Hack is stuck and cannot give you a diagnostic.
If you would have written an explicit `throw` like this, you wouldn't expect a typeerror either.

```HACK
function main(): void {
    return_in_dead_code();
}

final class DefinitelyNotAnInt {}

function return_in_dead_code(): DefinitelyNotAnInt {
    $int = 0;
    throw new \Exception();
    return $int;
}
```

### Footnote

This confused me for over an hour.
I usually check if code is dead code by doing an operation which is invalid on a type.
If this does not report an error, you are in dead code.

For example, inside of an `if false` you can do this:
```HACK
$int = 0;
if(false) {
  $int->calling_a_method_on_an_int();
}
```

However, in this `res['']` case, Hack actually decides to diagnose `$int->calling_a_method_on_an_int()` as an error after that line, which made me think I must be interpreting this wrong.
@Wilfred :heart:  has been a huge help and he took a sizeable chunk of time out of his day to help me explain what I was describing.
