### ISSUE TITLE
Hack uses PHP's broken rules for string comparison

### ISSUE THREAD

**Issue by DemiMarie** [facebook/hhvm#7410]
### HHVM Version
3.10.0 - 3.14.4
### Standalone code, or other way to reproduce the problem
```hack
<?hh // STRICT
function main() {
   var_dump("123" < "0124");
}
main();
```
### Expected result
Hack, unlike PHP, compares strings correctly, so that the result is `bool(false)`.
### Actual result
Hack uses PHP's [broken][1] rules for string comparisons, so the result is `bool(true)`.  This can [lead to vulnerabilities][2].

[1]: https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/
[2]: http://phpsadness.com/sad/47

**Comment by photodude** [comment]
Is this really a thing??? The example in the [link claiming string comparison "vulnerabilities"](http://phpsadness.com/sad/47) may apply to really old php versions (versions before php 5.4) but definitely doesn't apply to php 5.4.4+ see live code example https://3v4l.org/rVWZq

As for the other [link from a 2012 article regarding all kinds of php issues relating to broken rules for string comparisons](https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/), almost everything is relating to stuff before php 5.4 and much was fixed in php 5.4 (also noted in the article that it was fixed). 

As for the provided code example, this might be an edge case in both php and hack where expected is false (python returns false `print ('123' < '0123')` but c++ considers `"123" < "0124"` to be true ) but PHP and hack are returning true.  Since hack is, and I think php might be,  c++ based I'm not surprised that c++, php, and hack all consider `"123" < "0124"` to be true.

**Comment by DemiMarie** [comment]
[This page][1] shows actual examples of hashes that collide when using `==`.

[1]: https://github.com/spaze/hashes

**Comment by DemiMarie** [comment]
@photodude In C++ `"123" < "0124"` is Undefined Behavior because it is comparison of two pointers to different arrays.

**Comment by photodude** [comment]
@DemiMarie [that link](https://github.com/spaze/hashes) for "examples of hashes that collide when using `==`" references long out of date information
From the editor's note on the [PHP types comparisons](https://secure.php.net/manual/en/types.comparisons.php)

> As of PHP 5.4.4 this is no longer true. Integral strings that overflow into floating point numbers will no longer be considered equal"

As previously pointed out, that specific hash-string-compare issue was solved in php 5.4.4

As for c++,  `"123" < "0124"` is not "Undefined Behavior". You can do some types of literal string comparisons directly in conditional statements in c++. Although it is highly recommended never to do so and to always use the [c++ string compare function](http://www.cplusplus.com/reference/string/string/compare/). see this example c++ code https://goo.gl/qpfHmQ

**Comment by photodude** [comment]
@DemiMarie I got some clarification on the hash issue from [that link](https://github.com/spaze/hashes), the broken portion is due to integral strings with the starting form of `0e1` or `00e2` etc in other words it looks like a form of underflow happening on integral strings since `'0e1' == '00e2' == '0'`

**Comment by ricklavoie** [comment]
@photodude `"123" < "0124"` is undefined behavior because you're not comparing literal strings at all. You're comparing two `const char*` pointers and comparing pointers which don't point at the same array is undefined behavior. `"123" == "123"` isn't even guaranteed to be true, as the compiler and linker aren't required to merge identical string literals. There is no aliasing to string compare involved here.

**Comment by photodude** [comment]
@ricklavoie see this example c++ code https://goo.gl/qpfHmQ and this c++ example https://goo.gl/lZXec4 using `<` to lexicographically compare two strings

See also http://en.cppreference.com/w/cpp/string/basic_string/operator_cmp

**Comment by DemiMarie** [comment]
@photodude You are comparing two `std::string`s, not string literals (which are really `const char *` pointers).

**Comment by photodude** [comment]
@DemiMarie I kind of get what your saying, but you can see in this example c++ code https://goo.gl/qpfHmQ `"123" < "0124"` compiles and can be executed directly with no undefined behavior. Unless this is something removed in C++14, I'm not following as  `const char *` works in c++11 as shown in https://goo.gl/uvPOH3

**Comment by mofarrell** [comment]
@photodude I think @DemiMarie and @ricklavoie are right about the pointer comparison when the types are `char*`.  
This is one of your example https://goo.gl/uvPOH3, and this is it with the strings definitions flipped https://goo.gl/W92Fhz.  They yield different results depending on the ordering of the definitions.
However std::string will perform a string based comparison http://en.cppreference.com/w/cpp/string/basic_string/operator_cmp.

All of that aside.  We would like to keep php's behavior, but I believe the question here is if the current behavior is "safe".  This is the case that is concerning: https://3v4l.org/E9C4V
SHA might produce strings like above and increase collisions dramatically.  As posted earlier by @DemiMarie, https://github.com/spaze/hashes explains the issue well.

**Comment by DemiMarie** [comment]
I would at least like a warning from the type checker when < or > is used
on strings.  Same for ==.

I would personally always treat this warning as an error.  The current
behavior is virtually useless.  For one, I don't think it is transitive, so
you can't use it for sorting.

**Comment by ricklavoie** [comment]
@photodude Just because it happens to work doesn't mean its not undefined behavior. It just means its not guaranteed to work and may only fail on a sufficiently exotic system.

**Comment by mofarrell** [comment]
We won't be changing this behavior, as we are looking to keep backwards compatibility with PHP.  A correct string based comparison would be used if compared with `===`.

**Comment by DemiMarie** [comment]
Would it be possible to get a warning from the type-checker?  I want to be
able to weed out all uses of > and < on strings.

**Comment by photodude** [comment]
@DemiMarie you could probably write your own custom code sniffer for use with [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) to help you enforce rules like disalowing `uses of > and < on strings`.

**Comment by DemiMarie** [comment]
I was thinking about something for Hack.

**Comment by photodude** [comment]
It should still parse hack files

**Comment by DemiMarie** [comment]
But does it understand types?  I want a warning whenever a type is inferred
as a string and that string is used in < or >.

**Comment by photodude** [comment]
Depends on if the internal php tokenizer can figure it out based on one of the [parser tokens](http://php.net/manual/en/tokens.php) like T_STRING, T_STRING_CAST, T_STRING_VARNAME or based on a set of paser tokens like T_IF T_STRING, T_IS_EQUAL, etc. I haven't seen this exact case in one of the other standards out there so it might be something too complicated for the code sniffer. 

At the same time it might be something complicated enough that only a "smart" IDE can figure out using the Hack tooling APIs or if NuclideIDE for hack had such capabilities.

**Comment by DemiMarie** [comment]
Only a smart IDE (or the type checker) could figure it out, since it
depends on the results of type inference.  It is also a non-trivial footgun
for people coming to Hack directly (not through PHP), hence my suggestion
for a "lint" warning from the typechecker.
