### ISSUE TITLE
Proposal: provide a way to change the behavior of Hack strings in comparisons

### ISSUE THREAD

**Issue by DemiMarie** [facebook/hhvm#7418]
This is a feature request for a pragma of some form to change the behavior of string comparison in Hack, and/or to obtain a warning from the type-checker when a string is used in `<`, `==`, or `>`.

The current behavior cannot be changed for compatibility reasons.  However, it is error-prone, and some developers would prefer if strings did not convert to numbers in comparisons.  This pragma would allow such developers to opt-in to the new behavior, while not changing the behavior of existing code.  It is similar to how some PHP 7 features are not enabled by default, but must be turned on by a change in the INI file.

Currently, comparing 2 strings correctly requires a function call to `strcmp` or else prefixing both strings with a non-digit such as `$` before the comparison.

This pragma could take the form of
- an INI setting (probably not – too global an effect)
- a comment at the start of the file
- other special syntax

**Comment by DemiMarie** [comment]
I don't think that a warning would work, due to generics: a variable might be a string some of the time only.  So I think this needs to change the bytecodes generated for `<`, `==`, and `>` when this mode is turned on.

**Comment by fredemmott** [comment]
Closing:
 - ini setting is out because as you said, it's too global: it would mean you could only use libraries that use the same value for the setting as you
 - special syntax wouldn't give much value over functions, and we tend to be extremely conservative about adding new operators as mistakes there are extremely hard to undo, and may lead to confusion with possible future PHP operators
 - having the operators change their meaning per-file seems likely to be extremely confusing for developers, especially on large codebases

The best approach would probably be to do this in a linter, though as you noted, it would need to be aware of generics (building on top of the new Hack full fidelity parser may be a workable option).
