### ISSUE TITLE
Hack build issue

### ISSUE THREAD

**Issue by fzg** [facebook/hhvm#7472]
### HHVM Version
git revision 6b70db70508950842ec803c952aea672f4814546
### Standalone code, or other way to reproduce the problem
`cd hphp/hack;make`
### Expected result
hh_server builds
### Actual result
`File "_none_", line 1:
Error: hh_server.cmx
is not a compilation unit description.
Command exited with code 2.`

[See gist.](https://gist.github.com/fzg/d1a0d7674c57b0e9caeafc27f2700e01)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones unlikely to be resolved.

This issue demonstrates a build error. This issue is very, very old. Chances are great that this error does not occur with a modern checkout of hhvm. If it still does, it is likely not recognizable because of the changes made since the filing date of this issue.

If you are experiencing build errors, don't let the closing of this issue discourage you from filing a new issue.
