### ISSUE TITLE
Does HHVM support socket passing like php-fpm?

### ISSUE THREAD

**Issue by AnoopAlias** [facebook/hhvm#7514]
https://freedesktop.org/wiki/Software/systemd/DaemonSocketActivation/
The above feature is very handy in spawning HHVM on-demand based on request to a hhvm.server.file_socket or hhvm.server.port

Is this possible with HHVM?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones unlikely to be resolved.

This issue is a question. I feel sorry for you that this question remained unanswered at the time you created it. As it has been open for years, I'll assume you have moved on or found an answer / workaround.

I don't know the answer to this question. (If I did, I'd have left it here.) If anyone reading this has the same or a related question, don't let this discourage you from asking it in a new issue.
