### ISSUE TITLE
Add support for new array destructuring syntax

### ISSUE THREAD

**Issue by Daniel15** [facebook/hhvm#7535]
PHP 7.1.0 added new syntax for destructuring, similar to the short array syntax added in PHP 5.4. Instead of doing `list($foo, $bar) = $array`, you can do `[$foo, $bar] = $array`. See https://wiki.php.net/rfc/short_list_syntax for the RFC.

3v4l: https://3v4l.org/He86X

### HHVM Version
3.16.0-dev

### Standalone code, or other way to reproduce the problem
```
<?php
[$a, $b, $c] = ['aaa', 'bbb', 'ccc'];
echo $a, $b, $c;
```

### Expected result
```
aaabbbccc
```

### Actual result
```
Fatal error: syntax error, unexpected '=' in /tmp/test.php on line 2
```

**Comment by photodude** [comment]
@Daniel15 as this is a php 7.1 incompatibility issue you should look at issue #7544

**Comment by fredemmott** [comment]
I'm hoping to get this into 3.25, but it's fairly horrible: we can no longer parse list assignments as a separate thing as that ambiguous; instead, we're going to have to parse the LHS as an arbitrary array literal, then after parsing, make sure that it's a valid LHS.

**Comment by fredemmott** [comment]
internal diff: D7057672

Caveats:
 - not supported in Hack - PHP only
 - keyed destructuring is unsupported (and seems to be rarely used in the wild)

**Comment by proggeler** [comment]
PHP-Unit 6.4 uses this short list syntax, i hope you manage to add this soon

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Hhvm doesn't understand square bracket array literals anymore. The closest thing you can get to destructuring into an array literal is this:

```HACK
varray[$a, $b, $c] = varray['aaa', 'bbb', 'ccc'];
```

`list()` is both shorter and more explicit.
The typechecker error for this is good.

```
Parsing[1002] varray_intrinsic_expression is not allowed in write context
   --> src/file.hack
  3 |   varray[$a, $b, $c] = varray['aaa', 'bbb', 'ccc'];
    |   ^^^^^^^^^^^^^^^^^

Parsing[1002] Invalid lvalue
   --> src/file.hack
  3 |   varray[$a, $b, $c] = varray['aaa', 'bbb', 'ccc'];
    |
```
