### ISSUE TITLE
Using bindTo on a IIFE fails with a syntax error.

### ISSUE THREAD

**Issue by letr0n** [facebook/hhvm#7577]
Using bindTo on a IIFE fails with a syntax error. (It's working with PHP 7.0).

### HHVM Version

HipHop VM 3.17.0 (rel)

### Standalone code, or other way to reproduce the problem

```php
<?php

class Foo
{
}

$foo = new Foo;

(function($input)
{
        var_dump($input);
})->bindTo($foo)('foobar');
```

### Expected result

```
string(6) "foobar"
```

### Actual result

```
Fatal error: Uncaught Error: syntax error, unexpected T_OBJECT_OPERATOR in /home/developer/test.php:12
Stack trace:
#0 {main}
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

It is nolonger a syntax error to call a method on a parenthesized PHP closure expression.
However, the Hack typechecker ignores the fact that Closures have methods.
In practice, you end up having to `/*HH_FIXME*/` code that calls methods on closures.

`Closure::bindTo()` has been removed from the runtime in hhvm [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html). The only method you could call on a Closure is `__debugInfo()` (the magic method for `var_dump()`, since all other methods have also been removed.

```HACK
\var_dump((new \ReflectionClass('Closure'))->getMethods());
```

```
array(1) {
  [0]=>
  object(ReflectionMethod) (2) {
    ["name"]=>
    string(11) "__debuginfo"
    ["class"]=>
    string(7) "Closure"
  }
}
```
