### ISSUE TITLE
Fatal Error : exception 'BadMethodCallException' with message 'Call to a member function getRval() on a non-object (null)'

### ISSUE THREAD

**Issue by ektasingh2408** [facebook/hhvm#7596]
### HHVM Version : 3.15.1

Hello Team  , 

I m facing this issue when i upload my DFP API project on server . And my server is using hhvm . So please tell me how overcome from this issue

**ERROR** exception 'BadMethodCallException' with message 'Call to a member function getRval() on a non-object (null)' in /home/appfeedlight/public_html/webfeed/public/dfp/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Dfp/v201611/InventoryService.php:199 Stack trace: #0 /home/appfeedlight/public_html/webfeed/public/dfp/vendor/googleads/googleads-php-lib/examples/Dfp/v201611/InventoryService/GetAllAdUnits.php(53): Google\AdsApi\Dfp\v201611\InventoryService->getAdUnitsByStatement() #1 /home/appfeedlight/public_html/webfeed/public/dfp/vendor/googleads/googleads-php-lib/examples/Dfp/v201611/InventoryService/GetAllAdUnits.php(88): Google\AdsApi\Examples\Dfp\v201611\InventoryService\GetAllAdUnits::runExample() #2 /home/appfeedlight/public_html/webfeed/public/dfp/vendor/googleads/googleads-php-lib/examples/Dfp/v201611/InventoryService/GetAllAdUnits.php(92): Google\AdsApi\Examples\Dfp\v201611\InventoryService\GetAllAdUnits::main() #3 {main}

**Comment by DerPapst** [comment]
Have you tested your code with stock php and made sure it works there? If it does it would be helpful if you could create a minimal example of the problem because googleads-php-lib is rather large.

**Comment by DerPapst** [comment]
The `\Google\AdsApi\Dfp\v201611\InventoryService` class extends `\Google\AdsApi\Common\AdsSoapClient` which itsself extends php stock `SoapClient` and the error occurs because `__soapCall()` returns an unexpected response. It could be various things. Timeouts, issues with the connection setup in `AdsSoapClient::__soapCall()`, parsing the response or something else I haven't thought of.

Either of you has to figure out at which location the library behaves different running in php and hhvm and build a small example.

**Comment by renatko** [comment]
I have the same issue. Working on PHP 7.0 and not working on HHVM 3.17.2

The issue in SoapClient.
After a lot of debugging, I found that options from `stream_context` set at the time the constructor called. But it produces a change after this (https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsSoapClient.php#L105) and expects that the `stream_context` will be transferred to the SoapClient

**Comment by renatko** [comment]
also, there is another issue: something is wrong with populating data into classes specified in `classmap`.

eg: https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Dfp/v201611/Network.php

The constructor of resource called without params and setters isn't calling. But if I change properties to `public`, then it works as expected.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
