### ISSUE TITLE
instanceof on generic overeager

### ISSUE THREAD

**Issue by HRMsimon** [facebook/hhvm#7617]
### HHVM Version
3.18-dev
hh_client: 441002bba095256f8f01dda97189cd7164a029f7 Tue Jan 24 08:34:40 2017

### Standalone code, or other way to reproduce the problem

```hack
<?hh // strict

function isInstanceOf<T>(classname<T> $type, mixed $what): T {
  if ($what instanceof $type) {
    return $what;
  }
  throw new Exception();
}
```

### Expected result
```
No errors!
```
### Actual result

```
test.php:4:7,28: 'instanceof' cannot be used on a generic classname because types are erased at runtime (Typing[4162])
```

Given that `$type` is a `classname`, it's not erased at runtime. Just the `T` is.

**Comment by jesseschalken** [comment]
I don't get why it has to do such a check during typing at all, since the right hand side of `instanceof` is either an expression or a class name, putting a generic type there is already prevented by the parser.

**Comment by jesseschalken** [comment]
https://github.com/facebook/hhvm/commit/e5e54bb597bc55249403011399eadc85772763cb

**Comment by simonwelsh** [comment]
cc @fredemmott: I noticed this because of type-assert, so you may need to tell the type checker to shut up if it's still an issue in 3.18 stable.

**Comment by fredemmott** [comment]
cc @andrewjkennedy ; AIUI this is theoretically unsafe if T itself is a class that takes generics, but given I don't think you can't actually get a classname<T> for a specialized generic T, I don't see how it's actually a possible problem.

While this is clearly unsound...

```Hack
<?hh // strict

function foo(Vector<string> $value): void {
}

function refine_type<T>(classname<T> $type, mixed $what): T {
  // UNSAFE
  // just for typechecker, not going to ru nthis
}

function bar(mixed $value): void {
  foo(refine_type(Vector::class, $value));
}
```

... this is only because Hack appears to completely mishandle classname<T> in these cases anyway, regardless of instanceof, as this is also clearly unsound but the typechecker is fine with it:

```Hack
<?hh // strict

function foo(Vector<string> $value): void {
}

function factory<T>(classname<T> $type): T {
  // UNSAFE, just a typechecker demo for the other functions
}

function bar(): void {
  foo(factory(Vector::class));
}
```

**Comment by jesseschalken** [comment]
@fredemmott 

`Vector::class` has type `classname<Vector<[unresolved]>>` (according to the tooltips in Nuclide). I think this is correct, because it means `new Vector(null)` and `new (Vector::class)(null)` both produce a `Vector<[unresolved]>`. Then your second example is sound, because `factory(Vector::class)` produces `Vector<[unresolved]>` which unifies with `Vector<string>`.

But when it comes to `$x instanceof Vector::class`, `$x` should not be refined as `Vector<[unresolved]>` because the `instanceof` only goes one level deep (it can't check the generics since they don't even exist at runtime). But Hack does refine `$x` as `Vector<[unresolved]>`, which is why your first example is unsound but accepted by Hack.

![image](https://cloud.githubusercontent.com/assets/1559204/22423014/b633ad3c-e743-11e6-8159-10fe5242100c.png)

Maybe this is the original issue @andrewjkennedy was trying to fix?

What I think Hack needs to do is effectively make the `$x` in these two functions the same:

```php
function foo1<T>(Vector<T> $x): void {
  // ..
}

function foo2(mixed $x): void {
  if ($x instanceof Vector::class) {
    // $x: Vector<T> <- new type variable
  }
}
```

So when Hack sees `$x instanceof classname<SomeGenericType>`, it opens up `SomeGenericType` and replaces the generics with new type variables, to reflect the fact that the `instanceof` only goes one level deep and the actual generics for `$x` could be anything.

**Comment by jesseschalken** [comment]
In any case, the problem of `instanceof` on `classname<SomeTypeWithGenerics>` is orthogonal to the banning of `instanceof` on `classname<T>`.

**Comment by fredemmott** [comment]
If T is unconstrained, it can be SomeTypeWithGenerics

**Comment by jesseschalken** [comment]
What I mean is, banning `instanceof classname<T>` broke code that wasn't a problem (eg cases where `T` is filled with `SomeTypeWithoutGenerics`) and still let code pass that was a problem (eg a direct `instanceof SomeTypeWithGenerics`).

What should have been banned was cases of `instanceof classname<?>` where `?` is some type that is or may be generic, and then the fact that `T` might be generic is incidental. The resulting error message would also make more sense, something like "instanceof is only allowed on non-generic classes, T may be a generic class".

Then, to permit `instanceof classname<T>`, you could have a feature like this:

```php
function refine_type<T as nongeneric>(classname<T> $type, mixed $what): T {
  // ..
}

function bar(mixed $value): void {
  refine_type(Vector::class, $value);
  // ^ Error: Some type constraint(s) here are violated
  // 'T' is a constrained type
  // This is any nongeneric type
  // It is incompatible with an object of type Vector
}
```

Then `TypeAssert::isInstanceOf()` can still be type safe. (I don't know where else such a feature would be useful, though.)

Instead of banning, you could also unify the generics in a generic type with new type vars whenever it gets unified with `nongeneric`, as per my previous post. (`Vector<[unresolved]> <-> nongeneric` => `[unresolved] <-> T` => `Vector<T>`)

**Comment by andrewjkennedy** [comment]
Yes, the new restriction on classname<T> is too severe; the idea of a `nongeneric` "constraint" on T seems sensible.

**Comment by jesseschalken** [comment]
@andrewjkennedy revealed in https://github.com/facebook/hhvm/pull/7632 that the missing half of this is hidden behind `enable_experimental_tc_features = instanceof`, which when combined with the banning of `instanceof (classname<T>)` makes `instanceof` consistently sound.

A `T as nongeneric` constraint to accurately type `TypeAssert::isInstanceOf` would still be handy though (which either requires `T` not to be generic or triggers https://github.com/facebook/hhvm/commit/4c2a6097643f33b4da8c297e52363c6a2f23f4f4 for `T`), but it's up to the Hack team to decide if it would be sufficiently useful.

**Comment by fredemmott** [comment]
@jesseschalken if I'm understanding https://github.com/facebook/hhvm/commit/603cbd7cbf79f059365a1ff7787fef7b193e7ec3 correctly, this can be closed: while the safe behavior is still experimental, if the experimental flag isn't set, the old unsafe behavior is back - the latest build of the typechecker is now allowing https://github.com/facebook/fbshipit/blob/master/src/shipit/repo/ShipItRepo.php#L96-L98 to be removed without the experimental option

**Comment by jesseschalken** [comment]
@fredemmott I agree, but @HRMsimon or someone with permissions on this repo needs to close it.
