### ISSUE TITLE
Inconsistency with Zend when serializing a class and unserializing it to different class signature

### ISSUE THREAD

**Issue by hashar** [facebook/hhvm#7629]
### Abstract

Given an object had a private property and get serialized to a cache. Later on a new version of the class is deployed with the property visibility changed to public.

When unserializing from the cache (private property) to a new version of the class (public property), both Zend and HHVM create an object matching the class interface with a public property but unserialize() populate a private property with the same name and the actual value.  Zend/HHVM are consistent there.

When accessing the property from the class scope, Zend yield NULL as per the class interface, whereas HHVM returns a concatenation of both the private and public property:
```php
<?php
var_export( $o->prop(); );
# PHP:  NULL
# HHVM: valueNULL
```
### HHVM Version

3.15.4 3.17.1

### Standalone code, or other way to reproduce the problem

Quick view at https://3v4l.org/rcGhs which evaluate below code with Zend and HHVM and show different outputs.

**Update:** wrong example as pointed by @jesseschalken . Proper one below or at https://3v4l.org/jrmrO

```php
<?php
# Given two classes with the same property name but different visibility
class WithPublic {
    public $property;
    function __construct( $p ) { $this->property = $p; }
    function getProperty() { print $this->property; }
}   
class WithPrivate {
    private $property;
    function __construct( $p ) { $this->property = $p; }
    function getProperty() { print $this->property; }
}   


$priv = new WithPrivate( 'value' );
$cache = serialize( $priv );

$mut_priv_to_pub = unserialize(
    str_replace( '11:"WithPrivate"', '10:"WithPublic"', $cache) );

var_dump( $mut_priv_to_pub );
# class WithPublic#4 (2) {
#   public $property =>
#   NULL
#   private $property =>
#   string(5) "value"
# }

var_export( $mut_priv_to_pub->getProperty() );
# On Zend PHP: NULL
# On HHVM 3.15.4, 3.17.1: valueNULL
```

Note that serializing a public property and restoring it to a class having it private does not show the concatenation:

https://gist.github.com/hashar/a8dbb3bee8a0272350320136e9566100
https://3v4l.org/TZk8B

### Expected result

`NULL` for consistency with Zend

### Actual result

`valueNULL`

**Comment by jesseschalken** [comment]
Your `getProperty()` method prints `$this->property`, it doesn't return it. The `valueNULL` comes from `value` being printed by the call to `getProperty()` and the `null` that it implicitly returns being printed by `var_export()`.

On Zend, `$this->property` is still set to `null`, so the `print` prints nothing (`null` cast to string is `""`), but the `NULL` implicitly returned by `getProperty()` is still exported by `var_export()`.

As you can see in the `var_dump` output, there is clearly a difference with how HHVM and Zend have decided to handle the incompatible serialized data.

It's probably because the serialized data happens to correspond to how Zend stores object properties internally, so it just takes it verbatim and creates a private `property` property that doesn't exist, leaving the real `property` property still set to `null`.

HHVM on the other hand is doing some best-effort attempt to make the data fit the new class, assigning the data from the private property that doesn't actually exist to the public property that does. For compat with Zend, it probably shouldn't do that.

**Comment by jesseschalken** [comment]
The relevant code would be around here somewhere: https://github.com/facebook/hhvm/blob/902cbf05e4392f560366f76e10b11c4185e3b17a/hphp/runtime/base/variable-unserializer.cpp#L982

**Comment by hashar** [comment]
Thank you @jesseschalken to have pointed the getters were printing code instead of returning, I feel bad for that one.

I have  pasted the proper example at https://3v4l.org/jrmrO  (and again below). The serialized object has a private variable, when HHVM unserialize it, it seems to publish the class properties regardless of the visibility. Hence the private prop is gone:
```
object(WithPublic)#2 (1) {
    ["property"]=> string(5) "value"
}
```

C++ is a foreign language to me. Guessing at the code you pointed at, it looks like HHVM first retrieve the class properties and attempts to set their value solely based on the name regardless of the visibility. Hence the public property defined by the class get the value from the serialized private property that has the same name.

Eventually serialized properties that are not part of the class definition (apparently nicknamed "dynamic properties") are filled in. But the private property has been consumed already.

I cant tell what should be the proper behavior, HHVM graceful fallback is handy for this specific case. I am not sure if there is anything to fix here or whether it should be added to a HHVM/PHP group to investigate it further and determine a consistent behavior.


```php
<?php
# Given two classes with the same property name but different visibility
class WithPublic {
    public $property;
    function __construct( $p ) { $this->property = $p; }
    function getProperty() { return $this->property; }
}   
class WithPrivate {
    private $property;
    function __construct( $p ) { $this->property = $p; }
    function getProperty() { return $this->property; }
}   


$priv = new WithPrivate( 'value' );
$cache = serialize( $priv );

$mut_priv_to_pub = unserialize(
    str_replace( '11:"WithPrivate"', '10:"WithPublic"', $cache) );

var_dump( $mut_priv_to_pub );
# class WithPublic#4 (2) {
#   public $property =>
#   NULL
#   private $property =>
#   string(5) "value"
# }

var_export( $mut_priv_to_pub->getProperty() );
# On Zend PHP: NULL
# On HHVM 3.15.4, 3.17.1: 'value'
```

**Comment by hashar** [comment]
Result as of right now:

For 5.6.0 - 5.6.30, 7.0.0 - 7.1.20, 7.2.8, 7.3.0beta1
```
object(WithPublic)#2 (2) {
  ["property"]=> NULL
  ["property":"WithPrivate":private]=> string(5) "value"
} NULL
```

For hhvm-3.15.4, 7.2.0 - 7.2.6, 7.3.0alpha1
```
object(WithPublic)#2 (1) {
  ["property"]=> string(5) "value"
}
'value'
```

Seems php 7.2.0 was behaving the same as hhvm and eventually that got "fixed" in 7.2.8.

**Comment by lexidor** [comment]
Calling `\unserialize()` with a class definition that differs from the class definition at `\serialize()` time is undefined behavior. This may break type invariants or mess with Hack in other unforetold ways. The behavior of PHP and the behavior of HHVM differ. This doesn't have to a be a problem anymore, since hhvm doesn't target php-compatibility anymore.

**Comment by hashar** [comment]
I'd filed that cause at the time we'd had various issues unserializing to a different class signature. For MediaWiki we eventually stopped introducing new use cases of serialize and went to use an agnostic JSON representation ( https://phabricator.wikimedia.org/T161647 ).

I also found out Zend PHP had an RFC to remove serialize https://wiki.php.net/rfc/phase_out_serializable and it will be removed in PHP 9.

Then as said, HHMV no more supports PHP so this report is mostly obsolete. Thank you @lexidor to have closed it!
