### ISSUE TITLE
Calling non-static function statically should output a strict standards error

### ISSUE THREAD

**Issue by FlorianSW** [facebook/hhvm#7647]
### HHVM Version
3.12.7 + 3.17.1
### Standalone code, or other way to reproduce the problem
```
<?php

class StaticTest {
    public function test() {
        echo 'Works fine!';
    }
}

call_user_func_array( 'StaticTest::test', [] );
```

### Expected result
The above code should work fine, but should also output a strict standards error, e.g.:
```
Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method StaticTest::test() should not be called statically in /in/irrel on line 9
Works fine!
```

### Actual result
The output without any strict standards error:
`Works fine!`

PHP works fine and warns you about this problem, see https://3v4l.org/irrel

Spotted in: https://phabricator.wikimedia.org/T157213

**Comment by paulbiss** [comment]
This was fixed in d7861524234adddb38b37859a00ee4fe08827f0d (which made it into 3.17), and appears to work fine if you enable strict error reporting (`error_reporting(E_ALL | E_STRICT)`). It's controlled by the runtime option `hhvm.raise_missing_this` which is defaulted to `1` in PHP mode and `0` if `hhvm.force_hh` is set (in which case you can still explicitly enable it).

https://3v4l.org/OmC9u
