### ISSUE TITLE
"Sketchy null check on a primitive type" doesn't work in some cases

### ISSUE THREAD

**Issue by asuth** [facebook/hhvm#7689]
### HHVM Version
3.14.5

### Standalone code, or other way to reproduce the problem

```php
<?hh // strict

class User {
	private ?string $username;

	public function hasUsernameGood(): bool {
		if ($this->username) { // caught it!
			return true;
		} else {
			return false;
		}
	}

	public function hasUsernameGood2(): bool {
		if (!$this->username) { // caught it!
			return false;
		} else {
			return true;
		}
	}

	public function hasUsernameGood3(): bool {
		if (substr('abc', 0, 1) === 'a' && $this->username) { // caught it!
			return false;
		} else {
			return true;
		}
	}

	public function hasUsernameBad(): bool {
		if (substr('abc', 0, 1) === 'a' && !$this->username) { // failed to catch this!
			return false;
		} else {
			return true;
		}
	}

}
```

### Expected result

```
File "User.php", line 31, characters 8-22:
You are using a sketchy null check on a primitive type ...
Use is_null, or $x === null instead (Typing[4089])
```

### Actual result

Nothing

**Comment by jesseschalken** [comment]
In the first three cases either the `if (..) {..}` or the `else {..}` block have `$this->username` refined to `string`, but in the fourth case no refinement is done because the `!$this->username` check may not have been evaluated because it's guarded by `&&`. No refinement => no need to warn about a refinement being sketchy.

```php
class User {
  private ?string $username;

  public function hasUsernameGood(): bool {
    if ($this->username) { // caught it!
      $this->needsString($this->username); // allowed
      return true;
    } else {
      return false;
    }
  }

  public function hasUsernameGood2(): bool {
    if (!$this->username) { // caught it!
      return false;
    } else {
      $this->needsString($this->username); // allowed
      return true;
    }
  }

  public function hasUsernameGood3(): bool {
    if (substr('abc', 0, 1) === 'a' && $this->username) { // caught it!
      $this->needsString($this->username); // allowed
      return false;
    } else {
      return true;
    }
  }

  public function hasUsernameBad(): bool {
    if (substr('abc', 0, 1) === 'a' && !$this->username) { // failed to catch this!
      return false;
    } else {
      $this->needsString($this->username); // not allowed
      return true;
    }
  }

  private function needsString(string $x): void {}
}
```

**Comment by asuth** [comment]
Thanks for the quick response! Okay, I think I follow, but I still think the check would be useful. It seems to me you shouldn't be able to do sketchy checks on nullable values, period.

In my example, `hasUsernameGood` will give a typecheck error even though it doesn't use the `username` variable later.

I hit this problem because I actually had some production code like this:

```php
	public function hasUsernameBad(): bool {
		if (substr('abc', 0, 1) === 'a' && !$this->username) { // failed to catch this!
			$this->doScaryThing();
		} else {
			$this->doSafeThing();
		}
	}
```

In my case, `$username` was set to `''` and `doScaryThing` happened instead of `doSafeThing`

**Comment by jesseschalken** [comment]
I think the logic for the current behaviour is that if a refinement from `?string` to `string` is being done, then the dev is permitted to write code that depends on the refinement and it's most likely that what they intended is to check for `null` specifically (rather than truthiness).

But if no refinement is being done, then no code is allowed to assume the value isn't `null` and so Hack isn't in a position to say whether or not the semantics of `!$this->username` (checking for `null`, `""` and `"0"`) is what the dev wanted.

Nonetheless I happen to agree. I would prefer it if Hack barked whenever it saw _any_ suspicious comparisons or truthiness checks, to help catch bugs like this, but some devs (particularly sloppy ex-PHP devs) may find that too strict and may actually want to write `!$this->username` to check for `null`, `""` and `"0"`.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The typechecker doesn't do sketchyness checks anymore.

https://github.com/facebook/hhvm/issues/8561#issuecomment-531858031

> Sketchyness checks were moved to an ocaml linter, but that framework isn't open source.
