### ISSUE TITLE
Allow defining super globals from extensions

### ISSUE THREAD

**Issue by Samer-Al-iraqi** [facebook/hhvm#7720]
This is not a bug, but a feature request or explanation request.

In PHP, I can create a C plugin that simply let me use another custom super global variable. Here is the code 

```
PHP_MINIT_FUNCTION(pluginName){
	zend_register_auto_global(zend_string_init("G", sizeof("G") - 1, 1), 0, NULL);
	return SUCCESS;
}
```

When I put this code insde the C file prepared for PHP plugin, I can create .so file that I include in php.ini so I have a variable name **$G** that will be avialble inside all functions, methods and anonymous functions. Just like the super global variables: $_SESSION, $_GET, etc.

How can have similar functionality in PHP code that run under hhvm? 

This is very important for my project. Now, I am running my project in PHP_FPM. But I am intending to migrate to hhvm. Thanks

**Comment by mofarrell** [comment]
@Samer-Al-iraqi  At the moment, I don't think the extension system supports defining super globals like you are looking to do.  You might be able to get by using a function.  We do support creating global functions that return objects.  Instead of `$G`, you would end up with `G()`.  If this is okay for your use case, there are plenty of examples I can point you to.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hack does not really have superglobals.
You can access predefined globals `$argv` and `$_GET` using `\HH\global_get('argv')`, but direct use is always a typerror.
If you need to achieve something like this, define `G(): yourtype` as mofarrell suggested.
