### ISSUE TITLE
yielding result of function call where function named fromFOO() fails

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#7746]
### Standalone code, or other way to reproduce the problem
https://3v4l.org/gl97e

```php
function from1251($a) {
	return $a;
}
function foo() {
	yield from1251(42);
}
foreach(foo() as $bar) {
    var_dump($bar);
}
```

PHP Fix: https://github.com/php/php-src/commit/0fb640c71763ddb1b8017c87cec10fc76764feff

### Expected result
```
int(42)
```

### Actual result
```
Fatal error: Uncaught Error: Function name must be a string in /in/gl97e:5
Stack trace:
#0 (): foo()
#1 /in/gl97e(15): Generator->rewind()
#2 {main}

Process exited with code 255.
```

**Comment by fredemmott** [comment]
Based on your twitter comment: https://3v4l.org/uOSc7

**Comment by sgolemon** [comment]
And based on the PHP fix referenced :p

**Comment by Orvid** [comment]
So, I've had the diff to fix this up for the last week, I've just been trying to figure out why applying the same fix to the way we parse `else if` in HHVM causes a syntax error in systemlib. (`else if` is parsed as one token rather than as `else` followed by `if`) 

Unfortunately, debugging syntax errors in the systemlib is very painful, so I haven't found what edge-case is being hit. As we don't hit it with `yield from`, I've just landed the base fix for now.

**Comment by sgolemon** [comment]
Oh yeah, I remember that `else if` hack. :D

And yeah, seems to be problematic in the same way, I've opened a new issue for that: https://github.com/facebook/hhvm/issues/7762
