### ISSUE TITLE
add support to gnupg

### ISSUE THREAD

**Issue by apptvltd** [facebook/hhvm#7819]
http://php.net/manual/en/book.gnupg.php

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html). This means compatibility for compatibility sake is no longer a target. Nobody using HH m today depend on this extension (since it isn't there.)

If anyone has a need for this entension or similar functionality, don't be discouraged from opening a new issue. If anything were built, it would not need to be a 1 to 1 copy of the PHP api.
