### ISSUE TITLE
ReflectionClass::isIterable() incorrect for incomplete classes

### ISSUE THREAD

**Issue by sgolemon** [facebook/hhvm#7863]
See Thread attached to: https://twitter.com/SaraMG/status/870016752117309441

Interfaces (as well as traits or abstract classes) are not instantiable, therefore they can not actually be iterated over, ergo this method should return `false`.  I don't personally agree with this, but the mob (including the BDFL) have spoken.

### Standalone code, or other way to reproduce the problem
```php
var_dump((new ReflectionClass('Iterator'))->isIterateable());
```
https://3v4l.org/4Nd5F

### Expected result
bool(false)

### Actual result
bool(true)

### See Also
https://github.com/php/php-src/commit/d1cfd87fbe9e34bf909abedb61cfa4b2d7022b4d

Note as well that `isIterateable` is a terrible name and it's been renamed (with alias) to `isIterable`.
https://github.com/php/php-src/commit/c1500f8519aded29c3632de4240fbc0a4e485a81

**Comment by ciaranmcnulty** [comment]
Even if the argument doesn't seem strong, HHVM doesn't report `Traversable` as iterateable so consistency should win out https://3v4l.org/QtEeL

**Comment by fredemmott** [comment]
> Interfaces (as well as traits or abstract classes) are not instantiable, therefore they can not actually be iterated over, ergo this method should return false.

So, is this behavior for abstract classes a PHP bug?

https://3v4l.org/unHtX

**Comment by sgolemon** [comment]
It is, and it's already been fixed on master by https://github.com/php/php-src/commit/d1cfd87fbe9e34bf909abedb61cfa4b2d7022b4d

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version 4.0.0.

The current behavior, although different, is not buggy or broken. As S. Golemon pointed out, "I don't personally agree with this." Keeping the current behavior seems to be the best way to handle this. (If Iterator is not iterable according to php, hhvm doesn't have to copy that behavior for compatibility's sake.)
