### ISSUE TITLE
when a NUL char is used as key, apcu_store truncates the key

### ISSUE THREAD

**Issue by nicolas-grekas** [facebook/hhvm#7867]
### HHVM Version
HipHop VM 3.19.2 (rel)
Compiler: tags/HHVM-3.19.2-0-g8e7759b4b00535d65969dec6a56a03b4ed238b35
Repo schema: a02544d8eb49139aa02e1bc91bbdb6416e02af2c

### Standalone code, or other way to reproduce the problem
```php
apcu_store(array("a\0b" => 'foo'));
print_r(apcu_fetch(array("a\0b")));
```
### Expected result
```
Array
(
    [a<non-displayed-nul>b] => foo
)
```
### Actual result
```
Array
(
)
```

**Comment by Orvid** [comment]
@mofarrell You added the apcu aliases, right? Do you want to look at this as well?

**Comment by mofarrell** [comment]
I think @aorenste did that.  I will take a look after getting the release out.

**Comment by mofarrell** [comment]
As far as I can tell, we still don't have apcu aliases.  This is the observed behavior when using:
```
apc_store(array("a\0b" => 'foo'));
print_r(apc_fetch(array("a\0b")));
```

See https://github.com/facebook/hhvm/issues/6784.  I will investigate to see what is left to add the apcu functions.  This issue appears to be one such problem.

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

The behavior is the same as when the repro was made (an empty array is returned), but we get this warning.
_Warning: Invalid argument: apc key: (contains invalid characters)_.

If we make this warning an exception, problem solved.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The current behavior, although different, is not broken broken. Hhvm is more tolerant of invalid input and tries to "do what you wanted". APC keys may not contain null bytes. The warning hhvm emits can be handled by a user error handler and turned into an exception that way.

The current behavior isn't pretty, but I wouldn't be surprised if it was depended upon.

In my comment from 2020 I said "If **we** make.... This was in error. This "we" may have implied I am part of the hhvm runtime team. I am not and I never was. I am not affiliated with Meta or Facebook in any way.
