### ISSUE TITLE
get_class() returns invalid value for Closure

### ISSUE THREAD

**Issue by bkrukowski** [facebook/hhvm#7868]
### HHVM Version

`3.12` - `3.19`
I didn't test on earlier versions

### Standalone code, or other way to reproduce the problem

https://3v4l.org/JAvA4

```
<?php

echo get_class(function () {});
```

### Expected result

```
Closure
```

### Actual result

```
Closure$;1735914119$5c6a1ec710e0f92daae91216ad415486$
```

**Comment by lexidor** [comment]
What you are observing is the fact that each Closure "constructor" is a constructor for a class which name is generated during bytecode emission. If you define a closure inside of a function (instead of at the pseudomain level), the name will include the name of the function is which it was declare for example.

Although this behavior does not match PHP, it is "correct", since that is the actual class of the Closure object. HHVM dropped php compatibility with the release of hhvm 4.0.0.

```HACK
function main(): void {
  $f = () ==> {};
  echo \get_class($f);
}
```

```HHAS
.function (1,4) <"HH\\void" N > main() {
  .declvars $f;
  CreateCl 0 0
  SetL $f
  PopC
  NullUninit
  NullUninit
  NullUninit
  CGetL $f
  FCallFuncD <> 1 1 "0" - "" "get_class"
  Print
  PopC
  Null
  RetC
}

.class [no_override unique nontop] Closure$main (2,2) extends Closure {
  .method [public static] (2,2) <"" N > __invoke() isClosureBody {
    Null
    RetC
  }
}
```
