### ISSUE TITLE
Support composer in PHP7 mode

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#7869]
- [x] RecursiveDirectoryIterator/SplFileInfo/dirname() throws an exception
- [ ] Add to HHVM test suite
- [ ] fix `new FilesystemIterator($spl_file_info)`
- [ ] fix bad tar checksum calculation: phardata implementation thought that `unpack('C*')` gave single-char strings, but it actually gives uint8s; phardata implementation then passes them to ord() which complains

**Comment by fredemmott** [comment]
All done, hopefully will be backported to 3.20.1

**Comment by mofarrell** [comment]
working on that

**Comment by hopeseekr** [comment]
This issue is needed, because **WE ARE NOT IN A PHP5 WORLD ANY LONGER*. 

The HHVM team, and Facebook Corp., need to be *galvanized* to committing to stay compatible with PHP7 or they need to break all pretenses and start marking Hack Language as its own thing.

Otherwise, once all PHP5 code is collecting dust, relatively soon, all of your, my, and their HHVM efforts will have been in vain!

*Hopefully this PR is a wakeup call!*

**Comment by ganeshsoni** [comment]
7689
