### ISSUE TITLE
ReflectionType::__toString() returns invalid value for iterable pseudotype

### ISSUE THREAD

**Issue by bkrukowski** [facebook/hhvm#7870]
### HHVM Version

3.15 - 3.19

### Standalone code, or other way to reproduce the problem

https://3v4l.org/quhbu

```php
<?php

namespace MyNamespace;

class MyClass
{
    function foo(iterable $iterable, array $array, int $int) {
    }   
}

$reflection = new \ReflectionMethod(MyClass::class, 'foo');
$parameters = $reflection->getParameters();
echo (string) $parameters[0]->getType(), PHP_EOL;
echo (string) $parameters[1]->getType(), PHP_EOL;
echo (string) $parameters[2]->getType(), PHP_EOL;
```

### Expected result

```
iterable
array
int
```

### Actual result

```
MyNamespace\iterable
array
int
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

There is not pseudo type `\iterable` in Hack.
The runtime supported it for PHP compat, but Hack code can't use it.
Not to be confused with `\HH\Iterable<Tv>`.
