### ISSUE TITLE
Missing method Closure::fromCallable

### ISSUE THREAD

**Issue by bkrukowski** [facebook/hhvm#7874]
### HHVM Version

3.19 with `hhvm.php7.all=1`

### Standalone code, or other way to reproduce the problem

```
$closure = \Closure::fromCallable('strpos');
```

### Expected result

nothing

### Actual result

```
Call to undefined method Closure::fromCallable()
```

**Comment by mofarrell** [comment]
This is an added feature in PHP7.1 https://wiki.php.net/rfc/closurefromcallable

**Comment by bkrukowski** [comment]
@mofarrell on travis hhvm `3.18.3` with `hhvm.php7.all=1` reports php version `7.1.99-hhvm`

**Comment by mofarrell** [comment]
If it doesn't then almost no apps can run in PHP7.1 mode, even if they don't use `Closure::fromCallable`

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

The methods on `\Closure` that made it special over a function pointer have been removed.
You cannot `->bindTo()`, `->bind`, or `->call()` a closure at runtime.

In Hack, use `fun('strpos')`, which creates a function pointer or the string `"strpos", depending on your hhvm version and config.
