### ISSUE TITLE
Parentheses cause syntax error combined with null-coalescing operator and method invocation.

### ISSUE THREAD

**Issue by RealyUniqueName** [facebook/hhvm#7883]
### HHVM Version
HipHop VM 3.20.2 (rel)
Compiler: tags/HHVM-3.20.2-0-gad133f299ece0e45db8536473a8ef77cc4612ae3
Repo schema: 962ff68f0831a12b292f0eb9acd17f705a904446

### Standalone code, or other way to reproduce the problem
```
$ hhvm --php -r '($a ?? $b)->get();'
```
### Expected result
```
$ php -r '($a ?? $b)->get();'
PHP Notice:  Undefined variable: b in Command line code on line 1
```

### Actual result
```
$ hhvm --php -r "($a[0])->get('foo');"
Fatal error: syntax error, unexpected '(' in /tmp/php-wrap-UenqZg on line 2
```

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This works in hhvm 4.56. Syntax error is gone.
Your example throws a BadMethodCallException, because it calls `->get()` on an undefined variable (null). This can be fixed by using the `?->` operator.

```
Notice: Undefined variable: b in /tmp/php-wrap-duZ5AN on line 2

Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function get() on a non-object (null)' in /tmp/php-wrap-duZ5AN:2
Stack trace:
#0 {main}
```
