### ISSUE TITLE
wp-cli 1.2.0 & 1.2.1 fail to run

### ISSUE THREAD

**Issue by ocasta** [facebook/hhvm#7938]
### HHVM Version
3.18 & 3.20 & 3.21

_hhvm /usr/bin/local/wp --info_ fails with the error

Warning: include(phar://wp-cli.phar//php/boot-phar.php): File not found in /usr/local/bin/wp on line 4

**Comment by ocasta** [comment]
Just to clarify, these versions of wp-cli work fine with php7

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

Also phar support has been removed in hhvm version [4.1.0](https://hhvm.com/blog/2019/04/09/hhvm-4.1.0.html).
