### ISSUE TITLE
Non-hh parent/grandparent warning gets lost in incremental mode

### ISSUE THREAD

**Issue by JarredSimmer** [facebook/hhvm#7948]
### HHVM Version
3.20.3-dev

### Standalone code, or other way to reproduce the problem

Unfortunately this is easiest to explain in a short video rather than static text as it requires a series of steps.

See https://twitter.com/jarebearjarred/status/893203073463537664

### Expected result

The typechecker should detect that the strict file has a non-hh grandparent at the conclusion of the steps in the linked video. This is particularly harmful because when deploying to another machine that new machine will have the typechecker error while the original machine will not have any such error.

### Actual result

The typechecker failed to recognize a strict file with a non-hh grandparent after a specific series of modifications and subsequent undos in the inheritance hierarchy.

**Comment by fredemmott** [comment]
@Sniperlocked : are you able to reproduce this on 3.21? I can't.

I'm seeing:

1. create PHPClass, PartialClass extends PHPClass, StrictClass extends PartialClass, StrictClass2 extends StrictClass, all in separate files
2. run hh_client, see errors about non-hh ancestor for both StrictClass, StrictClass2 (expected)
3. change PartialClass to have no parent
4. change StrictClass2 to have no parent
5. run hh_client, get no errors (expected)
6. Change StrictClass2 to extend StrictClass again
7. run hh_client, get no errors (expected)
8. Change PartialClass to extend PHPClass again
9. run hh_client again
   - me: I get errors in both StrictClass and StrictClass2 (expected)
   - you: you only get errors in StrictClass2
I'm not able to reproduce any of the later issues in the video, and it seems reasonable that they woudl depend on this difference.

**Comment by fredemmott** [comment]
After 1, I have https://gist.github.com/fredemmott/18abad7c91fb90021ad8609ccd461d53

**Comment by fredemmott** [comment]
Also, are you using a VM with bind mounts, or NFS, or similar? hh_server uses inotify to observe changes, and this does not work correctly on NFS-like directories (and by default, hh_client will not start on an NFS directory for this reason)

**Comment by Sniperlocked** [comment]
We currently don't have  3.21 set up on our shared development environment and I don't think we want to upgrade just this moment. I can definitely let you know once we upgrade if we still see this.

One note about the example you linked is that the PHP file differs from my example in that yours is namespaced and mine is not (though I doubt this contributes to the problem).

We are using a VM with bind mounts, but no NFS (unless an AWS storage node would be considered here - I doubt it because as far as I know they look like real disks).

**Comment by fredemmott** [comment]
I had the same problem without namespaces; and yep, vm bind mounts can cause this, even without NFS (some are silently NFS, others just have the same problems)

**Comment by lexidor** [comment]
Does this issue still reproduce in the pure Hack world? (PHP code can not be referenced by Hack and hhvm can't run PHP code anymore.)

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to a mixed php/hack codebase. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
