### ISSUE TITLE
phpBB3 install issue

### ISSUE THREAD

**Issue by zertyuiop** [facebook/hhvm#7949]
### HHVM Version

HHVM 3.21.0
nginx 1.13.0
phpBB 3.2.1

### Standalone code, or other way to reproduce the problem

When installing phpBB on nginx + HHVM after "Server Settings" installation go back to "DB Settings"

### Expected result

After "Server Settings" Installation starts

### Actual result

Installation go back to "DB Settings"

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

This issue applies to running php code on hhvm. Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).

phpBB is a PHP project.
