### ISSUE TITLE
provide new sources and tags

### ISSUE THREAD

**Issue by munix9** [facebook/hhvm#8007]
Is there a chance to provide new sources (http://dl.hhvm.com/source/?C=M;O=D)
and tags (https://github.com/facebook/hhvm/tags) in a reasonable period of time?

On http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/?C=M;O=D there are already packages for
3.21.1, 3.21.2 and 3.21.3, but without corresponding tags and source packages.

Apart from Debian/Ubuntu, other distributions for HHVM are also used.
With regard to bug and security fixes, a timely release would certainly not be wrong.

Thanks.

**Comment by usox** [comment]
The tags for 3.21.1 -> x.x.3 and 3.22.0 are available now

**Comment by fredemmott** [comment]
3.21.(1 and 2) were buggy, so not announced and replaced within a few days.

We try to do this quickly, but we don't want to make the sources available until the binaries are up. We should move to a system where we publish them all at the same time, rather than separately - hopefully I'll be looking at that in Q4.
