### ISSUE TITLE
PHP Fatal error:  Uncaught SoapFault exception: [HTTP] hphp_invoke

### ISSUE THREAD

**Issue by craigcarnell** [facebook/hhvm#8019]
### HHVM Version
HipHop VM 3.22.1 (rel)
Compiler: tags/HHVM-3.22.1-0-ge8ce62608d2d14e6418772b07ebaddcbdb37598f
Repo schema: 05fc45ee8e70c9f18dfb1e867219c8528be87996

### Standalone code, or other way to reproduce the problem
```
<?php
$host = "ahost";

$api_user = 'auser'; // change to valid user
$api_key  = 'akey';  // change to valid api key

$api_url = "https://".$host."/index.php/api/v2_soap/?wsdl";

echo "Connecting to: " . $api_url . PHP_EOL;

$client = new SoapClient($api_url);

$session = $client->login($api_user, $api_key);

try {

    var_dump($client->__getLastRequest());
    var_dump($client->__getLastResponse());

    $result = $client->storeList($session);

    var_dump($result);

}
catch (\SoapFault $e) {

    echo "==> Error: ".$e->getMessage().PHP_EOL;
    exit();

}
```
### Expected result
SOAP output - in this case some stores from Magento

### Actual result
```
PHP Fatal error:  Uncaught SoapFault exception: [HTTP] hphp_invoke in test.php:25
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://xx...', 'urn:Action', 1, 0)
#1 test.php(25): SoapClient->__call('login', Array)
#2 test.php(25): SoapClient->login('xxx', 'xx...')
#3 {main}
  thrown in xx on line 25
```

**Comment by fredemmott** [comment]
Have you checked what the soap error actually is? You're not catching it as $client->login() is outside your try{} block

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue. I am closing this issue, since there is not enough information to reproduce the environment. The exception came from the login method. The information in the exception is too generic to pin point. The exception might depend on what the soap server on the other side does. Even if someone were to reproduce this issue, they wouldn't be able to conclude that they have hit the same issue as you.

When creating an issue that depends on another web service, reproduction is more difficult. Because issues with Soap can't be induced without another server, it would be helpful if the server code were also included.
