### ISSUE TITLE
same-site support in setcookie

### ISSUE THREAD

**Issue by ghost** [facebook/hhvm#8087]
Is there an ETA on when 'same-site' cookie parameter will be supported in hhvm?

See https://wiki.php.net/rfc/same-site-cookie

Thanks!

**Comment by jane42** [comment]
Puss

**Comment by lexidor** [comment]
Edited the description to not mention `\session_start()`, since that has been removed in hhvm [4.4.0](https://hhvm.com/blog/2019/05/06/hhvm-4.4.0.html).

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

Hhvm [nolonger supports running php code](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) since [hhvm version 4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html). PHP compatibility is not a target for hhvm anymore.

The `\setcookie()` function is part of the PHP API surface inherited from the PHP runtime. Every couple of years, a new sub flag is added to cookies (Partitioned comes to mind, but [there are many more](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes).) &lt;opinion>This php api has aged poorly.&lt;/opinion> The PHP project has [added an overload](https://www.php.net/manual/en/function.setcookie.php) that takes an option bag instead of n optional positional paramteters.

Even if the new overloaded signature were adopted, it would still leave users stranded every time a new attribute was added to the web standards. The PHP api exposes the `\header()` function for writing headers by hand. Writing a userland version of setcookie, taking all currently known flags, would be a small task. This would decouple your hhvm version from which cookie flags you are able to set.
