### ISSUE TITLE
Memory leak with empty php

### ISSUE THREAD

**Issue by TeBoring** [facebook/hhvm#8097]
hhvm 3.18.5 on ubuntu14
shell:
```valgrind --leak-check=yes hhvm memory_leak_test.php```
memory_leak_test.php:
```<?php```
Result:
```definitely lost: 553,624 bytes in 4,389 blocks```

**Comment by fredemmott** [comment]
Closing: if this is real (rather than e.g. an interaction between jemalloc) it seems extremely unlikely to be a practical issue: the 'leaked' memory is from loading buildings in hphp_process_init() - this data is loaded once, and used for all requests.

As an aside, 3.18 is scheduled to become unsupported on monday: https://docs.hhvm.com/hhvm/installation/release-schedule

**Comment by TeBoring** [comment]
If I update to a newer hhvm, can I expect no memory leak with the same test above?
If so, which version do you recommend?

**Comment by TeBoring** [comment]
If not, how shall I debug memory leak? I am developing my own extension and the existing memory leak is blocking me debugging.

**Comment by fredemmott** [comment]
You can look through the valgrind output and ignore the ones that come from systemlib and other init; otherwise, https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Leak-Checking may be helpful
