### ISSUE TITLE
dirname() expects exactly 1 parameter, 2 given 

### ISSUE THREAD

**Issue by SilverFoxA** [facebook/hhvm#8144]
### HHVM Version
HipHop VM 3.24.2 (rel)

### Operating System and Version
Ubuntu 17.10

### Standalone code, or other way to reproduce the problem
dirname(__DIR__,2).'/path'

### Expected result
Provide the file path before 2 directory level

### Actual result
Give erro 500

dirname() expects exactly 1 parameter, 2 given (View: /var/www/websites/alpha/resources/views/pages/index.blade.php) {"exception":"[object] (ErrorException(code: 0): dirname() expects exactly 1 parameter, 2 given (View: /var/www/websites/alpha/resources/views/pages/index.blade.php) at /var/www/websites/alpha/storage/framework/views/70f6855c1f72c9c2f2a6ea96ab7ad04a6bcd26f9.php:5, ErrorException(code: 0): dirname() expects exactly 1 parameter, 2 given at /var/www/websites/alpha/storage/framework/views/70f6855c1f72c9c2f2a6ea96ab7ad04a6bcd26f9.php:5)

**Comment by SilverFoxA** [comment]
Is there any solution available or do I need to change the scripts?

**Comment by fredemmott** [comment]
Sorry, you'll currently need to change the script.

**Comment by cmdajy21** [comment]
Text (512 bytes): 201707250941ÿÿÿÿ2,€,¬€P@Ûg»Ð¦¾1z±ÒÜŸC=§¢â?@‘/mÁü-Œø"ïf9.¡ÃHãùÆÝ.Jgw~.‡Ôw)CòoJøÎ†PŒ"@¶.!Jm²=U.)ÅsÁ…þ†×šÔ¯Ù,'O=¾‚C¿Ž{¿,V
È‚ºÖ™>|ýX.*G{Êm*0Å¯FôMî^UI¸É’2.qC±<CP.Ç—^X¢î´>ý˜ˆ+I
à.Q‚p‰Ø	õ=®«Ñÿ]Î™/.EùÁBÂ«Ô#ÅtBç¬—BI#²¡Ô0ÉëÝöˆ‰˜”ù“|HÝÚ“<À×üZ.>÷M?k{…\b…ÔŒÝÿÿÿÿ2ÿÿÿ!00ÿÿÿÿÿÿÿÿÿÿÿÿH€óˆH€GH€GIG  µ0ƒ0}0pµFFFàÌÅ>.úÒ.ÓÌÅ>.ÓÌÅ6à!x)pdmvùÒp½þçpGµðªøðÿðôÿðsúðûHx(ÑðOùð^ù.ððù.ðOù ½µðhø½\ øJ.BÙ ÀCpGöJPa .a...   coment faire pour decrypter sa ici

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version 4.0.0.

The current behavior, although different, is not buggy or broken. The second argument of dirname is convenient, but the same result can be achieved by calling dirname twice. A userland implementation with the second argument is a couple of lines.
