### ISSUE TITLE
Exiting server. Last used >7 days ago

### ISSUE THREAD

**Issue by lexerel** [facebook/hhvm#8189]
### HHVM Version
3.15.3

### Operating System and Version
ClearOS 7.4.0

### Standalone code, or other way to reproduce the problem
I am using a prebuilt HHVM CentOS package as a FastCGI under Apache. After a week or more after HHVM service launch, server automatically stops. In the log I can see a message `Exiting server. Last used >7 days ago`. Is it a server configuration or service launch script problem?

**Comment by fredemmott** [comment]
3.15 is unsupported - see https://docs.hhvm.com/hhvm/installation/release-schedule - and we don't support CentOS.

- are you able to reproduce the problem with a supported version of HHVM?
- if so, are you able to get an error message *from HHVM itself* rather than the service scripts? If not, you will need to try to get help from the provider of your packages.

**Comment by usox** [comment]
@lexerel If you need a more recent prebuild hhvm version for centos7:
http://devblues.de/centos/7/x86_64/hhvm/

**Comment by lexerel** [comment]
Very much appreciated, @usox. Installed the update, checking, if update solved the problem.

**Comment by lexerel** [comment]
Seems to be working fine after update.
