### ISSUE TITLE
hhvm crash on opening

### ISSUE THREAD

**Issue by marcodepolo** [facebook/hhvm#8219]
### HHVM Version
3.21 and 3.24
> Please include the output of `hhvm --version` and `hh_client --version`
root@becc37204cb6:/var/www/html# hhvm --version
HipHop VM 3.24.7 (rel)
Compiler: 1525451073_403239978
Repo schema: 1c622cfd34e82ac2c279b29ed5509e38ce86eb84

root@becc37204cb6:/var/www/html# hh_client --version
hh-07ec0d8e77593042b6de0688f9f1fba076ade535-3.24.7 Fri May  4 16:26:08 2018

### Operating System and Version
debian jessie (in docker image php:5.6-apache-jessie)
> For example, 'Debian Squeeze', 'Ubuntu 16.04', 'MacOS High Sierra'. Please
> also mention if you are using Docker or similar images.

### Standalone code, or other way to reproduce the problem
start using supervisord and the following command
[program:hhvm]
command=/usr/bin/hhvm --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini --user www-data --mode daemon -d hhvm.server.type=fastcgi -d hhvm.server.port=9000 -vPidFile=/var/run/hhvm/pid

### Actual result
hhvm crashes on opening with no output

### Expected result
until 3.18 hhvm didn't have trouble to run but seem to have become less stable for me in the latest versions. I want to upgrade but 3.21 or 3.24 crash on opening and 3.25 says package not found

do I have to upgrade to stretch ?

log output doesn't help, I only see this so no clue why it crashes at launch
cap_set_proc failed: Operation not permitted
cap_set_proc failed: Operation not permitted
cap_set_proc failed: Operation not permitted

**Comment by gregtampa** [comment]
im hacing same issue after rm the cache when i went to update the rules using advise found here: 
https://github.com/facebook/fbctf/issues/476

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones are very unlikely to be worked on.

This issue has been created some time ago and there is not enough information in this issue to reproduce this issue on a modern build of hhvm. I am closing this issue, since asking for more info and adding a _`needs-more-info`+`no-isolated-repro`-combo_ would turn a large percentage of hhvm's issues into this kind of issue. If you are reading this and have a way to reproduce this issue in a modern hhvm version, feel free to open a new issue.
