### ISSUE TITLE
bufferoverflow()

### ISSUE THREAD

**Issue by RootUp** [facebook/hhvm#8231]
Hi Team, 

`https://github.com/facebook/hhvm/blob/master/hphp/hack/src/fsevents/fsevents_stubs.c#L417`

i.e

`char *rpath = realpath(String_val(path), NULL);`

This function does not protect against buffer overflows, and some implementations can overflow internally references such as (CWE-120/CWE-785!).

Ensure that the destination buffer is at least of size `MAXPATHLEN` and to protect against implementation problems, the input argument should be checked to ensure it is no larger than `MAXPATHLEN`.

Request team to please have a look and advise.

Thank you 
Dhiraj

**Comment by Orvid** [comment]
`MAXPATHLEN` is the wrong value to use for the primary platforms HHVM supports, as linux defines this particular function in terms of `PATH_MAX`. Solaris and 4.4BSD define it as `MAXPATHLEN`, but neither are platforms HHVM supports, and both values (I believe) are the same on modern systems. 

Ignoring that, this instance of `realpath` will never overflow because `realpath` is allocating the buffer itself, and is specified to error when processing if the output is larger than `PATH_MAX`.
