### ISSUE TITLE
Reflection classes returning `HH\int` (and others) instead of `int`

### ISSUE THREAD

**Issue by bredman** [facebook/hhvm#8254]
### HHVM Version

```
bredman@slack-dev191:~/test$ hhvm --version
HipHop VM 3.26.3 (rel)
Compiler: remotes/origin/3.26.3-slack-0-gcea63133cb066ebff74f9fc42789fa2017beab55
Repo schema: 53a25f78844beabb2a017f2bcb782ce1b224d04c
bredman@slack-dev191:~/test$ hh_client --version
hh--3.26.3 Thu May 24 12:37:36 2018
bredman@slack-dev191:~/test$ hhvm --info | grep php7
hhvm.php7.all => 1
hhvm.php7.builtins => 1
hhvm.php7.deprecation_warnings => 1
hhvm.php7.disallow_unsafe_curl_uploads => 1
hhvm.php7.engine_exceptions =>
hhvm.php7.int_semantics => 1
hhvm.php7.ltr_assign => 1
hhvm.php7.no_hex_numerics => 1
hhvm.php7.scalar_types => 1
hhvm.php7.substr => 1
hhvm.php7.uvs => 1
bredman@slack-dev191:~/test$
```

### Operating System and Version

> Ubuntu 16.04.03

### Standalone code, or other way to reproduce the problem

```
<?hh

class BaseClass {
        protected static function _addItem(int $id): void { }
}

function main(){
        $reflection = new ReflectionClass("BaseClass");
        var_dump((string)$reflection->getMethods()[0]->getParameters()[0]->getType());
        echo "DONE\n";
}

main();
```
### Actual result

```
bredman@slack-dev191:~/test$ hhvm class-test.php
string(6) "HH\int"
DONE
bredman@slack-dev191:~/test$
```

### Expected result

We should be getting back the bare type `int` under PHP7

**Comment by lexidor** [comment]
This is indeed quite bugging, but it was done for PHP 5 support. PHP 5 does not have scalar types, so `int` was defined in the `HH\` namespace and autoimported.

**Comment by lexidor** [comment]
Hi, I am reading HHVM issues to see which issues are unlikely to be fixed.

This issue was created because HHVM's behavior was/is different from PHP's. HHVM stopped striving from php compatibility with the release of version 4.0.0.

The current behavior, although different, is not buggy or broken. It's just exposing some internals to the surface. Changing it now would not aid anyone in migrating a php codebase. All hack code that uses this api already checks for the HH name. I don't think it'd be worth the BC break to change this.
