### ISSUE TITLE
realpath php5/7 incompatibility 

### ISSUE THREAD

**Issue by timmahrt** [facebook/hhvm#8298]
### HHVM Version

> Please include the output of `hhvm --version` and `hh_client --version`

hhvm --version

HipHop VM 3.27.2-0brew (rel)
Compiler: 1534357986_N
Repo schema: 7ab0ba25c8d94beef7ef5fbd11ab64abe3c833e9

hh_client --version
hh-355245a4be3cebbd16a4604ca1233bdba6d0e604-3.27.2 Thu Aug 16 03:35:18 2018

### Operating System and Version

> For example, 'Debian Squeeze', 'Ubuntu 16.04', 'MacOS High Sierra'. Please
> also mention if you are using Docker or similar images.

MacOS High Sierra

installed from brew today

### Standalone code, or other way to reproduce the problem

> This should not depend on installing any libraries or frameworks. Ideally, it
> should be possible to copy-paste this into a single file and reproduce the
> problem by running `hhvm` and/or `hh_client`

```
<?php
#
echo(realpath('./non_existent_dir_name/..'));
echo('<br />');
echo(realpath('./existent_dir_name/..'));
```
### Actual result

> If applicable, please copy-paste output from `hhvm` or `hh_client`

```
/Users/timmahrt/test
<br />
/Users/timmahrt/test
```
### Expected result

(Tested in php 5.3, 5.4, 5.5, 5.6, 7.0)
```
<br />
/Users/timmahrt/test
```

## Explanation

realpath() returns false if a directory does not exist.  php seems to be resolving existence one directory at a time in a URL.  HHVM however resolves `..` and `.` in the URL before testing existence.

eg

php with input `./ok_dir/non_existent_dir_name/..`
```
1) '.' (exists)
2) './ok_dir/' (exists)
2) './ok_dir/non_existent_dir_name' (does not exist, do not process the rest of the url, return false)
```

php with input `./ok_dir/ok_dir2/..`
```
1) '.' (exists)
2) './ok_dir/' (exists)
3) './ok_dir/ok_dir2' (exists)
4) './ok_dir/ok_dir2/..' ('..' detected; resolve) -> './ok_dir/'
5) (we've consumed all input, return the absolute path location of './ok_dir')
```

hhvm `./ok_dir/non_existent_dir_name/..`
```
1) resolve '..' in input
 './ok_dir/nonexistent_dir_name/..' -> './ok_dir'
2) Test existence
'./ok_dir' (exists)
3) (we've consumed all input, return the absolute path location of './ok_dir')
```

**Comment by lexidor** [comment]
This issue as described and its repro are still 100% applicable. This issue was filed because the behavior of hhvm did not match the behavior of php. Hhvm has departed from php compatibility in version 4.0.0. The current behavior, although different, isn't buggy or broken.

If this issue were fixed in hhvm 3.xx.x (when porting a php app to hhvm was possible), this would have been a great step towards full compatibility. Changing it now would break existing Hack code with no obvious benefit. The more lax behavior of realpath has been like this for years.

If this issue is still relavant to you or to anyone else reading this, please open a new issue.
