### ISSUE TITLE
array_walk_recursive segfault with hack arrays inside php arrays

### ISSUE THREAD

**Issue by ssandler** [facebook/hhvm#8375]
### HHVM Version

```
$ hhvm --version
HipHop VM 3.29.0-0brew (rel)
Compiler: 1540227110_N
Repo schema: 8804f12e93815259de749013e1e6c7bfe9e9bda7
```

### Operating System and Version

MacOS High Sierra

Also reproduced on Ubuntu 16.04 with HHVM 3.28.3

### Standalone code, or other way to reproduce the problem

```
<?hh
$a = array(
  'a' => vec[1, 2, 3],
);
array_walk_recursive(
  &$a,
  function($key) {
    print($key);
  },
);
```

### Actual result

```
Core dumped: Segmentation fault: 11
```

### Expected result

`123` (I think?) or at least a fatal or some other error logged about not allowing Hack arrays.

**Comment by enjmusic** [comment]
This segfault is coming from the fact that the check for whether or not to recurse in [`ArrayUtil::Walk`](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/array-util.cpp#L517) uses the function `isArray`, which permits recursive calls on `vec`, `dict`, etc. 

However, when the `MArrayIter` in the recursive call goes to get the data from the `vec` in [`MArrayIter::getData`](https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/array-iterator.h#L451), it returns `nullptr` if `isArrayType` isn't satisfied. This check only allows PHP-style arrays, so any `vec`s or `dict`s that slipped through the first recursion check cause segfaults here when the returned data is used.

It feels like emitting a fatal error for arrays passed into `array_walk_recursive` that happen to have `vec`s or `dict`s in them is the wrong move, which leaves 2 possible fixes:

1. Restrict recursion to only PHP-style arrays by changing the check in `ArrayUtil::Walk` to use `isPHPArray` instead of `isArray`.

2. Allow recursion on `vec`s and `dict`s but prevent segfaults in `MArrayIter::getData` by changing `isArrayType` to `isArrayLikeType`.

**Comment by alexeyt** [comment]
2 won't work, because MArrayIter creates references in the array it is walking, and references are forbidden in hack arrays (if we ignore the restriction and create references we'll just crash in a different way).
I think we'll have to either ignore hack arrays we find while recursing, or throw when we find one (IMO the latter is better).

**Comment by alexeyt** [comment]
array_walk and array_walk_recursive were re-implemented in hack (without the magic ref behavior); among other things that also resolved this crash. array_walk_recursive now rejects hack arrays nested in other arrays without ever calling the callback. There is now a unit test for this: test/slow/array_walk_recursive.php
