### ISSUE TITLE
apt-get update fails with certificate error

### ISSUE THREAD

**Issue by miroirdelame** [facebook/hhvm#8393]
Hello,

i'm running HHVM 3.24.8 under Ubuntu 14.04 LTS, using the repository trusty-lts-3.24 with apt-get.
By the last 10 days, apt-get update keeps triggering the same error :

`W: Impossible de récupérer https://dl.hhvm.com/ubuntu/dists/trusty-lts-3.24/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

The HHVM repo is the only one I have issues with.
What should I do in order to solve this ?

[EDIT] : already tried to remove and reinstall ca-certificates, already tried update-ca-certificates too

Thanks in advance for your kind help.

**Comment by Wilfred** [comment]
The certificate looks correct to me:

```
$ curl -I https://dl.hhvm.com/
HTTP/2 200 
```

What happens if you run the above command on your machine?

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

I am closing this issue, since only applied to ubuntu 14.04 and support for ubuntu 14.04 has been dropped with the release of hhvm [4.20.0](https://hhvm.com/blog/2019/08/27/hhvm-4.20.0.html). There are no current version of hhvm older than hhvm 4.20.0 which are supported.
