### ISSUE TITLE
SlowTimer [61008ms] at curl: https://hostname/captcha.xml

### ISSUE THREAD

**Issue by sachinbanugariya** [facebook/hhvm#8450]
### HHVM Version
HipHop VM 3.15.3 (rel)
Compiler: tags/HHVM-3.15.3-0-g965cd8d30670726d88720412c3384225a2da011d
Repo schema: 7f22464926cb7fc3a19c6af88309c612a8581c55

### Operating System and Version
CentOS Linux release 7.6.1810 (Core)
> also mention if you are using Docker or similar images.
no we are not using any docker image

### Standalone code, or other way to reproduce the problem
i dont know how you can reproduce this problem

### Actual result
its not seems from code issue.

### Expected result
need to remove slowtimer issue,
because of this issue sites seems much loading or sometime gives nginx error page.

#### issue detail.###########
our website running with elgg and nginx use.

hopefully its not related code as because https://hostname/captcha.xml is our api from another server which is working fine.

some time our site gives backend error log like:
SlowTimer [61008ms] at curl: https://hostname/captcha.xml

where https://hostname/captcha.xml is the our other server api which is working fine if we fire in browser,
also working fine in our web server in which our website hosted using curl command.

if i set hhvm.http.slow_query_threshold = 10000 log seems like
SlowTimer [10008ms] at curl: https://hostname/captcha.xml

and if i set hhvm.http.slow_query_threshold = 60000 log seems like 
SlowTimer [61008ms] at curl: https://hostname/captcha.xml

that means whatever timeout i will increase it still same.

so please let me know where is issue or how can i debug error or solve it.
thanks

**Comment by sachinbanugariya** [comment]
need to restart hhvm after some time, then only website run for sometime then again gives nginx error so then again need to restart hhvm.

**Comment by fredemmott** [comment]
- both 3.15 and centos are unsupported
- these logs are merely indicating extremely slow curl requests - this almost always means that the site you are curling is slow to respond, not an issue with HHVM.

You are likely needing to restart HHVM because `https://hostname/captcha.xml` is taking > 1 minute to respond, and you're eventually ending up with all request threads waiting for it.

Things to do:
- if you control `https://hostname/captcha.xml`, check hoew long it's actually taking to respond. If there's a load balancer, check those logs.
- set a curl timeout in the code making the request. Changing the slow_query_threshold just changes how long it takes for HHVM to log a warning about this, it doesn't affect an actual timeout
- try using a supported version of HHVM (3.27, 3.30, or 4.0)

Marking 'needs more info' as right now there is not an indication of an HHVM problem, and the issue is for an unsupported configuration.

**Comment by sachinbanugariya** [comment]
ok, thanks for guide, let me try to debug as per you said,
if not fixed by this then let me again ping here, thanks.
