### ISSUE TITLE
[RAM usage | Memory leak?] `HH\Asio\join` consumes infinite memory in an async function with repeated invocation

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8584]
### HHVM Version

```
HipHop VM 4.26.0 (rel)
Compiler: 1570480091_055726735
Repo schema: e24c730ecd4902e383877e9e82598459f02b76f6
```

### Operating System and Version

`Ubuntu 18.04`

### Standalone code, or other way to reproduce the problem

*I understand that you will never find this code in a well designed codebase.*
This code is intentionally bad.

`$ hhvm main.hack`

```HACK
<<__EntryPoint>>
/*async*/ function main_async(): Awaitable<void> {
    while (true) {
        for ($i = 0; $i < 100000; $i++) {
            HH\Asio\join(HH\Asio\later());
        }
        echo memory_get_peak_usage().' bytes'.PHP_EOL;
    }
}
```

### Actual result

Without _async_:
```
2097152 bytes
2097152 bytes
2097152 bytes
...
2097152 bytes
2097152 bytes
2097152 bytes
```

With _async_
```
6291456 bytes
12582912 bytes
18874368 bytes
...
8285847552 bytes
8292139008 bytes
8298430464 bytes
```

### Expected result

RAM usage should not be climbing without end.

**Comment by lexidor** [comment]
```HACK
<<__EntryPoint>>
async function main_async(): Awaitable<void> {
    while (true) {
        for ($i = 0; $i < 100000; $i++) {
            await HH\Asio\later();
        }
        echo memory_get_peak_usage().' bytes'.PHP_EOL;
    }
}
```

```
2097152 bytes
2097152 bytes
2097152 bytes
...
2097152 bytes
2097152 bytes
2097152 bytes
```

**Comment by fredemmott** [comment]
Join does need to create a new context, but I would have expected that to be cleaned up

**Comment by jano** [comment]
What happens here is that when HH\Asio\later() runs, we are still in the root context constructed by HH\Asio\join() in the EntryPoint trampoline (if it is async). So, the newly constructed RescheduleWaitHandle gets registered with that context. If you HH\Asio\join() it, it will get imported into the child context, but it also stays registered in a priority queue of the root context. It will get cleaned up either once the RescheduleWaitHandle's priority level clears in the root context (e.g. the root context gets blocked on I/O), or upon termination of the root context (program exit in the case of <<__EntryPoint>>). Example:

```
<<__EntryPoint>>
async function main_async(): Awaitable<void> {
    while (true) {
        for ($i = 0; $i < 100000; $i++) {
            HH\Asio\join(HH\Asio\later());
        }
        // RescheduleWaitHandles will be cleared at this point
        await HH\Asio\usleep(10000);
        echo memory_get_peak_usage().' bytes'.PHP_EOL;
    }
}
```

In theory, we can remove RescheduleWaitHandle from the parent context when importing it into the child context so that it can be freed earlier, but in practice, this should not be an issue, as HH\Asio\join() is not intended to be used outside of an entry point (or at least not heavily).

**Comment by lexidor** [comment]
@jano, thanks for unfolding this for me. This is indeed a very unlikely and torturous scenario. As you alluded to, this use of `\HH\Asio\join()` is not intended to be used this way. I thought I had stumbled upon something, but hhvm's behavior is perfectly fine as you described it.

As far as I am concerned, this issue can be closed.
