### ISSUE TITLE
no folder /opt/hhvm and so no install_fastcgi.sh file

### ISSUE THREAD

**Issue by m3fist0** [facebook/hhvm#8709]
after installing hhvm i dont see install_fastcgi.sh file to configure nginx at all. 
hhvm installled from package by instructions:

```
apt-get update
apt-get install software-properties-common apt-transport-https
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94

add-apt-repository https://dl.hhvm.com/ubuntu
apt-get update
apt-get install hhvm

```

OS : ubuntu 18.04

**Comment by lexidor** [comment]
On my machine, I can find install_fastcgi.sh at `/opt/hhvm/4.56.0/share/hhvm/install_fastcgi.sh`.
What happens when you type `which hhvm` in console?
If all has gone well, it should respond with `/usr/bin/hhvm`.

**Comment by lexidor** [comment]
Could you also include the output of `sudo apt-get install hhvm` in your post?

**Comment by m3fist0** [comment]
which hvvm result:
`/usr/bin/hhvm`


sudo apt-get install hhvm result:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hhvm is already the newest version (3.21.0+dfsg-2ubuntu2).
The following packages were automatically installed and are no longer required:
  fsharp galera-3 libconfig-inifiles-perl libdbi-perl libfsharp-core4.5-cil
  libglib2.0-cil-dev libgtk2.0-cil-dev libnvidia-cfg1-430 libnvidia-common-430
  libnvidia-compute-430 libnvidia-compute-430:i386 libnvidia-decode-430
  libnvidia-decode-430:i386 libnvidia-encode-430 libnvidia-encode-430:i386
  libnvidia-fbc1-430 libnvidia-fbc1-430:i386 libnvidia-gl-430
  libnvidia-gl-430:i386 libnvidia-ifr1-430 libnvidia-ifr1-430:i386
  libqscintilla2-qt5-13 libqscintilla2-qt5-l10n libreadline5
  libterm-readkey-perl nvidia-compute-utils-430 nvidia-dkms-430
  nvidia-kernel-common-430 nvidia-kernel-source-430 nvidia-utils-430
  xamarin-gtk-theme xserver-xorg-video-nvidia-430
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 251 not upgraded.
```

**Comment by lexidor** [comment]
I see what happened. The hhvm version packaged by your distro maintainer is really outdated and apt didn't look in the dl.hhvm.com repository. Hhvm versions move really fast. Versions 3.22 to 3.30 and 4.0 to 4.59 have been released since then. See the [blog](https://hhvm.com/blog) for the breaking changes. I highly recommend [this post](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html) in particular. The oldest supported version is 4.32.

In order to get a more modern version of hhvm, you need to point apt to dl.hhvm.com. Your first post says you've already done this, but something must have gone wrong. Could you please include the terminal output of that step too? Be sure to include `apt purge hhvm` before the first step. Make sure to run them as root using `sudo su`.

**Comment by lexidor** [comment]
Closing issue. Fastcgi.sh has moved to a different directory. Older versions packaged by distro maintainers are very old and may use an older/different directory structure.
