### ISSUE TITLE
_OS\poll_async() on non-blocking server socket blocks forever after _OS\accept() and _OS\close()

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#8716]
**Describe the bug**

Best done by example code below. Also applies to resources/stream_await()

**Standalone code, or other way to reproduce the problem**

```hack
use namespace HH\Lib\_Private\_OS;
<<__EntryPoint>>
async function main(): Awaitable<void> {
  $sin = new _OS\sockaddr_in(0, _OS\INADDR_LOOPBACK);
  $server = _OS\socket($sin->sa_family, _OS\SOCK_STREAM, 0);
  _OS\bind($server, $sin);
  _OS\listen($server, 128);

  _OS\fcntl($server, _OS\F_SETFL, (_OS\fcntl($server ,_OS\F_GETFL) as int )| _OS\O_NONBLOCK);
  try {
    _OS\accept($server);
  } catch (_OS\ErrnoException $e) {
    invariant($e->getCode() === _OS\EAGAIN, 'unexpected errno');
  }


  $poll = _OS\poll_async($server, \STREAM_AWAIT_READ, 0);
  _OS\close($server);
  await $poll; // blocks forever
}
```

**Expected behavior**

`poll_async()` fails with` \STREAM_AWAIT_CLOSED`

**Actual behavior**

Blocks forever

**Environment**

 - Operating system: MacOS Catalina, Ubuntu 20.04
 - Installation method: homebrew, FB packages
 - HHVM Version: 4.59.0

**Additional context**

Originally filed as https://github.com/hhvm/hsl-experimental/issues/131

@jano : it looks like this is basically undefined behavior in the C++ side given the threading; I think that HHVM should track the `FileAwait`'s associated with each FD/resource, and either:
1. make the close call fail if any are pending, and provide a way to wait for them all
2. make the close() call cancel the fileawaits  - the stream_await()\poll_async() calls should fail with STREAM_AWAIT_CLOSED

IMO (2) is the correct solution - does it sound sane? I think this would be similar to the timeout cancellations - something like `runInEventThreadBaseAndWait(for(const auto& fa : m_fileawaits): fa.setFinished(FileAwait::CLOSED) }` ?

**Comment by jjergus** [comment]
The workaround seems to introduce another ugly edge case. To reproduce, in hsl-experimental:

```
vendor/bin/hacktest tests/tcp/HSLTCPTest.php tests/unix/HSLUnixSocketTest.php
# blocks forever (may not reproduce reliably on all systems)
```

My working theory is that when we "cancel" the awaitables, we don't actually cancel the underlying syscall, so it's still accepting connections. But calling `close()` frees up the FD for reuse. Running the hsl-experimental tests in the above order causes a FD to be reused (again, may not reproduce reliably on all systems) but when the client tries to connect, the old accept call (which is still waiting and has the same FD) accepts the connection instead of the new server from HSLUnixSocketTest, which blocks forever. I wasn't able to verify that the old accept call actually accepts the connection so that part is just my hypothesis.

I do have a very hacky proof of concept diff that "fixes" it. HHVM and hsl-experimental patch here: https://gist.github.com/jjergus/df568edd7cc02a39442217eb9861caf7

Calling `shutdown()` seems to cause the accept call(s) to unblock and fail with `EBADF`. But

- this seems to be undocumented behavior so probably not portable
- it doesn't even work reliably, it still block forever about 1/10 times when I tested (probably a race condition, the accept calls sometimes don't fail quickly enough?)

The correct solution is probably something along the lines of

- _OS\close sends a signal to any thread(s) that have blocked accept() calls so they can stop them
- _OS\close should probably also wait for those thread(s) to confirm that they have done so, to avoid race conditions if the FD gets reused very quickly

**Comment by fredemmott** [comment]
No threads literally have a blocking accept - the FD has O_NONBLOCK set, the accept returns immediately. The async part uses a platform-specific interface that is meant to be equivalent to a poll/select - O_NONBLOCK is defined as something like “when a connection is accepted, select() will indicate it’s ready for read” (might not literally be that, but along those lines)

In practical terms, what might need doing is making sure that the fd is no longer in the set of FDs that it’s actively watching

**Comment by fredemmott** [comment]
Also i don’t think this should be specific to accept - AIUI it should be anything with a pending awaitable

There is no specific awaitable for accept - after accept, we wait for read - which doesn’t literally mean waiting for readable data, it’s just how the man page for accept says it indicates accept completed

**Comment by jjergus** [comment]
Sorry when I said "blocked" I didn't actually mean "blocked" :) I meant there is still an active poll/select/whatever libevent does for the now-invalid (and reused) FD.

But I've been investigating more today (sorry, I couldn't help it) and I think my original hypothesis wasn't quite correct. I thought libevent would invoke the callback for the old "not quite cancelled" event instead of the new one, but it looks like it invokes neither callback, there's no event triggered at all by the client connecting to the unix socket, huh.

I don't understand why it works this way (I guess it's some "undefined state" like you said) but I was able to fix it by making sure that we call libevent's event_del just before we cancel the awaitables (normally this gets called from the destructor, but in this case the destructor gets called way too late after the FD has already been reused).

This is the hhvm + hsl-experimental patch (still kinda hacky but closer to what I'd expect to be a correct solution): https://gist.github.com/jjergus/ff131a33772486d2b011faf56baf33c6
