### ISSUE TITLE
hh_client errors on HSL require

### ISSUE THREAD

**Issue by LiangRongguo** [facebook/hhvm#8748]
I was following the instruction in [Getting Started: Starting A Real Project
](https://docs.hhvm.com/hack/getting-started/starting-a-real-project)

After I ran `composer require hhvm/hsl hhvm/hhvm-autoload` and `composer require --dev hhvm/hhast hhvm/hacktest facebook/fbexpect`, there were hh_client errors that were related to the HSL packages. 
:( It is really confused that the built-in libraries have hh_client errors. How can we fix this?

## What I have tried
I have tried to add something like `allowed_fixme_codes_strict = 123, 456` to get rid of these errors, but it doesn't clean all errors.

## Context:
I was running it on the Ubuntu VM on Windows.

**Comment by lexidor** [comment]
Hi, this problem has been [reported last week](https://github.com/hhvm/user-documentation/issues/904#issuecomment-678474028).
I have not gotten around to adding the extra steps required to the documentation.

The steps are:
 - Get the [jq script](https://gist.github.com/fredemmott/6fe221cacc1221b84264b2a476eaa2a7) from the [hhvm 4.62 blogpost](https://hhvm.com/blog/2020/06/16/hhvm-4.62.html) and place it at the root of your project.
 - Install jq version 1.6 or greater. (The default for Ubuntu is 1.5, I believe).
 - Invoke: `hh_server --check . --json | jq -r "$(<allowed-fixmes.jq)" >> .hhconfig`

I can save you the time and tell you which other directives you need, since you've told me your dependencies.
You'll need:
```
allowed_decl_fixme_codes=2053,4045,4047
allowed_fixme_codes_strict=2011,2049,2050,2053,4027,4045,4047,4106,4104,4107,4108,4110,4128,4135,4188,4200,4240,4248,4297,4323
```

If you are getting any more errors, you'll have to add them to `allowed_fixme_codes_strict` first.
If they don't go away and the error message says, `You cannot use ... to suppress error xxxx in declarations`, add that code to `allowed_decl_fixme_codes`.

I hope this helps, we should have this documented in more places soon.
