### ISSUE TITLE
Likely missing a generic in Coeffects extension php file

### ISSUE THREAD

**Issue by lexidor** [facebook/hhvm#8837]
The following two functions take a function type that returns `HH\Coeffects\Tout`. Are you missing a `backdoor<Tout>(...` here?

https://github.com/facebook/hhvm/blob/5fc855b21c1f62a456fc8c7a40421e0ec23f09ca/hphp/runtime/ext/hh/ext_hh.php#L569-L585

**Comment by oulgen** [comment]
Yes, the generic parameter is missing but that being said the runtime does not use erased (non-reified) generics and the typechecker does not typechecke these files (this function is purposefully left out of HHI since it is not meant to be used without overriding the typechecker).

Lack of the generic shouldn't affect anything.
