### ISSUE TITLE
json_decode not typed explicitly as mixed

### ISSUE THREAD

**Issue by muglug** [facebook/hhvm#8842]
This code is allowed to execute:

```hack
function foo(string $str): int {
  $a = json_decode($str);

  echo $a->foo + $a + $a[0] + $a();
  return $a;
}
```

Whereas this code 

```hack
function foo(string $str): int {
  $a = json_decode_mixed($str);

  echo $a->foo + $a + $a[0] + $a();
  return $a;
}

function json_decode_mixed(string $str): mixed {
  return json_decode($str);
}
```

Generates expected errors.

Not sure whether or not this is by design, but it feels like a bug.

**Environment**
 - MacOS Catalina
 - HHVM 4.111.0

**Comment by muglug** [comment]
The function is typed as returning `mixed` here: https://github.com/facebook/hhvm/blob/5fc855b21c1f62a456fc8c7a40421e0ec23f09ca/hphp/runtime/ext/json/ext_json.php#L36-L40

**Comment by lexidor** [comment]
Hi muglug. _I do not represent the project in any capacity. These statements may be partially false._

You have (re)discovered the fairly undocumented type `TAny` (also known as `_`, typename of hovering over `TAny` in vscode). This type is unsound, as it unifies with everything and permits any and all operations. This type stems from the early days of Hack. In order to allow projects to granuarly adopt Hack's typesystem, there had to be an escape hatch type. If you didn't specify a parameter, return or member type, Hack would implicitly assume `TAny`. You can do anything with (and to) a value of type `TAny` without getting an error from the typechecker. The definition you found of json_decode is the definition used by the runtime. There is a separate (and notably different) definition in the hack/hhi directory. This json_decode is missing a return type, ergo `TAny`. The typechecker can only see this hhvm-hack-interface (hhi) file. If this file got updated now, every user of Hack would have their projects broken, since this function is extremely common. I am doubtful a PR adding an explicit mixed there would be accepted.

`TAny` will have to be removed from Hack some day to become a completely sound type system, but we still have to deal with it for now. I would suggest wrapping this type unsafe function in one that returns mixed yourself. You can then use either hhvm/type-assert or `as dynamic` to use the value. TypeAssert is more correct, but incurs a not insignificant runtime overhead. As dynamic is less correct, but incurs no overhead. See docs.hhvm.com for more information on `dynamic`.

**Comment by lexidor** [comment]
I am closing your issue, not because this isn't something important, but because this is something well known to the developers of the typechecker. If there are other (less ubiquitous) functions which return a `TAny` and you would want them fixed, feel free to open an issue of PR. Just keep in mind that cases which are likely to break (nearly) every Hack project out there are less likely to be accepted. Functions which return something expected on a successful invocation, but false on failure can sadly not be annotated with anything.
