### ISSUE TITLE
Docker for Mac (ARM64) cannot run Hack scripts

### ISSUE THREAD

**Issue by muglug** [facebook/hhvm#8951]
Related to https://github.com/facebook/hhvm/issues/8875

In Docker for M1 Macs `hhvm --version` works, but HHVM fails when executing scripts or running in interactive mode.

Running

```
docker pull hhvm/hhvm:4.128.0
docker run --tty --interactive hhvm/hhvm:4.128.0 /bin/bash -l
hhvm -a
```

gives a segmentation fault, seemingly due to phpimagick:

```
Type: Segmentation fault
Runtime: hhvm
Version: 1632239621_499532144
DebuggerCount: 0


------------------------------hphp_compiler_parse-------------------------------
/:systemlib.phpimagick

-------------------------------Treadmill Information----------------------------
OldestStartTime: 0
InflightRequestsSize: 0

# 0  0000004000ef94ce
# 1  00000040012b55b6
# 2  0000004007d383c0
# 3  000000400186d467
# 4  00000040018efb1c
# 5  0000004000eacd3b
# 6  00000040018c7601
# 7  00000040018c76fc
# 8  000000400235a903
# 9  000000400235acff
# 10 0000004002622753
# 11 0000004002357cc1
# 12 000000400136d1f0
# 13 0000004001374e2e
# 14 0000004001377343
# 15 0000004000e73aa5
# 16 00000040098160b3
# 17 0000004000e707ae
```

**Comment by fredemmott** [comment]
I'm sorry, but given this works on real x86_64 hardware, we have to consider this a bug in whatever emulation/compatibility layer is being used.

While we do not currently consider M1 macs a supported platform via any means:
- in the future, we intend to support them via native AARCH64 support
- some users have reported success with installing intel homebrew, then using `brew tap hhvm/hhvm; brew install --install-from-source hhvm`; our bottles differ from this because they are built with `--bottle-arch=sandybridge`, which gives a 20x real-time speedup in common real-world use cases. This also makes the binaries incompatible with rosetta2 due to use of avx2

**Comment by muglug** [comment]
After assistance from @fredemmott, this worked for me in a fresh nightly:

```
apt-get update
apt-get install binutils
echo "<?hh" >empty.hack
objcopy --update-section ext.8cd6d83ea0d1=empty.hack --update-section ext.34d18fab9e8a=empty.hack $(which hhvm)
```
