### ISSUE TITLE
how to use hfsort with hhvm4.147.0

### ISSUE THREAD

**Issue by limibo777** [facebook/hhvm#8997]
**Describe the bug**
I want to use hfsort for my cpp program,but when I follw the guide in hhvm/hphp/tools/hfsort/README.md , there are some problems with oss-performance , some errors occured when I run hhvm perf.php, then I found that hhvm4.147.0 seems do not support php , so I cant use the hfsort as it is used in the  hhvm/hphp/tools/hfsort/README.md , how should I use the hfsort with 4.147.0?
**Environment**
 - Operating system
Debian 11
 - Installation method
built from source
 - HHVM Version
HipHop VM 4.147.0-dev (rel) (non-lowptr)
.

**Comment by lexidor** [comment]
The oss-performance tools have been archived. The tools themselves are written in Hack (not PHP), so that should still run. (Try `hh_client` to see if your hhvm version could run the Hack code.) You'll not be able to benchmark php code on hhvm, correct.

Sorry that your question has been sitting here unanswered for a year. Chances are you've moved on. Don't feel pressure to reply.

If you still want to use hfsort, you could reopen this issue. Make sure to include the `there are some problems` you've found in your reply. I could lend you a hand on the Hack/HHVM side if you have some Hack error or a Hack exception. I will not be able to help with the C plus plus side of things, I am afraid.
