### ISSUE TITLE
How do I run BOLT on a benchmark of HHVM?

### ISSUE THREAD

**Issue by ZahraHeydari95** [facebook/hhvm#9112]
Hello
I want to run a benchmark with HHVM.
On the other hand, I want to apply BOLT to it as well. But I don't know what to do.

hhvm perf.php --wordpress --hhvm=/path/to/hhvm

According to the BOLT instructions, I have to replace the execution binary in all three steps. But this binary (HHVM) has a series of inputs according to the above command.
As a result, the following questions arise for me:

How to add -Wl, -q to hhvm binary?

How to get a profile on the above command which is for running the benchmark?

How do I use ./perf2bolt in the command though wordpress--? Because it considers --wordpress as its own input and gives an error?

How do I still use ./llvm-bolt despite --wordpress? Because it still takes its own input and gives an error?

please guide me.

**Comment by lexidor** [comment]
Hi, if your intent is to benchmark hhvm with a PHP workload, that is not going to work anymore. Hhvm has not supported running unmodified php code since version 4.0.0. We are now at 4.163.0. The last version of hhvm that could run PHP code was 3.30.x. This version has been unsupported for about two years. (I am assuming that `--wordpress` would try to run WordPress on hhvm. If I am wrong there, please correct me.)

For more information about hhvm's development, see https://hhvm.com/blog. These posts lay out the story of PHP support in hhvm.

 - https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html
 - https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html
 - https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

I am closing this issue, because I expect that the above is a deal breaker for you. If this was an incorrect assumption from me, you can reopen the issue and ping me (@lexidor).
