### ISSUE TITLE
Facebook hack

### ISSUE THREAD

**Issue by Iefhe15** [facebook/hhvm#9448]
Now please teach me how to hack account

**Comment by haowanaa** [comment]
您好，来信我已收到，我将尽快给您回复。

**Comment by vassilmladenov** [comment]
Please don't spam our issue tracker.

**Comment by luisaglez1** [comment]
Since I realized that I started hacking Facebook without programs and the truth is that it is a simple task, I decided to communicate it to others so that they can enter as easily as I did to [any Facebook profile ](https://hackfreeonline.com/facebook/
)either from their smartphone or from their laptop, the only thing they need is to access online and they will see how easy it is to achieve what you are proposing and you will see how easy this will be for you and that is that you can manage to enter Facebook and thus obtain all the information you need to know about that person to enter in a simple way, in addition to the fact that it is a great and very useful tool. I had to [hack Facebook](https://hackfreeonline.com/facebook/
) easy right now so it's like if you were to be in a situation like having this information about this person would lead you to have more advantages, so you just need to keep in mind what you need to solve to be able to get to wherever you need for which I recommend that you use it in the best way so that you achieve what you set out to do and it is so simple just a matter of attitude for you to do it for this is that you must enter and realize for yourself, you will see how easy it will be for you, to start you just need to observe the visual tutorial that is offered to you at the beginning.
I had to hack Facebook online because it is so well structured that you only have to keep in mind what is taught to you so that you achieve your purpose, in addition to the fact that it is definitely one of the best pages that you will be able to know and that it will really be completely easy for you to use, it is a program that from the moment you use it you will see how it will be easier for you. The advantage that is offered to you is indisputable, this is how it is a totally free page, by hacking Facebook you do not need to pay any kind of salary to any account, this is how you save everything that you could have spent on some page and that maybe it was not even one that would have helped you.
